### ISSUE TITLE
Add cluster peers to docs.ipfs.io

### ISSUE THREAD

**Issue by alanshaw** [nftstorage/nft.storage#1000]
https://docs.ipfs.io/how-to/peering-with-content-providers/#content-provider-list

**Comment by dchoi27** [comment]
PR submitted here: https://github.com/ipfs/ipfs-docs/pull/987

**Comment by alanshaw** [comment]
Also added to repos in machine readable format:
https://github.com/web3-storage/web3.storage/blob/main/PEERS
https://github.com/nftstorage/nft.storage/blob/main/PEERS
