### ISSUE TITLE
Outstanding Docs work

### ISSUE THREAD

**Issue by dashcraft** [nftstorage/nft.storage#1010]
Items leftover from initial move to docusaurus

- [x] Needs final JS example for quickstart section
- [ ] Add image of on-chain metadata with IPFS URI link to off-chain data
 
Things that are still just placeholders:

- [x] all the how-tos
  - [x] retrieve from IPFS

Things that still need placeholders:
- [x] how-to: 10k NFT drop

**Comment by JeffLowe** [comment]
@yusefnapora sounds like the possible remaining item might already be done, or could be a simple content-only update?
