### ISSUE TITLE
Question: Importing pins from other nodes

### ISSUE THREAD

**Issue by Thegaram** [nftstorage/nft.storage#1011]
Hi, I just tried importing a file by its CID to nft.storage using the `POST https://api.nft.storage/pins` API. The "Files" page displays 0B as the file size, and querying this CID returns `"status": "queued"`.

Is this file now pinned on nft.storage? Is it safe to stop pinning it on other services?

![image](https://user-images.githubusercontent.com/7571518/147531427-905175db-49db-4309-89ec-d7aa7ad577f2.png)

**Comment by Thegaram** [comment]
For context, I'm trying to migrate pins from my own IPFS node to nft.storage.

**Comment by dchoi27** [comment]
Hi there - if there is no data size shown, then NFT.Storage hasn't yet been able to fetch the data. If this has been the case for a while, there's likely an issue with finding the data.

One call-out - we'll be restricting pinning service API access with NFT.Storage in the coming weeks to an allowlist of users who are verified to be storing NFT data. We'll be adding the pinning service API to our sister project, Web3.Storage, for verified non-NFT projects.

**Comment by Thegaram** [comment]
Thanks for your reply David! Just to clarify: in the future, when I upload files to NFT.Storage (through the file API), they'll still be pinned, right? But for importing pins by their CIDs, I'll need to migrate to Web3.Storage? Do existing users need to take any action? Is there an official announcement about this?

**Comment by dchoi27** [comment]
Main thing I was calling out is that NFT.Storage is for NFT data, regardless of whether it was uploaded directly or pinned! As long as it's NFT data, any data stored with NFT.Storage will continue to be persisted. Some folks have used the pinning service API with NFT.Storage to pin random data, so we're trying to tighten things up and enforce an allowlist for usage of the pinning service API (so we can first verify that a project is an NFT project before allowing them to use it). 

But for folks who want to pin non-NFT data to IPFS and Filecoin, we'll have a pinning service API with Web3.Storage. We'll make an announcement for this transition likely later this month.

Let me know if this still doesn't make sense!

**Comment by Thegaram** [comment]
It does, thank you for the explanation. We're using NFT.Storage for NFT data so hopefully this transition will require no change. I'll stay tuned to learn more about registering to this allowlist.

**Comment by dchoi27** [comment]
Hey there, just to follow up - we'll actually be implementing the allowlist in the next day or so, but will add everyone who are already using the API for NFT content. So you'll be automatically added to it, no action necessary on your part. Thanks!
