### ISSUE TITLE
Error with new nft.storage version

### ISSUE THREAD

**Issue by luffkaa** [nftstorage/nft.storage#1012]
Hi! 
I'm trying to use new features like encodeBlob with my React App and getting this errors:

```
./node_modules/nft.storage/src/platform.web.js
Module not found: Can't resolve 'ipfs-car/blockstore/memory' in '.../node_modules/nft.storage/src'
```

How to solve it?

**Comment by kochurovro** [comment]
I have the same issue

**Comment by alanshaw** [comment]
Please see the answer here: https://github.com/nftstorage/nft.storage/issues/876
