### ISSUE TITLE
cid in my list of files but not pinned

### ISSUE THREAD

**Issue by gregorym** [nftstorage/nft.storage#1014]
Hello,

I uploaded a `car` using `storeCar` and it is showing up in my account (see screenshot below). However, the CID is timing out on all Gateways. I also tried the using the IPFS desktop app and it also times out.

<img width="1318" alt="Screen Shot 2021-12-28 at 3 51 55 PM" src="https://user-images.githubusercontent.com/245300/147612920-f427df8c-149a-4463-9136-a7fc009ad4e2.png">

Is it possible to know from the UI if a CID has been pinned? (Like in we3.storage)

**Comment by gregorym** [comment]
Looks like it's still queued but it's been 13h. Is it supposed to be this long?

<img width="522" alt="Screen Shot 2021-12-28 at 4 26 08 PM" src="https://user-images.githubusercontent.com/245300/147614532-168652d8-536b-4a12-b939-b263cd184f2d.png">

**Comment by dchoi27** [comment]
Hey there - this is likely because the full CAR didn't get uploaded (e.g., connection was interrupted). Unfortunately, the information being shown by the WebUI and API are misleading in these situations, and we're looking to make the UX better in #896. For now, trying to reupload the file is probably best.

**Comment by alanshaw** [comment]
@gregorym did re-uploading work? If no then could you share the CID from your screenshots so we can take a closer look?

**Comment by alanshaw** [comment]
...another thought, our database is a little behind with syncing pin statuses right now. If it was uploaded successfuly then it might just be this - i.e. it has already been removed from the queue and pinned but there is a lag with the status being updated.

**Comment by vasco-santos** [comment]
The status for this CID is already `pinned` https://api.nft.storage/check/bafybeighciigkgu7npddcmiqgg6xbfz7kp2wdf5a33she6hvtynxrcvdua

Closing, but feel free to reopen if there is any other issue
