### ISSUE TITLE
Post instructions on how to acquire and use large file uploader electron ap

### ISSUE THREAD

**Issue by JeffLowe** [nftstorage/nft.storage#1016]
Draft instructions will come with completion of #1015.  We need to take those instrctions and publish to the correct documentation location.  We also need to provision the electron app for download.
Update Documentation / instructions on how to download and use the electron app 
- [ ] written documentation
- [ ] include video tutorial

**Comment by dchoi27** [comment]
One additional note - we should have a video tutorial on how to use the tool as well!

**Comment by dchoi27** [comment]
Given NFT UP, closing this one (tracking how we're marketing NFT UP in other places)
