### ISSUE TITLE
need to store 10k images in a single ipfs directory. is it possible? 

### ISSUE THREAD

**Issue by alexrmacleod** [nftstorage/nft.storage#1018]
would like to say thanks for making nft.storage its a great contribution! you guys are awesome!

...

I run into issues at the 100mb limit at 100 images but I have 10000 to upload. 

I need these 10000 images in the same ipfs directory so they can be referenced via my metadata (see below) 

question: is it even possible to have 10000 images in an ipfs directory without compressing all the addresses into a car file?

... or should I just upload 100 different directories with 100 images each, and update the metadata accordingly to reflect that 

a little confused on how to do this... happy new year! wagmi

```const client = new NFTStorage({ token: apiKey });
const images = true;
let files = [];

// joining path of directory
const directoryPath = path.join("build", "images");
// passsing directoryPath and callback function
const filenames = fs.readdirSync(directoryPath);
console.log("\ncurrent directory filenames:");
// iterate files
filenames.forEach((file) => {
  console.log(file);
  // get file data
  const data = fs.readFileSync("build/images/" + file);
  files.push(new File([data], file));
  // upload
  if (files.length === filenames.length) { // memory issues above 100 images
    console.log("files.lenght", files.length);
    console.log("filenames.lenght", filenames.length);
    upload();
  }
});

async function upload() {
  const cid = await client.storeDirectory(files);
  console.log(`https://${cid}.ipfs.dweb.link`);
}
```

metadata

```
[
  {
    "dna": "9f8fa578d4127d80514e71dc9aa425ac78aa0a48",
    "name": "cc cc #0",
    "description": "The HODLer - Txxxxo.",
    "image": "ipfs://bafybeig4qjehigdddcoka23crh2s3vrautbep3topuoqblb4chkvvhpilu/0",
    "edition": 0,
    "date": 1640963889656,
    "attributes": [
      {
        "trait_type": "Background",
        "value": "Pajamas"
      },
      {
        "trait_type": "Skin",
        "value": "Eggplant"
      },
      {
        "trait_type": "Face",
        "value": "Small"
      },
      {
        "trait_type": "Body",
        "value": "Bathrobe"
      },
      {
        "trait_type": "Head",
        "value": "High"
      },
      {
        "trait_type": "Animal",
        "value": "Owl"
      },
      {
        "trait_type": "Character",
        "value": "HODLer"
      }
    ]
  },
  {
    "dna": "f8084fdd5827fed9cd9f7763a2403e3d9471045e",
    "name": "cc cc #1",
    "description": "The HODLer - Txxx.",
    "image": "ipfs://bafybeig4qjehigdddcoka23crh2s3vrautbep3topuoqblb4chkvvhpilu/1",
    "edition": 1,
    "date": 1640963890645,
    "attributes": [
      {
        "trait_type": "Background",
        "value": "Pajamas"
      },
      {
        "trait_type": "Skin",
        "value": "Crew Neck"
      },
      {
        "trait_type": "Face",
        "value": "Small"
      },
      {
        "trait_type": "Body",
        "value": "Yellow"
      },
      {
        "trait_type": "Head",
        "value": "Bucket Hat"
      },
      {
        "trait_type": "Animal",
        "value": "Owl"
      },
      {
        "trait_type": "Character",
        "value": "HODLer"
      }
    ]
  },
  {
    "dna": "7b0415d4d3d454bba7afb3a8bf1be24918344f3b",
    "name": "ccc cc #2",
    "description": "The HODLer - xxxo.",
    "image": "ipfs://bafybeig4qjehigdddcoka23crh2s3vrautbep3topuoqblb4chkvvhpilu/2",
    "edition": 2,
    "date": 1640963891732,
    "attributes": [
      {
        "trait_type": "Background",
        "value": "Pajamas"
      },
      {
        "trait_type": "Skin",
        "value": "Hawaiian Shirt"
      },
      {
        "trait_type": "Face",
        "value": "Windsor Glasses"
      },
      {
        "trait_type": "Body",
        "value": "Hawaiian Shirt"
      },
      {
        "trait_type": "Head",
        "value": "Beret"
      },
      {
        "trait_type": "Animal",
        "value": "Owl"
      },
      {
        "trait_type": "Character",
        "value": "HODLer"
      }
    ]
  },```

**Comment by alexrmacleod** [comment]
@alanshaw 🙏

**Comment by dchoi27** [comment]
Hey there! Can you share more about the issues you're seeing at the 100MBs? The 100MB limit is actually just per request - there's no actual data limit for the data uploaded to the service if the data is chunked and sent over <100MB requests. The JS client library does this automatically for you.

There are some issues we see with really large directories (working on this in #928) but in the worst case scenario you should be able to split your directory up into just a few directories and be able to upload them.

wagmi indeed!

**Comment by alexrmacleod** [comment]
gm! @dchoi27 thank you for your response! when I use ```client.storeDirectory(files)``` on the JS client library it only works for 100mb as is documented. my issue is how to I upload the next 100mb into the same directory? currently I just have an array with all the files with is >100MB ```files.push(new File([data], file));```.

how do I send chunked <100MB requests to the same IPFS directory using ```client.storeDirectory(files)```?

I am totally lost and any code example will be very helpful! please have an amazing day.

**Comment by alanshaw** [comment]
storeDirectory should be splitting this data up for you automatically into several chunks. What version of the client are you using?

**Comment by alexrmacleod** [comment]
@alanshaw ```+ nft.storage@3.4.0```

**Comment by alanshaw** [comment]
Is it being run in the browser? Browser's have memory limits per domain and I believe also per tab.

**Comment by alanshaw** [comment]
(there is no such limit in nft.storage)

**Comment by alexrmacleod** [comment]
@alanshaw thank you for your response. It seems a simple npm update to version ```nft.storage@5.2.0``` did the trick. foolish of me to miss this! I am honoured to have conversed with you and appreciate you for pointing me in the right direction. I will pass the good word of this wonderful project onto my peers - and with that I bid you adieu!
