### ISSUE TITLE
[QUESTION] Endpoint to create Account + API Key

### ISSUE THREAD

**Issue by Kirbyrawr** [nftstorage/nft.storage#1019]
Hi, i'm wondering if there is any endpoint to create an API Key and account automatically, thanks.

This would help onboard users easily without exiting the onboarding on an external website/app.
It would also help store the API KEY Encrypted in a blockchain and use it as an approach to WEB3 login.

**Comment by Kirbyrawr** [comment]
I guess it's related to this: https://github.com/web3-storage/web3.storage/issues/261

**Comment by dchoi27** [comment]
Ah, looks like you've already seen the parallel issue in Web3.Storage where I just left a comment, but #851 is the current work to allow for this (basically letting NFT.Storage users create [UCANs](https://fission.codes/blog/auth-without-backend/) for their users to upload to NFT.Storage without needing to expose their API key). This would at first require you to run your own backend to delegate these UCANs. Does that work for you, or are there other needs that aren't met by this?

**Comment by Kirbyrawr** [comment]
I think that's perfect, thank you so much for the reply and work!
