### ISSUE TITLE
Login magic link is broken

### ISSUE THREAD

**Issue by vikasr111** [nftstorage/nft.storage#1020]
I tried signing up using the email. I received the magic link for login but when I clicked the link it showed a pages with message "Magic Link Expired". Tried again several times but same results. Check screenshot.

<img width="885" alt="Screenshot 2022-01-03 at 10 28 02 PM" src="https://user-images.githubusercontent.com/5301813/147957955-5693839e-cc2a-4793-84fb-2c394d6c251c.png">
.

**Comment by dchoi27** [comment]
Hey, a few of us tested and the sign up works fine for us. Can you share more about what browser you're using? Have you tried using other browsers?

**Comment by dchoi27** [comment]
Hey closing this for now, let us know if you have anything you'd like to update us on!
