### ISSUE TITLE
Large file uploader app, alert when upload is interrupted or partial

### ISSUE THREAD

**Issue by JeffLowe** [nftstorage/nft.storage#1024]
There should be a way to detect if an upload is interrupted and make this obvious to the user (even though per #896 the root CID will show up fine to the user)

This was first mentioned as comment on the Electron App MVP https://github.com/nftstorage/nft.storage/issues/1015#issuecomment-1004225093

**Comment by dchoi27** [comment]
Closing this given NFT UP has retries of upload pieces + Uploads v2 giving better visibility into this
