### ISSUE TITLE
Form for requesting pinning service API allowlist access

### ISSUE THREAD

**Issue by dchoi27** [nftstorage/nft.storage#1025]
To users' account pages, let's have a page with instructions for requesting pinning service API allowlist access. 

An email form to support (at) nft.storage that asks them to share 5 CIDs of NFTs / metadata they're looking to pin, as well as their profile on a marketplace.
 - [x] simple mailto link set to send to support at nft.storage
 - [x] put in GitHub issue template 
 - [x] put as link on user's /manage page. 

## Data to collect from submitter:
- Why you are looking for pinning service API access (e.g. you're an artist looking for extra redundancy)
- 5-10 CIDs of NFTs / metadata you are looking to pin
- Your profile on an NFT service (artist profile, collector, etc.)

**Comment by alanshaw** [comment]
Please can we add an issue template so we get a new button in the create issue page?

<img width="1259" alt="Screenshot 2022-01-05 at 14 25 05" src="https://user-images.githubusercontent.com/152863/148233530-bf62a7c7-6027-436b-842d-9d0c38fa8a98.png">

i.e. add https://github.com/web3-storage/web3.storage/blob/main/.github/ISSUE_TEMPLATE/config.yml

**Comment by dchoi27** [comment]
Could you share more about why you'd prefer GH issues over emailing support@? For Web3.Storage account limit increase requests we use an email form linked in their account, which comes with validation that they have an account / were logged in when they sent the request, and allows us to identify their account via their email. For PSA access, if it's a GH issue instead, we lose some of this - their request becomes public, they'd have to share a personal identifier in the issue, we don't have validation that they have an account yet, etc.

**Comment by dchoi27** [comment]
OK - completely misunderstood Alan, who was just saying we should in addition to the email form have an issue template for this. Agreed with that!

Hey @JeffLowe - this issue is actually not an admin issue, and is a frontend issue (get a link in the web UI to an email form for the user). The admin component to this we should just put in the admin post-MVP backlog (though we should flag that it's blocked on the back-end bit to not need to deploy to modify the allowlist).

**Comment by JeffLowe** [comment]
@dchoi27 updated the description with what I believe needs to be collected from the form.  Could you look and verify?  Also, is the desire a very simple mailto link (like the GitHub issue links eg https://mailxto.com/xy5ijb ) or is it a web form that collects and sends data in email?

**Comment by dchoi27** [comment]
Thanks! Don't think we need the autoinjected ID (since they'll be emailing from their account). Additional capacity required isn't a bad idea, thanks for adding.

**Comment by JeffLowe** [comment]
Ok.  Per slack message, we will implement this as a simple mailto link.

**Comment by dchoi27** [comment]
@orvn mentioned that long ago, we talked about maybe making these requests direct to an Airtable form asking for this information. Seems still worth exploring.

@JeffLowe could we look into whether this works in place of a mailto link? Main thing would be being able to pre-populate the form with their email address https://support.airtable.com/hc/en-us/articles/234982508-Prefilling-a-form and asking for the other things detailed in the OP

**Comment by dchoi27** [comment]
we'll just go with a mail link for now! cc @orvn

**Comment by JeffLowe** [comment]
@alanshaw @dchoi27 
Alternative proposal:
With the addition of application log to house user requests to admin (see #1401 ), we should implement web forms allowing users a simple means of submitting their request to get added to pinning api allowlist. The form will be presented to user on there /files page.  These requests will surface in admin .storage in list for admin action (see https://github.com/nftstorage/admin.storage/issues/21 )
We will also Add GitHub issue templates that link to web UI page containing the request webform (eg. Pinning Service Access Request “ Submit a request to access NFT.Storage's IPFS pinning service in your account!”  (likely pointing to https://nft.storage/files/)

**Comment by dchoi27** [comment]
Yup - let's still get the email links up (should be a quick win, and we have to triage the requests manually anyway + it's not a high volume right now). But definitely sounds like a good improvement later on!

**Comment by JeffLowe** [comment]
Cool.  I updated spec in description to define the quick "mailto link" approach if it blocks releasing the core pinning allowlist in admin.  Also, the preferred approach we will ultimately take

**Comment by dchoi27** [comment]
Wait - this ticket (mailto link) is completely independent of the admin console. It is a net improvement to the current process (where we can't add folks to the allowlist via the admin console). Let's just get this done.

Separately, I think it makes sense for the ability to modify the allowlist via the admin console should block the form getting implemented (since the form isn't useful without the ability to block).

**Comment by dchoi27** [comment]
Hey! Let's make sure this lands soon so @yusefnapora can finish #1026 in this sprint.

**Comment by dchoi27** [comment]
Can this be closed? Looks like #1551 got merged

**Comment by JeffLowe** [comment]
Still needs a GitHub template issue to complete this.  The mailto link, however, is done and on the /manage page.

**Comment by JeffLowe** [comment]
@cmunns dont forget the github issue template.

**Comment by cmunns** [comment]
@JeffLowe @dchoi27 it's already merged but it looks like contact_links can only contain valid http(s) urls because the mailto link is simply not showing up.

**Comment by dchoi27** [comment]
Can check out how it's done here: https://github.com/web3-storage/web3.storage/issues/new/choose
