### ISSUE TITLE
Docs for pinning service API allowlist

### ISSUE THREAD

**Issue by dchoi27** [nftstorage/nft.storage#1026]
In the upcoming docs website, let's add instructions on how to request pinning service API access (once #1025 lands) and how to configure the pinning service API! 

- [ ] move content from doc https://docs.google.com/document/d/1_XQ5gOxlgJ02PCCrYVlms0aOT5WCa7rpsiusjnAUN4U/edit#heading=h.6du961pmbdil into /docs page
- [ ] ensure we make the routing adjustment the page will need (like other pages)

**Comment by JeffLowe** [comment]
FYI @yusefnapora https://bf96ca8e.docs-web3-storage.pages.dev/how-tos/pinning-services-api/

**Comment by dchoi27** [comment]
hey folks - bumping this up to a P1! I think there are a number of big-time collabs that are going to be looking into using the pinning service API. cc @Codigo-Fuentes @JeffLowe

**Comment by JeffLowe** [comment]
@alanshaw @yusefnapora 
 Would appreciate a review of this draft (based on a Web3 pinning draft, thus it will be mostly accurate but not fully) https://docs.google.com/document/d/1_XQ5gOxlgJ02PCCrYVlms0aOT5WCa7rpsiusjnAUN4U/edit?usp=sharing
 Feel free to edit directly. Once we are satisfied with accuracy, we can get it added to docs.

**Comment by dchoi27** [comment]
^ can we just put this in a PR?
