### ISSUE TITLE
Testing data availability and retrievability

### ISSUE THREAD

**Issue by alanshaw** [nftstorage/nft.storage#1030]
We store CIDs and locations where data is hosted. We should perioidcally verify that data is still where we expect it to be, is discoverable, availabile and retrievable. We need to report the findings with enough information to allow us to follow up on any inconsistencies.

**IPFS Cluster**

* Test status is pinned
* Test at least 1 (pref 3) cluster peers are are listed as providers on the DHT
* Test data can be retrieved from each peer it is stored on

**Filecoin**

* Test deal(s) exists and is still active on chain (✅ handled by dagcargo)
* Test data can be retrieved from storage provider(?)

**Pinata** (for discussion)

* Test status is pinned.

Marked as for discussion because API limits may make this difficult/very slow and it is a backup, not primary storage. I think it is reasonable to just test for pin status and delegate the responsibility of discoverability and retrievability to Pinata.

**S3** (for discussion)

* Test bucket contains CAR file.
* Test completeness of data.

Marked as for discussion because it is our disaster recovery backup, not primary storage. I think we can delegate the responsibility of retrievability to Amazon although checking for completeness will indirectly test for retrievability.

**Comment by ribasushi** [comment]
@alanshaw yes, the `deals` table `sate` field is dynamic and has a lag of max 5 minutes. If a deal goes away - you will be able to query in real time.
The "re-do deal" part is half-delegated to estaury ( switching to "full" when the linkage works smoothly in a month or two )

**Comment by alanshaw** [comment]
Building it over here https://github.com/nftstorage/checkup

**Comment by alanshaw** [comment]
Dashboards availabile here:
* https://protocollabs.grafana.net/d/-2uEWFLnz/checkup-nft-storage?orgId=1&refresh=1m
* https://protocollabs.grafana.net/d/NHkzPpLnz/checkup-web3-storage?orgId=1&refresh=1m

**Comment by alanshaw** [comment]
The dashboards are testing that root CIDs are available on each peer. It does not transfer entire DAGs. This would make checking very slow (and probably expensive), however Cluster tracks pin status and only reports "pinned" when the entire DAG is available. An enhancement to pick up on whether the DAG is fully available or not would be to add cluster pin status information to the metrics.

**Comment by dchoi27** [comment]
Closing!
