### ISSUE TITLE
This Package is not working due to blockstore-core update

### ISSUE THREAD

**Issue by yousuf-hossain-shanto** [nftstorage/nft.storage#1046]
Please check this issue https://github.com/ipfs/js-blockstore-core/issues/10

I am facing this error.....

nft.api     | Error: No "exports" main defined in /usr/src/app/node_modules/ipfs-car/node_modules/blockstore-core/package.json
nft.api     |     at new NodeError (node:internal/errors:371:5)
nft.api     |     at throwExportsNotFound (node:internal/modules/esm/resolve:429:9)
nft.api     |     at packageExportsResolve (node:internal/modules/esm/resolve:638:7)
nft.api     |     at resolveExports (node:internal/modules/cjs/loader:482:36)
nft.api     |     at Function.Module._findPath (node:internal/modules/cjs/loader:522:31)
nft.api     |     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:919:27)
nft.api     |     at Function.Module._load (node:internal/modules/cjs/loader:778:27)
nft.api     |     at Module.require (node:internal/modules/cjs/loader:999:19)
nft.api     |     at require (node:internal/modules/cjs/helpers:102:18)
nft.api     |     at Object.<anonymous> (/usr/src/app/node_modules/ipfs-car/dist/cjs/blockstore/memory.js:5:27)

**Comment by ljmf00** [comment]
Latest version of blockstore should close this. See https://github.com/ipfs/js-blockstore-core/tree/v1.0.5 .
