### ISSUE TITLE
Webpack error thrown using nft.storage (storeBlob) to store a new Blob

### ISSUE THREAD

**Issue by 0xPr0f** [nftstorage/nft.storage#1055]
# Trying to store a new blob with nft.storage
This returns an error  `TypeError: merge_options__WEBPACK_IMPORTED_MODULE_0__.bind is not a function`

## To reproduce and isolate
i copied the code for storing a new blob from https://github.com/nftstorage/nft.storage/blob/main/packages/client/examples/node.js/storeBlob.js and excluded fs, to import a file from a url and it still gave the same error .

```js
import { Blob } from "nft.storage";
import { NFTStorage } from "nft.storage";
async function Test() {
 const client = new NFTStorage({
        token: process.env.NFT_STORAGE_API_KEY,
      });

    await client.storeBlob(
        new Blob([
          {
            chain:"rinkeby",
            contract_address: "0x....(a valid contract address )",
            transaction_hash: "0x....(a valid tx hash)",
            description:"Test work",
            address:"0x.....(a valid address )",
          },
        ])
      );

}

export default Test;
```
<img width="960" alt="Screenshot 2022-01-10 at 11 11 25 AM" src="https://user-images.githubusercontent.com/94965754/148835273-0f8a0cfd-3316-4ae2-81ed-3dc22c77b182.png">

**Comment by dchoi27** [comment]
Hey - can you try importing using the info in the last FAQ here? https://nft.storage/faq/#skypack-issues-or-webpack-4-not-bundling

**Comment by vasco-santos** [comment]
Hey @0xPr0f 
Did you manage to get this working with https://nft.storage/faq/#skypack-issues-or-webpack-4-not-bundling

**Comment by yusefnapora** [comment]
@0xProf, any chance you're using Next.js v11? This sounds like the same issue described in https://github.com/nftstorage/nft.storage/issues/929.

If you're using Next v11 and can upgrade to v12, that should hopefully fix the issue. If you're not using next, please let us know so we can dig further :)

**Comment by 0xPr0f** [comment]
@vasco-santos , well at some point in the future it started working I don't know why tho but it was working with nextjs 11 and it was alright

**Comment by 0xPr0f** [comment]
@yusefnapora , it started working with the nextjs version I was using which was 11 I think but that was it with nextjs is was weird at the beginning where it wasn't working, I don't really know what was wrong and the prebuilt library was the same, when it started working on next I tried to experiment the prebuilt library and see it is will work but it wasn't, and my next js should be using webpack 5 , but I will comment with the correct /accurate version of things later on 😅 when I do more testing

**Comment by 0xPr0f** [comment]
@vasco-santos, this is the code 
```js
import {
  NFTStorage,
  Blob,
} from "https://cdn.jsdelivr.net/npm/nft.storage@v5.1.3/dist/bundle.esm.min.js";
```
and i am getting an error 
```sh
Failed to compile.

./src/Stream.js
Module not found: Can't resolve 'https://cdn.jsdelivr.net/npm/nft.storage@v5.1.3/dist/bundle.esm.min.js' in '/Users/praise/Documents/unstoppable-stream/src'
```
i am using `webpack@4.44.2` for this project.
i will try with webpack 5 and give updates 🙂

**Comment by alanshaw** [comment]
@0xPr0f since you're using webpack, you need to import like this:

```js
import { NFTStorage } from 'nft.storage/dist/bundle.esm.min.js'
```

**Comment by alanshaw** [comment]
I commented here with the solution that was working for me in your code: https://github.com/nftstorage/nft.storage/issues/1125#issuecomment-1025802117
