### ISSUE TITLE
Restrict delete operation for particular API KEY

### ISSUE THREAD

**Issue by kfartusov** [nftstorage/nft.storage#1056]
I'd like to use nft.storage in backend less solution, it means i have to store api key on the client side, which is React JS app.
I'm afraid it gives potential possibility to use this "shared" API KEY to remove some content. 

It would be nice to have possibility to restrict delete operations for exact API KEY.

**Comment by dchoi27** [comment]
We're tracking the direct ask in #138 - though in general you should not bundle an NFT.Storage API key with an application. Being able to enable backendless interactions will be tackled in #851 over the next few weeks!
