### ISSUE TITLE
401 Unauthorized

### ISSUE THREAD

**Issue by SomeBoyFrom** [nftstorage/nft.storage#1061]
I have an issue when trying to add a CID file to nft.storage, It shows this message "Error: reason: "UNAUTHORIZED", details: "Pinning not authorized for this user, email support@nft.storage to request authorization.": 401 Unauthorized".
How to solve this?
Thank you.

**Comment by dchoi27** [comment]
Follow the instructions and reach out to the email address :) if you can provide example CIDs of content you're looking to pin and some sort of artist profile or other social proof showing that you're in the NFT space, that'd be helpful to make sure we know you're actually going to be pinning NFTs!

**Comment by orangbunian** [comment]
Hi, today I encountered the same `Error: pinning QmSxzxnu9xnVCxZeH29EBjHq58BRw849tsM96B9Yn83xJB: 401: Unauthorized` when use `node import.js pinlist.txt` (I only put the above CID on the pinlist.txt)

I already email support@nft.storage two days ago for this `bafybeidpzmsqqvvhwlj6utbrgwzxyelins6vexeqo4fhne6b66p4g2sija` CID (lower image size) yet still no response until now.

**Comment by sosaucily** [comment]
So, although there is a self-service API Key system online, all accounts need to be verified via email? I'm getting the same error.

**Comment by dchoi27** [comment]
Please read the docs: 
https://nft.storage/docs/
https://nft.storage/docs/how-to/pinning-service/

**Comment by hoangtam101** [comment]
So I got the same error when I tried to pin a CID.
I read the document so I still stuck at it.
