### ISSUE TITLE
Add IPFS and Arweave URL support to Solana block explorer website

### ISSUE THREAD

**Issue by dchoi27** [nftstorage/nft.storage#1062]
Right now, Solana NFTs use HTTP URLs rather than decentralized URLs like `ipfs://` or `ar://` URLs. Digging into it a bit deeper, it looks like this is the case because this NFT tooling in the Solana ecosystem only speaks HTTP, and not having HTTP URLs breaks things. One major case of this is in the Solana block explorer, where NFTs are detected based on the mint transaction and metadata, and the NFT's image is displayed using the HTTP URL (https://explorer.solana.com/address/FdUZuAenEbAbSPtZjDtw2EkUVkBZt9TqN9rNCAP967bN/metadata).

Let's PR the Solana Explorer (https://github.com/solana-labs/solana/tree/master/explorer) to detect IPFS and Arweave URLs and convert them to gateway URLs. We should take a stab at this in the least invasive way possible, and getting this PR up will let the Solana block explorer team engage on preferences (e.g. where in the code / how to set preferred gateway).

Ideally we submit a PR using the library we're making in #1045, but there's no need to block on this.

**Comment by dchoi27** [comment]
Any updates here?

**Comment by JeffLowe** [comment]
PR Submitted to their repo https://github.com/solana-labs/solana/pull/22761
It's a first step towards handling.
