### ISSUE TITLE
Unit tests not working

### ISSUE THREAD

**Issue by RustemYuzlibaev** [nftstorage/nft.storage#1068]
When running tests an error occurs
It requires missing carbites/treewalk

<img width="741" alt="Screenshot 2022-01-13 at 16 30 10" src="https://user-images.githubusercontent.com/27702061/149322980-cb0b5ea2-8740-4c04-bd1d-0c4113c32d4e.png">

**Comment by vasco-santos** [comment]
Hello @RustemYuzlibaev 

What environment/setup are you using? It looks like you are using an old version of webpack that does not recognize package.json exports like https://github.com/nftstorage/carbites/blob/main/package.json#L51

**Comment by alanshaw** [comment]
This might help: https://github.com/nftstorage/nft.storage/issues/876#issuecomment-985687135

Please shout if you're still having troubles.
