### ISSUE TITLE
Investigate partners to allow browsing / scoring a wallet or collection

### ISSUE THREAD

**Issue by JeffLowe** [nftstorage/nft.storage#1082]
This is related to @jchris draft nifty score product

Vision of this use case is that a user (Artist, Dev, Collector) can paste in a wallet or contact address, and get a list of the NFTs owned or minted by that address. There may be a rollup of the NiftyScore detail data from all of the NFTs in the set, but that can come later. (Not sure if we want to do % or count, etc)

**Comment by jchris** [comment]
NFTs by contract https://docs.nftport.xyz/docs/nftport/b3A6MjAzNDUzNTQ-retrieve-contract-nf-ts
NFTs by wallet https://docs.nftport.xyz/docs/nftport/b3A6MjE0MDYzNzM-retrieve-nf-ts-owned-by-an-account

**Comment by dchoi27** [comment]
Research complete - @jchris with next steps. Closing for now
