### ISSUE TITLE
make discord channels more prominent 

### ISSUE THREAD

**Issue by mikeal** [nftstorage/nft.storage#1102]
we have the channel there for community support, and it’s hooked up to slack, but people aren’t easily finding it and are finding my personal DM’s easier than the discord ;)

- [ ] add github issue template in repo that links out to Discord channel

- [ ] Add to Docs content (when up)

(moved footer updates to #1295 )

**Comment by alanshaw** [comment]
Added discord to the README [here](https://github.com/nftstorage/nft.storage/pull/1107).

Suggestions for places where we could also surface it:

* Website docs section - "Need help? Chat with us on discord."
* Website footer - we could add discord, twitter, github logos
* Github [new issue](https://github.com/nftstorage/nft.storage/issues/new/choose) template chooser - you can add external links here
