### ISSUE TITLE
Limit /files page Storage Providers to 3 max

### ISSUE THREAD

**Issue by JeffLowe** [nftstorage/nft.storage#1110]
With deploy of #959 users have new /files UI view.   Some CIDs have large number of storage providers...for now let's immediately limit to 3.  Eventually, we will want to implement way to display "and n more" with n being total count of storage providers. 

- [ ] display only 3 max storage provider links.
- [ ] adjust width of Storage Provider column to allow more room for the CID column

**Comment by alanshaw** [comment]
Please can we tackle the following small tweaks at the same time?:

<img width="1461" alt="Screenshot 2022-01-19 at 09 44 06" src="https://user-images.githubusercontent.com/152863/150107358-40f60924-54e6-4ff8-b9ad-01095f8a70ae.png">

I think 3 providers might be more appropriate considering the space in the table when viewing on a typical laptop screen - ideally the CID column wouldn't wrap at this width (or any column), but I think this won't be possible with 6 providers shown.
