### ISSUE TITLE
Instant crash while using the storeDirectory method

### ISSUE THREAD

**Issue by buddbro** [nftstorage/nft.storage#1119]
Hi, I'm testing to upload some files, however, it seems to be crashing everytime I try without any explanation as to why. So I don't know if there's a bug or if I'm doing any mistakes.

The input object looks like this from the variable initialFiles
```
[
  File { _name: '1.png', _lastModified: 1642644380208 },
  File { _name: '1.json', _lastModified: 1642644380209 }
]
```

and what I am trying to run is
```
async function main() {
  const client = new NFTStorage({ token: 'API_TOKEN', endpoint })
  const initialFiles = await parseFiles()
  const cid = await client.storeDirectory(initialFiles)
  console.log(cid)
}

main()
```

with the variables 
```
const API_TOKEN = '<token-omitted>'
const endpoint = 'https://api.nft.storage'
```

And finally the error that I get is
```
node:internal/process/promises:246
          triggerUncaughtException(err, true /* fromPromise */);
          ^

Error
    at pRetry__default.default.retries (C:\Users\username\Documents\GitHub\nft-generator\node_modules\nft.storage\dist\src\lib.cjs:160:23)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async RetryOperation._fn (C:\Users\username\Documents\GitHub\nft-generator\node_modules\p-retry\index.js:50:12)
```
Thanks :)

**Comment by alanshaw** [comment]
I believe this is an unauthorized error. Please check your token is correct.

**Comment by buddbro** [comment]
I have double checked it, by copying the token from nft.storage and CTRL+F in my editor. I also tried to delete it and create another API key and verified that by the same method. It was still not working.

**Comment by buddbro** [comment]
It appears to have been so, thank you :)

**Comment by dchoi27** [comment]
Check out NFT UP for storing large directories! https://nft.storage/blog/post/2022-04-05-announcing-nftup/
