### ISSUE TITLE
Can't resolve 'ipfs-car/blockstore/memory' 

### ISSUE THREAD

**Issue by 0xPr0f** [nftstorage/nft.storage#1125]
i have a code sample like this, this is a create-react-app. it isn’t really specific on which webpack version am using. 
```js
import { Blob } from "nft.storage";
import { NFTStorage } from "nft.storage";
async function Test() {
 const client = new NFTStorage({
        token: process.env.NFT_STORAGE_API_KEY,
      });

    await client.storeBlob(
        new Blob([
          {
            chain:"rinkeby",
            contract_address: "0x....(a valid contract address )",
            transaction_hash: "0x....(a valid tx hash)",
            description:"Test work",
            address:"0x.....(a valid address )",
          },
        ])
      );

}

export default Test;
```
import NFTStorage and Blob like this cause the app to have errors, when the code isnt even been executed 
```sh
Failed to compile.

./node_modules/nft.storage/src/platform.web.js
Module not found: Can't resolve 'ipfs-car/blockstore/memory' in '/workspace/Unstoppable-Stream/node_modules/nft.storage/src'

```
there seems to be a problem with the dependencies. ipfs-car has been a troublesome dependency for me, it has caused my code not to compile on vercel, and locally 

if ipfs-car can be compatible with webpack 4 , or a prominent solution 

using the prebuilt library also cause a memory heap (like it's running out of memory and falling to allocate more) . and cause the code to exit
some thing like this
`import { NFTStorage } from 'nft.storage/dist/bundle.esm.min.js'`
will cause
```sh
<--- Last few GCs --->

[46836:0x160008000]    22648 ms: Scavenge 2030.8 (2074.2) -> 2027.2 (2074.7) MB, 2.7 / 0.0 ms  (average mu = 0.257, current mu = 0.226) allocation failure 
[46836:0x160008000]    22655 ms: Scavenge 2031.5 (2075.0) -> 2028.1 (2075.7) MB, 3.6 / 0.0 ms  (average mu = 0.257, current mu = 0.226) allocation failure 
[46836:0x160008000]    22663 ms: Scavenge 2032.3 (2075.7) -> 2028.9 (2076.2) MB, 7.2 / 0.0 ms  (average mu = 0.257, current mu = 0.226) allocation failure 
...
45: 0x100966d8c node::fs::AfterNoArgs(uv_fs_s*) [/Users/praise/.nvm/versions/node/v16.13.0/bin/node]
46: 0x1011cb144 uv__work_done [/Users/praise/.nvm/versions/node/v16.13.0/bin/node]
47: 0x1011ce8a4 uv__async_io [/Users/praise/.nvm/versions/node/v16.13.0/bin/node]
48: 0x1011e05b8 uv__io_poll [/Users/praise/.nvm/versions/node/v16.13.0/bin/node]
49: 0x1011ced34 uv_run [/Users/praise/.nvm/versions/node/v16.13.0/bin/node]
50: 0x1008b2e00 node::SpinEventLoop(node::Environment*) [/Users/praise/.nvm/versions/node/v16.13.0/bin/node]
51: 0x10099b6f4 node::NodeMainInstance::Run(int*, node::Environment*) [/Users/praise/.nvm/versions/node/v16.13.0/bin/node]
```
any additional info needed, feel free to request

**Comment by alanshaw** [comment]
@0xPr0f there seems to be 2 seperate issues here.

The first is a known problem with webpack 4 - it does not support the `exports` field in `package.json` and unfortunately v4 of webpack is so old that it is only accepting security fixes and not backports for new features. The workaround is to use the pre-built bundle (`nft.storage/dist/bundle.esm.min.js`) or upgrade to webpack5.

The second issue (the out of memory error) I've only seen before when uploading a huge amount of data. This is also a known issue that we're trying to fix. However, in your comment you seem to be suggesting that importing the bundle is the cause of the error. Can you verify this? Is the error happening for you locally or only on vercel?

Lastly if you can share the code you're using (and the file you're trying to upload) I can look into it further.

**Comment by 0xPr0f** [comment]
@alanshaw , i am not uploading a static file, the user choose the file to upload, but that code isnt been run because the user hasnt choose a file and i am just opening my home page and it is crashing, are the prebuilt bundles for NFTStorage and Blob the same or different ?
https://github.com/0xPr0f/Unstoppable-Stream/blob/acb0a987eb8e28b0152e304601699b6267f93231/src/Stream.js#L137 this is where the code is.

**Comment by alanshaw** [comment]
The same, you can import like:

```js
import { NFTStorage, Blob } from "nft.storage/dist/bundle.esm.min.js";
```

Does it crash for you like this?

Secondly, if you get this far, you need to `JSON.strinigfy()` your blob data or you'll get `[object Object]` stored (the `toString` of a plain object) e.g.:

```js
    await client.storeBlob(
        new Blob([
          JSON.stringify({
            chain:"rinkeby",
            contract_address: "0x....(a valid contract address )",
            transaction_hash: "0x....(a valid tx hash)",
            description:"Test work",
            address:"0x.....(a valid address )",
          })
        ])
      );
```

https://github.com/0xPr0f/Unstoppable-Stream/blob/acb0a987eb8e28b0152e304601699b6267f93231/src/Stream.js#L142-L150

**Comment by 0xPr0f** [comment]
@alanshaw , hey I will try that but I test a bit with create-react-app on webpack 5 and I was going through the same issue when not using the prebuilt library, but I will do further testing and try out your method and get back with more info

**Comment by 0xPr0f** [comment]
@alanshaw
<img width="676" alt="Screenshot 2022-01-24 at 8 21 26 PM" src="https://user-images.githubusercontent.com/94965754/150850245-32a521b1-baae-419d-93eb-854cc019cd90.png">
this is what i got using the code you sent
<img width="336" alt="Screenshot 2022-01-24 at 8 21 54 PM" src="https://user-images.githubusercontent.com/94965754/150850386-f691d8a8-dbe6-4d51-8ca7-1456d3f15a09.png">
my versions of the packages, using `webpack@4.44.2`
if you need any more info, you can request

**Comment by alanshaw** [comment]
Ok so, I cloned the repo, upgraded nft.storage to v5.2.2 and changed the import to `nft.storage/dist/bundle.esm.min.js` and I was able to load the site in my browser and use the `NFTStorage` class to upload a file.

Note: I actually did `npm i nft.storage@5` and for some reason I didn't see `node_modules/nft.storage/dist/bundle.esm.min.js`. I removed the `node_modules` directory and did a fresh install and then it was there.

Anyway, I think this is resolved! Shout if you still have troubles.

**Comment by burakkaraceylan** [comment]
Hello,

I have the same error and simpy adding this import statement

    import { NFTStorage } from "nft.storage/dist/bundle.esm.min.js";

causes "FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory".

I am using "nft.storage": "^6.0.0" and "react-scripts": "^4.0.3"

**Comment by xcrispy** [comment]
@burakkaraceylan try opening a new issue, this one is closed, there is something wrong with nft.storage and i dont think they want to fix it but i advice you to use another protocol
