### ISSUE TITLE
Requesting an easy way to get existing NFTs onto nft.storage

### ISSUE THREAD

**Issue by Oosik** [nftstorage/nft.storage#1129]
I think NFT owners need to be a little more responsible in pinning the work they own -- but setting up and running a node is out of many peoples reach. nft.storage is the perfect solution for developers starting new projects but I would love to have a way to import the nfts I already own into my account. Ideally a collector could click the upload button and there would be two fields one to upload a file and one to insert and ipfs link (or possibly an opensea link if you want to get fancy with it). once you submit the form nft.storage would pull the file into your account as it would had you uploaded an image.

**Comment by dchoi27** [comment]
Hey there! Totally agreed on your thoughts, "permanence" for NFTs on any network is impossible, and though we're trying to provide long-term storage for NFTs for our users, we definitely need owners to take responsibility for storing local copies, storing in multiple places, etc. 

We actually do have the [IPFS pinning services API](https://ipfs.github.io/pinning-services-api-spec/) implemented for NFT.Storage, and this allows you to pin content via its CID. This isn't open to the public to limit abuse, but we're implementing #1025 to make it easy for folks to request access. You can email us at support (at) nft.storage with some example CIDs you're trying to pin and your public profile in the NFT space and we can give you access.

The easiest way to use the Pinning Services API would be then to use IPFS Desktop to add or download the NFTs with your account, and then set up NFT.Storage as a pinning service (instructions [here](https://docs.ipfs.io/how-to/work-with-pinning-services/#use-an-existing-pinning-service)). We can add instructions for this in the NFT.Storage docs - it's a great idea! cc @yusefnapora

**Comment by Oosik** [comment]
Wow, thank you. I'll check this out!
