### ISSUE TITLE
Pin Status "Queued" take long time

### ISSUE THREAD

**Issue by SomeBoyFrom** [nftstorage/nft.storage#1142]
Hi guys, Please help to upload my file to nft.storage
I've tried 2 MB file to test if it worked, but the Pin status showed "Queued"
Ipfs version: go-ipfs version: 0.11.0 / Repo version: 11
Line command: `ipfs pin remote add CID --service nft.storage`
Thank you

**Comment by dchoi27** [comment]
Hey there - pin status being queued doesn't mean that your data hasn't been uploaded - in the vast majority of cases the file is stored on our infrastructure, but it might take some time for it to be fully replicated. How long were you waiting for? Also, if you could share the CID then that could be helpful.

**Comment by SomeBoyFrom** [comment]
> Hey there - pin status being queued doesn't mean that your data hasn't been uploaded - in the vast majority of cases the file is stored on our infrastructure, but it might take some time for it to be fully replicated. How long were you waiting for? Also, if you could share the CID then that could be helpful.

Thanks for your response. I deleted the previous file because it took more than 4 hours to appear, and it didn't.
I have now tried another 14Kib file, and this is the CID "QmaifZNGj8VveCRno7KjuizanUuwWnAsZsmvkjCbsyhB1U"

![Screenshot from 2022-01-24 21-32-54](https://user-images.githubusercontent.com/84801446/150860747-c9283d62-2ed7-4efa-990b-3b25bbbdd498.png)

I have another question, please. My nft files folder contains png files of 3.7 GB. Can I upload this large file without any problems?
Thank you.

**Comment by scottlove** [comment]
I am seeing same issue.  Queued for over 24 hours

**Comment by dchoi27** [comment]
Hm, I think something might be wrong with the updating job for pin status. You don't have to concern yourself if you've uploaded to NFT.Storage directly (content is still safe and available on NFT.Storage - the status just needs to get updated).

If you're using the pinning service API, if it's still showing 0B after a while then that means the content couldn't be found on the network (so your node wasn't available or providing records to the DHT).

**Comment by dchoi27** [comment]
#1172 should resolve this in the coming days (bit of a backup in the queue). Again, your data should still be available unless you're using the pinning service API and NFT.Storage was never able to find your content (e.g. your node is offline).

**Comment by scottlove** [comment]
Thanks David!
