### ISSUE TITLE
Metadata API documentation updates

### ISSUE THREAD

**Issue by alanshaw** [nftstorage/nft.storage#115]
Tracking tasks from here https://github.com/ipfs-shipyard/nft.storage/pull/56#pullrequestreview-653380390

* [x] We need an update to the [OpenAPI schema](https://github.com/ipfs-shipyard/nft.storage/blob/main/packages/website/public/schema.yml)
* [x] We should alter the docs for the JS client on the homepage to use the new `store` method
* [x] We should change the example [here](https://github.com/ipfs-shipyard/nft.storage/tree/main/packages/client#usage) to use the new API
* [x] We should add example(s?) [here](https://github.com/ipfs-shipyard/nft.storage/tree/main/packages/client/examples)
    * https://github.com/ipfs-shipyard/nft.storage/pull/108

**Comment by dchoi27** [comment]
@alanshaw can this be closed?

**Comment by Gozala** [comment]
Last piece was done in https://github.com/nftstorage/nft.storage/pull/693 closing this
