### ISSUE TITLE
feature request: allow for empty directory creation

### ISSUE THREAD

**Issue by Brodan** [nftstorage/nft.storage#1157]
I'm trying to use the [storeDirectory.js](https://github.com/nftstorage/nft.storage/blob/main/packages/client/examples/node.js/storeDirectory.js) example, but it seems that `storeDirectory` can only be called if you have files to upload. Trying to use it currently gives me the following error:

`Error: Total size of files should exceed 0, make sure to provide some content`

There are use cases where I should be able to create a directory without having to also put something in it (such as when I need to set a baseURI for my metadata, but haven't minted anything yet so I don't have the actual metadata to upload.

**Comment by alanshaw** [comment]
You could use the empty CID for this [`bafkqaaa`](https://cid.ipfs.io/#bafkqaaa) (zero-length "identity" multihash with "raw" codec) - no need to upload anything to NFT.Storage.

**Comment by dchoi27** [comment]
Closing this, feel free to reopen if you feel like there's a key case that isn't covered!
