### ISSUE TITLE
Uploading folders.

### ISSUE THREAD

**Issue by Fingers007** [nftstorage/nft.storage#1164]
Hi NFT Storage, Id like to ask how I can upload a folder with 10k NFT images? At the moment I can only see a way to upload individual files?
Many thanks,
Stephen.

**Comment by dchoi27** [comment]
Is your question about uploading via the website? If so, you can't currently upload folders (tracked in #1047). You can definitely upload folders using the `storeDirectory()` method in the Javascript client though: https://nftstorage.github.io/nft.storage/client/classes/lib.NFTStorage.html#storeDirectory

There's also this in the works for a no-code solution to upload large directories: #1015 We really want to make it easy to support folks doing 10K drops! So stay tuned.

**Comment by dchoi27** [comment]
Check out NFT UP for storing large directories! https://nft.storage/blog/post/2022-04-05-announcing-nftup/
