### ISSUE TITLE
Add tooltip descriptions for columns to Web UI /Files page

### ISSUE THREAD

**Issue by dchoi27** [nftstorage/nft.storage#1174]
In Web3.Storage, we have tooltip descriptions for what various column means to preemptively answer questions about things like pin status.

Can we just replicate this in NFT.Storage? We don't have to add the Availability column for now (so just descriptions for CID, Pin Status, Storage Providers).

- [ ] CID column header's tooltip:  "The content identifier for a file or piece of data.  Learn more"  (Learn More should link to https://nftschool.dev/concepts/content-addressing/ )
- [ ] Pin Status column header tooltip:  "Reports the status of a file or piece of data stored on the IPFS Cluster. Status might not be fully up-to-date. Data is still available even when still in Queued state."
- [ ] Storage Providers column header tooltip:  "Service providers offering storage capacity to the Filecoin network. Learn more"  (Learn more should link to https://nftschool.dev/concepts/content-persistence/ )

![image.png](https://images.zenhubusercontent.com/5fa04bd64afb77249c77235b/afd6685d-fa5d-4b75-97ee-a197d16a8769)

**Comment by JeffLowe** [comment]
@dchoi27 Itemized the specific tooltip updates needed in the description above.  Please review and let me know if that sounds good (particularly the learn more links).

**Comment by dchoi27** [comment]
LGTM!
