### ISSUE TITLE
Report pinned status from API if active FIL deals

### ISSUE THREAD

**Issue by alanshaw** [nftstorage/nft.storage#1177]
Occasionally pin status syncing with cluster might fall behind, however if a Filecoin deal has been made and is active it means that we _do_ have the data and it's more than likely there is just a lag in the status being synced.

In the status, check and list API we can could flip the ststus to 'Pinned' if we find this is the case.

**Comment by ribasushi** [comment]
You could do it earlier, as soon as `size_actual` is available: there's no way for cargo to compute it without local access to the full dag.

**Comment by dchoi27** [comment]
Closing because this would give too inconsistent of results. Have the bulk status query API from Cluster so this should be mitigated.
