### ISSUE TITLE
Error uploading: The requested file could not be read, typically due to permission problems that have occurred after a reference to a file was acquired

### ISSUE THREAD

**Issue by alessandrohk** [nftstorage/nft.storage#1184]
Hello, I am trying to upload a CAR file (8.5GB) with the browser upload but i keep getting the following message when i press upload:

Error uploading: The requested file could not be read, typically due to permission problems that have occurred after a reference to a file was acquired

this doesnt happen with smaller files,  is there a way to fix this issue?

Please let me know

**Comment by dchoi27** [comment]
Hey there! Hm - super odd, it might be hard for us to reproduce. Could you share what browser you're using, where is the file coming from (off your computer or potentially a network drive?), and even share the file if you're able to?

**Comment by alessandrohk** [comment]
Hi,
Im using the latest version of google chrome on a mac, and the files are 10kpng stored in a folder on my desktop 8.5gb

also when i tried to convert a folder with less images in it to a .car and i tried to upload it, i had no issues. This makes me think that it could be a file size issue

**Comment by alessandrohk** [comment]
![D52DAFC6-1E78-4F9C-8AE7-93D899CE59D4](https://user-images.githubusercontent.com/98262761/151645261-da35b608-1a0e-417c-9794-9d1a29ff13b2.jpeg)

**Comment by alanshaw** [comment]
This is almost certainly because the library will try to buffer the entire contents of that 8GB directory into memory before it is sent. It's browser dependant but I believe Chrome has 1-2GB memory limit and I believe this is the root of the the error message you're receiving.

We're building a [desktop uploader](https://github.com/nftstorage/nft.storage/issues/981) and also making changes under the hood to allow full streaming of the content.

**Comment by alanshaw** [comment]
Please follow along with https://github.com/nftstorage/nft.storage/issues/981 for updates on the large file uploader.

The other way is to use the [client library](https://www.npmjs.com/package/nft.storage) in Node.js to upload the files, which uses the `/tmp` directory to store the created DAG before sending it. Example https://github.com/nftstorage/nft.storage/blob/main/packages/client/examples/node.js/storeDirectory.js
