### ISSUE TITLE
Update Grafana Cluster space remaining graph to point to nft3

### ISSUE THREAD

**Issue by dchoi27** [nftstorage/nft.storage#1202]
This one: ![image.png](https://images.zenhubusercontent.com/5fa04bd64afb77249c77235b/18e03bea-41a0-4978-8437-d8838ae28699)

My heart jolts every time I see the number low, but I think it's still pointing to the first Cluster 😅

**Comment by vasco-santos** [comment]
Just updated the grafana query to use nft3
