### ISSUE TITLE
building site

### ISSUE THREAD

**Issue by NotGoodInternet** [nftstorage/nft.storage#1205]
I have a quick question if you don't mind. If I add my site files to https://nft.storage/ which I built using publii https://getpublii.com/ can I then use a domain from unstoppable domains to resolve using Cloudflare https://www.cloudflare.com/en-gb/distributed-web-gateway/ so that users who visit the site in a normal browser can see the content as well as those using an ipfs browser, is that possible

**Comment by dchoi27** [comment]
Hi there - yes, something like that should be possible. But please don't host your website on NFT.Storage, unless you are making an NFT for your website code. NFT.Storage is a service for hosting off-chain NFT data - other types of data are generally not allowed.

You can use our sister project, [Web3.Storage](https://web3.storage/), to host your website, or a service designed for this kind of use case like [Fleek](https://fleek.co/).
