### ISSUE TITLE
Implement PSA allowlist solution in nft.storage then port to Web3 

### ISSUE THREAD

**Issue by dchoi27** [nftstorage/nft.storage#1213]
Alan approves Joe's recommended approach to managing pinning allow list.  
We'll implement in nft.storage first (get it integrated with admin.storage), THEN port this approach over to Web3 and integrate with admin. 
## Notes
Makes it easier to integrate with Admin.Storage, doesn't require a deploy to update anymore
https://github.com/web3-storage/web3.storage/pull/705

Joe has a slightly different, but more preferred solution, let's do that

**Comment by JeffLowe** [comment]
with recent release, the PSA management is in admin.storage
