### ISSUE TITLE
NFT.Storage gateway docs

### ISSUE THREAD

**Issue by dchoi27** [nftstorage/nft.storage#1217]
Quick explainer in Retrieve section about NFT.Storage gateway and how to use.

**Comment by dchoi27** [comment]
https://www.notion.so/pl-strflt/NFT-Storage-Gateway-details-soft-launch-50bd61e3258a4b60a1cf0a1fa91318ea should be useful too

**Comment by vasco-santos** [comment]
We should have:
- a glimpse of https://docs.ipfs.io/concepts/ipfs-gateway/#overview as well as different types of resolutions (path vs subdomain).
- our rate limits https://github.com/nftstorage/nft.storage/tree/main/packages/gateway#rate-limiting

Probably some examples using CURL would be nice
