### ISSUE TITLE
For /docs, Consider getting typedoc to output markdown in embed

### ISSUE THREAD

**Issue by JeffLowe** [nftstorage/nft.storage#1221]
Any chance we can get typedoc to output markdown in embed here? https://github.com/nftstorage/nft.storage/pull/1168#issuecomment-1027849639

**Comment by dchoi27** [comment]
@yusefnapora can we also make the navbar more clear (this is pretty confusing right now)
![image.png](https://images.zenhubusercontent.com/5fa04bd64afb77249c77235b/c870bde7-0e84-461f-a442-d512ca0ca712)
Section should probably be called "Javascript client library," having the subsections just be called "client" and "lib" is pretty confusing, and there should be something linking to the HTTP docs as well.

**Comment by dchoi27** [comment]
@yusefnapora one more thing - before this lands, can we ASAP at least make sure the client and HTTP docs are linked in these places? realizing that `storeDirectory` and `storeBlob` aren't referenced anywhere on the docs page, and we should point folks to the client docs to at least see the set of store methods we have.

**Comment by JeffLowe** [comment]
This is resolved.
