### ISSUE TITLE
How to get the url of files distinctly when you upload multiple files at once?

### ISSUE THREAD

**Issue by newshahn** [nftstorage/nft.storage#1238]
I used nft.storage to upload two files and then i used the response of upload request to store my nft with the metadata. Now my question is, is there any way to get the url of files i uploaded? because now, i get a url for both of them and i have to open that url to see the url of each of those files.

**Comment by dchoi27** [comment]
Hey there - by "uploading multiple files at once," do you mean uploading a directory? If so, you can refer to specific files within the directory using relative pathing, similar to how it would work in a traditional file system (so `<directoryCID>/file1.jpg`, `<directoryCID>/file2.json`, etc.)
