### ISSUE TITLE
Clarify NFT.Storage funding story on homepage

### ISSUE THREAD

**Issue by dchoi27** [nftstorage/nft.storage#1239]
Update copy on homepage subtitle to align with this mock https://user-images.githubusercontent.com/9259185/155785570-c9db7f2b-a6dc-403c-a8b8-68f69b724235.png

## Original note
Asked Design team to provide a mock on how to do this https://github.com/protocol/design-shop/issues/1308

**Comment by dchoi27** [comment]
Hey @JeffLowe this came back from the design team - can we implement this at some point this or next sprint? https://user-images.githubusercontent.com/9259185/155785570-c9db7f2b-a6dc-403c-a8b8-68f69b724235.png

**Comment by JeffLowe** [comment]
Yeah, I'll put in shortlist and assign to Munns.
To verify, those links should lead to https://protocol.ai/
and to https://web3.storage/
Correct?

**Comment by dchoi27** [comment]
exactly!
