### ISSUE TITLE
skip running release-please on PRs from forks

### ISSUE THREAD

**Issue by yusefnapora** [nftstorage/nft.storage#1242]
This will avoid errors like [this one](https://github.com/nftstorage/nft.storage/runs/5071360929?check_suite_focus=true) on https://github.com/nftstorage/nft.storage/pull/1240 - they're not a blocker, since the action will succeed once the PR is merged. But it will be nice to get rid of the red X 😄

**Comment by gobengo** [comment]
@yusefnapora Currently this website.yml 'release' job is run on all PRs into main
* Just checking... but are there times where we do expect this to work? i.e. releasing a feature-branch?
* Assuming yes, the smallest change here would be to keep running the release job on PRs to main, *unless* the source branch is on a repo not-owned by github.com/nftstorage (i.e. exclude forks)

**Comment by gobengo** [comment]
candidate solution: https://github.com/nftstorage/nft.storage/pull/1698
