### ISSUE TITLE
Need help with ipfs upload of 9GB

### ISSUE THREAD

**Issue by Ysh-22** [nftstorage/nft.storage#1281]
Firstly, hats off to you guys for trying to provide the world with free NFT storage. It is amazing what you guys are doing. 
Coming to the trouble. I have created a total of 9.9GB of NFTs that has to be stored on NFT.storage. I've tried using https://car.ipfs.io/ but chrome couldn't process the amount of data and the website kept crashing. So I tried using other methods to create a .CAR file out of the 9 Gigs of images, but I'm having trouble with that. It seems it doesn't recognize 'ipfs-car' as a function, which is used to pack the content. Please help me out here. It's just a beginner in the world of programming, but I'm willing to learn.
I just need to upload my NFTs to nft.storage and get the CID, then I'm sorted. Thanks in advance people, please help me out.
Also, attaching a screenshot of the issue.

![githelp](https://user-images.githubusercontent.com/99244035/152941198-0f710141-8bc7-4826-bfa7-1cb3aa539b5b.png)

**Comment by Ysh-22** [comment]
Update: I'm able to convert my files to .CAR format but uploading to nft.storage give me the following error
Error uploading: The requested file could not be read, typically due to permission problems that have occurred after a reference to a file was acquired.
Also, there is a bug in the website. The error cannot be read.

![image](https://user-images.githubusercontent.com/99244035/152997547-b5e2f2ff-c9f2-4bf2-bd66-cd890a81cc89.png)

**Comment by Ysh-22** [comment]
i tried both brave and chrome browsers

**Comment by dchoi27** [comment]
(Note for the team, working with this person on Discord)

**Comment by alanshaw** [comment]
I believe this is simply because the files are too big to fit into the memory the browser allocated to the site. Currently when creating a DAG we have to buffer the whole thing into memory so currently the only way to import big files like this is programmatically using Node.js...or split into multiple smaller uploads.
