### ISSUE TITLE
Update footer with new links and taller space

### ISSUE THREAD

**Issue by JeffLowe** [nftstorage/nft.storage#1295]
- [x] update nft.storage site footer with logos and links to  Twitter https://twitter.com/nft_storage , Github https://github.com/nftstorage , Discord https://discord.com/channels/806902334369824788/831502708082081822
- [x] Increase height/size of footer, possible relayout to accommodate this and possibly more future content.  See https://ipfs.io/ for possible inspiration)
- [x] ensure there's a space between heart icon and "Protocol Labs" 

- [ ] Add Protocol Labs logo that links back to site https://protocol.ai/ (similar to treatment in ipfs footer https://ipfs.io/ )

## current nft.storage footer that needs updating
![Screen Shot 2022-02-08 at 11 53 10 AM](https://user-images.githubusercontent.com/2078567/153046776-3b82337a-913c-4926-b030-b271289f2277.png)

**Comment by JeffLowe** [comment]
#1336 appears to have added most of the above, but we will still need to address: 
- ensure there's a space between heart icon and "Protocol Labs"
- Add Protocol Labs logo that links back to site https://protocol.ai/ (similar to treatment in ipfs footer https://ipfs.io/ )

**Comment by JeffLowe** [comment]
@cmunns 2 items remain on this one (see description)

**Comment by cmunns** [comment]
The heart icon already had the space added. So just the one item for adding the logo is what I fixed.

**Comment by JeffLowe** [comment]
Heart icon apparently is edge case.  Space is there, but on very large screens, heart icon renders slightly larger (see https://github.com/nftstorage/nft.storage/issues/1448) 
But to confirm, the space is indeed there :)
