### ISSUE TITLE
Improve visibility of primary logo

### ISSUE THREAD

**Issue by JeffLowe** [nftstorage/nft.storage#1307]
Logo is very difficult to visually discern on several pages of nft.storage. Recommending updates to improve readability and discernability. 
![Screen Shot 2022-02-08 at 1 53 16 PM](https://user-images.githubusercontent.com/2078567/153065048-3c6f6012-c002-4fda-87a9-4181198c8e0b.png)
![Screen Shot 2022-02-08 at 1 54 01 PM](https://user-images.githubusercontent.com/2078567/153065116-20b0a805-f501-41d4-a930-7a1ef7e4be76.png)
![Screen Shot 2022-02-08 at 1 54 28 PM](https://user-images.githubusercontent.com/2078567/153065191-84316130-98ff-4785-ad61-b3e9a80f8492.png)

**Comment by cmunns** [comment]
<img width="1728" alt="Screen Shot 2022-02-09 at 9 20 39 AM" src="https://user-images.githubusercontent.com/1189523/153254933-a5cb5cc3-8342-4af4-840d-96a46e497c3e.png">
<img width="1727" alt="Screen Shot 2022-02-09 at 9 13 57 AM" src="https://user-images.githubusercontent.com/1189523/153254941-e910bf90-1b2b-4f62-9ab4-6b2d88d2058e.png">
<img width="1727" alt="Screen Shot 2022-02-09 at 9 13 47 AM" src="https://user-images.githubusercontent.com/1189523/153254951-564c90b2-d591-4843-b3f2-eea8d60260a4.png">
<img width="1727" alt="Screen Shot 2022-02-08 at 11 26 37 AM" src="https://user-images.githubusercontent.com/1189523/153254953-d9d52a67-ed81-4d28-b7e3-8e0f009ca481.png">
