### ISSUE TITLE
Capitalization of URI or URL in Files page

### ISSUE THREAD

**Issue by dchoi27** [nftstorage/nft.storage#1310]
In the Files page listing on the website, not sure if it's supposed to be URI or URL (think the former?), but capitalization is still off. Can we do a quick fix? ![image.png](https://images.zenhubusercontent.com/5fa04bd64afb77249c77235b/56b6a149-d274-4ef6-8117-27eacc7fcee3)

**Comment by JeffLowe** [comment]
Closing this out.  A;lready ticketed here https://github.com/nftstorage/nft.storage/issues/1185
