### ISSUE TITLE
Feature request: Access settings per API key

### ISSUE THREAD

**Issue by pichiste** [nftstorage/nft.storage#1314]
It would be very useful to be able to have access settings for API keys.

Two specific ones come to mind:

1) Ability to restrict what domains can utilize a given API key. The equivalent of setting `Access-Control-Allow-Origin` to a specific origin.

2) Ability to restrict which endpoints a given API key can utilize.

**Comment by dchoi27** [comment]
These are great ideas! We're implementing UCAN authorization for our tokens (#851), and (2) above should be taken care of by the work there, and once that's implemented, we can add (1) as well.

cc @hugomrdias
