### ISSUE TITLE
Fix blurry NFT.Storage logo in left of navbar at top

### ISSUE THREAD

**Issue by dchoi27** [nftstorage/nft.storage#1324]
Asking Design to get us a better resolution version of it

**Comment by JeffLowe** [comment]
Might consider using @cmunns ideas on logo mark (see here https://github.com/nftstorage/nft.storage/issues/1307#issuecomment-1034007070 ).  It also reenforces the .storage domain as the brand.

**Comment by dchoi27** [comment]
Oh yeah I'm good with that! Can close this one
