### ISSUE TITLE
car.ipfs.io not taking my images to convert to .car

### ISSUE THREAD

**Issue by Ysh-22** [nftstorage/nft.storage#1334]
I have 9.4 GB of images to be converted to car file but the website mentioned on nft.storage (car.ipfs.io) keeps crashing after I selected my files and tried uploading. I have used Chrome Canary, Chrome, Brave as well as Edge browser but nothing seems to be working.
Need help!

![IMG20220210223442.jpg](https://user-images.githubusercontent.com/99244035/153458784-3e8e1aee-4257-4cd3-91db-28e141b4e4e1.jpg)

**Comment by Ysh-22** [comment]
I made a car file from the code on GitHub. Tried uploading to nft.storage but i get the following error.

![IMG-20220210-WA0017.jpg](https://user-images.githubusercontent.com/99244035/153459597-b749fec1-8a50-441a-aff1-88db9a55278f.jpg)

**Comment by dchoi27** [comment]
Hey, yeah the file is too big to convert into a CAR or upload in the browser due to browser memory limitations, but sounds like you figured out how to create a CAR in your local environment.

**Comment by dchoi27** [comment]
Check out NFT UP for storing large directories! https://nft.storage/blog/post/2022-04-05-announcing-nftup/
