### ISSUE TITLE
Issue with IPFS in queue status for over 48 hours

### ISSUE THREAD

**Issue by winterfate17** [nftstorage/nft.storage#1335]
Hi - I'm having an issue trying to mint an NFT project. I uploaded the image IPFS car and the metadata IPFS car at the same time and the image car worked fine. The metadata car is still in queue phase going on 72 hours. Is this normal or is something wrong?

**Comment by dchoi27** [comment]
What do you mean queue phase (are you referring to the Pin Status)? Are you able to open your file? If not, have you tried reuploading it?

**Comment by vasco-santos** [comment]
@winterfate17 If you mean Pin Status, could you share your CID for us to diagnose? (You can pm me in nft.storage discord if you are not comfortable to share the CID in the open)
