### ISSUE TITLE
Remote pinning on IPFS Desktop doesn't work if no files have yet been added via PSA

### ISSUE THREAD

**Issue by dchoi27** [nftstorage/nft.storage#1337]
For some reason, if no files have yet been added to an account (API token? not sure) via the pinning services API (even if that account has been added to the allowlist), IPFS Desktop won't let you add any files since it gives an error (says `Failed to fetch` under `Number of pins`).

@alanshaw dug into it and it might be because NFT.Storage API returns a 404 when listing number of pins if there are 0 pins with an NFT.Storage account, rather than what IPFS Desktop expects (probably an empty array).

**Comment by alanshaw** [comment]
https://github.com/nftstorage/nft.storage/blob/d57c7383708e23dd02e8d0dff8be82ca2e28bca6/packages/api/src/routes/pins-list.js#L32-L43
