### ISSUE TITLE
For niftysave modify nft.storage api endpoint to accept cid instead of upload

### ISSUE THREAD

**Issue by JeffLowe** [nftstorage/nft.storage#1364]
modify nft.storage api endpoint to accept cid instead of upload

This Covers case where it already exists on ipfs, but needing to add to nft.storage
Reference https://github.com/nftstorage/nft.storage/issues/626 
This was addressed in the shortterm with #1363

**Comment by alanshaw** [comment]
Just use the [Pinning Service API](https://ipfs.github.io/pinning-services-api-spec/) which NFT.Storage implements.
