### ISSUE TITLE
JS API Usage - Issue with Larger Files: ipfs cat /ipfs/<CID>: unknown node type

### ISSUE THREAD

**Issue by woodwardmatt** [nftstorage/nft.storage#1367]
Hey All, 

I'm seeing a similar issue to this: https://github.com/nftstorage/nft.storage/issues/216

My code / approach works for small (e.g. 10KB) files but not for slightly larger files (e.g. ~3MB).

Please see this CID as an example: bafyreiat7ny3clujzhpan2v7qb7hktnjuxewq435d7yfhxt7tpfsqq4ezq

- [Link](https://ipfs.io/ipfs/bafyreiat7ny3clujzhpan2v7qb7hktnjuxewq435d7yfhxt7tpfsqq4ezq)

This does store the metadata & file at: 

- [Metadata](https://ipfs.io/ipfs/bafyreiat7ny3clujzhpan2v7qb7hktnjuxewq435d7yfhxt7tpfsqq4ezq/metadata.json)
- [File](https://ipfs.io/ipfs/bafybeicsujlqbs22fhimqnmsbrsipnaot6z5zit6dgpmb47lnq26avtfs4/006-I-Am-Light-Full.png)

But the base CID url wont automatically resolve to the file as with smaller files. Any thoughts?

Here's how I upload: 

```
    const metadata = await storageclient.store({
        name: nft.name,
        description: nft.description,
        creator: creator,        
        image: new File(
          [await fs.promises.readFile(mediaPath + nft.image)],
          nft.image,
          { type: nft.type }
        ),
        type: nft.type,    
      })
```

**Comment by woodwardmatt** [comment]
I later identified that I has a # symbol at the start of the filename and removing this seemed to resolve the issue. It also seemed I needed to allow a few hours for the image to sync across to the nodes a wallet was referencing.

**Comment by adzharkahar** [comment]
@woodwardmatt were you able to estimated how many hours needed for the image to sync ?
