### ISSUE TITLE
docs: should include how-to for solana / metaplex

### ISSUE THREAD

**Issue by yusefnapora** [nftstorage/nft.storage#1374]
I started working on this last week, but realized it's not tracked anywhere.

I'd like to add a page to the nft.storage docs on using NFT.Storage with Solana / Metaplex, with an example of using the candy-machine CLI to upload.

Things that would be good to include:

- [ ] link to metaplex metadata standard
- [ ] example with NFT image & metadata upload
- [ ] link to metaplex-auth repo and explain that it can be used independently
- [ ] mention Magic Eden as a partner

Once this is merged, we can make a PR to the metaplex docs to link to our page.

**Comment by dchoi27** [comment]
@yusefnapora Is there a PR for this?
