### ISSUE TITLE
Add Project Galaxy logo to homepage

### ISSUE THREAD

**Issue by dchoi27** [nftstorage/nft.storage#1377]
Note:  Homepage should have shorter list than the Stats page (which has full list) 

## Early Notes
https://www.figma.com/file/HhOpjYpzzEXmtvSnVD1b8p/Project-Galaxy-Brand-Kit?node-id=121%3A17

Can wait until we have another logo to add so we can add in pairs

Also could consider replacing a logo on the homepage with this logo, and then just have all logos get added to the upcoming public stats page (#1074)

**Comment by JeffLowe** [comment]
Might consider moving to a 3 column and increasing size slightly (like the tablet breakpoint now).  But, I'll leave it to @cmunns to consider best solution.
