### ISSUE TITLE
Client side tokens and scoped tokens

### ISSUE THREAD

**Issue by Ronak-59** [nftstorage/nft.storage#138]
Just tried to use the JS library and noticed that the API calls exposes the `API_TOKEN` in the header field "Authorization" as also mentioned in the [docs](https://nft.storage/#docs).

This `API_TOKEN` can then be used by anyone to create a client and execute [`client.delete`](https://ipfs-shipyard.github.io/nft.storage/client/classes/lib.nftstorage.html#delete) function maliciously, thereby, deleting all the NFT IPFS files in the dApp. 

With the exposed `API_TOKEN`, any user can get admin access to the data associated with it, right?

If so, this library is only suitable for use in a backend environment.

Please correct me if I'm wrong or if I'm missing something here.

**Comment by alanshaw** [comment]
Yes - this is a known issue 😄! An nft.storage API key **should not** be **bundled** with a web application. A web application _could_ request a user obtain a key from nft.storage for use with the app though.

We're working to allow client side wallet auth so this flow will be smoother/safer in the future.

**Comment by Ronak-59** [comment]
@alanshaw In that case, maybe the landing page  / docs should not mention that the library can be used in the browser side until this is fixed? Or maybe there should be a note mentioned?

> A web application could request a user obtain a key from nft.storage for use with the app though

You mean asking users for nft.storage key everytime they visit the dApp site? That would be a bad UX for users of NFT applications. Web3 applications are already confusing for non-technical users as they struggle to learn Metamask, etc and to not make it more complicated, we shouldn't ask for nft.storage key for every visit.

Extension is a good idea because not only it would solve the issue but it will help the solution be less centralised. For example, users will be in control of storing and deleting their own content. Applications shouldn't have this control for better decentralisation.

**Comment by alexkeating** [comment]
Is there any place to track the progress of resolving this issue or something with the preferred implementation to help guide a contribution? I would love to use this package in a project I am working on

**Comment by alanshaw** [comment]
@alexkeating not just yet, we're currently planning for this and will hopefully be working to resolve it soon.

**Comment by Kirbyrawr** [comment]
Hi there, is there any info regarding this, or an alternative to how to workaround the issue?

Thanks in advanced!

**Comment by dchoi27** [comment]
Hey folks - sorry forgot to update, but you can use https://github.com/nftstorage/ucan.storage to delegate write-only tokens to end-users! Closing this issue
