### ISSUE TITLE
API users with blocked API key should receive custom error message

### ISSUE THREAD

**Issue by JeffLowe** [nftstorage/nft.storage#1382]
When users with blocked keys use API they should get a specific error message instead of a generic message. It should inform them the API key is blocked, and to use another api key.

**Comment by olizilla** [comment]
I agree with the premise, but I'm just tyring to get my head around when we would block an API token but not a user? I could imaging someone contacting us saying "i published my key please kill it", but then they could delete it themselves. Perhaps if we got automated alerts from github telling us a key was published... I'm new to the admin.storage functionality, so I'm just curious if we are actually blocking user api keys at the moment, or if we mainly just hit the "block user" button.

It's worth unpacking the intersection of "blocked user" and "blocked api key" as we have a curious _feature_ currently that a blocked user is still allowed to log in, list things and, delete things.

@dchoi27 what steps do you normally take when we see malicious activity? Do you block users or api keys?
