### ISSUE TITLE
Feature request: Http gateway URI for the image Parameter

### ISSUE THREAD

**Issue by bakeiro** [nftstorage/nft.storage#1387]
### Hi!
First of all, thanks for creating this tool, and give it for free to the developers and community 🙌

Although I'm very happy with the tool I'm missing just one thing: Be able to use HTTP gateway in the image property.

I know that docs encourage to use the ipfs uri (because it's the safest option) but if I use the http gateway, I can obtain the ipfs URI later (from the CID) plus any browser, or wallets can display the NFT content automatically (so good user experience).

In case that the choosed HTTP gateway goes down, I can upload another file with another HTTP provider, and then use it later in the existing NFT (by changing the tokenURI in the contract's state) so no downsides plus user can see the NFT in the wallet :)

### Feature request:
Would be nice to have, at least, the possibility to specify a http gateway, which, by default is disabled, but developer can set it on, by specifying manually the gateway, also property can be called something like `useRiskyHTTPProvider`, so developer it's aware that using a HTTP gateway can have some downsides.

With that this tool would be perfect (for my use case)
edit: grammar and text style

**Comment by bakeiro** [comment]
Ah I see... so if I'm not wrong I should: 
- I have to upload the image using `storeBlob` (for example)
- Get the CID from the image
- Generate the http gateway
- Generate the JSON with the image gateway and all the info
- Then use the send an HTTP with post with the JSON as data to the `https://api.nft.storage` endpoint
- Get the CID?

If I understood correctly this is the way, would be nice some JS examples or some easy method to do it quickier, but in any case if it's doable it's fine ;) (but I would prefer just one method parameter or something 😅)

**Comment by jchris** [comment]
Thanks for the feedback. You are correct that's how it'd be done today. We'll keep thinking about this as we build -- there are some emerging standards that would make sense to store the `ipfs://` alongside the gateway url, so your use case would be one reason for us to include them.

**Comment by bakeiro** [comment]
I see, I hope to see that feature included some day, in the meantime I'll will do it via API, thanks for your time and feedback :)

**Comment by bakeiro** [comment]
Just in case someone checked this issue and needs this featured, just change the following line of code and then you can get easily the HTTP gateway just by using the nft.store method (so, no need to adapt the script which uses nft.storage package)

changing this line:
https://github.com/nftstorage/nft.storage/blob/main/packages/client/src/token.js#L116
