### ISSUE TITLE
Add triggers to sync updated_at from pin and upload

### ISSUE THREAD

**Issue by hugomrdias** [nftstorage/nft.storage#1388]
context
```sql
explain analyze SELECT
            ds.source_cid AS source_key,
            GREATEST(
              ds.updated_at,
              (
                SELECT MAX(p.updated_at)
                  FROM pin p
                WHERE
                  p.content_cid = ds.content_cid
              )
            ) AS entry_last_updated
          FROM upload ds
        WHERE
          ds.updated_at > '2021-02-11'
;
```
this is really slow now to make faster we need to do something like this, until we have a better permanent solution

```sql

CREATE OR REPLACE
  FUNCTION update_upload_timestamp_by_content_cid() RETURNS TRIGGER
    LANGUAGE plpgsql
AS $$
BEGIN
  UPDATE upload SET updated_at = NOW() WHERE upload.content_cid IN ( NEW.content_cid, OLD.content_cid );
  RETURN NULL;
END;
$$;
CREATE TRIGGER trigger_upload_update_on_related_pin_change
  AFTER INSERT OR UPDATE OR DELETE ON pin
  FOR EACH ROW
  EXECUTE PROCEDURE update_upload_timestamp_by_content_cid()
;
```

**Comment by alanshaw** [comment]
We lose the meaning of `updated_at` in the `upload` table.

**Comment by alanshaw** [comment]
As per [discussion on slack](https://filecoinproject.slack.com/archives/C02BZPRS9HP/p1644659206413519).

A `completed_at` (name TBC) on `upload` which would be updated when the upload is properly pinned/fully received looks like it might work.

We need to specify exactly how this works and verify with riba that it would definitely solve the issue.

**Comment by alanshaw** [comment]
@ribasushi is going to see if he can do some optimisation on his side, if that is not good enough we can persue https://github.com/nftstorage/nft.storage/issues/1428 to fix.
