### ISSUE TITLE
"Error: 526" with JS client library

### ISSUE THREAD

**Issue by vale-dinap** [nftstorage/nft.storage#1396]
I had to upload a series of 10000 images to IPFS and so wrote a script that wraps some of the functions of the JS library into a for loop. It all went well with nearly 90% of the images, until the process suddenly failed returning the error below:

Error: 526: Origin SSL Certificate Error
    at pRetry.retries (file:///C:/Users/valer/Desktop/LOLPOPS/node_modules/nft.storage/src/lib.js:159:21)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async RetryOperation._fn (C:\Users\valer\Desktop\LOLPOPS\node_modules\p-retry\index.js:50:12) {
  attemptNumber: 6,
  retriesLeft: 0
}

I retried multiple times but keeps doing the same.
Also ensured both the integrity of the file I am attempting to upload and that the full size of my folder is smaller than the maximum account allocation.

What could be the cause?

![2022-02-17 193915](https://user-images.githubusercontent.com/69582234/154549883-a09e2661-1249-418f-be7d-142ffc4baf88.png)

**Comment by njovy** [comment]
I am also having this issue.

**Comment by vale-dinap** [comment]
Update: also having the same issue with ANY file through the upload page https://nft.storage/new-file/

**Comment by Brodan** [comment]
I'm having this issue right now with any file I try to upload. things were working fine as recently as yesterday.

**Comment by gurleynm** [comment]
Also in the same boat. Things were working all day yesterday as well. Now I can't upload any file, regardless of whether I use the upload page or API.

**Comment by antonio-fr** [comment]
Same issue : POST /upload
-> {'ok': False, 'error': {'code': 'Error', 'message': '526: Origin SSL Certificate Error'}}

**Comment by Brodan** [comment]
their status page is finally reflecting this: https://status.nft.storage/

**Comment by gurleynm** [comment]
I'm now able to upload via the upload page. Testing the API now

**Comment by vale-dinap** [comment]
The JS API seems to work as well, I'll give a shout if it fails again

**Comment by vasco-santos** [comment]
Hey folks! We had this issue and it was fixed as mentioned in status page. Thanks for the reports
