### ISSUE TITLE
Timestamp for when DAG is fully received

### ISSUE THREAD

**Issue by alanshaw** [nftstorage/nft.storage#1428]
It would be useful if the `upload` table had a timestamp that would be set when NFT.Storage _knows_ it has received and stored a DAG in it's entirety.

It will simplify dagcargo queries, since it needs information stored in `upload` and has to join with `pin` to filter by favourable status. This timestamp would remove the need to do that and it would be a step towards a non-pin centric future...

We'd also be able to track time-to-availability. It wouldn't be super accurate since often times we'd have to wait for the pin sync cron to set it but it would give us a rough idea of how long things are taking to get uploaded that we could then improve on.

For complete DAGs sent in a single CAR or for raw file uploads we'd be able to set this timestamp immediately and we'd be able to flag availability in the UI even if the DAG is being queued by Cluster for pinning.

Related: https://hackmd.io/E0jxc0pCSxSkYgSUUq9lJA

**Comment by dchoi27** [comment]
Upload v2 will do for us, unless Riba comes back and says he needs this in the short-term we won't do. Closing for now

**Comment by ribasushi** [comment]
I NEED THIS!!!



( ... in a few months, when you ship v2 :trollface: )
