### ISSUE TITLE
Publish docs on how to use UCAN

### ISSUE THREAD

**Issue by yusefnapora** [nftstorage/nft.storage#1431]
Tracking issue for user-facing UCAN docs.

- [ ] Overview / what is UCAN
  - [ ] link to specs, fission docs, etc

- [ ] Service SDK docs (for marketplaces, etc)
  - [ ] Basic install / usage info (how to import, etc)
  - [ ] How to request a UCAN from the .storage service
  - [ ] How to issue a new UCAN for an end user
    - [ ] How to restrict scope of issued tokens
  - [ ] How to validate a UCAN chain

- [ ] End-user docs
  - [ ] How to get a UCAN token from your service provider
  - [ ] maybe: how to delegate privileges with your UCAN to another user
 
 @hugomrdias feel free to add anything here that you think needs documenting :)

**Comment by hugomrdias** [comment]
There only one sdk the ucan.storage sdk/package, the concept of service was removed.

**Comment by hugomrdias** [comment]
marketplace user and end user have the same flow and use the same package `ucan.storage`, they get a ucan (parent) from someone and use that to sign a new ucan with the parent ucan as proof.

**Comment by hugomrdias** [comment]
The user can get the service DID through the API `/did` to issue the last token to us.

**Comment by dchoi27** [comment]
@yusefnapora know we still need this to land in /docs. do we want to close this ticket if that's being tracked elsewhere? or leave this open as we copy the info from README over to /docs?

**Comment by dchoi27** [comment]
ping @yusefnapora - this is currently in the review column in zenhub, just want to know where to put it!
