### ISSUE TITLE
nft.storage footer heart icon renders large on high rez wide screens

### ISSUE THREAD

**Issue by JeffLowe** [nftstorage/nft.storage#1448]
Tested on devices:  MacOS Chrome (latest), MacOS Safari (latest), Android chrome, iphone 8 safari. 

Looks good on all tested devices (minus wide screens) 
<img width="286" alt="Screen Shot 2022-02-22 at 3 44 00 PM" src="https://user-images.githubusercontent.com/2078567/155224693-55afc763-39c2-4112-aa24-aa6d3d66f55a.png">

## On large screens, heart icon in footer renders larger, appearing to not have space in between it and "by Protocol Labs"
![Screen Shot 2022-02-22 at 3 42 30 PM](https://user-images.githubusercontent.com/2078567/155224518-26e7fdab-6f05-43a1-8641-175cc1ecf0b9.png)

## Monitor in which heart icon renders larger
![Screen Shot 2022-02-22 at 3.35.07 PM.png](https://images.zenhubusercontent.com/5285300029fe34596000054e/a7b82d9b-45eb-4525-9c86-eb33c33311f3)!

**Comment by cmunns** [comment]
I have a huge monitor and still can't replicate this on prod.
