### ISSUE TITLE
Links to sections on homepage don't work correctly

### ISSUE THREAD

**Issue by Codigo-Fuentes** [nftstorage/nft.storage#1456]
Arriving at the homepage with a hash link doesn't take the user to the section as expected. For example:
https://nft.storage/#getting-started
https://nft.storage/#about
https://nft.storage/#faq

It does work on docs and faq pages:
https://nft.storage/docs/concepts/architecture-considerations/#api-keys
https://nft.storage/faq/#how-is-nft-storage-free-to-use

**Comment by cmunns** [comment]
Added on homepage branch here: d1bb05de25e37ba2fac3d0a0c79438d562b44900

**Comment by JeffLowe** [comment]
Will close once https://github.com/nftstorage/nft.storage/pull/1005 get's deployed

**Comment by JeffLowe** [comment]
@cmunns 1005 deployed, but this is still an issue.
