### ISSUE TITLE
Fix identified issues with dev environment

### ISSUE THREAD

**Issue by JeffLowe** [nftstorage/nft.storage#1464]
Resolve the following issues with dev environment identified in working session between @dashcraft and @alanshaw 

1. salt was a random value

2. API token in readme for api is for a different magic link id than the one in seeded data

3. Database token in readme is incorrect, should be:

4. Pinning services api, requires a PSA allow list for authoritzation

**Comment by JeffLowe** [comment]
Resolved with #1462

**Comment by plwileverts** [comment]
@JeffLowe @dashcraft does this actually close this issue? Noting that 1462 notes "Linked to https://github.com/nftstorage/nft.storage/issues/1464 **_as part of solution (will not close the whole thing, but a nice quick win improvement)_**"

**Comment by JeffLowe** [comment]
Yeah, that could be confusing.  Let me clarify.

The immediate partial solution in #1462 addressing current setup became the full fix once #1690 was introduced ( which focuses on docker setup ).
So, no more work is needed on this ticket.  What remains needed is being worked on in #1690
