### ISSUE TITLE
Highlighted section in docs sidebar doesn't always match where I am

### ISSUE THREAD

**Issue by dchoi27** [nftstorage/nft.storage#1468]
When I go to: https://nft.storage/docs/how-to/mint-solana/#using-candy-machine-cli

And scroll down just a bit, the highlighted section in the docs sidebar changes to something earlier. Think it might have to do with the header levels?

**Comment by JeffLowe** [comment]
Looking at this and other pages ( like https://nft.storage/docs/how-to/mint-custom-metadata/ ) and it seems the pattern is this...
When user hits a section with an h3 in the content, it causes the sidenav position to move back to the first H2 on the page (top of page).   However, once user hits the next h2, sidenav position moves back to the correct h2 spot.

**Comment by JeffLowe** [comment]
Issue is with Nextra.  Instead of implementing a hack fix, we ticketed issue with Nextra https://github.com/shuding/nextra/issues/381 
We'll monitor and if not resolved soon then we'll implement our backup fix.
Placing this in Paused for now.
