### ISSUE TITLE
Show upload timestamp instead of just date in Web UI /files

### ISSUE THREAD

**Issue by dchoi27** [nftstorage/nft.storage#1473]
Full timestamp is shown in hover over date (although it is slow to appear). 
Consider adding more of the timestamp in what is shown to user.  Condsider possibly displaying YYYY-MM-DD HH:MM at minimum

**Comment by alanshaw** [comment]
FYI we show the _full_ timestamp on hover.

@dchoi27 what specifically is the request here - add hour and minute to the table? Formatted like: `YYYY-MM-DD HH:mm`?

**Comment by JeffLowe** [comment]
Currently there is no hover showing more time in nft.storage.  
Web3.storage shows this curently
![Screen Shot 2022-02-28 at 11 50 47 AM](https://user-images.githubusercontent.com/2078567/156033350-cb1c0537-55c7-4206-a0f6-723e8040e3f9.png)

Web3 new design will show this
![Screen Shot 2022-02-28 at 11 51 16 AM](https://user-images.githubusercontent.com/2078567/156033367-614bd964-a857-4d7d-9718-c6c54fc89308.png)

One problem is timezone.  I'm assuming that server side we are storing as UTC or something and converting to browser detected TZ on client side?  Might be wise to list detected TZ on the listing.  

@dchoi27 @alanshaw So, would a good approach be:

```
Column label:  "Timestamp"
Cell value:  "YYYY-MM-DD HH:MM AM/PM TZ"

```

**Comment by JeffLowe** [comment]
Correction on this. Hover does show full timestamp, it's just slow to open.

**Comment by cmunns** [comment]
I'm unclear on how we landed here, but I have a PR ready with the time added in to match web3.storage. Please advise if we were hoping for something else here.

**Comment by dchoi27** [comment]
Yes that's great! Thank you
