### ISSUE TITLE
Fail to Fetch Error

### ISSUE THREAD

**Issue by dddproject4** [nftstorage/nft.storage#1481]
I have been unable to log in for the past several hours.

I am using macOS. I have replicated this error in Chrome and Brave.

I have tried using existing accounts and creating a new one.

Whenever I click on the magic link, I am not logged in. I am routed to www.nft.storage/callback rather that .../files. Which is what I have seen when I successfully have logged in in the past. The same error occurred when trying to log in with GitHub.

I got a similar error as well earlier when trying to upload a .car file.

Any help would be much appreciated!

**Comment by dchoi27** [comment]
Spoke with this person (same person encountering the second bullet in #1484) - it sounds like it's something specific to their local network + Cloudflare, which unfortunately makes it really hard for us to debug :/ leaving open for now in case folks have ideas
