### ISSUE TITLE
Reports of uploads ending in "Failed" status

### ISSUE THREAD

**Issue by dchoi27** [nftstorage/nft.storage#1484]
There are cases where uploads are successful (both directly to NFT.Storage and via PSA) but the status eventually ends up going from Queued to Failed. Because there's a few of these anecdotes around the same time, they might be related.

Some more specifics on the cases:
- Case 1: Someone said they successfully uploaded directly to NFT.Storage, and it was a brand new CID (since it was their first time using that specific chunk size). But it immediately returned as Failed.
- Case 2: Used pinning services API to pin a 2+ GiB directory to NFT.Storage using https://github.com/nftstorage/nft.storage-tools - their upload showed up as Failed initially, they retried and it seemed to work, and running `node status.js pinlist.txt` from nft.storage-tools gave them the screenshot below (so seems successful). however, pin status is still showing up as Failed using /check. Keeping the CID private in case it's a drop, but folks with access to the private Slack channel can grab it here: https://filecoinproject.slack.com/archives/C02BZPRS9HP/p1645805030810139
![image.png](https://images.zenhubusercontent.com/5fa04bd64afb77249c77235b/0368cdb9-7e5f-4637-8de7-8969258c9ce3)
- Case 3: Someone with general intermittent login and upload problems (where usually when they upload, they get `"Failed to fetch"`) finally managed to upload some files, but the pin status behind those came back as `Failed` (https://discord.com/channels/806902334369824788/831502708082081822/946802019992240148). It sounds like they were still able to access the files through the gateway (though some intermittent timeouts did occur). I thought that anything that got successfully uploaded should never show pin status "Failed."

There's been some other mentions of this but we don't have much detail on those cases.

It sounds like we have all the data (good) but maybe something's up with how we're updating pin status. Think a lot of this might be user error / uploads not completing, but something feels like it's changed. Previously, in cases where the whole upload didn't finish, Cluster would report Queued for a really long time, but potentially now they update to Failed much more quickly (in which case, it sounds like it's a net improvement, and we could start using Cluster for things like reporting incomplete uploads. I tried running `SELECT date_trunc('day', inserted_at), status, count(id) FROM public.pin WHERE inserted_at > '2022-02-26' GROUP BY 1, 2` on our production DB stats replica but that timed out, but some light digging here would be helpful.

**Comment by dchoi27** [comment]
Quick update here - in the second case, they didn't actually upload all chunks of their CAR file (which explains why they were able to access some of their files, and the pin of the root CID "Failed." They didn't upload all chunks because they encountered #1318.

But question still stands around whether we retry Failed pins when the upload succeeds the second time (both direct uploads and through the PSA).

**Comment by dchoi27** [comment]
Another one ![image.png](https://images.zenhubusercontent.com/5fa04bd64afb77249c77235b/84379212-528f-463d-b18e-4f917f853c0b)

Again - might be that they didn't end up uploading the entire file, but the behavior from Cluster feels different than before (I thought it would just show queuing forever, unless I missed a PR).

**Comment by dchoi27** [comment]
Going to give more clarity on pin statuses and how users can identify whether it's user or NFT.Storage error in #1423

**Comment by dchoi27** [comment]
Reopening this so we can do more digging

**Comment by dchoi27** [comment]
One more 
![image.png](https://images.zenhubusercontent.com/5fa04bd64afb77249c77235b/53ac85b7-cb89-473c-a682-0841186a1eaf)

**Comment by dchoi27** [comment]
Another example in #1557; "Failed" upload is here and fully accessible: https://bafybeibhz2r5w5apkouhsbukuhcpl6v3xsaryd5jlscs7h23qvfzzomgm4.ipfs.nftstorage.link/

**Comment by alanshaw** [comment]
@dchoi27 I believe that this is due to us getting quicker at syncing pin statuses. Statuses used to take longer to sync and so had longer to transition into "Pinned" status before we got to them. Now we're seeing pin statuses in `PinError` or `Unpinned` (before they even enter the pin queue) state and are updating our DB accordingly.

IPFS continually tries to pin data and it's possible for Cluster to timeout for bigger pins and set `PinError` temporarily while in the background IPFS finishes pinning the data. The issue is that when we sync a `PinError` status, we re-check on that pin much less frequently so folks are seeing `PinError` for up to a week before it has a `Pinned` status, even though it's available via IPFS and the gateways.

I'm thinking about introducing a grace period to mitigate this, so any _new_ upload (i.e. less than 24h old) won't transition into `PinError` (it'll be set to `Pinning`). It means we'll checkup on that item more frequently until it transitions to `Pinned` status.
