### ISSUE TITLE
Docs page on what pin statuses mean

### ISSUE THREAD

**Issue by dchoi27** [nftstorage/nft.storage#1489]
Important points to hit:
- Pin status is just reporting what Cluster is reporting on. Just because the data doesn't say `Pinned` yet (e.g., `Queuing`) doesn't mean it's not safe
- Cluster is constantly trying to pin `Queuing` and `Failed` pins in the background
- If your data is retrievable, then Cluster has the data and will soon finish pinning
- If your data's pin status says `Failed`, then the full set of data you tried to upload wasn't available the last time NFT.Storage tried to update pin status from the Cluster
- If you used the Pinning Services API to try and pin data from somewhere else and it reports as `Failed`, then this is almost certainly because the full data was not available - this is really hard to debug because it's so situational (e.g., if you originally uploaded the content via your local IPFS node, there could be local network issues preventing connectivity, etc.). If the data was originally uploaded to Pinata or another pinning service, then it's far more likely that we should be able to grab this content, so feel free to file an issue
- If you uploaded directly to NFT.Storage, pin status reporting as `Failed` is usually because the service did not get your full upload

Since the pin status that Cluster and that NFT.Storage report back aren't always in-sync, sometimes it's tricky to debug whether a pin status `Failed` really means that your full upload wasn't gotten by NFT.Storage. We're working on new infrastructure to make this clearer, but in the meantime, the best thing to do is check whether the `Failed` status is true is to check if your upload was successful
- To check, you can try grabbing your data from an IPFS gateway. If you successfully can, then the pin status being reported by NFT.Storage just hasn't been updated
- If you uploaded a large directory, you should check whether a large sample of individual files in the directory are retrievable (e.g., `ipfs.io/ipfs/{CID of directory}/filename.png`)
- For uploads, we highly recommend using the JS client library or other tooling that programmatically uploads content. Because uploads often come across multiple requests, if there is latency in the full upload finishing, then it might report back pin status as `Failed` at some point
- NFT.Storage checks if `Failed` pins have been found and pinned by Cluster once a week for a month after initial pin status has been updated. If you find your file is retrievable but pin status still says `Failed`, then file an issue here with the relevant CIDs (or DM one of our devs on Discord if you'd like to keep the CIDs private), and we'll take a look for you

**Comment by JeffLowe** [comment]
@yusefnapora we have some prior notes from Niftysave meetings addressing some of the definitions of statuses.
