### ISSUE TITLE
Simplify examples in docs

### ISSUE THREAD

**Issue by JeffLowe** [nftstorage/nft.storage#1504]
Mentioned by Alan here #1498

The examples in the docs are too complicated. They ask you to install the “mime” module for example which is unnecessary noise.

- [ ] We need to consider simplifying examples in Docs (specifically on https://nft.storage/docs/quickstart/ )

**Comment by yusefnapora** [comment]
Seems like a good opportunity to use the new create-nft-storage starter kit from https://github.com/nftstorage/nft.storage/pull/1593

I'll play with that this week and see if I can tighten things up a bit. Will also get rid of the mime dependency.
