### ISSUE TITLE
Improve UX of mobile /docs menu to clearly differentiate from site nav

### ISSUE THREAD

**Issue by JeffLowe** [nftstorage/nft.storage#1506]
Probably need a different menu indicator to differentiate it from main hamburger menu.  Maybe Bento, kebab, or meatballs.  

- [ ] improve UX of mobile /docs menu to differentiate from site nav

Alan mentioned here #1498
"The double hamburger on mobile isn’t great UX…"

**Comment by cmunns** [comment]
We are pretty limited on what we can customize in the nextra config but it would be possible to do some CSS workaround with a pseudo element to at least add a label to the menu
<img width="530" alt="Screen Shot 2022-03-07 at 10 52 20 AM" src="https://user-images.githubusercontent.com/1189523/157099018-2dd120be-1eff-4153-845e-1feeb05fb905.png">

**Comment by JeffLowe** [comment]
That approach (adding on mobile the "Table of Contents") seems reasonable to set the context of the page menu icon (given the config limitations).  
Unless there are objections, let's go this direction. It's a small but meaningful change.
