### ISSUE TITLE
Consider refining homepage getting started section with more relevant (or no) image

### ISSUE THREAD

**Issue by JeffLowe** [nftstorage/nft.storage#1508]
**_Blocked until Designed image received._**

Alan mentioned here #1498

Alan stated:  "7. The image on the getting started section on the homepage is not relevant to the content."

We could ditch the image and just go with steps text centered.  I believe the thought here was to put some relevant visual to break up the text.  We used the current one as placeholder.   I'll ticket this refinement recommendation for Munns.  

- [ ] Consider either more relevant getting started image OR removal with centered step test (or something better).

**Comment by JeffLowe** [comment]
@dchoi27 What's the best way to engage PL design team to create a relevant image for this homepage section?

**Comment by dchoi27** [comment]
I filed an issue, with a request to have it done by Mar 22. Thanks for flagging!

**Comment by dchoi27** [comment]
FYI - this is the image design came back with. What do folks think? https://user-images.githubusercontent.com/97632209/158723075-e3605f52-adea-497e-b6e5-dc4a777f8ea2.png

**Comment by JeffLowe** [comment]
This image doesnt seem any more contextually relevant than the one currently used.   We can easily update homepage to use this new image, but not sure if there is a need. Thoughts @cmunns

**Comment by cmunns** [comment]
Perhaps if we updated to "Getting started is quick and easy"? I dunno, it appears like a stop watch but yeah in the current context it's still ambiguous although I will say I like the new option better if I had to choose between the 2.

**Comment by dchoi27** [comment]
Let's either close this or go with the new image + change the text. @jchris can make the call
