### ISSUE TITLE
Spec out the No code API for data quality check

### ISSUE THREAD

**Issue by jchris** [nftstorage/nft.storage#1519]
@alanshaw suggested we have an API similar to build status images in README files. eg we have a URL like 

```
http://nft.storage/api/quality.png?nft=NFT_ID
```

and it returns whatever the right grade is for that NFT's storage quality. We can have an additional link that is the reason behind the data quality rating for that NFT: `http://nft.storage/api/quality.html?nft=NFT_ID`

**Comment by dchoi27** [comment]
@jchris can we flesh this out more to include the backend / scoring piece? Since we had previously discussed using a 3rd party like FungyProof to do scoring, more detail would things clearer.

**Comment by dchoi27** [comment]
@jchris bumping!
