### ISSUE TITLE
Examine & adjust needed alignment of page content and top header

### ISSUE THREAD

**Issue by JeffLowe** [nftstorage/nft.storage#1521]
- [ ] Examine alignment of top header logo and login button, as well as footer elements, to ensure correct alignment. Check mobile logo with menu icon to ensure proper alignment. 
- [ ] Ensure footer elements are aligned correctly where needed, especially on mobile. On mobile, all elements appear left aligned, and might look better centered?
- [ ] throughout site, page content left and right extend beyond header and footer elements.  Examine margins on all pages to ensure proper global alignment with all elements (adjust if needed). 

Alan commented in #1498 about this
Logo in the header is scaled by 0.8 which brings it in from the left hand edge, this looks off when you look at the login button, which is fully right aligned.
On mobile, the NFT.Storage logo is not centred - it’s off to the right.
In the footer, the social icons are not centred - they’re off to the left.

**Comment by cmunns** [comment]
We should consider tabling this for the Tailwind conversion. @JeffLowe

**Comment by JeffLowe** [comment]
Good point @cmunns That would resolve this and several other issues likely.  I'll put this in backlog, but link this to the tailwind ticket
