### ISSUE TITLE
Starting the storage service

### ISSUE THREAD

**Issue by tajjapan** [nftstorage/nft.storage#1528]
I’m looking into offering the storage services with NFT.  Is that possible for me to do that?

**Comment by dchoi27** [comment]
If you're a Filecoin Storage Provider looking to store data from NFT.Storage, we use Textile's BidBot (https://github.com/textileio/bidbot) and Estuary (https://estuary.tech/) to make Filecoin storage deals. You can look into being a Storage Provider that receives deals from these dealmaking services.

If you're not yet a Filecoin Storage Provider, you can learn more here: https://filecoin.io/provide/

To be honest, this is my best guess for what you're asking (the question's not super clear). Closing for now!
