### ISSUE TITLE
Have storeDirectory accept a directory reference

### ISSUE THREAD

**Issue by dchoi27** [nftstorage/nft.storage#1550]
This would be in addition to accepting a Files list. We would just do the work for them to use `filesFromPath` (or `getFilesFromPath` if that's just universally better, as flagged in #1525.

We should update the storeDirectory docs example when this is done.

**Comment by alanshaw** [comment]
You can only read from the filesystem from Node.js, not from a browser, so this needs to be a separate utility just for Node.js.
