### ISSUE TITLE
User Auth - Remove Localstorage in favor of magic api

### ISSUE THREAD

**Issue by dashcraft** [nftstorage/nft.storage#1556]
Storing in localstorage is unnecessary, @hugomrdias pointed out there the `isLoggedIn` method handles essentially
the same functionality as putting information in localstorage, we can very likely remove it and just use magic links
method to accomplish the same functionality without the duplicated implementation details.

https://magic.link/docs/api-reference/client-side-sdks/web#isloggedin

**Comment by alanshaw** [comment]
🙏 I think this change has introduced a bug where the token stored in localStoage is stale - the site thinks the user is logged in but the token is no longer valid.
