### ISSUE TITLE
Uploading metadata folder

### ISSUE THREAD

**Issue by M1lfsh4k3** [nftstorage/nft.storage#1557]
Hi, i used the code for uploading a folder and it worked for the images (tried a folder with 5 pngs).
However the same code but changing only the path to the metadata folder gives the Pin status "Failed" although they are visible under "files" on the website.

Whats the problem causing them to fail? See screenshots below.

![image](https://user-images.githubusercontent.com/100882557/156891475-c899dbe6-8103-40c2-a2ea-9d34d7aa8335.png)
![image](https://user-images.githubusercontent.com/100882557/156891504-312a5131-9ccc-452e-b51a-5d77bcd35073.png)

**Comment by dchoi27** [comment]
Hey, thanks - we've been getting some reports of this. As long as you can access the data off the IPFS network, your data is safely pinned. It's likely an issue with what our IPFS infrastructure is reporting (the pin statuses aren't always reflective of what's actually going on, so we're taking a look to see what's going on, and figuring out how we can report a more reflective status.

**Comment by OutOfTheDarkCave** [comment]
FYI, I am having the same issue, hoping it's not something critical as mentioned above.

**Comment by M1lfsh4k3** [comment]
OK thanks guys!

**Comment by dchoi27** [comment]
FYI - #1577 should solve this!

**Comment by dchoi27** [comment]
Looks like this should be good now (just checked your CID using /check). Closing!
