### ISSUE TITLE
Remove /docs page on OpenAPI generated clients

### ISSUE THREAD

**Issue by dchoi27** [nftstorage/nft.storage#1573]
- [ ] remove the OpenAPI Generated Client docs page from /docs ( https://nft.storage/docs/client/generated/ ) 

We should either slap on a bunch of warnings for the OpenAPI generated clients in the /docs page, or take down the page https://nft.storage/docs/client/generated/

These libraries haven't been tested or kept up-to-date, and we shouldn't be actively pointing folks to them.

**Comment by JeffLowe** [comment]
If they are out of date and the libraries not being maintained, we should remove them.  
I'll go ahead and add this to the sprint.
