### ISSUE TITLE
Redirect nftstorage.link to NFT.Storage Gateway docs page

### ISSUE THREAD

**Issue by dchoi27** [nftstorage/nft.storage#1579]
Let's link https://nftstorage.link/ to https://nft.storage/docs/concepts/gateways/

Right now it's a domain squatting landing page...cc @vasco-santos

**Comment by vasco-santos** [comment]
Added a CF Page Rule https://dash.cloudflare.com/fffa4b4363a7e5250af8357087263b3a/nftstorage.link/rules for the redirect

**Comment by dchoi27** [comment]
Hm, I see the rule set up
![image.png](https://images.zenhubusercontent.com/5fa04bd64afb77249c77235b/1476e92c-4c8f-4fc0-9f90-6ee61ca23088)

but seeing this error when I go to nftstorage.link
![image.png](https://images.zenhubusercontent.com/5fa04bd64afb77249c77235b/0e87944d-cf3e-43c9-a41e-d2076547dd81)

**Comment by dchoi27** [comment]
Turned this off in case this is why Google flagged nftstorage.link as malicious

**Comment by dchoi27** [comment]
Ah sorry didn't update this but it's back on.

**Comment by vasco-santos** [comment]
> Ah sorry didn't update this but it's back on.

Yeah, we put it back on to be more trusted to people looking into unblocking us

**Comment by dchoi27** [comment]
oh weird i had turned it back on last night too
