### ISSUE TITLE
Add gateway config option to metaplex integration

### ISSUE THREAD

**Issue by dchoi27** [nftstorage/nft.storage#1586]
cc @yusefnapora

**Comment by yusefnapora** [comment]
Made a PR here: https://github.com/metaplex-foundation/metaplex/pull/2021

**Comment by dchoi27** [comment]
Hate to add work here, but after the craziness with the nftstorage.link gateway yesterday/today, wanted to see how quickly we'd be able to add a parameter in Candy Machine where they can specify the gateway to use (and just have nftstorage.link as default)

**Comment by yusefnapora** [comment]
Just updated the card title to reflect what needs doing here - the change to the hard-coded gateway was merged in last week.
