### ISSUE TITLE
Auth improvements with magiclink

### ISSUE THREAD

**Issue by dashcraft** [nftstorage/nft.storage#1587]
Thoughts:
1. Reduce number of calls to magic link via controlling the behavior with a wrapper, checking the state periodically, but returning cache
2. Potentially wrap calls on failure to nuke magic link and redirect to login, so that a user who was logged in but has invalid token, would have to re-auth on a 401 or similar error from magic link.

- [ ] we shoudl evaluate if same optimizations are needed on web3 side.  if so, ticket so we can implement there.

**Comment by dashcraft** [comment]
These are performance optimizations and general cleanup ideas, I wanted to put into an issue for future tracking/backlog

**Comment by JeffLowe** [comment]
Closing this out since w3access will be implemented.
