### ISSUE TITLE
Complete DB tasks to enable merging of admin.storage PR

### ISSUE THREAD

**Issue by JeffLowe** [nftstorage/nft.storage#1592]
admin.storage updates to manage pinning, storage limits, and user blocking nearing completion in this admin.storage PR. https://github.com/nftstorage/admin.storage/pull/22

Before the admin.storage PR can be merged the following needs to be done in the following order:
- [x] 1. nft.storage DB schema in prod needs [the latest user_tag_type and user_tag SQL](https://github.com/nftstorage/nft.storage/blob/main/packages/api/db/tables.sql) ( @hugomrdias said he'll be able to have this completed in the next day or so)
- [x] 2. we need to run INSERT INTO statements in the nft.storage prod DB to migrate the current values of PSA_ALLOW into user_tag with HasPsaAcces=true  (i've attached a migration script with values @vasco-santos  provided on February 26th.  by now there's likely some user_ids that have been added, therefore i need an updated list of user_ids in PSA_ALLOW.  i wrote a script to generate this migration file so if someone can get me an updated PSA_ALLOW value from prod nft.storage i can provide a more up to date migration file)
- [x] 3. approve and merge the PR that migrates nft.storage to use the user_tag table instead of the global PSA_ALLOW cloudflare variable https://github.com/nftstorage/nft.storage/pull/1389

**Comment by hugomrdias** [comment]
@trigramdev9 send me the insert statements to finish 2. and 3. is already reviewed
