### ISSUE TITLE
File page Actions "View URL" issue

### ISSUE THREAD

**Issue by dashcraft** [nftstorage/nft.storage#1617]
In PR: #1258

Jesse noticed that:
Using a url that the cid begins with ba, it leads to ipfs://${cid}
which means the view url button is a redirect the browser will never use

This seems to be new, the old link used:
`https://ipfs.io/ipfs/${cid}`

which seemed to be ok, wanted to point it out in case this is a regression

**Comment by dchoi27** [comment]
oh hm - yeah that doesn't seem right. I think we can probably just kill the "View URL" button (since you can get to the gateway link without even having to go into the menu). WDYT?

**Comment by dchoi27** [comment]
Was this change deployed? Right now "View URL" directs you to an `ipfs.io/ipfs` URL, rather than an nftstorage.link URL.

I honestly think we can just kill the "View URL" option - it's not intuitive why "View URL" would lead to a gateway link being opened.

**Comment by JeffLowe** [comment]
Awaiting deploy of website which contains fixes (see https://github.com/nftstorage/nft.storage/pull/1678 )
