### ISSUE TITLE
Three CIDs pinning status is Failed

### ISSUE THREAD

**Issue by lloydcarroll** [nftstorage/nft.storage#1632]
How do I fix? I have deleted one and re-uploaded but showed back up with same CID (probably because it's the same content) and pnning status is failed.

**Comment by dchoi27** [comment]
How did you upload the content? Are you able to access the content from a gateway?

**Comment by lloydcarroll** [comment]
I am, but each one has 10k items. Hard to check that many, but spot
checking probably 20-30 and so far (randomly picking) they pull up. So, how
do I verify what the fail part is? I've tried importing through local node,
but tired of trying that as it's slow and never works. Just wondering what
the failure is and why it's not showing as pinned. Thanks for your help
again!

**Comment by lloydcarroll** [comment]
OH, and I used the js client we discussed before.

**Comment by dchoi27** [comment]
Did you try all the uploads at some point previously? If so, the pin status probably just needs to update. If it was your first time uploading any of the directories and it immediately showed as `Failed`, then it might not be that.

**Comment by lloydcarroll** [comment]
SO the first status it showed was queing or something like that. Then they
showed Pinning. THen they showed Failed. Now, I will say that if I remember
right, these three CIDs, during the upload, it "seems" like the upload hung
as on average, they took 3 hours 15 minutes to upload. THese three I let go
an extra 3-4 hours and was still looking like it was uploading (command
line had not returned to the prompt). So, I figured it just hung and I
killed the process. I could be wrong. But I also thought I did that on
another CID that is showing Pinned. IDK, my brain is fried at this poing.
One of the three, I deleted and re-uploaded and showed up as the same CID
as previous and instantly showed Failed instead of first saying Queuing as
before. I'm assuming the Fileservice recognizes the same content and
re-assigns the same CID. It went through that time and I didn't have to
kill, but that was a couple days ago now and it still shows failed. If I
use the CID Verify tool it doesn't really tell me much. All the data looks
the same (or similar) between Failed and Pinned CIDs. I just wish I could
visit the url in nft.storage and would actually show the list of files but
it just hangs and hangs and eventually errors or times out. I'm going to
work on pushin smart contract to testnet and see if I can see it somehow
that way.

**Comment by lloydcarroll** [comment]
Also, not sure if I should put this as a new thread but, I think it """"MIGHT"""" be related. The JSON files are unable to be found and validated. I'm using the site https://rinkeby-api.opensea.io/asset/CID/1/validate/ and I'm getting 

HTTP 200 OK
Allow: OPTIONS, GET
Content-Type: application/json
Vary: Accept

{
    "valid": false,
    "token_uri": "https://opensea.mypinata.cloud/ipfs/CID",
    "errors": [
        "InvalidTokenUrlResponseException: Invalid JSON response for URL: https://opensea.mypinata.cloud/ipfs/CID"
    ]
}

Odd thing is, I can click the link and the json data shows up. I'm posting this in several places in hopes someone somewhere can help. I'm not convinced of much yet except 1 of 3 things is going on: Hash engine is not creating properly formated json file; ipfs is not serving correctly; or testnets.opensea.io is not correctly pulling data.

it LOOKS as if when you create the contract and an nft is minted, opensea pins the data to it's own ipfs node on pinata. It's been 24 hours AND the link I'm clicking in the results is what opensea should be pointing to. I posted to art engine and now here. Next will post to opensea.

**Comment by lloydcarroll** [comment]
So looking into the opensea api, the JSON files ARE formatted properly. Still unsure where the issue is. :/

**Comment by lloydcarroll** [comment]
Ok, so issue was an extra comma and in the image code, file_url was used but needs to be changed to image.
