### ISSUE TITLE
Nft.Storage /Stats page, use a separate Image for the "data stored" metric card

### ISSUE THREAD

**Issue by the-simian** [nftstorage/nft.storage#1636]
Design calls for 2 different images for the stat cards on the /stats page.  

- [ ] update the right card (Data Stored" with the following image (Be sure to minify before uploading)
![data-stored-svgo-out](https://user-images.githubusercontent.com/954596/158219424-135ff8d4-4ca4-48fd-9e35-ec268d63c035.svg)

## Design for reference
![Screen Shot 2022-03-18 at 8 10 54 AM](https://user-images.githubusercontent.com/2078567/159008928-a4ea9b31-e38e-4a19-8393-ee219aed73e7.png)

**Comment by dchoi27** [comment]
Here's the Figma design for reference: https://www.figma.com/file/h1tkDWGVrJSDn28HcOCJ2h/nft.storage-stats-page?node-id=0%3A1
