### ISSUE TITLE
Instrument alerting for checkup.nft.storage

### ISSUE THREAD

**Issue by dchoi27** [nftstorage/nft.storage#1637]
Can use NFT.Storage outage (https://status.nft.storage/) from Mar 30 ~4-10 UTC to see what the alerts should be configured for

- (very sensitive and specific) https://protocollabs.grafana.net/d/-2uEWFLnz/checkup-nft-storage?orgId=1&from=now-7d&to=now&viewPanel=20&refresh=1m
- (very sensitive, somewhat specific) https://protocollabs.grafana.net/d/-2uEWFLnz/checkup-nft-storage?viewPanel=6

Should alert P1 Opsgenie dotStorage rotation for critical things, and optionally a P2 alert for when things are trending in a bad direction.

Netops might be alerting things here as well (though not certain - they for sure are for #1452) - worth checking with them to see if we need to coordinate

**Comment by yusefnapora** [comment]
I added alerts for these, but it wasn't obvious how to make an alert P1 vs P2. @dchoi27 is there a switch I should flip for that? For now, the Bitswap NO RESPONSE alert sends to the dotStorage Opsgenie and the #dot-storage-alerts channel, but the Bitswap availability alert only sends to #dot-storage-alerts.

I put the threshold for NO RESPONSE so it will alert if any peer is above 10% failure for 5m.

Bitswap availability will fire if it stays below 50% for 5m. Based on eyeballing the graph, it seems like it occasionally dips below 50% during normal operation and recovers quickly. It might be too noisy to keep it at 50%, so maybe we need to tweak it if it fires a lot.

Here's some screenshots of the alert setup:

Bitswap no response:

![alert-bitswap-no-response.png](https://images.zenhubusercontent.com/5ce6c86bb78f08227f0959c3/3a330597-ba99-49a3-87fe-874cd2c639b5)

Average bitswap availability:

![image.png](https://images.zenhubusercontent.com/5ce6c86bb78f08227f0959c3/e67cc9ad-8150-4d4e-9c5d-af566c53c612)

**Comment by dchoi27** [comment]
cc @hugomrdias to chime in!

also - @yusefnapora, thanks for picking this up to get you familiar with things! for the rest of these alerting kind of tickets, definitely loop our new SRE so they can start owning.

**Comment by dchoi27** [comment]
@yusefnapora we should also confirm that NetOps also has access to these alerts

**Comment by hugomrdias** [comment]
@yusefnapora ping in slack so we can go over the alerts config
