### ISSUE TITLE
[Question] / endpoint vs /check endpoint returns different results for queued pins

### ISSUE THREAD

**Issue by elatoskinas** [nftstorage/nft.storage#164]
I've pinned some files using remote pinning yesterday. When I call the endpoint via `/`, I can see a CID as `queued` in the pin. However, when I use `/check/{cid}`, it shows that the pinning has `failed` status.

Is there any recommendation for resetting the pin or otherwise solve the issue to ensure the files get pinned? And are the messages inconsistent in this case, or should these two results be interpreted differently?

Thank you, and love the service!

**Comment by alanshaw** [comment]
Can you post the CID you're seeing this issue with? They should be the same.

**Comment by elatoskinas** [comment]
@alanshaw Thanks, re-pinning again via `pin.remote.add` resolved the issue, and I managed to get all the files pinned. I have left one CID on failed, so you can examine the issue: `Qmava2gbqnmnYXEmvZorb1MaR2uzm7qzwrMhnmX92qve4V`

It appears that this also happens for other statuses. For example, this one checks with `pinned` successfully: `QmUP87EjWywkXLk3jfhhJKWtJQXqjuuH8zxNBVPxb1UGSX`, but shows `queued` in the `/` endpoint query

**Comment by alanshaw** [comment]
So, I can see that the filecoin deal for this CID is "queued" but the _pin_ "failed". The systems for pinning and deal making are separate so there's a chance the deal making system was able to retrieve from the network but our IPFS cluster was not.

https://api.nft.storage/check/Qmava2gbqnmnYXEmvZorb1MaR2uzm7qzwrMhnmX92qve4V

I can't see why it would appear as "queued" in the pin info for the `/` (status) API but "failed" for the `/check` API. Are you sure it was "queued" in the pin info?

**Comment by alanshaw** [comment]
ping @elatoskinas

**Comment by elatoskinas** [comment]
@alanshaw In the pin info via `/`, it shows this (which still says queued, and doesn't show the deal):
```
        {
            "cid": "Qmava2gbqnmnYXEmvZorb1MaR2uzm7qzwrMhnmX92qve4V",
            "created": "2021-05-26T23:42:57.400Z",
            "type": "remote",
            "scope": "NFT",
            "files": [],
            "pin": {
                "cid": "Qmava2gbqnmnYXEmvZorb1MaR2uzm7qzwrMhnmX92qve4V",
                "status": "queued",
                "size": 0,
                "created": "2021-05-26T23:42:57.400Z"
            },
            "size": 0,
            "deals": []
        },
```

The "queued" in the pin info I'm referring to is another CID:
```
        {
            "cid": "QmUP87EjWywkXLk3jfhhJKWtJQXqjuuH8zxNBVPxb1UGSX",
            "created": "2021-05-26T23:42:56.864Z",
            "type": "remote",
            "scope": "NFT",
            "files": [],
            "pin": {
                "cid": "QmUP87EjWywkXLk3jfhhJKWtJQXqjuuH8zxNBVPxb1UGSX",
                "status": "queued",
                "size": 0,
                "created": "2021-05-26T23:42:56.864Z"
            },
            "size": 0,
            "deals": []
        },
```

Upon checking, it gives a different result:
```
{"ok":true,"value":{"cid":"QmUP87EjWywkXLk3jfhhJKWtJQXqjuuH8zxNBVPxb1UGSX","pin":{"cid":"QmUP87EjWywkXLk3jfhhJKWtJQXqjuuH8zxNBVPxb1UGSX","created":"2021-05-26T23:42:56.472Z","size":1083813,"status":"pinned"},"deals":[{"status":"queued","lastChangedUnix":"1622476900.467","lastChanged":"2021-05-31T16:01:40.467Z"}]}}
```

Do you recon this is a discrepancy in consistency overall?

**Comment by hugomrdias** [comment]
This should be fixed now. Please reopen if not. Thank you
