### ISSUE TITLE
Upload and pinning of photo .DNG failing

### ISSUE THREAD

**Issue by LMKev1982** [nftstorage/nft.storage#1640]
I have been uploading some photographs for a collection of NFTs I'm creating on OpenSea. 

Out of the 8 one of them seems to not want to upload or pin. First the upload seems to freeze on the GUI at around 50%. I usually wait it out but eventually it times out.

When I look in the "Files" page. A new row is added for that file with "Queued" status. It stays like that for a while, days even. Eventually, the Pin Status switches to "Failed", while Storage Providers are still in "Queuing".

It has not changed at the time of me submitting this query.

CID is bafybeiee56qjt3ywbf7qy7nruqtp55tsjku2ll3dhb3xrdcgrvd7bi4ca4/

I apologize beforehand since I'm new at this and had done something incorrectly. I zipped up the DNG file and attached in case it would help. I zipped it because DNG was not an allowed file type to attach.

Thank you
[DNG file.zip](https://github.com/nftstorage/nft.storage/files/8249205/DNG.file.zip)
u

**Comment by alanshaw** [comment]
Looks like it was triggering a firewall rule that Cloudflare has in place. This uploads fine for me now.
