### ISSUE TITLE
Blocked On NFT Storage

### ISSUE THREAD

**Issue by beforethefans** [nftstorage/nft.storage#1641]
Was wondering receiving more information on being blocked on the site. 6ec51eed9c02abef is CloudFlare ID, as I was loaded my car file for an NFT project, as soon as I clicked to verify all the information was there I was redirected to the blocked page. Any information provided I would like to thank yall in advance.

**Comment by beforethefans** [comment]
Hello, I am planning to create a 10K NFT collection, I was going through a site called Generate NFT Online and so to create a nft minter where the community can mint an nft from the collection. This site has a list of instructions to follow among them creating my art and metadata into a site called car.ipfs.io and convert them to car files. As i received the car files a CID was created. These files then had to be saved on either A NFT. Storage or B Pinata. I went with NFT storage and I uploaded the car files (content addressed archive) and upon completion of upload I received a CID. After that I clicked on the links to see if the car file or art had uploaded successfully, however, I reached a screen saying I have been blocked from NFT.Storage.

**Comment by dchoi27** [comment]
Can you share a screenshot of the screen? I haven't heard of anything like this before.

**Comment by vasco-santos** [comment]
Hey @beforethefans 

You likely hit one of the rate limits we have in place to provide a fair share of usage to everyone. We have them on the gateway (nftstorage.link https://nft.storage/docs/concepts/gateways/#rate-limits), as well as on the API. Can you please provide more details so that we can help you?

**Comment by dchoi27** [comment]
Closing for now, let us know if issues persist
