### ISSUE TITLE
Please help to make a folder in nft storage

### ISSUE THREAD

**Issue by osinting** [nftstorage/nft.storage#1669]
Dear sir/mam,

i am a newbie in nft cloud storage, and trying to make a good use of your nft storage

i need to make a folder and put the files in the folder so i can manage the cid for each folder containing files. and i can rettieve the content via json

please help me how to make a folder and upload files 

thank you very much

**Comment by dchoi27** [comment]
Hi - there are tons of examples in the docs: https://nft.storage/docs/

Jump into our Discord if you need additional help, and folks in the community might be able to help: https://discord.com/invite/KKucsCpZmY

**Comment by dchoi27** [comment]
Check out NFT UP for storing large directories! https://nft.storage/blog/post/2022-04-05-announcing-nftup/
