### ISSUE TITLE
Upload entire folder

### ISSUE THREAD

**Issue by patrickmack89** [nftstorage/nft.storage#1670]
How do you upload an entire folder?

**Comment by dchoi27** [comment]
https://nft.storage/docs/how-to/store-directory/

**Comment by patrickmack89** [comment]
If I upload a zip file trough the website would it work?

**Comment by dchoi27** [comment]
yeah but you wouldn't be able to access the contents of the zip file without downloading the whole thing (just like any other zip file)

**Comment by dchoi27** [comment]
Check out NFT UP for storing large directories! https://nft.storage/blog/post/2022-04-05-announcing-nftup/
