### ISSUE TITLE
Uploading error, please help!

### ISSUE THREAD

**Issue by M1lfsh4k3** [nftstorage/nft.storage#1672]
I have uploaded entire directories before using nftstorage so I know that this should work.
The following error shows when executing "node storeDirectory.mjs "path""

PS C:\Users\alors\Desktop\folder\NFT engine\nft.storage-main> node storeDirectory.mjs "C:\Users\alors\Desktop\folder\folder1\Generator\build\images"
storing 10750 file(s) from C:\Users\alors\Desktop\folder\folder1\Generator\build\images
node:events:498
      throw er; // Unhandled 'error' event
      ^

Error: EMFILE: too many open files, open 'C:\Users\alors\Desktop\folder\folder1\Generator\build\images\7693.png'
Emitted 'error' event on ReadStream instance at:
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  errno: -4066,
  code: 'EMFILE',
  syscall: 'open',
  path: 'C:\\Users\\alors\\Desktop\\folder\\folder1\\Generator\\build\\images\\7693.png'
}

Is it because its too many files? In that case how do I resolve this problem because all images has to be under the same CID folder when it's done. Thank you in advance!

**Comment by M1lfsh4k3** [comment]
Please can someone help me with this. Is it possible to upload in two batches but to the same CID folder?

**Comment by alanshaw** [comment]
@vasco-santos looking into this we might be able to fix by switching to https://www.npmjs.com/package/graceful-fs in [files-from-path](https://github.com/web3-storage/files-from-path) because it:

> Queues up open and readdir calls, and retries them once something closes if there is an EMFILE error from too many file descriptors.

@M1lfsh4k3 I'll look into this tomorrow morning and hopefully get a fix out asap.
