### ISSUE TITLE
[Discussion] Center footer to window?

### ISSUE THREAD

**Issue by dchoi27** [nftstorage/nft.storage#1685]
This caught my eye as looking a bit funky
![image.png](https://images.zenhubusercontent.com/5fa04bd64afb77249c77235b/73f856ec-7eed-4792-8103-d51ce2e17df4)

But open to discussion on what others think - it looks like it's just centered relative to the other footer elements rather than to the whole window

**Comment by JeffLowe** [comment]
This was called out previously (see https://github.com/nftstorage/nft.storage/issues/1521 ) and will be addressed in the new tailwind work.
