### ISSUE TITLE
remove magic.link dependency from local dev flow

### ISSUE THREAD

**Issue by yusefnapora** [nftstorage/nft.storage#1689]
The goal with this is to remove friction from local development by not requiring a real magic.link account in order to use the site in local mode, It should still be _possible_ to use real magic.link credentials locally, just not required.

The current thinking is to add a new "testing" token type that skips the backend validation flow and just uses a fixed dev secret. 

To make the token available to the frontend, we can add the token to the URL hash fragment, where the frontend code will grab it if there's no magic.link token available. This plays nicely with our future plans to have sharable links with embedded UCAN tokens in the hash fragment. Running in local dev mode should open a browser with the dev token in the URL.

Note that this means that local dev will not be using the production login flow by default, but with the hash fragment trick we should be able to write CI tests that depend on the logged in state.

**Comment by plwileverts** [comment]
Redaphid already has an approach to this, he will sync with Hugo to ensure this approach works and then either finalize that work or change directions.

**Comment by redaphid** [comment]
Found some of the code I was using for my personal localdev [here](https://github.com/redaphid/nft.storage/tree/simple-dev/proxy/packages/api/docker) that puts an nginx proxy between the front and backend. This also allows us to curl the api w/o explicitly referencing the bearer token!

**Comment by redaphid** [comment]
And [here](https://github.com/nftstorage/nft.storage/compare/feat/more-generic-token-check)'s an idea re: how the code would look in the website. Though some hacks would obvs be removed.

**Comment by yusefnapora** [comment]
Hey @redaphid, any updates here or things you need buy-in on to get unblocked? I haven't made time to play with the code you linked yet, but I think the proxy approach makes sense.

@hugomrdias this doesn't implement the token in hash fragment that we discussed earlier. Instead it uses a proxy to decorate your requests with an auth token if you want to be logged in. Just wanted to make sure you're looped in and cool with that, or else hear why it's a bad idea :) 

Our thinking is that we don't want to implement the hash-fragment parsing in a way that boxes in the future UCAN use cases, and since UCANs expire pretty frequently, we can just use the existence of a token in local storage as evidence that you're logged in anyway...

I think the hacks that @redaphid is talking about are related to checking whether you're logged in or not? It looks like there's a new endpoint to return user info and we detect that you're logged out if the request fails with an auth error.
