### ISSUE TITLE
use separate docker-compose projects for tests and local dev databases

### ISSUE THREAD

**Issue by yusefnapora** [nftstorage/nft.storage#1690]
The current docker-compose setup for testing and local development supports two use cases that have a lot of overlapping functionality: running unit / integration tests, and manually poking at things during iterative development.

The first use case wants a clean slate for each run, while the second benefits from a persistent data store so you can make small changes and see their effects while developing.

All the docker containers for the database setup are tagged with a docker-compose project name, so we could use a second project name for each use case. Then we can always reset / clear the "testing" project after each run, but leave the "debug" project alone and let the developer manually clear it when they need to.

**Comment by yusefnapora** [comment]
Note that we should bind to non-default ports where possible to avoid conflicts with everything that wants to run on port 3000, etc.

If it's easy to bind to ephemeral ports and automatically set the correct env variables, let's do that :)

**Comment by redaphid** [comment]
We could look into [docker compose overrides](https://docs.docker.com/compose/extends/) for this.

**Comment by redaphid** [comment]
Also:
* Remove `container_name` from docker-compose keys, so there aren't collisions and we keep the env self-contained
* Minimize when we need to expose ports in general - and maybe don't expose them by default
* Maybe there's some simple dns solution?

**Comment by yusefnapora** [comment]
If we're willing to run everything inside containers (including miniflare and the frontend dev server), we could probably get away with just exposing the port for the frontend. Everything else could use the internal docker network by default, although you should be able to flip a switch to expose what you need for debugging.

That means we'd need to bind-mount the source tree into the container, so changes are picked up as you edit. Adding a [devcontainers.json](https://code.visualstudio.com/docs/remote/containers) for VS Code integration could help, but not everyone uses VS Code, so it's not a perfect solution.

I'm not saying we definitely should do this, btw... just tossing it out there as something to consider.
