### ISSUE TITLE
Getting rate limited on one image

### ISSUE THREAD

**Issue by alfonso-paella** [nftstorage/nft.storage#1700]
I am making an app which fetches NFTs from a user, and displays them as a wallet. There is one image, and only one, that is being rate limited. I do not think I went over 200 req / minute, and the rate limit didn't go away in 30 sec as advertised in the docs.

https://nftstorage.link/ipfs/bafybeidfmd7aya26zh6rgnft4jms6mwcyicwntcap2r2hocwqksioqu4hq/media/002202100010100000720080101102250.FYVD.jpg

<img width="880" alt="Screen Shot 2022-03-23 at 9 26 41 PM" src="https://user-images.githubusercontent.com/93743232/159823676-215c77c1-6d31-450c-8e38-2c6d4bfdaf9a.png">

**Comment by dchoi27** [comment]
@vasco-santos some nftstorage.link rate limiting weirdness!

**Comment by vasco-santos** [comment]
Weird thing, it resolves well now for me. Can you recheck?

It looks like it was rate limited before and response cached, which should not happen.

**Comment by dchoi27** [comment]
I couldn't replicate, but they were saying that they weren't getting rate limited on other URLs, just this specific one.

**Comment by alfonso-paella** [comment]
> @alfonso-paella I looked through our data from Cloudflare worker firewall and looks like this was really triggered by the rate limiter. 

Totally possble. I loaded many files in a short period of time. Over 200 sounds unlikely to me, but posisble if some requests accidentally fired more thn they should have

> You meant that you tried other CIDs and they were working good but not this specific URL only?

Correct

> I just doubled check our Firewall config and it claims 30 seconds blockage, but I am not sure if timer is reset when same IP keeps trying it out. 

It lasted more than 30s for sure. It may be that the timer is reset on each attempt?

> Was there by any chance an IP that was shared by multiple machines?

Not sure sorry

**Comment by vasco-santos** [comment]
>  It may be that the timer is reset on each attempt?

From what I heard from CF folks, it shouldn't reset. Could you replicate this again?
