### ISSUE TITLE
Failed pinning

### ISSUE THREAD

**Issue by M1lfsh4k3** [nftstorage/nft.storage#1702]
Im trying to use the pining service through IPFS Desktop to pin on NFT.storage but on the status page (IPFS Desktop) i cant see that the uprate is doing any "uploading" to nft.storage. How can i resolve this, tried with the JS code but it complained that it was too many files and lack of memory. Until that is fixed and I have to use IPFS Desktop but its not working with NFT.storage
On NFT.storage status is "Failed". Please help.

CID for foler1: QmWfRK92JiN7rny26YEUTrnNtoZS39zhWMX6UutbWrLcXP
CID for foler2: QmNt4Md96ND5yEMXPiM7HeuAazg55394nDYDUV5GGU41hb

See screenshot below about the uprate..
![image](https://user-images.githubusercontent.com/100882557/159905195-26acd5c5-8d55-4c6f-b4fe-faaed464f9df.png)
![image](https://user-images.githubusercontent.com/100882557/159905412-9e39bfbb-e283-4a5c-bafd-c549317fd478.png)
![image](https://user-images.githubusercontent.com/100882557/159905500-f14eb07a-b00a-496c-9288-cd3b8da0d152.png)

**Comment by dchoi27** [comment]
Were you saying you could retrieve your CIDs from a public gateway? I couldn't.

**Comment by M1lfsh4k3** [comment]
What do you mean? How do i try that?

**Comment by dchoi27** [comment]
Use something like ipfs.io/ipfs/{cid} or nftstorage.link/ipfs/{cid}, e.g. https://nftstorage.link/ipfs/QmWfRK92JiN7rny26YEUTrnNtoZS39zhWMX6UutbWrLcXP

Pin stats would show failed if NFT.Storage's IPFS nodes can't grab the content from the network. Another way of testing this is using a public gateway. If the only place it's stored is on your local node, most likely it's a connectivity issue with your node.

Please note that in the coming weeks we'll have an updated upload flow to eliminate memory constraints to upload large files / directories! So you won't have to rely on workarounds like this.

**Comment by M1lfsh4k3** [comment]
That sounds awesome! Thanks mate.

**Comment by M1lfsh4k3** [comment]
I dont know what im doing wrong, the node is open but i want it to be decentralized. If I shutdown my pc people has to be able to see their minted NFTs.

**Comment by vasco-santos** [comment]
Thanks for the update @M1lfsh4k3 

Closing the issue, feel free to re-open if you find this problematic again
