### ISSUE TITLE
Performance issues for Metaplex integration

### ISSUE THREAD

**Issue by dchoi27** [nftstorage/nft.storage#1707]
A user reported that using the upload integrated in Candy Machine is much slower than storeDirectory in the JS lib alone. This might be because of the wallet auth? But worth checking out and seeing if there's any low-hanging fruit. cc @yusefnapora

**Comment by yusefnapora** [comment]
working on this in https://github.com/nftstorage/metaplex-auth/pull/39. I'm hoping to open a PR to the metaplex repo by EOD tomorrow.

**Comment by yusefnapora** [comment]
Quick status report here. I've got the nft bundle upload working on [a branch](https://github.com/yusefnapora/metaplex/tree/nft-storage-perf) of the metaplex repo, but you need to `yarn link` to the PR branch of metaplex-auth at the moment.

Everything seems to work, so I'll plan to merge the metaplex-auth PR and release a new version on Monday morning, with the goal of getting a candy machine PR in by EoD Monday once I kick the tires a bit more.

**Comment by yusefnapora** [comment]
Published a new version of metaplex-auth yesterday with bundle support and opened a new [candy machine PR](https://github.com/metaplex-foundation/metaplex/pull/2060).

That PR also adds the config option for the gateway URL, so it will close #1586 also.
