### ISSUE TITLE
how to use generate a car file use java

### ISSUE THREAD

**Issue by ToShared** [nftstorage/nft.storage#1708]
i want generate cid custom

**Comment by yusefnapora** [comment]
Unfortunately, native Java support for IPLD is lacking at the moment, and I don't think there's a JVM implementation for the CAR format.

If you're okay with doing the CAR generation in another process, you could use the `ipfs-car` CLI or go-ipfs to generate the CAR, as described here: https://nft.storage/docs/concepts/car-files/#command-line-tools

Hope that helps. I'll close this issue, but please open a new one if you have questions about the docs above.
