### ISSUE TITLE
Gateway CID blocklist

### ISSUE THREAD

**Issue by vasco-santos** [nftstorage/nft.storage#1717]
We will receive takedown requests for problematic CIDs over time and we should have a solution for this. At the moment, we are relying on Cloudflare WAF with hardcoded domain but it would be wise to get a KV store in place where we could have a status and reason for better management of blocked CIDs.

@alanshaw 's suggestion: Key is normalized CID and value is a JSON object with status and reason.

**Comment by olizilla** [comment]
Suggestions:
- talk to Cloudflare about this and see if we can get an unlimited WAF rules.
- add problematic CIDs to the bad bits list and check that for inclusion https://badbits.dwebops.pub/

**Comment by alanshaw** [comment]
Situation with Cloudflare:

> Can I purchase additional active rules?
> No. The number of active rules is fixed based on customer plan. Refer to [Entitlements](https://developers.cloudflare.com/firewall/cf-firewall-rules/#entitlements)

We have the max (1,000 rules) already.

Note we currently have 1 rule blocking 3 CIDs, but the expression [limit is 4KB](https://developers.cloudflare.com/firewall/cf-dashboard/create-edit-delete-rules/#expression-builder-and-editor) so it can grow a bit but not loads.

I was thinking originally that using the firewall would be the way to go but now I think KV is probably better/easier - we can add millions and millions of records here from various sources.

**Comment by olizilla** [comment]
## Notes on Google Safe Browsing

We are looking at 72hrs until the "Deceptive site ahead" phishing protection warning clears...

> Phishing review processing time: Phishing reviews take about a day to process. If successful, the user-visible phishing warning will be removed and your page may again surface in search results.
>
> If Google finds that your site is clean, warnings from browsers and search results should be removed within 72 hours.
>
> – https://web.dev/request-a-review/#c.-phishing-or-social-engineering

**Comment by olizilla** [comment]
Entries in the badbits list are
- Normalised to base32 cidv1
- Include a path and `/` is set as the default
- SHA-256 hashed

e.g

```js
sha256(cidv0 + "/")
```
see: https://github.com/protocol/badbits.dwebops.pub/blob/main/badbits-lambda/helpers.py#L7-L17

**Comment by vasco-santos** [comment]
Created https://github.com/publicsuffix/list/pull/1548 for publicsuffix

**Comment by olizilla** [comment]
Also worth fixing http -> https redirect rule for nftstorage.link as the `http` url currently turns up a domain parking link farm which doesn't help our look

**Comment by thattommyhall** [comment]
I want to replace it, but the check logic is 

```
function helpers.check_denylist(cid, path)
    local pp = require "pl.path"

    path = path or "/"

    local converted_cid, err, level = helpers.convert_base(cid)
    if not level then
        level = ngx.ERR
    end
    if err then
        ngx.log(level, err)
        return
    end

    local keys = {}

    -- check if root hash(`CID/`) is blocked via denylist.json
    local new_key = helpers.sha256(converted_cid .. '/')
    if new_key then
        table.insert(keys, new_key)
    end

    -- if a nested path, also check each directory level
    local _, count = string.gsub(path, "/", "")
    if count > 1 then
        local dir = path
        while (dir ~= '') do
            ngx.log(ngx.DEBUG, "Walking " .. converted_cid .. " with " .. dir)

            local new_key = helpers.sha256(converted_cid .. dir)
            if new_key then
                table.insert(keys, new_key)
            end

            -- move up 1 directory level
            dir = pp.dirname(dir)
        end
    end

    for _, v in ipairs(keys) do
        local key_found, _ = ngx.shared.denied:get(v)

        if key_found then
            ngx.log(ngx.INFO, "Blocked CID: " .. cid .. " with " .. v)
            ngx.exit(410)
        end
    end
end
```

**Comment by thattommyhall** [comment]
Note `410` is [blessed by legal](https://github.com/protocol/bifrost-infra/issues/1771#issuecomment-1079235631)

**Comment by thattommyhall** [comment]
Having the check logic in JS is useful for me, at the moment we have to call out to the api to canonicalise CIDs, I did [the crux](https://github.com/thattommyhall/njs-ipfs/blob/main/njs/src/cid.ts) of moving to use NJS inside nginx when we sat together in London @alanshaw / @olizilla. Tracking https://github.com/protocol/bifrost-infra/issues/1707 in bifrost-infra

**Comment by alanshaw** [comment]
resolved by https://github.com/nftstorage/nft.storage/pull/1721
