### ISSUE TITLE
Error 520

### ISSUE THREAD

**Issue by stefanogalizia** [nftstorage/nft.storage#1718]
Dear team, 
thanks for the wonderful job. 
From time to time, when uploading a car file i get this error:

{"ok":false,"error":{"code":"Error","message":"520: "}

can you please tell what this is referred to?

Thanks

**Comment by dchoi27** [comment]
Hm - do you have any more details (what size of files, when it has happened, which client you're using, etc.)? It looks like it's a Cloudflare thing for when it's not sure what the error is.

**Comment by stefanogalizia** [comment]
hi @dchoi27 , 
i used to split uploaded files in CAR of 90 mbytes each... client is a custom client made by me be basically is a simple upload script. I cannot reproduce the issue, in the sense it happens from time to time without any apparent reason...

**Comment by dchoi27** [comment]
Is this with the HTTP API directly? It'll be hard for us to help if we can't reproduce, unfortunately.

**Comment by dchoi27** [comment]
Can you try using the JS client to store and see if you encounter the same problem?

**Comment by stefanogalizia** [comment]
I did another try, maybe i had an high degree of parallelism.. now i have tried to upload one file at once ... will let you know

**Comment by stefanogalizia** [comment]
Ok all the transfers made tonight didn't get the 520 error, so maybe that was related to the parallelism. Another thing i noticed, sometime when i send a CAR the response from the server come after 30 seconds or even 1 minute, so another thing to take into account is to put a proper timeout, not less than one minute:

look at the attached log, the response from server arrived after 1 minute and 23 seconds.



[log.txt](https://github.com/nftstorage/nft.storage/files/8387567/log.txt)

**Comment by stefanogalizia** [comment]
Hi @dchoi27 , i would add this problem

look at the attached log.. i got this error

{"ok":false,"error":{"code":"Error","message":"524: Origin Time-out"}}

is there anything i can do? Reduce size of CAR, or put size of CAR to 100mb? Or simply i must do a retry ? 

thanks for your help

[log2.txt](https://github.com/nftstorage/nft.storage/files/8387660/log2.txt)

**Comment by vasco-santos** [comment]
> is there anything i can do? Reduce size of CAR, or put size of CAR to 100mb? Or simply i must do a retry ?

Hey @stefanogalizia 

We recommend using nft.storage JS client as it already comes with CAR splitting and retries out of the box. Both 520 or 524 errors can happen sometimes sadly. This happens adding the uploaded data into IPFS Cluster, which sometimes with heavy load might have issues connecting to the IPFS Nodes underneath causing this error.

We are working on a new Upload mechanism that will solve these issues. But for the time being, you will need to rely on retries.

**Comment by stefanogalizia** [comment]
Ok then, will do retry.
Thanks ...
