### ISSUE TITLE
Feature request: Electron.js GUI 

### ISSUE THREAD

**Issue by owlsm** [nftstorage/nft.storage#1735]
Hi,

Will it be possible to create a simple GUI app to upload NFTs collection for average people who are not into coding?

The feature needed are just uploading a single file or a directory.

Best regard.

**Comment by alanshaw** [comment]
Yes! It's coming. Try out the alpha release and let us know how you get on.

https://github.com/nftstorage/nftup

**Comment by dchoi27** [comment]
We'll have an official release for this in the coming week or so! Closing this issue
