### ISSUE TITLE
Upgrade ipfs-cluster to v1

### ISSUE THREAD

**Issue by dchoi27** [nftstorage/nft.storage#1736]
Sister issue to: https://github.com/web3-storage/web3.storage/issues/1184

~~...but we want to do it first for NFT.Storage~~

**Comment by olizilla** [comment]
For this, we will need

- Update dep on ipfs-cluster client to v5.0.1
- Merge to main and update **staging** env cloudflare worker secrets for `CLUSTER_SERVICE` to `IpfsCluster` & `CLUSTER_BASIC_AUTH_TOKEN` from 1pass - to use the new staging cluster running ipfs-cluster@1.0.0-rc.4
- Test on staging
- Wait till maintenance window: https://status.nft.storage/incidents/m54cpnvpm3zz
- Enable read-only mode
- Deploy ipfs-cluster@1.0.0-rc.4 binaries to production cluster
- Merge API release PR to deploy api to prod with support for ipfs-cluster@1.0.0-rc.4
- Merge cron pin update for cluster@1.0 PR to update cron jobs with support for ipfs-cluster@1.0.0-rc.4
- Monitor
- FIN
