### ISSUE TITLE
Refine on-call playbook to include escalation to NetOps

### ISSUE THREAD

**Issue by dchoi27** [nftstorage/nft.storage#1743]
We have an on-call playbook, but let's make sure there are instructions to escalate things to NetOps, as well as expectations on our side on when to just hand things off / when we should hang on to help drive issues to resolution (e.g., updating Statuspage, making sure that our things are prioritized by Netops). Should apply to both NFT.Storage and Web3.Storage.

![image.png](https://images.zenhubusercontent.com/5fa04bd64afb77249c77235b/fe163d56-a715-4454-a4bd-6eb78c333f77)

**Comment by fabiolrodriguez** [comment]
Created document to check cluster health before escalation:

https://www.notion.so/Check-cluster-health-6307732f1f5b469cb3bc160d2ab6599f

Doc linked on on-call playbook.
