### ISSUE TITLE
Refine playbook we give to power users to escalate issues to us

### ISSUE THREAD

**Issue by dchoi27** [nftstorage/nft.storage#1744]
We currently have a playbook we give to power users of the service so they can alert us if anything goes wrong. No one uses it though - we get alerts through mostly me monitoring the shared Slack channels.

Let's review this document to make sure we're happy with it and refine it. From there we can reinforce with our power users to use it (coach them, pin to shared channels, etc.).

Ping @dchoi27 to see this escalation instructions sheet

**Comment by fabiolrodriguez** [comment]
Playbook refined. https://www.notion.so/NFT-Storage-and-Gateway-severe-issue-escalation-instructions-69ad782c9d9c497f9f6d96e4ad67303f
