### ISSUE TITLE
Failed remote pins

### ISSUE THREAD

**Issue by Eroo36** [nftstorage/nft.storage#1745]
For some weeks now everything i remote pin to nft.storage shows failed after queue in the web ui. But i think they are pinned fine. I already mentioned this in discord and it was indeed the case. Here are some example files to check status:
QmfQX2FPDSXAh8Hj2sXRGYPXFcxMF1kdTK2n63uzXtjXzc
QmV8VauacrAZNLGWj5e8YEDqK581jhwSkBP3am6wFBybhL
QmQQWuUAysJicwMgmxanLEHZCKktZAcaXSjFyZ8t2QB719

![Screenshot_2022-03-31-20-54-11-592_com.android.chrome.jpg](https://user-images.githubusercontent.com/13486466/161119155-32aadd90-7a89-4bfd-bb17-e12b5a264023.jpg)

**Comment by OnahProsperity** [comment]
This same issue brought me here.
