### ISSUE TITLE
Error in uploading car file

### ISSUE THREAD

**Issue by BocasNFT** [nftstorage/nft.storage#1750]
I tried for so many times upload the file .car to the ipfs, but this message appers all time: "Error uploading: The requested file could not be read, typically due to permission problems that have occurred after a reference to a file was acquired."

Somebody could help me to fix it? Appreciated...

**Comment by vasco-santos** [comment]
Hello @BocasNFT 

It looks like you are trying to upload really large files that won't fit your memory, which is currently necessary in the browser.

If you need to upload really big files, please look into running a Node.js script like https://github.com/nftstorage/nft.storage/blob/main/examples/client/node.js/storeCar.js

**Comment by alanshaw** [comment]
You could also look into using https://github.com/nftstorage/nftup if you don't need to do it programmatically.

**Comment by alanshaw** [comment]
@BocasNFT please shout if you need more help.
