### ISSUE TITLE
change nft image after mint

### ISSUE THREAD

**Issue by fiubit** [nftstorage/nft.storage#1751]
Hello i need help ...how to change NFT image after minted ? i'm not a developer but i read it's possible Change your BaseUri of your Generated NFT'S   right?  but how ?

**Comment by OnahProsperity** [comment]
on your contract do you have a function to reset the baseURI ?
if yes you can call this function to reset the URI and update with the new hash that you have otherwise it is not possible to change such on the same contract so the other option is redeployment.

**Comment by alanshaw** [comment]
@OnahProsperity is correct you'll need the ability to change the URI from the contract.
