### ISSUE TITLE
Add alert / metrics for Pin Reports

### ISSUE THREAD

**Issue by dchoi27** [nftstorage/nft.storage#1763]
Sister issue to https://github.com/web3-storage/web3.storage/issues/1092

**Comment by fabiolrodriguez** [comment]
Instrumented alerts on this PR: https://github.com/protocol/monitoring-infra/pull/313

![image](https://user-images.githubusercontent.com/15051788/168810392-9680b84f-e9f5-4fac-9689-3768982d0f1e.png)
