### ISSUE TITLE
Error in the client after the last update

### ISSUE THREAD

**Issue by jedipython** [nftstorage/nft.storage#1775]
Error in the python  client after the last update  
`TypeError: _from_openapi_data() missing 1 required positional argument: 'last_change'`
What is required to be specified in this argument?

**Comment by dchoi27** [comment]
When you say last update what do you mean? Were you using the library before and it was working fine?

**Comment by jedipython** [comment]
> When you say last update what do you mean? Were you using the library before and it was working fine?

Yes, I have used it many times and the other day within an hour it abruptly stopped working

**Comment by alanshaw** [comment]
Closing this - lets track in the python client library! https://github.com/nftstorage/python-client/issues/4
