### ISSUE TITLE
Links to NFTUp on nft.storage website

### ISSUE THREAD

**Issue by jchris** [nftstorage/nft.storage#1779]
- [x] Update Step 1 copy on homepage getting started section to include nftup reference and link to new doc page https://nft.storage/#getting-started
-add  "Or download and use our NFTUp application (link to new docs page)"
## Mock showing possible copy update on homepage
<img width="941" alt="Screen Shot 2022-04-14 at 8 59 53 AM" src="https://user-images.githubusercontent.com/2078567/163407288-71029dcd-6d72-4d1b-8432-4f3d5231d156.png">

- [x] Add cta on https://nft.storage/files/ page leading user to the new NFTUp docs page
- Use similar treatment as seen on the /manage page with the "Request API Pinning Access" button
- button label copy should be "Upload directories easily with NFTUp"
- Probably should use the ? icon like in column headers instead of the "?" as seen in rough mock
- include a hover tooltip explaining more about why user should learn about NFTUp
## Mock showing placement of cta on /files page to learn more about nftup 

<img width="679" alt="Screen Shot 2022-04-14 at 9 09 56 AM" src="https://user-images.githubusercontent.com/2078567/163409135-7637a883-c197-49b6-93cc-12b0f8b842f5.png">

## Overview of business need
NFTUp should be easy to download from all over the site. (Accounts, Uploads listings, etc)
We should detect architecture and then have an option to list all downloads.

**Comment by dchoi27** [comment]
My 2c is that we probably just need a link on the upload new file page (NFT.Storage at its core is a developer tool, but the folks who will use NFT UP will be the ones going to the uploads page anyway)

**Comment by alanshaw** [comment]
Agree we should link from the upload page and also direct folks to it when they try to drop "BIG DATA".

We could also add a link (and text) to the getting started section and a link ("App") in the footer.

The page should just explain what NFTUp is and give the user the download button (for their detected arch) and all downloads link (as @jchris suggests).

**Comment by JeffLowe** [comment]
What is the direct link we should use to allow users to direct download?

Do we need a new page on nft.storage that explains what NFTUp is, a section in docs that explains, or only rely on the ctas throughout the website?  Seems like minimally we need 
- CTAs to dedicated page throughout nft.storage (upload page, Getting started section in docs, footer link)
- Dedicated page in /Docs explaining nftUp and with all necessary content/functions (explain, direct download button based on arch, and all download links).

**Comment by jchris** [comment]
@JeffLowe you are right we need all that. For now I am keeping the blog post up to date with the latest by hand. (here is a link to a draft that will go live soon, updating to beta and Universal builds) https://5fa0f865.nft-storage-1at.pages.dev/blog/post/2022-04-05-announcing-nftup/

**Comment by JeffLowe** [comment]
@jchris requirements updated based on our planning session yesterday.  
Can you confirm the details in the description?
Also, could you provide the desired tooltip copy that will appear for the button placed on the /files page?

**Comment by jchris** [comment]
CTA phrases: @dchoi27 any thoughts?

"Install our drag-and-drop NFT uploader."

"Get our easy uploader."

**Comment by dchoi27** [comment]
Think probably something like the 3rd for me! Want to tell them what pain point they're solving for
