### ISSUE TITLE
Interrupted directory upload

### ISSUE THREAD

**Issue by M1lfsh4k3** [nftstorage/nft.storage#1787]
Hello again! :)
Managed to upload 100K Images without a problem, but when i tried to upload the metadata for them i ran into this error:

"C:\Users\alors\Desktop\NFT\NFT Generator\build\json"
storing 100001 file(s) from C:\Users\alors\Desktop\NFT\NFT Generator\build\json
file:///C:/Users/alors/Desktop/NFT/NFT%20program/IPFS%20storage/NFT%20Storage/node_modules/nft.storage/src/lib.js:163
              throw new Error(result.error.message)
                    ^

Error: 524: Origin Time-out
    at pRetry.retries (file:///C:/Users/alors/Desktop/NFT/NFT%20program/IPFS%20storage/NFT%20Storage/node_modules/nft.storage/src/lib.js:163:21)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async RetryOperation._fn (C:\Users\alors\Desktop\NFT\NFT program\IPFS storage\NFT Storage\node_modules\p-retry\index.js:50:12) {
  attemptNumber: 6,
  retriesLeft: 0

What is it saying? XD

**Comment by M1lfsh4k3** [comment]
I dont understand for some reason the folder is on NFT.storage now and pinned aswell!
CID: bafybeietwsh56ilda4imqhrxhul7jk63qj3ishw6nohek7ypuy6inxkgmy
URL: ipfs://bafybeietwsh56ilda4imqhrxhul7jk63qj3ishw6nohek7ypuy6inxkgmy

However clicking on the link makes a page load for a while until gateway fail appears.
But starting up IPFS Desktop and entering the url: with added extension 1.json etc. opens and shows the files conents.

Shouldn't I be able to view the CID folder online without opening IPFS Desktop?
Also if the upload failed how can i make sure all 100K .json files are there and not just a damaged copy without trying to open and view each of the 100k files?? Any help appreciated, thank you guys!

**Comment by dchoi27** [comment]
Hm, it looks like you ran into rate limits in the client, which shouldn't be the case. @alanshaw any thoughts?

However, if it says the folder is pinned, then it probably completed the upload maybe on a subsequent try. You can get specific files from the folder by appending `/filename.extension` to the end of a gateway link (e.g., nftstorage.link/ipfs/CID/filename.extension`. It doesn't look like there's a file called `1.json` (I tried https://nftstorage.link/ipfs/bafybeietwsh56ilda4imqhrxhul7jk63qj3ishw6nohek7ypuy6inxkgmy/1.json) but try with an actual file in the folder.

**Comment by M1lfsh4k3** [comment]
Yeah also tried removing _metadata.json from the upload since its a combined file of all the jsons which summed up to 100mb. Maybe to big to be uploaded i thought, but same problem remains.

**Comment by dchoi27** [comment]
Sorry a bit confused by your response. I was asking about whether you tried a gateway URL (in response to your question `Shouldn't I be able to view the CID folder online without opening IPFS Desktop?`). 

In either case, the JS client library should handle rate limits so the size of your metadata folder shouldn't be super relevant (not sure what you mean by "removing _metadata.json from the upload" - maybe you were trying to upload a directory with images and metadata all at once? Which should be fine regardless)

In the future, if you need a no-code solution for uploading large directories, try: https://nft.storage/blog/post/2022-04-05-announcing-nftup/

**Comment by M1lfsh4k3** [comment]
Sorry, forget my gateway related question. I just want to know how I resolve the error code i pasted here from the client. Also i would like to know if there is a way to "double check" that all 100k files are pinned and working without having to try ipfs://CID-ID/1.json up to ipfs://CID-ID/100000.json manually in the browser.

Since the js script failed according to the error code i would assume a file is missing or damaged?

**Comment by M1lfsh4k3** [comment]
> Sorry a bit confused by your response. I was asking about whether you tried a gateway URL (in response to your question `Shouldn't I be able to view the CID folder online without opening IPFS Desktop?`).
> 
> In either case, the JS client library should handle rate limits so the size of your metadata folder shouldn't be super relevant (not sure what you mean by "removing _metadata.json from the upload" - maybe you were trying to upload a directory with images and metadata all at once? Which should be fine regardless)
> 
> In the future, if you need a no-code solution for uploading large directories, try: https://nft.storage/blog/post/2022-04-05-announcing-nftup/

By the way thanks for the link to the no code version - awesome! :)

**Comment by alanshaw** [comment]
This error is saying it failed to send a chunk 6 times and the last error that occurred had a HTTP 524 status code.

524 is a timeout error (cloudflare sets this) - in our case it is more often than not a timeout writing to cluster. We occasionally get these when cluster is under load but to have 6 failures in a row is _very_ unusual.

We have a new cluster version coming tomorrow that will hopefully improve the situtation 🤞. For now, just restarting the upload is the only way to fix.

**Comment by M1lfsh4k3** [comment]
Ok, i actually restarded the upload several times and the same problem occurred multiple times. I even opened the config file for the node and edited the amount of times it retries to 10 - it failed anyway :/

**Comment by alanshaw** [comment]
> Also i would like to know if there is a way to "double check" that all 100k files are pinned and working without having to try ipfs://CID-ID/1.json up to ipfs://CID-ID/100000.json manually in the browser.

You can ask the API for the status for the root CID e.g. https://api.nft.storage/check/bafkreiem4twkqzsq2aj4shbycd4yvoj2cx72vezicletlhi7dijjciqpui - if `value.pin.status` is `pinned` then we have all the data.

> Since the js script failed according to the error code i would assume a file is missing or damaged?

Yes if you got an error we likely don't have all the data.

**Comment by dchoi27** [comment]
@alanshaw interestingly enough their upload is showing up as `Pinned` https://api.nft.storage/check/bafybeietwsh56ilda4imqhrxhul7jk63qj3ishw6nohek7ypuy6inxkgmy

**Comment by alanshaw** [comment]
If it's `pinned` then we have it all.

So what may be happening is that you got a timeout but cluster received all the data and was just taking too long, so the worker timed out but cluster finished what it was doing.

I'll download the data and try uploading it to see if I can replicate.

**Comment by dchoi27** [comment]
Hi there - we rolled out some new infra last week that should solve this. Please reopen if not!
