### ISSUE TITLE
Implement NetlifyCMS for nft.storage blog & website

### ISSUE THREAD

**Issue by dchoi27** [nftstorage/nft.storage#1797]
Following recommendation detailed in https://www.notion.so/Content-Release-Cycle-Improvement-Rec-2656dcf910a94b33881b973ec4d6f1ca we are to implement netlifyCMS for the NFT.storage blog and website (starting with the /stats page). 

- use the netlifycms hosted by netlify
- if it makes sense, one cms for both the website and blog
- will likely need to store the content in a new content-centric GH repo.

**Comment by JeffLowe** [comment]
Repo created for content https://github.com/nftstorage/nft.storage-content

**Comment by dchoi27** [comment]
Hey - what's the latest here? Would love to have this and the web3.storage blog ready by mid Sept

**Comment by JeffLowe** [comment]
We need the domain mapped (see https://github.com/nftstorage/nft.storage/issues/2176 and the notion doc I posted in slack) by someone with registrar access.  Current checklist of remaining items are here https://github.com/nftstorage/nft.storage/issues/2175

**Comment by JeffLowe** [comment]
closing this out as complete.  cms will go out with #2175
