### ISSUE TITLE
I can't login.  

### ISSUE THREAD

**Issue by gdcode4i** [nftstorage/nft.storage#1818]
I get a magic link and click it, but then I am not logged in and can't see my files. 
gdalston@gmail.com

**Comment by dchoi27** [comment]
Hi, is this still the case? Can you give some more details if so (does it just take you back to the homepage, etc.)? Have you tried Github auth? Etc.

**Comment by gdcode4i** [comment]
Hi,

It works today.

It sent me the magic link, which took me to the home page.  Sat for a while
and the "Files" and "API keys" links did not show.

Thanks

**Comment by dchoi27** [comment]
Great! Thanks to @alanshaw  for fixing
