### ISSUE TITLE
staging links are leaking to google

### ISSUE THREAD

**Issue by jchris** [nftstorage/nft.storage#1819]
BLOCKED until we can get someone with cloudflare admin access to setup http auth on staging. 

see https://www.google.com/search?q=pinning+services+api+nft+storage&oq=pinning for a staging link  

- [ ] consider implementing a simple auth on staging site (share password with team in notion & slack)
- [ ] recommend to marketing team to access google search console and purge the staging.nft.storage from all search results. 

## Screenshot of search results
![82470E10-13F7-4642-AE93-6015C87BC3BE_1_105_c](https://user-images.githubusercontent.com/253/163045677-f3524e06-2baf-4ea2-aa03-08f517d5443a.jpeg)

**Comment by JeffLowe** [comment]
Suggestion:  A simple auth on staging site would prevent indexing of the staging site.

**Comment by johnathonroach** [comment]
@JeffLowe someone with admin access to the Cloudflare worker for staging will likely need to add basic HTTP auth to the staging website. We may need to create a spike and learn how this can be done on Cloudflare.

I agree this is the best approach and will keep the site out of Google indexing. Once that is completed, the content team can hop on Google Search Console and remove any staging links.

**Comment by JeffLowe** [comment]
@jchris

**Comment by hugomrdias** [comment]
I have added a transform rule in cloudflare to add the `X-Robots-Tag: none` header to all responses from staging.nft.storage. This will remove any results from that domain.
