### ISSUE TITLE
Error: 524:

### ISSUE THREAD

**Issue by mounir82** [nftstorage/nft.storage#1821]
Hi everyone. i get the same error when i upload 50000 json files equal to 100Megabyte. The script create car for 50000 json files . But the upload of the car file fails. Thank you for your help.
file:///D:/fullproject/myapp/node_modules/nft.storage/src/lib.js:159
throw new Error(result.error.message)
^

Error: 524:
at pRetry.retries (file:///D:/fullproject/myapp/node_modules/nft.storage/src/lib.js:159:21)
at runMicrotasks ()
at processTicksAndRejections (node:internal/process/task_queues:96:5)
at async RetryOperation._fn (D:\fullproject\601-700\myapp\node_modules\p-retry\index.js:50:12) {
attemptNumber: 6,
retriesLeft: 0
}

**Comment by dchoi27** [comment]
Hi, what version of the client are you using? Also, feel free to check out NFT UP for the best no-code experience for uploading large directories https://nft.storage/blog/post/2022-04-05-announcing-nftup/

**Comment by soft-top-notch** [comment]
I'm also getting this error when I try to mint an NFT with an image. Can you please tell me how to fix it?

**Comment by dchoi27** [comment]
^ we were seeing some errors earlier due to infra issues but those should be resolved now. lmk if not

**Comment by soft-top-notch** [comment]
not fixed. It keeps showing the error

**Comment by maxb94** [comment]
I'm also getting this error

**Comment by dchoi27** [comment]
Hi folks - we rolled out some new infrastructure last week and this should be solved based on our monitoring. Please open a new issue if not!
