### ISSUE TITLE
Login

### ISSUE THREAD

**Issue by NFT-PLAYMATE** [nftstorage/nft.storage#1823]
Won't log into existing account. Enter email, then sends link, click link and link bri gs me back to login page, not logged in.

**Comment by OnahProsperity** [comment]
been facing this same issue for days now.

**Comment by olivierayache** [comment]
Just try to login via my email and it is not working.

**Comment by OnahProsperity** [comment]
Browser: Chrome (Version 100.0.4896.127 (Official Build) (64-bit))
OS: Windows 11 Pro
Processor	Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz   2.81 GHz
Installed RAM	16.0 GB (15.9 GB usable)
Device ID	F126B6D3-4C82-4EA6-86CD-842A17BE5412
Product ID	00342-50608-02141-AAOEM
System type	64-bit operating system, x64-based processor
Pen and touch	No pen or touch input is available for this display


i Have been experiencing this issue for about a week plus now.

**Comment by alanshaw** [comment]
@OnahProsperity do you see any errors in the browser console?  "View > Developer > JavaScript Console"

Also, do you have any ad-blocking enabled or something else that may be blocking requests?

**Comment by alanshaw** [comment]
@OnahProsperity if you use Edge, and copy the link from the email and paste it into a new tab do you get the same problem?

**Comment by alanshaw** [comment]
Is this still happing for you? I was able to reproduce and _think_ I found the issue.

**Comment by OnahProsperity** [comment]
Alright, thanks.

**Comment by dchoi27** [comment]
Closing this, please reopen if you're still facing.
