### ISSUE TITLE
"Deceptive site ahead" on ipfs.nftstorage.link

### ISSUE THREAD

**Issue by uaktags** [nftstorage/nft.storage#1844]
Hello all,
It looks like all *.ipfs.nftstorage.link links are being flagged by Chrome as being deceptive. This appears as the same issue with #1715.

**Comment by xrzhuang** [comment]
+1 pls fix

**Comment by dchoi27** [comment]
Google had implemented a bad regex statement leading to this. They apologize for the inconvenience. Thanks for your patience!

**Comment by xrzhuang** [comment]
Darn the centralized web!
