### ISSUE TITLE
Module not found: Can't resolve 'ipfs-car/blockstore/memory'

### ISSUE THREAD

**Issue by soft-top-notch** [nftstorage/nft.storage#1872]
Hi, there!

When I installed the latest version of this package, I'm getting this error:
![image](https://user-images.githubusercontent.com/48213961/166009834-1f00a777-a3a0-4e56-ad73-334bbbafb181.png)
Could you please let me know why this error comes up? And How to fix it?

Thanks

**Comment by dchoi27** [comment]
https://nft.storage/docs/troubleshooting/#why-am-i-seeing-module-not-found-errors try this!
