### ISSUE TITLE
Store metadata but reuse an existing image URI already on IPFS

### ISSUE THREAD

**Issue by hhff** [nftstorage/nft.storage#1879]
Hi there!

I have a case where I'd like to store new NFT metadata while reusing an image that's already on IPFS. (In my system, users are able to "revise" the name & description of their NFT, but the image may not change when they do that).

Is something like this possible?
```js
    const data = await nftstorage.store({
      image: 'ipfs://existinghash/image.jpg',
      name: newName,
      ...
    });
```

I _could_ download the image and reupload it, but that will add at least a few seconds to the request cycle (which is already pretty slow).

Any plans to support that?

**Comment by dchoi27** [comment]
Hey there - you can always craft your own metadata that references known CIDs. Check out: https://nft.storage/docs/how-to/mint-custom-metadata/#preparing-your-metadata

Closing this issue!

**Comment by hhff** [comment]
Oh thanks @dchoi27 - so I'd just do a HTTP request (using `fetch` or similar) instead of using the client?

**Comment by dchoi27** [comment]
It's even simpler than that if I understand what you're saying correctly - you can just create your own JSON file for your metadata and include the `ipfs://{cid}` link in there (don't have to pull down the data itself as long as you know the CID). Then you can just upload that JSON blob to NFT.Storage using the `storeBlob` method in the JS client or `/upload` HTTP API endpoint.

**Comment by hhff** [comment]
Got it thank you @dchoi27 - will try it soon and let you know if any further questions come up!

**Comment by hhff** [comment]
For anyone that comes after me - this worked:

```js
    // nft image is an existing CID
    if (typeof coverImage === "string") {
      const metadataFile = new File(
        [JSON.stringify({
          image: coverImage,
          name,
          description,
          properties,
        })],
        `metadata.json`,
        { type: 'application/json' }
      );
      const hash = await nftstorage.storeDirectory([metadataFile]);
      return res.status(200).json({ hash });
    } else {
      // nft image is a `File`
      const data = await nftstorage.store({
        image: coverImage,
        name,
        description,
        properties,
      });
    }
```
