### ISSUE TITLE
What go next?

### ISSUE THREAD

**Issue by Jensyr13** [nftstorage/nft.storage#1881]
Hi team

I have uploaded my nft images to nft.storages, but on pin status still say queued and on storing providers queuing...Please help!

Thanks!

![Upload](https://user-images.githubusercontent.com/70280940/166299591-651536ca-ce57-4e5c-813b-9dd74eb2a399.jpeg)

**Comment by Jensyr13** [comment]
Hi David, thank for your help!

In fact what bring me worried is exactly that this contents is uploaded but do not work as it shoulds...on the following links you can realize what i mean...the first one go fine, then the sencond fail and so the others. What should I do in this case? thanks for your help!

https://bafybeiaqyfygafmyca5q5l4ve3hqgmvbwrlqje6as3hiqc3ueygarj6qei.ipfs.nftstorage.link/1.png



https://bafybeiaqyfygafmyca5q5l4ve3hqgmvbwrlqje6as3hiqc3ueygarj6qei.ipfs.nftstorage.link/2.png



[https://bafybeiaqyfygafmyca5q5l4ve3hqgmvbwrlqje6as3hiqc3ueygarj6qei.ipfs.nftstorage.link/1.png]

________________________________
De: David Choi ***@***.***>
Enviado: martes, mayo 03, 2022 9:17 AM
Para: nftstorage/nft.storage ***@***.***>
Cc: Jensy Antonio Rodriguez ***@***.***>; Author ***@***.***>
Asunto: Re: [nftstorage/nft.storage] What go next? (Issue #1881)


Hey, you don't really have to worry about this - if you can retrieve the data from a gateway, you're fine: https://nft.storage/docs/how-to/get-status/

Closing this issue.

**Comment by dchoi27** [comment]
You can try refreshing. We'll have some improvements coming out in the next few weeks to make reads from the gateway this more reliable when NFT.Storage has the content!
