### ISSUE TITLE
Include distribution of response times in nftstorage.link Grafana

### ISSUE THREAD

**Issue by dchoi27** [nftstorage/nft.storage#1893]
Graph for 50th%, 75th%, 90th%, 95th%, 99th% response times for each race and race+cache

**Comment by vasco-santos** [comment]
Partially done in grafana for race+cache. Needs https://github.com/nftstorage/nftstorage.link/pull/79 to be finished up

**Comment by vasco-santos** [comment]
Now live in grafana dashboard 🎉
