### ISSUE TITLE
Secret Keys

### ISSUE THREAD

**Issue by TheCryptovist** [nftstorage/nft.storage#1896]
Sorry I have the key to upload files on the site but I have reate  anft marketplace an want to link to NFT storage to be able to have nfts stored there but the data sent back to the site on the nfts dont i need two keys a public and secret for that?

**Comment by yusefnapora** [comment]
We've recently added a new "delegated authorization" system based on [UCAN tokens](https://ucan.xyz) that would let you hand out tokens to your marketplace users without having to reveal your secret API key.

You can find an overview of the process here: https://nft.storage/docs/how-to/ucan/

To issue UCAN tokens, you'll need the [ucan-storage](https://nftstorage.github.io/ucan.storage/) library, which you can find API docs for here: https://nftstorage.github.io/ucan.storage/

BTW, I'm going to close this issue, but please feel free to open a new one if you have trouble or need help setting up UCAN auth. It's pretty new, so we could use some feedback from users to improve the experience.
