### ISSUE TITLE
how can i upload .glb file

### ISSUE THREAD

**Issue by usama1050** [nftstorage/nft.storage#1934]
is it possible to upload .glb file with the help of nft.storage?

**Comment by yusefnapora** [comment]
Sure, you should be able to store any file type using the `storeBlob` or `storeDirectory` methods on the [JavaScript client](https://nft.storage/docs/client/js/). 

If they're less than 100MiB you can also send a POST request to the `/upload` endpoint of the [HTTP API](https://nft.storage/api-docs/).
