### ISSUE TITLE
allow configuring carSplitter targetSize when storing using client.store

### ISSUE THREAD

**Issue by gobengo** [nftstorage/nft.storage#1962]
When using a client to [store](https://github.com/nftstorage/nft.storage/blob/main/packages/client/src/lib.js#L263) an nft, I want to be able to configure the [targetSize](https://github.com/nftstorage/nft.storage/blob/main/packages/client/src/lib.js#L162) used by the `TreewalkCarSplitter`.

Motivation:
* @alanshaw [suggested a good thought](https://github.com/nftstorage/nft.storage/issues/1943#issuecomment-1143650993) on #1943:
    > We don't have to upload 10MB every time. In the Web3.Storage client we expose the DAG splitting size as a param to put. In NFT.Storage you could use carbites to split the DAG by a smaller size and then call storeCar multiple times.
    * but when I went to implement this, I couldn't figure out how to do this without this type of change that would make the targetSize configurable instead of using the [`MAX_CHUNK_SIZE`](https://github.com/nftstorage/nft.storage/blob/main/packages/client/src/lib.js#L162) constant

Candidate Solutions
1. allow configuring `targetSize`
2. allow injecting a custom [`splitter`](https://github.com/nftstorage/nft.storage/blob/main/packages/client/src/lib.js#L163), which can have a customized targetSize as well as be any other implementation of something like `typeof TreewalkCarSplitter`

Current Preferred Solution
  * Candidate solution 2. This seems more flexible with little downsides

Afterward:
* make use of this in cron nft-ttr so it stores smaller files but with a carsplit

**Comment by alanshaw** [comment]
The service requires the CAR to be split with a particular strategy, so exposing a splitter option could be problematic.

Exposing the chunk size is something we could do...

Do we _need_ to add this low level configurability though - _why_ do we need it?

**Comment by gobengo** [comment]
@alanshaw I don't think we *need* it. But without it I'm not sure how to implement your thought on #1943 to use smaller than 10Mb images while also testing the carsplit path

**Comment by alanshaw** [comment]
@gobengo lets add a `maxChunkSize` option to `putCar` but ensure validation is in place to ensure folks pick suitable values ([as per this PR](https://github.com/web3-storage/web3.storage/pull/1000)).
