### ISSUE TITLE
error code: 1010 while calling REST API

### ISSUE THREAD

**Issue by nicola-attico** [nftstorage/nft.storage#1969]
GET https://api.nft.storage
Authorization: Bearer <mytoken>

HTTP status: 403
Error message: Method failed: (/) with code: 403 - Forbidden username/password combo

Token is correct

**Comment by alanshaw** [comment]
Are you still receiving this? The only way we'd send a 403 is if your account was blocked, but that message isn't something that comes from NFT.Storage as far as I can tell. What is the JSON response you're receiving?

**Comment by vasco-santos** [comment]
Closing this for lack of response and unknown error code. @nicola-attico feel free to re-open if this is still a problem for you
