### ISSUE TITLE
Error: 401: Unauthorized

### ISSUE THREAD

**Issue by chengpengjava** [nftstorage/nft.storage#1983]
Hi,I want to create IPFS locally with docker like this:
![image](https://user-images.githubusercontent.com/33616855/173764556-d4f6baac-7cc9-4c62-9e49-71db22b2a31d.png)
and then I tried to connect ipfs node,so I wrote this:
![image](https://user-images.githubusercontent.com/33616855/173764785-bf7ebb2a-af49-44fa-b8a6-1db5cb1b14d6.png)
the Authorization "Basic QWxhZGRpbjpvcGVuIHNlc2FtZQ==" I don't know what it means so I copied from document of @nftstorage/ipfs-cluster on npm:
![image](https://user-images.githubusercontent.com/33616855/173765466-ec14888a-5af1-429b-aa62-d1064c863aed.png)
and then I run with wrong:
![image](https://user-images.githubusercontent.com/33616855/173765651-d855229e-8755-4fdd-b2c6-aec2b4eec1cf.png)
why?

**Comment by vasco-santos** [comment]
Hi @chengpengjava 

Thanks for reaching out. The authorization token is what makes cluster accepts requests. In your docker config, you have CLUSTER_SECRET which must match what you have set in your docker container. See what Cluster Secret is at https://github.com/ipfs-cluster/ipfs-cluster/blob/9aebbb3fd1854abd2a767b8ec5013bbbfe1638c6/cmd/ipfs-cluster-service/main.go#L238-L241

In nft.storage we define cluster basic auth token in https://github.com/nftstorage/nft.storage/blob/38df3fbfda7c3461d9a94476874f7b8b0ec8dfee/.env.tpl#L36-L37
