### ISSUE TITLE
upgrade cron et al to tsc >= 4.6

### ISSUE THREAD

**Issue by gobengo** [nftstorage/nft.storage#1995]
Motivation:
* https://github.com/nftstorage/nft.storage/pull/1945#issuecomment-1155533297
* it would allow use of a second arg to Error constructor with `cause` option

Risks
* touching lots of code without a good reason to could always introduce new bugs

**Comment by gobengo** [comment]
@alanshaw this seems risky but I'm happy to do it if you think it's worth prioritizing. if so, should it be just for cron subpackage or the whole monorepo?

**Comment by dchoi27** [comment]
@gobengo is this critical for your initiative, or should we prioritize with the support PI?

**Comment by dchoi27** [comment]
^ @gobengo bump on the above

**Comment by gobengo** [comment]
@dchoi27 its not critical at all
