### ISSUE TITLE
I get the same CID

### ISSUE THREAD

**Issue by mGonzim** [nftstorage/nft.storage#2001]
I want to re-upload a folder with the same file structure (file names and quantity of files). I made some changes within the content of some of the files and want to re-upload. I would like to get a different CID. It seems as if the system is identifying it as the same files and building upon the previous upload. 

Any insight would help

**Comment by alanshaw** [comment]
You won't get the same CID unless the content is _exactly_ the same. Are you sure the changes are saved and you are uploading the correct set of files?

**Comment by dchoi27** [comment]
Closing this issue, please provide more details if this is still an issue
