### ISSUE TITLE
Configure nft-ttr to respect release-please releases

### ISSUE THREAD

**Issue by alanshaw** [nftstorage/nft.storage#2002]
Needs some extra config in the workflow yaml e.g. https://github.com/nftstorage/nft.storage/blob/530d74203ab9793f24b620b55ccead426d637075/.github/workflows/cron-dagcargo-sizes.yml#L20-L23

**Comment by gobengo** [comment]
I believe this is done. I've started doing releases of cron-nft-ttr via release-please
