### ISSUE TITLE
Add grafana panel(s) for NFT TTR

### ISSUE THREAD

**Issue by alanshaw** [nftstorage/nft.storage#2003]
Similar to https://protocollabs.grafana.net/d/fmj7-9Znz/web3-storage-stats?orgId=1&viewPanel=25

**Comment by gobengo** [comment]
@alanshaw I wrestled with this a not understanding why there were differences in grafana UI of the metric you point to above compared to the ones I'm sending.

I noticed that the metric you're using there is a `gauge` https://github.com/web3-storage/web3.storage/blob/78ef3c2a7d0c810a1dc816072e88acbfacd5e742/.github/workflows/cron-test.yml#L39
Whereas in #1943 [we used](https://github.com/nftstorage/nft.storage/pull/1945#discussion_r886983932) a histogram.

**Comment by gobengo** [comment]
@alanshaw There are two panels [in this dashboard i made](https://protocollabs.grafana.net/d/9wQvbG37k/bengo-nft-ttr?orgId=1&from=now-24h&to=now)

I think you should be able to see it?
There aren't many datapoints yet, but the panels/queries should be right for when more data comes in.

I used these docs: https://grafana.com/blog/2020/06/23/how-to-visualize-prometheus-histograms-in-grafana/

If you want a plot exactly like the one you linked to, I believe I'll need to add another metric of type `gauge`.

**Comment by lanzafame** [comment]
@gobengo With histograms, three metrics are actually created, the *metric*_buckets, *metric*_count, and *metric*_sum. To create the panel that @alanshaw is after you should be able to use the *metric*_sum metric.

**Comment by gobengo** [comment]
Data now flowing in after realizing what was wrong (nft.storage needed PUSHGATEWAY_BASIC_AUTH secret, which I added).

https://protocollabs.grafana.net/d/9wQvbG37k/bengo-nft-ttr?orgId=1&from=now-12h&to=now

lmk if these aren't sufficient @alanshaw, or if you want me to add them to any specific other dashboards (or make available as reusable panels) and we'll reopen/fast-follow
