### ISSUE TITLE
website won't load

### ISSUE THREAD

**Issue by ilanoh** [nftstorage/nft.storage#2004]
Website won't load after login,

Been like this for hours,

Any idea how to resolve ?

<img width="748" alt="Screenshot 2022-06-20 at 11 47 41" src="https://user-images.githubusercontent.com/4743669/174563201-1d878ad7-068f-425d-9eb2-e09f72623ef2.png">

**Comment by dchoi27** [comment]
Closing for now, please reopen if still an issue
