### ISSUE TITLE
Add Rarible logo to homepage and stats page

### ISSUE THREAD

**Issue by dchoi27** [nftstorage/nft.storage#2010]
- [ ] On the homepage, replace "Gallery" logo with this Rarible logo. 
- [ ] Add Rarible to the collection of logos on stats page. 

https://rarible.com/branding

**Comment by TkKonstantin** [comment]
Is there a timeline for this update? 
Would be great to time it with an announcement blogpost about integration.
It is planned for the mid of July

**Comment by dchoi27** [comment]
The update to the website itself is super simple and can be done whenever. We're more waiting on the green light to do it.
