### ISSUE TITLE
error - unhandledRejection: TypeError: property `image` must be a Blob or File object

### ISSUE THREAD

**Issue by BernardoOlisan** [nftstorage/nft.storage#2017]
So I'm using nodejs to use the api for storing ipfs files, all works, except for the image file, I heard that is not possible to upload base64 images, but blobs are possible, So I convert a base64 image to blob like this

```
const { Blob } = require("node:buffer");

const blobImage = new Blob([image], {type : 'image/png'});
console.log(blobImage);
```

Now, I guess I just need to pass blobImage to the image part of NFT.STORAGE

```
           const metadata = await nftstorage.store({
                image: blobImage,
                name: "Bluetoken",
                description: "This is your Bluetoken!",
            });
```

The problem is that this is giving me this error
`error - unhandledRejection: TypeError: property "image" must be a Blob or File object`
Any idea of what that is? I'm giving the actual blob as an image, Idk what is going on:(

Thank you in advance.

**Comment by vasco-santos** [comment]
@BernardoOlisan can you try to use https://github.com/web-std/io/tree/main/packages/blob instead of new Blob from Node.js?

**Comment by vasco-santos** [comment]
Closing this as answer should be above. @BernardoOlisan feel free to re-open if this is still a problem. Thanks
