### ISSUE TITLE
Cannot Upload NFT Metadata via NFTUP

### ISSUE THREAD

**Issue by gateforce** [nftstorage/nft.storage#2024]
I have tried dozens of times and cannot manage to upload my NFT metadata(17MB Total)

I keep getting this error msg:

Error: storing files: request to https://api.nft.storage/upload/ failed, reason: socket hang up

I have had no problem uploading all the NFTs(10+Gb)

**Comment by Timilo77** [comment]
Same for me...

**Comment by Tkd-Alex** [comment]
Yup, I've the same

**Comment by dchoi27** [comment]
Hey folks, we'll be rolling out a new backend infra likely tomorrow that's been tested with our sister project Web3.Storage and should solve this. Mind trying in 1-2 days and reporting back?
