### ISSUE TITLE
Pinning Service Compliance Checker failures

### ISSUE THREAD

**Issue by SgtPooki** [nftstorage/nft.storage#2030]
Hey NFT.storage, 

This is a friendly notification that your pinning service is failing some compliance checks. As mentioned in https://github.com/ipfs-shipyard/pinning-service-compliance/issues/125#issuecomment-1167880416, we won't be continuing to open issues moving forward, but I did open a PR https://github.com/ipfs-shipyard/pinning-service-compliance/issues/140 that could help keep you informed about your compliance results in an automated fashion. 

Latest report permalink:
https://github.com/ipfs-shipyard/pinning-service-compliance/blob/dbd8adcbb410579845dcbb584f097b3f74848c54/nft.storage.md?plain=1#L2-L28

Let me know if you have any questions/comments!

**Comment by plwileverts** [comment]
This should be addressed in @olizilla's current work stream (pickup). Rather than refactor the old way, it should just work in the completed version of that.
