### ISSUE TITLE
How to get a LARGE folder to upload??

### ISSUE THREAD

**Issue by Founder-Bricks** [nftstorage/nft.storage#2032]
Hello, I need to upload a large folder 52.44 gb . Is there a paid or different version that can help me upload? 

I need this files uploaded urgently! 

Thanks ALOT for the help here- 

Bryan

**Comment by dchoi27** [comment]
Hi - if you split the folder into smaller folders, you could upload it to NFT.Storage. Otherwise, you can check out other solutions like Pinata.
