### ISSUE TITLE
nftup 

### ISSUE THREAD

**Issue by steelmythos** [nftstorage/nft.storage#2042]
when using NFTup it freezes see attachment, It has happened 3 times the file are large but under 30GB

![Screenshot 2022-06-30 104242](https://user-images.githubusercontent.com/6610971/176581935-a42e5ec2-5f10-4f41-9121-460785781fc0.png)

**Comment by dchoi27** [comment]
Hey - does it work for other uploads? Would it be possible to share the upload data with us so we can use it for testing?
