### ISSUE TITLE
Error in Uploading

### ISSUE THREAD

**Issue by K1-Nft** [nftstorage/nft.storage#2044]
I have tried dozens of times and cannot upload my NFT metadata (475MB Total)

I keep getting this error msg:

Error: **storing files failed, reason: read ECONNRESET**

**Comment by dchoi27** [comment]
If you can share the data you are trying to upload, we can help debug.

**Comment by swdreams** [comment]
Same error for 10k files (15MB size) even though I tried to pin on the server.
