### ISSUE TITLE
Add E-IPFS node to peerlist

### ISSUE THREAD

**Issue by dchoi27** [nftstorage/nft.storage#2046]
Once https://github.com/web3-storage/web3.storage/issues/1605 is done, we should add peer to NFT.Storage peer lists:
- https://docs.ipfs.io/how-to/peering-with-content-providers/#content-provider-list
- https://github.com/web3-storage/web3.storage/blob/main/PEERS

**Comment by alanshaw** [comment]
Done:

https://github.com/nftstorage/nft.storage/pull/2107
https://github.com/ipfs/ipfs-docs/pull/1228

We will update when the domain name changes.
