### ISSUE TITLE
Issue with SSL - I can't see any of the files

### ISSUE THREAD

**Issue by grigb** [nftstorage/nft.storage#2049]
Example link:
https://bafybeigzcazxeu7epmm4vtkuadrvysv74lbzzbl2evphtae6k57yhgynp4.ipfs.nftstorage.link/399.png
<img width="661" alt="image" src="https://user-images.githubusercontent.com/385333/177019355-c480d68d-172e-46a6-bfba-f7861e5b9d9e.png">

**Comment by vasco-santos** [comment]
Hi @grigb 

Can you please try in another network and let us know if it works. Also useful if you can get through https://hackmd.io/-yEon-sMSgq8bCMP-ZFLRA and let us know the results.

From previous situations, there are some security vendors/ISPs/browsers that flag nftstorage.link badly.  You can read more about it in https://nft.storage/blog/post/2022-04-29-gateways-and-gatekeepers/

For now, would be awesome if we can get more information to try to get this unblocked by the party who is blocking it.

**Comment by HRK44** [comment]
same issue, keep having SSL problems can't grab any metadata

**Comment by vasco-santos** [comment]
Hi @HRK44 

Can you try the reference above? It is likely ISP blockage and we need more information in order to solve this. Please try using other ISP (or a VPN) and if it works as expected, please let us know your ISP so that we reach out to them and get nftstorage.link unblocked

**Comment by vasco-santos** [comment]
Closing this for now as issue should be solved. @HRK44 if this is still an issue let us know by re-opening the issue
