### ISSUE TITLE
CID Showing Invalid Response

### ISSUE THREAD

**Issue by DABIT12** [nftstorage/nft.storage#2053]
Hello, 

I am unable to access my IPFS information through the CID option on my account. Every time I've tried to visit it, I keep getting an invalid response due to lack of security. Could you please help me with this?

![image](https://user-images.githubusercontent.com/108684336/177184783-21d008f4-bc8a-4365-a646-b6b12673341d.png)

**Comment by dchoi27** [comment]
Hi - this is likely an issue with your ISP, VPN, or security software messing with the connection to nftstorage.link. For now, you can try using any of the other public gateways like dweb.link (see: https://docs.ipfs.io/concepts/ipfs-gateway/)

Otherwise, we'd appreciate your help getting to the bottom of this. Who is your ISP? And do you mind following the instructions here and sharing the output? https://hackmd.io/-yEon-sMSgq8bCMP-ZFLRA

**Comment by DABIT12** [comment]
> Hi - this is likely an issue with your ISP, VPN, or security software messing with the connection to nftstorage.link. For now, you can try using any of the other public gateways like dweb.link (see: https://docs.ipfs.io/concepts/ipfs-gateway/)
> 
> Otherwise, we'd appreciate your help getting to the bottom of this. Who is your ISP? And do you mind following the instructions here and sharing the output? https://hackmd.io/-yEon-sMSgq8bCMP-ZFLRA

Could you provide some clarification as to how this would have occurred? I've been using it fine for a few weeks now with no issues. Suddenly after the latest maintenance session today around 10:00am EST I started having the issue.

**Comment by dchoi27** [comment]
It's a 3rd party issue, and has nothing to do with the maintenance window or the NFT.Storage service itself. We're here to help figure out what's going on, but it's nothing caused by NFT.Storage itself.

**Comment by DABIT12** [comment]
I currently use Spectrum as my internet service provider.

![image](https://user-images.githubusercontent.com/108684336/177411169-404d74e0-9ea7-47d3-b5a7-3f2eccf6bc2d.png)

**Comment by dchoi27** [comment]
Thanks! @vasco-santos mind taking a look when you have a sec?

In the meantime @DABIT12 - do you use a VPN? If not, do you mind trying one to see if it works? Would help us isolate whether it's the ISP or elsewhere

**Comment by DABIT12** [comment]
Do you have a recommended VPN that is free?

**Comment by vasco-santos** [comment]
@DABIT12 Could you have a try on it?

**Comment by vasco-santos** [comment]
Closing as this should be fixed. @DABIT12 feel free to re-open if this is still not working for you

**Comment by DABIT12** [comment]
Hey Vasco,

Sorry for the delay. I thought I already replied to this. I got everything
figured out as it was an error on my end. Thank you guys for being quick to
try and resolve the issue though.
