### ISSUE TITLE
NFT uploading issues

### ISSUE THREAD

**Issue by NutellaOnYou** [nftstorage/nft.storage#2055]
Hi there
I'm trying to upload an NFT collection that contains 10K images and weights 17.6 GB.
Well, first of all Ive tried using the web, converted the collection to CAR file and basically got a red line (same as this issues #2029 ) and the upload button aint working anymore.
Next Ive dropped the folder with the images to NFTUP and got an error around 2.5 GB, "no such file directory".
Now I wanna try to use the JS client provided here to try uploading the CAR file but unfortunately I don't know and understand coding, even tho there are some examples but I still cant get it.
Is there any guide?  I mean step by step, like: 1 do this, 2 do that and 3 do this and this and you're done.
Thanks in advance.

**Comment by dchoi27** [comment]
NFT Up would be your best bet. Try clicking the upload box and then uploading that way (rather than dragging and dropping).

**Comment by NutellaOnYou** [comment]
I will try, gonna update soon !

**Comment by NutellaOnYou** [comment]
Why Im not surprised
The NFTUP got stuck at the end and "Pin Status:Failed"
![Yeah](https://user-images.githubusercontent.com/108725066/177636999-826aaefb-1078-4b8a-96bf-7f0d1b9de55f.jpg)

**Comment by vasco-santos** [comment]
@NutellaOnYou can you get us the CID for looking into current pin status? It looks like all the upload chunks were sent by the progress bar

**Comment by LinmyChi-you** [comment]
How was your problem solved in the end? I also faced the problem of getting stuck at the end.

**Comment by NutellaOnYou** [comment]
Hi
you will not believe but the solution was kinda stupid.
Ive upgraded my internet connection to optical fiber.
