### ISSUE TITLE
Error when uploading .CAR

### ISSUE THREAD

**Issue by cbertozz** [nftstorage/nft.storage#2056]
Any ideas why this error appears when I upload .CAR file
<img width="1108" alt="Screen Shot 2022-07-05 at 7 24 37 pm" src="https://user-images.githubusercontent.com/108720727/177300155-b3728620-f226-44dd-a42a-96d1ff4fd7ea.png">

**Comment by dchoi27** [comment]
Hi - for large uploads, we recommend using NFT Up https://nft.storage/docs/how-to/nftup/
We'll add a warning to the Web UI to point users to NFT Up for larger files / directories

**Comment by swdreams** [comment]
Hi @dchoi27 
I can't pin a directory with 10k JSON files with NFT Up. I tried many times, but got stuck!
Even though I tried a CAR, it failed.
Is there any solution like progressive pinning for a lot of files?
In practice, we might face more than 10k NFTs. (I experienced 60k NFTs)
Thanks

**Comment by vasco-santos** [comment]
@cbertozz can you let us know how you created the CAR file? It looks like it does not have all the blocks inside it.

If you can also provide us the CAR file would be great for debugging
