### ISSUE TITLE
Upload Assets one by one

### ISSUE THREAD

**Issue by manic007** [nftstorage/nft.storage#2058]
Hello,
     I am creating solana NFTs. I used candymachine V2 and nft-storage for uploading NFTs. I tried uploading 10 NFTs, but all the 10 assets

 are uploaded at once that means in single bundle. Until everything is uploaded cache file is not uploaded with the links to assets. I have planned to upload 10,000 NFTs, so if something happens inbetween like network error or something I have to upload everything again. Is there any way to upload NFTs one-by-one and get the cache updated instantly when 1 asset is uploaded.
I have attached snapshots of the issue
![Issue](https://user-images.githubusercontent.com/10615926/177505941-aa22d18a-cf46-485b-8e0e-4e1adf303ea9.PNG) 
and the output i expect.
![NeedLikeThis](https://user-images.githubusercontent.com/10615926/177505935-c0f66395-cf26-429e-b620-d6083fea57f2.PNG)

Thank you

**Comment by alanshaw** [comment]
Yes, you can upload assets individually. I don't know how to configure the tool you are using to do that. @yusefnapora syas you could set the batch size to 1...maybe can elaborate?!

**Comment by yusefnapora** [comment]
Hi @manic007, you can set the `batchSize` param in your config json to `1`, and it will upload each NFT individually and add them to the cache as soon as they're uploaded
