### ISSUE TITLE
Ensure links in FAQ page styled as links

### ISSUE THREAD

**Issue by JeffLowe** [nftstorage/nft.storage#2059]
Ensure all links in faq content render visibly as hyperlinks.  May want to wait until #1812 lands to use this component. 

![image](https://user-images.githubusercontent.com/2078567/177589278-8f69a313-8238-4344-a4c0-9d80c67f12a6.png)

**Comment by cmunns** [comment]
Implementing tailwind typography plugin is a minimal lift here that will handle these links for us and won't require us waiting on the other open issue.

<img width="1716" alt="Screen Shot 2022-07-06 at 10 41 43 AM" src="https://user-images.githubusercontent.com/1189523/177601654-a3bee73a-8d7d-4ae5-a6da-61152812586b.png">
