### ISSUE TITLE
Pin Status Failed: Content Retrievable

### ISSUE THREAD

**Issue by jeevikakh** [nftstorage/nft.storage#2062]
Hello, I had uploaded data on nft.storage. The pin status says Failed, but I am able to retrieve it. The documentation instructed to file an issue if it was retrievable, but not pinned.

I had used NFTUp to upload the files.

**CID:** bafybeif4i36exjtppyze4bzelm2dh4cgduo3jk7fbgodpfpsrmaxafppfe

**Comment by 0xe094** [comment]
Upload size is around 64 GB. Would this be causing the issue, it says the individual upload should be 31 GB, but I'm not sure it is for the whole upload or a single file.

**Comment by alanshaw** [comment]
Note that 64GB will not currently make it onto the Filecoin network. It should become pinned by our cluster though...

I can see the uploaded CAR files on our system, just checking to see if the DAG is complete (might take a while). This could be why it is not becoming pinned.

**Comment by alanshaw** [comment]
@0xe094 we don't have the full DAG for this, and this is why it's not becoming pinned on cluster. You should re-upload.

Probably not helpful, but the first CID we don't have yet: `bafkreici6n4ah322i47coikcc5pfvmrzt7scnu2ipltxrxv7c2qzqktdou`

**Comment by ribasushi** [comment]
@alanshaw I have it though... 🤔

**Comment by vasco-santos** [comment]
It looks like we got it to our bucket but not in Cluster @alanshaw ? As we moved to our new infra with E-IPFS we should now have the entire dag?

**Comment by ribasushi** [comment]
@vasco-santos afaik `pin-status` is being retired as a concept. Poke @olizilla for details.
