### ISSUE TITLE
failed to initialize nft.storage in angular

### ISSUE THREAD

**Issue by Rasoooll** [nftstorage/nft.storage#2069]
after npm install nft.storage , I added :
`    let nftstorage = new NFTStorage({ token: NFT_STORAGE_KEY });`
Got error: 
./node_modules/nft.storage/src/lib.js:620:20-24 - Error: export 'default' (imported as 'pipe') was not found in 'it-pipe' (possible exports: isDuplex, isIterable, pipe, rawPipe)

**Comment by GJanuario** [comment]
Hey there!

Had the same issue. Solved by editing the file `node_modules/nft.storage/src/lib.js`.

Before editing:
```javascript
...
import pipe from 'it-pipe'
...
```

After editing:
```javascript
...
import { pipe } from 'it-pipe'
...
```
