### ISSUE TITLE
Transferring from pinata to nft.storage

### ISSUE THREAD

**Issue by OtoMatt** [nftstorage/nft.storage#2079]
Hi, 

I am currently using pinata, but want to transfer to nft.storage, how do I do this? I already have files on ipfs with their respective CIDs, but don't see how I can import this here? 

Thanks, 
Otomatt

**Comment by vasco-santos** [comment]
Hey @OtoMatt 

The best way to do this is with the Pinning Service API. You can read more about it https://nft.storage/docs/how-to/pinning-service/

You will need to request access. Closing this, but feel free to re-open if you have any question around it
