### ISSUE TITLE
Filing an Issue

### ISSUE THREAD

**Issue by drean-nft** [nftstorage/nft.storage#2083]
Pinning failed CID - bafybeiflq6wq3jrzxpbcowp2bbmbrardiwsmehs4zd5xdelpchatehls54

**Comment by vasco-santos** [comment]
Hey @drean-nft 
This Is now pinned and should be reflected in your side https://api.nft.storage/api/check/bafybeiflq6wq3jrzxpbcowp2bbmbrardiwsmehs4zd5xdelpchatehls54

Feel free to reopen if not the case
