### ISSUE TITLE
Filing an Issue

### ISSUE THREAD

**Issue by drean-nft** [nftstorage/nft.storage#2087]
I just uploaded my file on NFT storage. It has uploaded successfully and all the files are retrievable. But the pinning status after a long time still shows failed. CID of the files - bafybeiflq6wq3jrzxpbcowp2bbmbrardiwsmehs4zd5xdelpchatehls54

**Comment by vasco-santos** [comment]
Hey @drean-nft 

Your provided CID should now be pinned. It likely had a delay on getting ingested by our infra. 
 https://api.nft.storage/api/check/bafybeiflq6wq3jrzxpbcowp2bbmbrardiwsmehs4zd5xdelpchatehls54

Feel free to reopen if still an issue
