### ISSUE TITLE
re-enable skipped test when miniflare bug is fixed

### ISSUE THREAD

**Issue by yusefnapora** [nftstorage/nft.storage#2088]
This issue is a reminder to re-enable the test in `nfts-store.spec.js` that was disabled by #2065 once the issue with file paths not being preserved in Miniflare is sorted.

Revisit once https://github.com/cloudflare/miniflare/pull/309 is merged (or the bug is fixed some other way :smile:).

**Comment by plwileverts** [comment]
@yusefnapora is on this!
