### ISSUE TITLE
Problem with displaying ipfs link

### ISSUE THREAD

**Issue by seldakocak** [nftstorage/nft.storage#2089]
Hi there, 
I cannot access my json data via opera or brave browser with ipfs cid code (ipfs://bafkreiebpfuubif7qt7zpyepemeqcewdqhljvi3d2tbygx3p4ukivvfwqa/1.json)

I'm getting a warning like this:
ipfs resolve -r /ipfs/bafkreiebpfuubif7qt7zpyepemeqcewdqhljvi3d2tbygx3p4ukivvfwqa/1.json: func called on wrong kind: "LookupBySegment" called on a bytes node (kind: bytes), but only makes sense on map or list

I download my json files at the link ipfs://bafkreiebpfuubif7qt7zpyepemeqcewdqhljvi3d2tbygx3p4ukivvfwqa. But I want to view.

Can you help me?

Thanks,
Selda

**Comment by vasco-santos** [comment]
Hey @seldakocak 

The provided CID `bafkreiebpfuubif7qt7zpyepemeqcewdqhljvi3d2tbygx3p4ukivvfwqa` resolves to a ZIP file, you can check it using https://ipfs.io/ipfs/bafkreiebpfuubif7qt7zpyepemeqcewdqhljvi3d2tbygx3p4ukivvfwqa

As a result, it won't be possible for getting `/1.json` from it, as this content is not a directory. Not related to Opera/Brave browsers.

Closing the issue, feel free to re-open if you need more help here
