### ISSUE TITLE
NFT.Storage vs IPFS Desktop

### ISSUE THREAD

**Issue by bigrobertdesigner** [nftstorage/nft.storage#2114]
@vasco-santos Hi! Greetings. I'm new here. Can I load a project directly into NFT.Storage even though I previously loaded it from IFPS? I don't want to have problems with fixing my project, so I don't want to do it through API. I found out about NFT.Storage later and had already uploaded everything to IFPS, but if I can upload it through NFT.Storage it would be great. Will I have any problems with this? Can anyone help me with this noob question? hahahaha

**Comment by vasco-santos** [comment]
@bigrobertdesigner With IPFS Desktop you can upload files to your local IPFS node. You can then setup https://nft.storage/docs/how-to/pinning-service/ to have nft.storage IPFS nodes to get your content and pin it in our infrastructure so that content is available while your node is offline or not reachable.

You can have content uploaded into multiple storage providers with same CID, there won't be issues with that.

Closing the issue, feel free to re-open if you need more help

**Comment by bigrobertdesigner** [comment]
> @bigrobertdesigner With IPFS Desktop you can upload files to your local IPFS node. You can then setup https://nft.storage/docs/how-to/pinning-service/ to have nft.storage IPFS nodes to get your content and pin it in our infrastructure so that content is available while your node is offline or not reachable.
> 
> You can have content uploaded into multiple storage providers with same CID, there won't be issues with that.
> 
> Closing the issue, feel free to re-open if you need more help

Thank you very much for your feedback. I managed to pin my nodes to IPFS-Desktop through the API. My question now is: My structure in IPFS-Desktop is divided into two folders: One for the metadata and another for the images. When fixing the nodes in NFT.Storage through the API, another CID appeared, and when clicking on the link of this CID, my folders stored in the IPFS-Desktop appear. Is this right? Which CID should I use to Deploy my smart contract? The CID created in IPFS-desktop?

**Comment by yusefnapora** [comment]
@bigrobertdesigner you should be able to use either CID, but you should verify by trying to fetch it through an HTTP gateway (e.g. `https://nftstorage.link/ipfs/$YOUR_CID`).

If the CID from IPFS Desktop starts with `Qm`, it may actually be the same CID as the one from nft.storage, just encoded differently. nft.storage always returns Version 1 CIDs (usually starts with `bafy`), but I think IPFS Desktop may still show Verson 0 CIDs (starts with `Qm`).

You can check whether they are the same CID using the HTTP gateway - if you go to `https://nftstorage.link/ipfs/$VERSION_ZERO_CID` it will redirect to `https://$VERSION_ONE_CID.ipfs.nftstorage.link`.

**Comment by bigrobertdesigner** [comment]
Wow!!!It worked!! Thank you very much!!!!
