### ISSUE TITLE
Support UMD

### ISSUE THREAD

**Issue by njovy** [nftstorage/nft.storage#2115]
I am trying to use this library in a flutter web application but ESM is not supported at the moment. Web3 libraries such as ethers, walletconnect, etc. provide UMD so there is a library that bridges these to dart. 
I would really appreciate if this library can provide a rollup config for UMD and distribution.

Thank you for this awesome library.

**Comment by olizilla** [comment]
Thanks! There is a pre-bundled version of nft.storage client (see: https://nft.storage/docs/troubleshooting/#why-am-i-seeing-module-not-found-errors)

```
import { NFTStorage } from "nft.storage/dist/bundle.esm.min.js";
```

Does that work for you in Flutter, at least as a workaround until it supports ESM?

**Comment by njovy** [comment]
@olizilla The bundle file didn't work because it's ESM.
I actually created an extra rollup config for umd and built it. I didn't run a full test but basic features that I need work as expected.
```
// @ts-ignore
import { terser } from 'rollup-plugin-terser'
import commonjs from '@rollup/plugin-commonjs'
import resolve from '@rollup/plugin-node-resolve'
import json from '@rollup/plugin-json'

export default {
  input: 'src/lib.js',
  output: [
    {
      inlineDynamicImports: true,
      file: 'dist/bundle.umd.min.js',
      format: 'umd',
      name: 'NFTStorage',
      plugins: [terser()],
      sourcemap: true,
    },
  ],
  plugins: [
    commonjs(),
    resolve({
      preferBuiltins: false,
      browser: true,
    }),
    json(),
  ],
}
```
I am not familiar with JS ecosystem so you can edit it to provide UMD later.

**Comment by vasco-santos** [comment]
Thanks @njovy to share the insights to solve this.

Closing this issue, if you need further help feel free to open a new issue
