### ISSUE TITLE
Broken link in blog entry

### ISSUE THREAD

**Issue by dawnkelly09** [nftstorage/nft.storage#2116]
Hello, team! I wanted to create a PR to update this for you but I can't find where the blog lives in this set of repos. 

Blog post needing update: https://nft.storage/blog/post/2022-07-06-elastic-ipfs/

Update needed: the link to Elastic IPFS in the first paragraph under "Announcing Elastic IPFS" is broken and returns a 404 error. 

Correct link to replace broken link: https://github.com/elastic-ipfs/elastic-ipfs

If you can point me toward where the blog lives, I'm happy to make a PR myself to update this link. Thanks!

**Comment by mishmosh** [comment]
Good catch! The blog entries live here: https://github.com/nftstorage/nft.storage/tree/main/packages/website/posts. (I found it by searching this GitHub repo for "announcing" which is a relatively unique word from the blog post.)

**Comment by JeffLowe** [comment]
Looks like this one was fixed with https://github.com/nftstorage/nft.storage/pull/2118
Thank you for ticketing this find!
