### ISSUE TITLE
Upload Stuck

### ISSUE THREAD

**Issue by Aquanoxius** [nftstorage/nft.storage#2124]
Hello!
Try to upload 10k files for my nft collection and looks like uploading stuck within 12 hours already

![upload stuck](https://user-images.githubusercontent.com/58363451/183398620-7e9e959d-ad24-48ba-80b1-1257b256fc72.png)

**Comment by Aquanoxius** [comment]
But...

![files](https://user-images.githubusercontent.com/58363451/183399195-3955330f-50df-44dc-9e5e-d8dc210d1127.png)

**Comment by Aquanoxius** [comment]
Rampp tell me that this CID is not ok

![error](https://user-images.githubusercontent.com/58363451/183399512-4eabbff2-a64a-4bcd-90d3-d195f3d56185.png)

**Comment by Janous** [comment]
I have the same issue but the files are viewable now. Not sure if I am going to close the application or not.
![image](https://user-images.githubusercontent.com/14030635/184519293-cce30a4b-77d8-4ce9-89ff-cac63a1727c3.png)

**Comment by vasco-santos** [comment]
@Aquanoxius did you try to get this CID with a IPFS public gateway like nftstorage.link ?

The content is pinned by one of the screenshots, which means that the upload should be completed and data accessible. If this is not the case, can you provide us the CID for debugging?

Thanks
