### ISSUE TITLE
How-to for peering with NFT.Storage

### ISSUE THREAD

**Issue by dchoi27** [nftstorage/nft.storage#2129]
Once we have the final domain name for our E-IPFS node (in the next week or so, @francardoso93 is working on this and can follow up when ready), let's share the peer ID / info in a new section here: https://nft.storage/docs/concepts/architecture-considerations/#retrieving-data-for-end-users 

It should also mention that it takes some time for new uploads' records to be picked up by the DHT (via indexers), and if you're using your own IPFS nodes to fetch data, you can circumvent this by peering.

Let's also stick a line in the Store docs that references this section as well as something to keep in mind!

We can put a new subsection at the bottom called "Peering with NFT.Storage nodes" and include information about what situations you'd consider peering (you're running your own IPFS nodes and/or gateway) and how to peer.

**Comment by elizabeth-griffiths** [comment]
Closing as this ticket is over 1 year old. If you still need support, please re-open this issue and provide more detail. Thanks!
