### ISSUE TITLE
Analytics support for nft.storage website

### ISSUE THREAD

**Issue by dharmapunk82** [nftstorage/nft.storage#2132]
Please add GTM tracking code to nft.storage site:

Paste this code as high in the <head> of the page as possible:

`
<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'[https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f)](https://www.googletagmanager.com/gtm.js?id=%27+i+dl;f.parentNode.insertBefore(j,f));
})(window,document,'script','dataLayer','GTM-MS25MX2');</script>
`

Additionally, paste this code immediately after the opening <body> tag:

`
<noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-MS25MX2"
height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
`

**Comment by elizabeth-griffiths** [comment]
Closing as this ticket is over 1 year old. If you still need support, please re-open this issue and provide more detail. Thanks!
