### ISSUE TITLE
Interactive API Doc for `POST /ucan-upload` is failing with a 404

### ISSUE THREAD

**Issue by 0x00000010** [nftstorage/nft.storage#2155]
### Step 1

Open https://nft.storage/api-docs and navigate to the `POST /ucan-upload` endpoint.

### Step 2

Attach a valid bearer token via the padlock

### Step 3

Attach a file and execute the request. You will receive a silent failure

### Failing Request

```
Request URL: https://api.nft.storage/ucan-upload
Request Method: POST
Status Code: 404 
Referrer Policy: strict-origin-when-cross-origin
```

#### Note - the preflight OPTIONS call is still successful

```
Request URL: https://api.nft.storage/ucan-upload
Request Method: OPTIONS
Status Code: 204 
Remote Address: 104.x.x.x:443
Referrer Policy: strict-origin-when-cross-origin
```

**Comment by alanshaw** [comment]
This is a docs error - you just need to send your request to `/upload` with the `x-agent-did` header instead.
