### ISSUE TITLE
"Storing files" stage of my upload is taking a very long time

### ISSUE THREAD

**Issue by JORDANOVICH** [nftstorage/nft.storage#2162]
I am concerned that my upload is not completing. 

I am using the desktop client (mac) to upload files to nft.storage for use in minting NFTS.

The files are pretty large, in total the package is 5.04gb.

I am able to get the file uploader to reach complete, and then the modal shows that the the files are "storing". My concern is that this "storing" process is taking a long time, im not sure if its working, frozen, timed-out?

Please help.
https://www.loom.com/share/b053eb5125f747aa9b9369693894e953

**Comment by alanshaw** [comment]
@JORDANOVICH I'm not sure why, but it looks like NFTUp failed to clean up the blockstore after the upload completed and wasn't able to then inform you that the upload had completed.

We have a [new release of NFTUp](https://github.com/nftstorage/nftup/releases) you should download and install which guards against this. It looks likely that this upload succeeded but I recommend you re-upload again just in case. You should then receive a CID and if you paste it here I can check we received all the data.
