### ISSUE TITLE
File not recognized

### ISSUE THREAD

**Issue by msantamaria86** [nftstorage/nft.storage#2164]
What is the exact format I need to use so that nft.storage recognizes a file as such?
This file gets the `TypeError: property `image` must be a Blob or File object`

```
image: {
    fieldname: 'image',
    originalname: 'certifcado.png',
    encoding: '7bit',
    mimetype: 'image/png',
    destination: 'uploads/',
    filename: 'c904fae32dc289ef3d2157e7804a0663',
    path: 'uploads/c904fae32dc289ef3d2157e7804a0663',
    size: 127516
  }
```

How should it be formatted? I am using the **multer** middleware for an API running on expressjs and this is the way the file gets parsed.

**Comment by alanshaw** [comment]
Something like this?

```js
import fs from 'fs'
import { NFTStorage, File } from 'nft.storage'

const storage = new NFTStorage({ token: 'YOUR API TOKEN' })
const data = await fs.promises.readFile(multr.image.path)
const cid = await storage.storeDirectory([new File([data], multr.image.originalname)])
```

...and then you'd access on the gateway like: `https://nftstorage.link/ipfs/[CID]/certifcado.png`

More examples:

* https://github.com/nftstorage/nft.storage/blob/main/examples/client/node.js/storeDirectory.js
* https://github.com/nftstorage/nft.storage/blob/main/examples/client/node.js/storeBlob.js
