### ISSUE TITLE
Uploading gltf 3d fils

### ISSUE THREAD

**Issue by randoiable** [nftstorage/nft.storage#2166]
Am I just uploading wrong type of files because Im getting API key is malformed or failed to parse error?
I'm web3 fashion designer and want to upload 100 3d files (.gltf) to create nft collection from them. I have try to upload 1,7 gb collection of 100 3d files (.gltf) and get API key is malformed or failed to parse error. How to solve that problem?

**Comment by yusefnapora** [comment]
Hi, sorry you're having problems uploading. If you're using the upload button on the nft.storage website, you might try [nftup](https://nft.storage/docs/how-to/nftup/) instead. It's a desktop app that often works better for uploading large files.

**Comment by alanshaw** [comment]
> API key is malformed or failed to parse

Indicates that you're using a bad API key. Maybe it was copied incorrectly? You can try generating a new key on the website.

If you share the code you're using to upload then we can perhaps diagnose further. Alternatively, as @yusefnapora says, you can try NFTUp.

**Comment by elizabeth-griffiths** [comment]
If you still need support, please re-open this issue and provide more detail. Thanks!
