### ISSUE TITLE
Remove "week over week change" from /stats page metrics

### ISSUE THREAD

**Issue by JeffLowe** [nftstorage/nft.storage#2167]
- [x] remove the "Week over week change" % stats from both the "Upload count" and the "Data Stored" metrics:
<img width="231" alt="Screen Shot 2022-09-05 at 10 31 17 AM" src="https://user-images.githubusercontent.com/2078567/188482086-0ba858ba-02cb-4705-b9da-a7ce4bec42c8.png">

<img width="1197" alt="Screen Shot 2022-09-05 at 10 31 28 AM" src="https://user-images.githubusercontent.com/2078567/188482120-b0b50b30-cc35-45ae-95dd-663e66ec1bc7.png">

## After removing, the two metric cards should look like the followoing:
<img width="1225" alt="Screen Shot 2022-09-05 at 10 32 52 AM" src="https://user-images.githubusercontent.com/2078567/188482330-84ee9019-2453-4787-a4a6-fccc6df1c2c7.png">

**Comment by e-schneid** [comment]
Fixing this as part of #1597
