### ISSUE TITLE
Sponsorship

### ISSUE THREAD

**Issue by Siriogv** [nftstorage/nft.storage#2172]
We are an Italian startup that deals with carbon credits by registering them on blockchain through nft, we are using your service and we like the work you are doing, we would like to be able to include your service among the partnerships of our project in our presentation and website , and if there was any way we could help you on the Italian market let us know how we could support you.

If you need carbon credits to offset your activities and make the project more eco-friendly we would be happy to support you, or maybe we could offer it as a service for user-uploaded projects on your platform.

g.votta@dragonvalues.it

**Comment by dchoi27** [comment]
Thanks for the message. We have existing sustainability efforts, but will reach out if carbon credits become a priority.
