### ISSUE TITLE
CMS stats partial components dont drag/drop reorder

### ISSUE THREAD

**Issue by JeffLowe** [nftstorage/nft.storage#2174]
Stats partial images do not drag/drop to reorder.   Although it's easy enough to simply swap out the images in the sections to reorder, we should diagnose and resolve to ensure it's more intuitive for use. 
If there is any port of this solution we need to port over to web3, let's do that too.

**Comment by elizabeth-griffiths** [comment]
If you still need support, please re-open this issue and provide more detail. Thanks!
