### ISSUE TITLE
Move docs content into CMS

### ISSUE THREAD

**Issue by JeffLowe** [nftstorage/nft.storage#2178]
To streamline authoring certain docs content, we should move it into the CMS

**Comment by plwileverts** [comment]
@JeffLowe anything that needs to be done on our side to assign or approve this? (Just doing some issue triage of the New Issues column.)

**Comment by JeffLowe** [comment]
@plwileverts Only need a final confirmation to proceed.  We were waiting on this one until both blogs were launched, and the partial pattern was set.  With both, runway for doing this is clear, as long as it's still desired.
