### ISSUE TITLE
User with issue when logged in and refreshing /files page

### ISSUE THREAD

**Issue by dchoi27** [nftstorage/nft.storage#2179]
Report from user on Chrome (not sure which version, but for both MacOS and Windows):

I've hit this a few times over the last couple weeks. This happens just by pressing the refresh button on the browser whilst I'm on the Files page. I end up stuck with just a loading icon. Happens at the same time on macOS & Windows When I'm testing if our uploads have made it through to the site. 

Logging out and back in doesn't resolve the issue unfortunately. Anytime after I've hit this I just see the loading Icon whenever I log in. Typically takes about an hour before I can get back into the site. 

![image](https://user-images.githubusercontent.com/11778450/189237896-f091a163-c926-4f3d-b23f-082f940144ba.png)

**Comment by e-schneid** [comment]
I've been trying to reproduce this one but so far no luck.  Is this a common complaint @dchoi27 ?

**Comment by dchoi27** [comment]
no, but it's a user who's close to us . if you have any ideas on how to reproduce / more information, i can get them to chime in here!
