### ISSUE TITLE
Rate limits on nftstorage.link OPTIONS requests

### ISSUE THREAD

**Issue by zpalmtree** [nftstorage/nft.storage#2180]
Hi,
I have an app which is often hitting this domain in browser.

On occasion I hit rate limits, I am working on improving my software to handle this better, however, it seems the domain will also return a 429 on a browser OPTION preflight request.

![image](https://user-images.githubusercontent.com/22151537/189515949-902bd0e5-8922-46f3-b389-2422778ae32a.png)

Due to how CORS requests work, I can't get the error code programmatically in browser to determine that it was a 429 and stop sending requests to the server.
https://stackoverflow.com/a/47418538/8737306

Is it possible to only apply 429s on regular requests?

It would also be nice to have the rate limit apply over a shorter period, with shorter limits, to make it easier to implement a generic exponential backoff algorithm on hitting a rate limit, rather than needing a more custom solution explicitly for this domain, since 30 seconds is a bit of an unacceptable delay on loading speeds.

Thanks.

**Comment by vasco-santos** [comment]
Hey @zpalmtree 

Thanks for reaching out. I totally agree we should not have rate limiting for OPTIONS requests and that should not be blocking. Can you confirm?

> It would also be nice to have the rate limit apply over a shorter period, with shorter limits, to make it easier to implement a generic exponential backoff algorithm on hitting a rate limit, rather than needing a more custom solution explicitly for this domain, since 30 seconds is a bit of an unacceptable delay on loading speeds.

Could you open an issue for this please? Probably an example on how that would benefit users would be rad to try to prioritise this change

**Comment by zpalmtree** [comment]
Sorry for the slow response.

I do seem to still be seeing CORS related issues when getting rate limited.

![image](https://user-images.githubusercontent.com/22151537/192116642-c745f209-0514-488d-86f7-753d8c8a7693.png)
![image](https://user-images.githubusercontent.com/22151537/192116674-b407d76e-776b-43dd-9485-b0f951a7180e.png)

It appears to be Cloudflare enforcing the rate limits:  
![image](https://user-images.githubusercontent.com/22151537/192117572-74d2a5f8-9009-496c-aa0a-73ab188c20af.png)

Maybe it's not that OPTIONS requests are getting rate limited, but there is no Access-Control-Allow-Origin header present when a 429 is returned on a regular GET? 

It seems when that header is not present, `fetch()` in browser will reject the promise and return a generic error, with no way for me to detect it was a 429 causing it.

Indeed, looking at the headers of one of my 429 responses, it is missing `Access-Control-Allow-Origin`: 
![image](https://user-images.githubusercontent.com/22151537/192117651-7652bedf-44b8-4893-b35a-878dcd29e697.png)

Then requesting the file later when the rate limit has elapsed, the header is present:

![image](https://user-images.githubusercontent.com/22151537/192117723-baa56d69-5ef3-4dfc-a6e2-643a812a5294.png)

**Comment by vasco-santos** [comment]
Closing. Feel free to re-open if still an issue
