### ISSUE TITLE
New uploads not connecting to Storage Providers - stuck in "Queuing"

### ISSUE THREAD

**Issue by F1TVMEGA** [nftstorage/nft.storage#2181]
Hello,

I uploaded some files using NFTUp. And new uploads don't connect to Storage Providers anymore. It started 1 week ago and keeps going with every upload. What to do?

Thank you.

**Comment by ribasushi** [comment]
There was a slight hiccup on the end of the filecoin ingestor, queue is starting to drain as I am writing this. Everything should be caught up and back to normal in ~24~48h. All your uploads are completely safe in the meantime of course, it is a pipeline towards the end that got stuck.

**Comment by F1TVMEGA** [comment]
Hello. Why Storage Providers are STILL Queuing?

**Comment by carloscip** [comment]
> Hello. Why Storage Providers are STILL Queuing?

I am experiencing this as well

**Comment by F1TVMEGA** [comment]
> I am experiencing this as well

Since when you got this issue? For me it's almost 2 weeks ago.

**Comment by carloscip** [comment]
> > I am experiencing this as well
> 
> Since when you got this issue? For me it's almost 2 weeks ago.

Yeah kind of the same, I've uploaded last week, on the 8'th.

**Comment by ribasushi** [comment]
Things are still draining 😿 

Give me the last 6 characters of a random CID of yours - I can double check the upstreaming system has it and it is properly in he queue ‼️

**Comment by F1TVMEGA** [comment]
> Give me the last 6 characters of a random CID of yours - I can double check the upstreaming system has it and it is properly in he queue ‼️

Ok.

This one is uploaded at **2022-09-05 17:54** (first upload that got no storage provider yet):
4eywv4

This one is uploaded at **2022-09-16 17:46** (latest upload):
xbohfm

**Comment by ribasushi** [comment]
@F1TVMEGA things are flowing, nearly drained now ( another ~day left for everything )
```
 cid_suffix | actual_size |       entry_created        |        entry_analyzed         |       entry_aggregated        
------------+-------------+----------------------------+-------------------------------+-------------------------------
 xbohfm     | 3112 MB     | 2022-09-16 14:46:00.959+00 | 2022-09-16 23:28:57.336503+00 | 2022-09-17 04:49:04.36335+00
 4eywv4     | 3491 MB     | 2022-09-05 14:54:17.637+00 | 2022-09-13 19:06:28.801781+00 | 2022-09-19 22:39:02.533426+00
```

I will confirm with you when this process catches up

**Comment by ribasushi** [comment]
@F1TVMEGA @carloscip at the time of writing this all processes have caught up. Please spot-check that everything you expected to be in fil is now there, and close the ticket if the case.

Apologies for the trouble!

**Comment by alanshaw** [comment]
I'm going to close this as there's been no response for a while. Please re-open/shout if there's still any problem.

ps thank you for helping @ribasushi 😘
