### ISSUE TITLE
cid bafybeicucojv2ntkb2vhujc33x72jecjdny2fckwvlqjdvrmgx6zdsstgy Pin status FAILED but accessible 

### ISSUE THREAD

**Issue by 0xbiju** [nftstorage/nft.storage#2183]
`ipfs://bafybeicucojv2ntkb2vhujc33x72jecjdny2fckwvlqjdvrmgx6zdsstgy` has a pinned status of failed,  but I'm able to view various files inside through the explorer  from nft.storage. However, I am unable to access it from other ipfs viewers like the one provided by Brave Browser. The directly was uploaded via the script example provided by the docs. I've uploaded other files and directories via the same script and they have worked fine.

**Comment by alanshaw** [comment]
This now has a pinned status: https://api.nft.storage/check/bafybeicucojv2ntkb2vhujc33x72jecjdny2fckwvlqjdvrmgx6zdsstgy
