### ISSUE TITLE
Pin cron it's running on primary pg db

### ISSUE THREAD

**Issue by ericssontadashi** [nftstorage/nft.storage#2184]
Cron job it's running on primary db, should be running on replica:
https://github.com/nftstorage/nft.storage/blob/db63ad1035ef30c4f7e295676aa90cbbcfcb08f2/packages/cron/src/bin/pins.js#L13

![image](https://user-images.githubusercontent.com/2631225/190103579-0fe6e6ef-6890-4a2d-8f60-ff0a006c1844.png)

**Comment by alanshaw** [comment]
To clarify, it does not write access to the db but I believe read can be done on the replica.

**Comment by elizabeth-griffiths** [comment]
If you still need support, please re-open this issue and provide more detail. Thanks!
