### ISSUE TITLE
Uploading .car file "Error uploading: missing block"

### ISSUE THREAD

**Issue by joelwright-dev** [nftstorage/nft.storage#2186]
I created a new .car file using koalamint.com and when I try to upload it to nft.storage I just get the error:
Error uploading: missing block for bafybeidlgeq23qfucfoupxd5uea374zgk5luu6tfntirj3rwq3hzydd4tm

There are also quite a few errors in console which should probably be tidied up...

Using Firefox on Arch Linux

**Comment by vasco-santos** [comment]
Hey @joelwright-dev 
Do you know where we have information about CAR files created by koalamint? It looks like the provided CAR file is not valid.
