### ISSUE TITLE
Change pin status column and descriptions

### ISSUE THREAD

**Issue by dchoi27** [nftstorage/nft.storage#2195]
Once @olizilla updates the `status` field in the NFT.Storage Postgres database to use `linkdex` to check DAG completeness, let's change how we're showing the "Pin Status" column in the Web UI on the /files page.

## Requirements:
- [x] Change "Pin Status" column name to "Archived?"
- [x] Change the tooltip description for "Archived?" to say: `Indicates whether NFT.Storage received a complete graph of data (e.g., a full file). 📌 indicates that NFT.Storage has successfully received your file, and your data is safely archived. If you intentionally uploaded an incomplete graph, ignore this column.`
- [x] Have the value of the "Archived" column be:
   - If `status` in DB reports `pinned`, show 📌
   - Else, show whatever is in the database (with formatting like capitalization - probably can just leave that part of the code as-is)
- [ ] Modify https://nft.storage/docs/how-to/get-status/#pin-status to reflect the new state of things
   - ✅ done in #2200 
   - [ ] screenshot needs to be updated

## Current version (for reference)

![Screen Shot 2022-09-21 at 4 09 03 PM](https://user-images.githubusercontent.com/2078567/191611198-6cc4eea9-0d8d-4f00-b793-49f23cfa09e3.png)

**Comment by dchoi27** [comment]
hey @e-schneid - why wasn't https://github.com/nftstorage/nft.storage/pull/2200 reviewed/merged along with the rest of the PRs?

**Comment by JeffLowe** [comment]
Sorry.  We didnt see the connection between the PR and this ticket.  Getting this deployed soon
