### ISSUE TITLE
Unable to Login to my account, just randomly logs in after multiple attempts..!

### ISSUE THREAD

**Issue by ds-hamza** [nftstorage/nft.storage#2197]
According to best knowledge there is a problem with the response of this request (``https://api.magic.link/v1/auth/user/login/email/status``)...

**Response before verification is**
``
Status Code: 401, 
data: {}
error_code: "AUTH_PASSWORDLESS_LOGIN_NOT_VERIFIED"
message: "Passwordless login is not verified yet"
status: "failed"
``
**Response after verification is:**
``
Status Code: 200 
data: {
auth_user_id: "some_id"
auth_user_session_token: "some_id"
refresh_token: null _<== I guess the problem lies here..._
}
error_code: ""
message: ""
status: "ok"
``
Also in console 
this request (``https://auth.magic.link/v1/session/refresh``) fails with status_code --> 400

**Comment by alanshaw** [comment]
Did you manage to log in? Are you using your email to login or github? Did you click on the link you received in the email to login?

**Comment by ds-hamza** [comment]
> Did you manage to log in? Are you using your email to login or github? Did you click on the link you received in the email to login?

I am using my email to login.
Browser is chrome.
What happens is when I click on the button or link received via email the system doesn't redirect me to the dashboard instead I have to retry again and again.

After multiple attempts the system logs me in randomly after 4-5 tries.

I have no clue whatsoever what is stopping system from redirecting me to dashboard.

**Comment by BrionyYoung** [comment]
I ran into the same problem too, the email redirect me to the login page in Safari; when I copy the link in the email into Chrome, it showed that "magic link has expired".

**Comment by elizabeth-griffiths** [comment]
If you still need support, please re-open this issue and provide more detail. Thanks!
