### ISSUE TITLE
Automatic client side CAR chunking for large data

### ISSUE THREAD

**Issue by alanshaw** [nftstorage/nft.storage#220]
Currently we require users to upload CAR files when they want to upload big data.

Our client could automatically detect large files and create a chunked CAR automatically to make development easier.

**Comment by Moikapy** [comment]
Is there an ETA on this feature?

**Comment by Gozala** [comment]
> Is there an ETA on this feature?

Not at the moment as we have few higher priority things in flight. However if you do want to use this feature there is already [`storeCar`](https://ipfs-shipyard.github.io/nft.storage/client/classes/NFTStorage.html#storeCar) that could be used today.

@Moikapy If you would like to help with an effort, there is actually a code that just needs to be ported from web3.storage library that would be a pretty straight forward

https://github.com/web3-storage/web3.storage/blob/17a4c562459ddeb1ceac0348833dfa382547b1bf/packages/client/src/lib.js#L103-L120

**Comment by Moikapy** [comment]
@Gozala 
Which function needs to be ported?

**Comment by Gozala** [comment]
>  Which function needs to be ported?

Linked `put` function takes iterable of `File` like objects, encodes it as a `car` bundle and hands it off to `putCar` (which I think is roughly equivalent of `storeCare` in nft.storage.

I think what would be required is change `storeBlob`, `storeDirectory` do equivalent of `putCar`. Which is encode input as a `car` bundle and hand it off to `storeCar`. 

That said I have not looked if `storeCar` behaves exactly like `putCar` and if mentioned methods have input / output values that would align. Chances are they don't so some refactoring may become necessary.

**Comment by Gozala** [comment]
I was thinking about it last night and I think it would make a lot of sense if nft.storage client turned into a wrapper around the web3.storage client. I am not sure if all the pieces would align (e.g API endpoints), but if they do it might be a good idea.

**Comment by dchoi27** [comment]
Just to be clear here (please let me know if this is wrong), we'll need to implement chunking in the client for `store()` and `storeDirectory()`? But `storeCar()` already does the multipart uploading?

**Comment by alanshaw** [comment]
@dchoi correct
