### ISSUE TITLE
Problem uploading metadata

### ISSUE THREAD

**Issue by Boobuskers** [nftstorage/nft.storage#2207]
I successfully uploaded the assets (10,000 png images) of an NFT project to IPFS using NFT Storage on Saturday 24th September by downloading and using NFT UP.

I then copied the ipfs link that I was sent into a metadata tool and updated the metadata with this link.

I then tried to upload the updated metadata (10,000 files) using NFT UP and I got this below error:-

Error: reading files: ENOENT: no such file or directory, stat"

I have node js installed on my computer.

What am I doing wrong?

How do I upload the metadata to IPFS?

Could please assist me.

Thanks,

Paul Menear
![Error Message](https://user-images.githubusercontent.com/110915823/192371179-cc13fdb7-e3d5-4146-8a9f-e78d53d12027.jpg)

**Comment by alanshaw** [comment]
Hmm, looks like the files were moved or removed while they were being read. Can you try again?

**Comment by elizabeth-griffiths** [comment]
If you still need support, please re-open this issue and provide more detail. Thanks!
