### ISSUE TITLE
Use a .env.test or similar to capture the expected testing environment

### ISSUE THREAD

**Issue by olizilla** [nftstorage/nft.storage#2210]
`test-context.js` is loads in the .env from the root of the project to set up the test .env. That's surprising! 

Let's use the .env file just for local dev, and create a .env.test file for setting the test env.

**Comment by plwileverts** [comment]
To be assigned within the support initiative.

**Comment by elizabeth-griffiths** [comment]
If you still need support, please re-open this issue and provide more detail. Thanks!
