### ISSUE TITLE
 What to do if the applied apiKey expires？

### ISSUE THREAD

**Issue by f-hk** [nftstorage/nft.storage#2214]
i m developing a dapp and want to use nftstorage to storage some image for users. So i need to use api and apiKey. 

But today I found that apikey is expired
![img_v2_97479391-d00e-4466-8723-09714d84165g](https://user-images.githubusercontent.com/107092758/193445628-6c2b5baf-b0d9-4aa5-a9c1-b3d07cd5e998.jpg)
what to do can i refresh apiKey? Or some other solution?
Thank you for giving me an answer.

**Comment by alanshaw** [comment]
You need to login on the website and generate an API key. You cannot use the magic link tokens to interact with the API.
