### ISSUE TITLE
Update `engines.node` in api package.json to require node>=18

### ISSUE THREAD

**Issue by olizilla** [nftstorage/nft.storage#2217]
Since https://github.com/nftstorage/nft.storage/pull/2065 we require node>=18 for the api, but the package.json `engines.node` field requires node>=16 so folks aren't being nudged to use node 18, which then causes hard to debug test failures.

Updating this needs some tweaks to our CI test config as we hit:
[`error api@4.0.4: The engine "node" is incompatible with this module. Expected version ">= 18.0". Got "16.17.0"` ](https://github.com/nftstorage/nft.storage/actions/runs/3175917997/jobs/5174577335#step:4:28)

...with our other packages like the client which is still built on node 16... we can probably update the builder to use node18 everywhere, but it we do want to be able to test it on node 16 for as long as it is LTS...

**Comment by LinmyChi-you** [comment]
![image](https://github.com/nftstorage/nft.storage/assets/113030732/0f7a1bff-4bf8-4839-b28f-c8fb30277fa4)
I've been stuck here for a long time. I want to know what's the reason and how to solve it. I've tried it many times and it still looks like this.
