### ISSUE TITLE
Show cidv0

### ISSUE THREAD

**Issue by fudgebucket27** [nftstorage/nft.storage#2224]
Hi I would love to use your service but I was wondering if you would be able to allow export of cids to cid v0? The reason I ask this is because cidv0 is needed to mint nfts on the Loopring network.

**Comment by dchoi27** [comment]
Hey, CIDs are generally generated client-side, so you're welcome to use whatever CID type you want. The tooling that we work on has the option to use CIDv0s (outlined in the example here https://github.com/nftstorage/nft.storage/blob/041d43187c50c9a1a69693cf1d6a0ac1b000a936/examples/client/node.js/old-cidv0.js) but you can always just generate a CAR file with a CIDv0 and upload that (e.g., add data to a local kubo node using a CIDv0 and export the CAR).
