### ISSUE TITLE
My api keys and old upload are missing

### ISSUE THREAD

**Issue by WildBeanClub** [nftstorage/nft.storage#2228]
Previously i have logged in through gmail and now it isnt logging. Only logs in with github.
So all data and api keys not able to access , because it isnt logging in with gmail...pls solve this problem

**Comment by yusefnapora** [comment]
Do you get any kind of error message when trying to log in with gmail?

**Comment by vasco-santos** [comment]
@WildBeanClub closing this by lack of activity. Please feel free to re-open if you did not figure this out and still need support
