### ISSUE TITLE
NFT Unlockable content stored at nft.storage - security questions...

### ISSUE THREAD

**Issue by justanothersailor** [nftstorage/nft.storage#2229]
When going to store a media file on nft.storage as unlockable content for an NFT on Opensea, 1) Is it private in other words encrypted? and 2 How does the CID get transferred securely to future buyers so that it remains with the NFT and not with the old buyers?
Thank you

**Comment by xavier238** [comment]
Ask opensea support for assistance it should be that diffiult to do.  [CLICK HERE](https://opns.support/)

**Comment by justanothersailor** [comment]
Thank you
