### ISSUE TITLE
multiple account

### ISSUE THREAD

**Issue by chav13** [nftstorage/nft.storage#2242]
Hi,
I was trying to create a second account, after clicking on the email I got a popup saying "Magic link expired" and the login screen error:
Magic RPC Error: [-10005] User requests to edit the email address for authentication.
Is there a way to setup a second account?

Thanks,
Chav

**Comment by vasco-santos** [comment]
Hey @chav13 
You should be able to setup a second account with a different e-mail. Can you let me know what flow you are attempting?

**Comment by chav13** [comment]
Hi,

Thank you for following up and answering. I have a followup question, is there a way to generate the CID locally and use your get method to verify if a file already exist before doing an upload?
Or is there a better method to check if file already exist on IPFS?

Thanks,
Chav

**Comment by vasco-santos** [comment]
Hey @chav13 
 > is there a way to generate the CID locally and use your get method to verify if a file already exist before doing an upload?

yes, you can either use https://www.npmjs.com/package/ipfs-only-hash (be aware that in options you should provide `cidVersion` 1.

Or you can also use a IPFS daemon for this. Example:

```sh
ipfs add --only-hash --cid-version 1 package.json
```

Regarding second part, you can use our check endpoint for this https://nft.storage/api-docs/

It only checks content stored with nft.storage

**Comment by chav13** [comment]
Thank you!

**Comment by vasco-santos** [comment]
Closing the issue @chav13 

Happy to help you, always feel free to re-open or create a new issue if you have further questions
