### ISSUE TITLE
Files still not synced yet after 40 hours!

### ISSUE THREAD

**Issue by Salmuun** [nftstorage/nft.storage#2243]
To whom it may concern,

I have uploaded metadata and images of my collection to NFT Storage on 21st Oct. Its been well over 40 hours but the files aren't indexed yet according to onemint.io (the site I use for building NFT Smart Contracts). 

I have been using NFT Storage for months and never faced this prolonged indexing issue. I have attached the screenshots below.
I hope you understand the problem and fix it as soon as possible.

NFT Storage:
![image](https://user-images.githubusercontent.com/54441153/197394339-0ebbc1d8-3a27-42fd-8cc1-da1d759562fd.png)

Onemint.io:
![image](https://user-images.githubusercontent.com/54441153/197394372-6b71cc93-f8a5-435e-adc6-73e7c512c78e.png)

**Comment by alanshaw** [comment]
Can you copy and paste the CIDs in question?

**Comment by Salmuun** [comment]
> Can you copy and paste the CIDs in question?

Thanks for your swift reply.
The CIDs in question are as follows:
Images: bafybeidzevcoravedoktma6qag5zsgzbayfvu34yjodrug3onblnwxsifi
Metadata Json files: bafybeih5hjniqwdwntx44c27bovzqfv3qy3tqgw75dmftsl6jo34jv55ai

**Comment by alanshaw** [comment]
I'm seeing that this is "pinned" via the API: https://api.nft.storage/check/bafybeih5hjniqwdwntx44c27bovzqfv3qy3tqgw75dmftsl6jo34jv55ai

Please shout if something else is up!
