### ISSUE TITLE
Implement  Plausible.io analytics for nft.storage and nft school sites

### ISSUE THREAD

**Issue by JeffLowe** [nftstorage/nft.storage#2251]
BLOCKED until we have access to account (account should be the Protocol Labs account to keep nft.storage in outercore)

We need to implement basic tracking via an analytics system for nft.storage and nft school sites.  Plausible and Simple analytics being considered

- [ ] Vet Plausible (local deploy, etc) particularly the ux of the dashboard interface, does it have enough to achieve reporting needed (see https://github.com/web3-storage/web3.storage/issues/2030 as example of reporting needed)
- [ ] let David know what account access we need in system to implement
- [ ] implement on nft.storage website properties (nft.storage, blog.nft.storage, docs )
- [ ] implement on nftschool https://github.com/protocol/nft-website

**Comment by JeffLowe** [comment]
Complete on nft site and blog (just awaiting review and deploy of https://github.com/nftstorage/nft.storage/pull/2232
Awaiting review and deploy of https://github.com/nftstorage/nft.storage-content/pull/16 to get plausible onto nft school site.

**Comment by dchoi27** [comment]
thanks! i think https://github.com/protocol/nft-website/pull/284 this might be the PR for NFTSchool
