### ISSUE TITLE
Pinning After uploading on NFT.Storage

### ISSUE THREAD

**Issue by hamzamughal74** [nftstorage/nft.storage#2252]
I'm uploading NFT's Data using client.store() and client.storeDirectory() 
it's setting Complete Graph Status 📌 in Archived column but not showing Pinned status
so please let me know if this data is permanent on Nodes or i still have to pin it myself?

**Comment by alanshaw** [comment]
If we have a complete graph then yes it is stored according to the duration specified in the terms of service https://nft.storage/terms/
