### ISSUE TITLE
Error storing files: User not found when uploading.  (About half way throught the upload)

### ISSUE THREAD

**Issue by ditkaNFT** [nftstorage/nft.storage#2256]
I don't know why this started happening, but all of a sudden I cannot complete my uploads.  This is an account I have used for several months, same API key, same PC, same everything.

![image](https://user-images.githubusercontent.com/111548881/201762613-283f9467-161a-419e-b3ca-042cd36e020e.png)

But now when I upload I get this message.

I am trying a workaround by re-installing NFTUp, trying a completely new account created with a new email address. 

The same account also had problems logging in on a different PC

**Comment by vasco-santos** [comment]
Hey @ditkaNFT 

Did creating new account/auth token help with this?

**Comment by vasco-santos** [comment]
Closing this as issue seems solved. Fell free to reach out in case you need further support :)
