### ISSUE TITLE
The If-None-Match header causes the server to respond with a 502 error

### ISSUE THREAD

**Issue by fend25** [nftstorage/nft.storage#2257]
Hi!

Quick example:

```bash
curl 'https://bafybeielstfwd5dlrocolh4z3rvikoxetanbtxeamennlqmeq6fhif2m2q.ipfs.nftstorage.link/12.jpeg' -I
```
The result will be 200 OK:
```
HTTP/1.1 200 OK
...
ETag: "bafybeia2uczj5fdg6drrmxszof4f4pcwc7wyr4rwc25aewu7nruopl54ga"
...
```

Let's take this ETag and add to the next request:

```bash
curl 'https://bafybeielstfwd5dlrocolh4z3rvikoxetanbtxeamennlqmeq6fhif2m2q.ipfs.nftstorage.link/12.jpeg' -I \
  -H 'If-None-Match: "bafybeia2uczj5fdg6drrmxszof4f4pcwc7wyr4rwc25aewu7nruopl54ga"' 
```

And the result will be 502:

```
HTTP/1.1 502 Bad Gateway
```

Actually I faced with "zebra-striped" behaviour in a browser (modern Chrome): 
200 - refresh - 502 - refresh - 200 - refresh - 502 - ...

So, most probably there is some problem with the If-None-Match header

**Comment by vasco-santos** [comment]
Thanks for the report. This is being handled in https://github.com/web3-storage/reads/pull/120

**Comment by vasco-santos** [comment]
Hey @fend25 

Great news. We shipped last week new release of gateway that should have addressed this. Closing this issue, please have a look once you get some time and let us know if there is anything still not working for you :)

**Comment by fend25** [comment]
Hi @vasco-santos !

I can confirm that I cannot reproduce this problem anymore. Zebra-style browser behavioir is also gone.

Thank you.
