### ISSUE TITLE
NFT Storage client.store failing from server 

### ISSUE THREAD

**Issue by KayAlbertus** [nftstorage/nft.storage#2262]
await client.store

works fine on localhost but once application is deployed and running on server one receives the following error :

 TypeError: Cannot read properties of undefined (reading 'digest')
    at i.encode (63-54d8bd43e497b53e.js:1:137322)
    at i.digest (63-54d8bd43e497b53e.js:1:137004)
    at pr (63-54d8bd43e497b53e.js:1:193995)
    at 63-54d8bd43e497b53e.js:1:196437
    at 63-54d8bd43e497b53e.js:1:66797
    at Array.map (<anonymous>)
    at t.exports (63-54d8bd43e497b53e.js:1:66789)
    at async 63-54d8bd43e497b53e.js:1:196781
    at async t.exports (63-54d8bd43e497b53e.js:1:66170)
    at async br (63-54d8bd43e497b53e.js:1:194406)

Please could you assist team why would this be happening ?

**Comment by KayAlbertus** [comment]
Hello Team Any Feedback on the above ?

**Comment by vasco-santos** [comment]
Hi @KayAlbertus 

Can you provide any more information? A code snippet (or an example repository), as well as how your bundling is being done would be appreciated to give some help

**Comment by Hilicot** [comment]
I had the same problem, this was the solution: https://stackoverflow.com/questions/57146558/typeerror-digest-of-undefined-in-development-environment

**Comment by xuht724** [comment]
> I had the same problem, this was the solution: https://stackoverflow.com/questions/57146558/typeerror-digest-of-undefined-in-development-environment

I think it just explain the problem. But how can I set my dev server as a secure origin?

**Comment by elizabeth-griffiths** [comment]
Closing as this ticket . If you still need support, please re-open this issue and provide more detail. Thanks!
