### ISSUE TITLE
Magic link expired when trying to sign up

### ISSUE THREAD

**Issue by zoan37** [nftstorage/nft.storage#2264]
<img width="470" alt="Screen Shot 2022-11-19 at 7 02 15 PM" src="https://user-images.githubusercontent.com/104385984/202876362-3f720f0b-3496-4053-ac7a-8e0940c39535.png">

I'm getting magic link expired when trying to sign up with my email, even though it's supposed to expire after 20 minutes.

**Comment by lak1024** [comment]
I met the same problem with you. Finally it worked whe i closed VPN

**Comment by lak1024** [comment]
The Magic will send email to calculation expired time by your online position, if use vpn it only get your virtual position that vpn gave.I tryed so many time that find this solution 🤧

**Comment by zoan37** [comment]
@lak1024 Good you found a workaround; it is still not working for me; I tried on Brave and Chrome browser, and I'm not using a VPN.

**Comment by vasco-santos** [comment]
Hey @zoan37 

Did you end up figuring out this one? Could have been a temporary failure from magic link service. Let us know if you still need help

**Comment by zoan37** [comment]
Hi @vasco-santos, I tried again and still face the same issue. (I ended up using web3.storage to store my NFT images--the Magic Link in web3.storage works.)

**Comment by heyjay44** [comment]
Closing this issue. Trying different browsers will sometimes solve this, which we know is not ideal. We are moving away from Magic Link.
