### ISSUE TITLE
My files are still queued on NFT storage even though its been over 48 hours.  

### ISSUE THREAD

**Issue by pauluk333** [nftstorage/nft.storage#2268]
My files are still queued even though its been over 48 hours, how can I get the files fully uploaded so I can send a link to have the pictures downloaded by the dev.

My email is pauluk3@googlemail.com

<html>
<body>

25/11/2022, 15:13 | bafybeig...hdjvwyva | 📌 | Queuing | 20.71KB | Actions
-- | -- | -- | -- | -- | --
25/11/2022, 15:12 | bafybeie...xes4nda4 | 📌 | Queuing | 22.05KB | Actions
25/11/2022, 15:12 | bafybeib...bot3wq3m | 📌 | Queuing | 23.41KB | Actions
25/11/2022, 15:11 | bafybeih...n5vpdyrm | 📌 | Queuing | 22.45KB | Actions
25/11/2022, 15:11 | bafybeia...ymi77dgq | 📌 | Queuing | 21.07KB | Actions
25/11/2022, 15:10 | bafybeia...sqgo7lh4 | 📌 | Queuing | 22.69KB | Actions
25/11/2022, 15:10 | bafybeic...i7gwb3ru | 📌 | Queuing | 21.26KB | Actions
25/11/2022, 15:09 | bafybeib...yo3i73py | 📌 | Queuing | 19.07KB

</body>
</html>

thanks 25/11/2022, 15:13	[bafybeig...hdjvwyva](https://nftstorage.link/ipfs/bafybeig6aytgfeeoy7xa7n2gocrxix7pxwebemin7dw7u2wpylhdjvwyva)	📌	
Queuing
20.71KB	Actions
25/11/2022, 15:12	[bafybeie...xes4nda4](https://nftstorage.link/ipfs/bafybeieenjxngar636s3xkiyju5vkp43t5pbgrlr43gjzuwzsaxes4nda4)	📌	
Queuing
22.05KB	Actions
25/11/2022, 15:12	[bafybeib...bot3wq3m](https://nftstorage.link/ipfs/bafybeibeeykx34qkvbtqixobbnekfhhnnz6h7pjfnrc2xrl6ulbot3wq3m)	📌	
Queuing
23.41KB	Actions
25/11/2022, 15:11	[bafybeih...n5vpdyrm](https://nftstorage.link/ipfs/bafybeih6zo6mmwbcm7knqsj5exenufsnvlvajkv6cklupedfrln5vpdyrm)	📌	
Queuing
22.45KB	Actions
25/11/2022, 15:11	[bafybeia...ymi77dgq](https://nftstorage.link/ipfs/bafybeiatfnlo6ccdflv5sbfrjarwhik35whkc4tfqxw4r7mnbiymi77dgq)	📌	
Queuing
21.07KB	Actions
25/11/2022, 15:10	[bafybeia...sqgo7lh4](https://nftstorage.link/ipfs/bafybeiaqf23zsgqbezqnq5ch6uke5ruef37tuisd7kjfmkeb6osqgo7lh4)	📌	
Queuing
22.69KB	Actions
25/11/2022, 15:10	[bafybeic...i7gwb3ru](https://nftstorage.link/ipfs/bafybeicpqrm3iqy3pqpg25a5duog3f6gtaadw4vvp52ff4gi6di7gwb3ru)	📌	
Queuing
21.26KB	Actions
25/11/2022, 15:09	[bafybeib...yo3i73py](https://nftstorage.link/ipfs/bafybeibo7t566ywjjs6b3pqfgzx3rvmvzsdg3ooph7f42jivriyo3i73py)	📌	
Queuing
19.07KB

**Comment by vasco-santos** [comment]
Hi @pauluk333 

It looks now they are already pinned https://api.nft.storage/check/bafybeig6aytgfeeoy7xa7n2gocrxix7pxwebemin7dw7u2wpylhdjvwyva and queued for Deal in Filecoin. Did you mean queued for Pinning or Filecoin?

**Comment by vasco-santos** [comment]
Closing this. We currently have an incident open on delays for Filecoin deals. You can keep track in https://status.nft.storage/

If there are any further issues, please re-open this and let us know :)
