### ISSUE TITLE
random nfts metadata files are error 404

### ISSUE THREAD

**Issue by Yogi3D** [nftstorage/nft.storage#2269]
Hello,

bafybeia4twvsqqicanwvhmit2suyizdsdhnzrasloagfkgygl3xx4e67gi

some files eg. NO. 37 the metadata is error 404 and so the nft and traits do not populate to view or read. I am very curious what would be going on here. I have gone over the metadata and con not find errors, but a random few when trying to view through ipfs always get error 404 and as stated they do not populate on open sea or in wallets etc.

 thank you

**Comment by vasco-santos** [comment]
Hey @Yogi3D 
I was just able to get 37 https://bafybeia4twvsqqicanwvhmit2suyizdsdhnzrasloagfkgygl3xx4e67gi.ipfs.nftstorage.link/37.json . Can you let us know what IPFS Gateway or client were you using?
Thanks,
Vasco
