### ISSUE TITLE
Bulk uploading 

### ISSUE THREAD

**Issue by Bippetybop** [nftstorage/nft.storage#2270]
Hi guys, thank you for this great service. 
I don't have broadband so use my phone as WiFi. 
I tried uploading 10000 images yesterday but it failed from a time out error. 
Can I upload my files in smaller batches to stop timeouts on my connection ?

**Comment by vasco-santos** [comment]
Hi @Bippetybop 

Yes, creating uploads with smaller batches will certainly help.

Apologies for having issues with current upload. We are working on the new upload API that will help significantly with these use cases.
