### ISSUE TITLE
whitelist api.nft.storage in the CSP

### ISSUE THREAD

**Issue by austinchau** [nftstorage/nft.storage#2275]
Currently due to CSP, any asset pinned by nft.storage cannot make direct API call to nft.storage public API.  If your dapp is hosted on nft.storage and tried to make an API request, it would get this error

**Refused to connect to 'https://api.nft.storage/upload/' because it violates the following Content Security Policy directive: "connect-src 'self' **

I understand the intent of CSP to prevent phishing and other nefarious things but whitelisting the api.nft.storage domain seems reasonable.  Thank you.

**Comment by vasco-santos** [comment]
Hey @austinchau 
We are going back with this decision and remove exception for API https://github.com/nftstorage/nftstorage.link/pull/212
This is because our API could end up being used to store user data by malicious parties
