### ISSUE TITLE
Upload problem

### ISSUE THREAD

**Issue by hellobou** [nftstorage/nft.storage#2276]
Hello
I want to upload a .car file to the site. I ran into a problem on the nft.storage site while doing the steps. When I want to upload the .car file on the site, I get the following error and the upload is not done.

Error uploading: missing block for bafybeidh4pskxeloocooqozqhr6v53o4sb2vpwqx7xbpf7r2xbsjt5h7oe

Also, when I want to upload my files through the NFT Up software, the upload does not progress and remains at 0.01B. My internet connection has no problem.

**Comment by dchoi27** [comment]
it sounds like the CAR file is incomplete (i.e. "missing block")
