### ISSUE TITLE
Error while uploading files

### ISSUE THREAD

**Issue by Mars4Metaverse** [nftstorage/nft.storage#2277]
Hello, I am trying to upload the files and I get an error message. 
It says: Error uploading: missing block for bafybeicsnxnoaki5d3f7v6ngqlwy2z5qvg3zcu6nqbdidvapo4bhm55e74
Here's the screenshot: https://i.gyazo.com/ce76b1c133f4594967744505ae65ca68.png

Please help me solve this issue.

**Comment by dchoi27** [comment]
sorry, without being able to replicate, it's impossible to know what could be going on. you're welcome to share the upload, otherwise closing the issue.
