### ISSUE TITLE
Worker errors on expired UCANS

### ISSUE THREAD

**Issue by Gozala** [nftstorage/nft.storage#2278]
As per incident report https://sentry.io/organizations/protocol-labs-it/issues/3467899469/?project=5747297

This line here throws when UCAN has expired

https://github.com/nftstorage/nft.storage/blob/78cdc5a845963cc0a32d64e93b2ee77acbe2c915/packages/api/src/utils/auth.js#L47

We should probably catch the error and return 401 instead with a message saying that token has expired instead of crashing

**Comment by Gozala** [comment]
@hugomrdias your probably most familiar with this code, mind taking it on. I'm not sure if there are other kinds of errors that could occur that we should handle differntly

**Comment by elizabeth-griffiths** [comment]
We’re closing this ticket for now, please re-open if it’s still an issue.
