### ISSUE TITLE
Pinned file not available through IPFS p2p

### ISSUE THREAD

**Issue by Thegaram** [nftstorage/nft.storage#2279]
I pinned a file on nft.storage: bafybeidfxmcyzmj6iak7fqbu7wonqvkqtqdi5imqrd5545dr2lciougegi

I can retrieve it through https://bafybeidfxmcyzmj6iak7fqbu7wonqvkqtqdi5imqrd5545dr2lciougegi.ipfs.nftstorage.link and the UI shows it's already archived:

<img width="1197" alt="image" src="https://user-images.githubusercontent.com/7571518/207559908-2a8b3ccb-ed0f-4541-9d9b-1c3ef8526806.png">

However, I fail to retrieve and pin it on my own IPFS node:

```
$ ipfs pin add --recursive=true --progress bafybeidfxmcyzmj6iak7fqbu7wonqvkqtqdi5imqrd5545dr2lciougegi
Fetched/Processed 0 nodes
```

(Note: I manually added a number of peers from this list: https://github.com/nftstorage/nft.storage/blob/main/PEERS).

**Comment by elizabeth-griffiths** [comment]
We’re closing this ticket for now, please re-open if it’s still an issue.
