### ISSUE TITLE
uploading metadata with problems

### ISSUE THREAD

**Issue by lorenzotamietti** [nftstorage/nft.storage#2288]
hi, i wrote small scripts that, using provided api, pin an image on NFT storage, 
i put this image in a FILE object as i've seen and it is correct if i try to print file object.
However, after this file is pinned on my dashboard i see every time an object empty with 0 bytes. i don't understand why

fs.promises.readFile(imagePath).then(async (res)=>{
         
            const type = mime.getType(imagePath)
            let _image= new File([res],_name, { type })
            console.log(_image)
            const response = await client.store({

                "image": _image,
                "name": _name,
                "description": `An adorable ${_name}`
            })

            console.log(response)
           
        })

**Comment by alanshaw** [comment]
Can you paste the CID you receive and we can take a look. You might just need to add `/image` to the end of your URL...
