### ISSUE TITLE
NFT.Storage docs pages need relevant h1 pagetitles and metatags

### ISSUE THREAD

**Issue by JeffLowe** [nftstorage/nft.storage#2304]
All nft.storage doc pages have the same page titles.  This results in sub-optimal seo.  Also, all og tags are the same across all pages, resulting in the same content in social share previews (undesirable). 

- [x] ensure page title uses the H1 from the page content if at all possible.  
- [ ] ensure the og tags for each page are at least updated for url and title (description if possible)

## Example image showing OG tags and title which is the same on every docs page. 
![Screenshot 2023-02-01 at 2 25 46 PM](https://user-images.githubusercontent.com/2078567/216155652-59974ca0-56ed-44aa-bd10-302786520f52.png)

**Comment by e-schneid** [comment]
I have a [PR](https://github.com/nftstorage/nft.storage/pull/2319) up for the title tag, but for Nextra to properly update the og tags it seems way may need to upgrade Nextra.  Upgrading Nextra appears to also require upgrading Nextjs (and thus React as well).
