### ISSUE TITLE
Cant upload my folders with the nft up app

### ISSUE THREAD

**Issue by itsaihdz** [nftstorage/nft.storage#2305]
Im trying to upload two folders as the instructions on the faq section and it says _Error: storing files: Can't parse: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9: Can't parse as base64url._

At the beginning I thought it was due to my metadata not having .json extension but had to edit all my 1234 files and is still the same, it just dont let me upload my folders, thanks

**Comment by dchoi27** [comment]
hey, please provide more details so we can help. screenshots, where you're receiving the errors, the instructions you're referring to, etc. otherwise closing for now
