### ISSUE TITLE
[Docs] Missing link to `concepts-content-addressing`

### ISSUE THREAD

**Issue by iamashwin99** [nftstorage/nft.storage#2307]
In https://nft.storage/docs/concepts/car-files/#what-is-a-content-archive or https://github.com/nftstorage/nft.storage/blob/main/packages/website/pages/docs/concepts/car-files.md
theres a broken link to `concepts-content-addressing` but the file doesn't exist.

**Comment by elizabeth-griffiths** [comment]
We’re closing this ticket for now, please re-open if it’s still an issue.
