### ISSUE TITLE
improving metadata to display page-specific descriptions & information

### ISSUE THREAD

**Issue by heyjay44** [nftstorage/nft.storage#2308]
## Problem Statement
When sharing nft.storage's subdirectory links, the card doesn't display page-specific metadata. An example of this can be found with: https://nft.storage/docs/.

## Success Criteria
Each page’s title and description to be displayed on the share card on social media and search engines.

Duplicate ticket here: https://github.com/nftstorage/nft.storage/issues/2304

**Comment by elizabeth-griffiths** [comment]
We’re closing this ticket for now, please re-open if it’s still an issue.
