### ISSUE TITLE
1GB IPFS Storage not working

### ISSUE THREAD

**Issue by systementcorp** [nftstorage/nft.storage#2323]
Hello I tried to store a collection of NFTs over 1GB and IPFS still has not backed them up. https://opensea.io/collection/arcade-playing-cards Can you please help resolve these to IPFS?

**Comment by dchoi27** [comment]
we can't necessarily control how 3rd party apps fetch data from nft.storage. we were having some bitswap availability issues last week, so hopefully your issue is resolved. however, this is likely either user error, or something you'll need to resolve with opensea.

**Comment by systementcorp** [comment]
I have a 20,000 collection of nfts that will not back up to IPFS but my
dmaller collections do. Do you know when u will back up my large
collections to IPFS? My small ones are working without
