### ISSUE TITLE
Issue with image

### ISSUE THREAD

**Issue by ClaudiuOCF** [nftstorage/nft.storage#2324]
Hello,
I'm Claudiu.
I have uploaded my NFT collection 10 days ago on nft.storage (1000 images .png)
Everything was fine till today, Two people minted two NFTs from my collection and the image of the NFT is not loading. I spoke with the admin from the marketplace i use (xoxno.com on multiversx blockchain) and he told me it's not a market issue but a ipfs issue and he adviced me to contact the upload site team.
The mint went smooth untill it reached 458 minted.
Now there are 460 minted but the image is not loading for the last two.
Name of the collection is: CypherApes and you can find it on xoxno.com.
claudiuvadvanu@gmail.com is my mail in case you need more details.
CID of the collection: bafybeihzfasqabnlqqaaq4j2scowq5vys25w4np4dkwu5kjxyy5u45bxya

**Comment by dchoi27** [comment]
i can fetch your content fine here https://bafybeihzfasqabnlqqaaq4j2scowq5vys25w4np4dkwu5kjxyy5u45bxya.ipfs.nftstorage.link/

we can't necessarily control how 3rd party apps fetch data from nft.storage. we were having some bitswap availability issues last week, so hopefully your issue is resolved.
