### ISSUE TITLE
My nft file is not loading

### ISSUE THREAD

**Issue by blockfy20** [nftstorage/nft.storage#2329]
Hi There,

I used NFT storage to store my NFT file and my NFT files type is GLB. My all NFT was loading correctly and display in Solscan well. But few days ago I noticed it's not loading and when I search glb file link, it will receive "Gateway Time-out". Please assist to solve this probelm.

Thank you

**Comment by rocpoc** [comment]
+1

**Comment by dchoi27** [comment]
we can't necessarily control how 3rd party apps fetch data from nft.storage. we were having some bitswap availability issues last week, so hopefully your issue is resolved. but without any specific details, it's tough to help.
