### ISSUE TITLE
Hello i have uploaded this two IPfs contents. One are images and Metadata json

### ISSUE THREAD

**Issue by arsenelupincrypto** [nftstorage/nft.storage#2330]
My metadata are nos visible yet, after 24 hours.  IO can see al right on own NFT STORAGE LINKS, but not on ipfs general.
So i can no see My nfts on OPensea. Only i see number , but all black.
My email JESUSVIPZE@GMAIL.COM

ipfs://bafybeiaadgp5rf3oqe2xcbzm36g4lnopyubia5prgb3n5eej3243krtg7m

**Comment by rocpoc** [comment]
+1

**Comment by arsenelupincrypto** [comment]
you have same issue? :(

**Comment by Klim1987** [comment]
Hey buddy, can you please tell me why in my "Archived" "Storage Providers" there is no change
![2023-03-02_00-25-08](https://user-images.githubusercontent.com/87778844/222257564-4d24b00d-aa1b-419f-ae78-a5a49828838d.png)

**Comment by dchoi27** [comment]
i can fetch your content fine here https://bafybeiaadgp5rf3oqe2xcbzm36g4lnopyubia5prgb3n5eej3243krtg7m.ipfs.nftstorage.link/

we can't necessarily control how 3rd party apps fetch data from nft.storage. we were having some bitswap availability issues last week, so hopefully your issue is resolved.

**Comment by arsenelupincrypto** [comment]
yes it is solved. Thanks very much !

**Comment by arsenelupincrypto** [comment]
yes, it is solved. Thanks very much!
