### ISSUE TITLE
The visuals of the NFTs we created using CID in the OpenSEA tests are not visible

### ISSUE THREAD

**Issue by Ciwone21** [nftstorage/nft.storage#2332]
In the OpenSEA tests, the visuals of the NFTs are not visible. He sees visuals when he uses a different service like Pinata, but in your service, the OpenSEA test server does not appear.

**Comment by alanshaw** [comment]
Do you have an example? Are you receiving an error message?

**Comment by dchoi27** [comment]
we can't necessarily control how 3rd party apps fetch data from nft.storage. we were having some bitswap availability issues last week, so hopefully your issue is resolved. if not, please provide more specific details so we can help.
