### ISSUE TITLE
Delay Issue in Pinning Images for My NFT Collection

### ISSUE THREAD

**Issue by metawearse** [nftstorage/nft.storage#2336]
Hello everyone,

I wanted to report an issue I'm experiencing with pinning images for my 15GB NFT collection on nft.storage. I have noticed an extreme delay in pinning images of my collection.

I have verified that all images have been properly pinned and my internet connection is stable and fast. However, the delay is so high that I am having difficulty displaying my NFT collection to other users.

I verified my images are already visible via the url provided, but the archived column shows Pinning instead of the pin icon.
while in the Storage Providers column both the images and the metadata are Queuing.

I just want to understand if it's just a delay problem or if I made some mistake while loading.

thank you so much everyone, metawearse.
![Immagine 2023-03-01 215311](https://user-images.githubusercontent.com/126721877/222262882-1ab835d6-7683-4b80-b6f6-4b73b9f14928.jpg)

**Comment by alanshaw** [comment]
Wow 14.35GB! Please could you share the CID and we can look into why it's still pinning.

Obviously we cannot get your data into a Filecoin deal until we have it all so that's why Storage Providers are saying queuing. That and https://status.nft.storage/incidents/qnb9q666cn4f.

**Comment by metawearse** [comment]
> Wow 14.35GB! Please could you share the CID and we can look into why it's still pinning.
> 
> Obviously we cannot get your data into a Filecoin deal until we have it all so that's why Storage Providers are saying queuing. That and https://status.nft.storage/incidents/qnb9q666cn4f.

Ok, the cid is: bafybeic5rx3jwga3m7wpfipk76khhxdodxhzdxobjhhqrycxauyidty3om

**Comment by dchoi27** [comment]
- to check if your upload was successful, we have a job that traverses the IPFS graph of the upload to check if all the blocks of data are there. for large uploads, sometimes this job times out, and the status will just say Pinning
- of course, if your upload gives an error or doesn't complete, it probably wasn't successful. so that's the most reliable way
- otherwise, you can spot check individual images / metadata in your uploaded directory from the NFT.Storage gateway to see if the upload was successful. if some of the URLs don't load, it probably wasn't successful.

**Comment by metawearse** [comment]
> * to check if your upload was successful, we have a job that traverses the IPFS graph of the upload to check if all the blocks of data are there. for large uploads, sometimes this job times out, and the status will just say Pinning
> * of course, if your upload gives an error or doesn't complete, it probably wasn't successful. so that's the most reliable way
> * otherwise, you can spot check individual images / metadata in your uploaded directory from the NFT.Storage gateway to see if the upload was successful. if some of the URLs don't load, it probably wasn't successful.

>

ok, thanks but it's a collection of 8888 images, I can't check all of them manually, there were no errors while uploading.
I'm not good at programming but I would like to know if there are any solutions/codes to use in vscode, to check everything automatically
