### ISSUE TITLE
NFTs are not loading 

### ISSUE THREAD

**Issue by Samreen-Kazi** [nftstorage/nft.storage#2337]
I have created an NFT Marketplace and I am using nft.storage to store the nft and the metadata. Everthing was perfectly running up untill yesterday for some reason the nfts are not loading, they are getting minted but are not showing up. On my nft.storage dashboard 4 of them are stuck on queueing... some of them were minted in january and were showing up perfectly but somehow now there seems to be an issue. Can someone please guide as to what might be going wrong all of a sudden. 

<img width="522" alt="image" src="https://user-images.githubusercontent.com/86507773/222943457-9ac5f03e-ccf6-4a0f-ab99-7a12bbc9c870.png">

**Comment by alanshaw** [comment]
We're still experiencing issues getting uploads into Filecoin deals, your new uploads will appear like this until that is resolved. The data will remain accessible on IPFS and via IPFS gateways though.

**Comment by dchoi27** [comment]
however, there shouldn't be any changes with the ability for you to read the data out of IPFS. if you provide the CIDs we can take a deeper look.

**Comment by Samreen-Kazi** [comment]
Sure, 
bafyreidwm2xwoa5bt632vzt54csphcoi3bjvj7vwknipnljbd7gtx3bioy
bafyreia4mjk4crmp5eqtqzixc7ultt6o7briyvw5wzrel5nei7wenpxely
bafyreid3w344ztpluhflfniqhllzyedxdzujvkaqiidx3dl5a4upx3rgcm
bafyreiaffkyfyboapl4e3bvgrtugvb443hl4oa74657rjugbonsxj4jpty

**Comment by dchoi27** [comment]
is it possible you might be mistaken that you were able to load these CIDs before? all these CIDs do not appear to have been successfully uploaded (data sizes are all null, e.g. https://api.nft.storage/check/bafyreidwm2xwoa5bt632vzt54csphcoi3bjvj7vwknipnljbd7gtx3bioy https://api.nft.storage/check/bafyreia4mjk4crmp5eqtqzixc7ultt6o7briyvw5wzrel5nei7wenpxely)

successfully reuploading should do the trick

**Comment by Samreen-Kazi** [comment]
Hey, when i first uploaded these CIDs they were successfully uploaded and were clearly visible now however I am not able to see them and they are stuck on queuing and the data which is not stuck on queuing that is also not loading up. Like you suggested I tried reuploading but it is still stuck on queuing.

**Comment by dchoi27** [comment]
oh, i think you just have to append `/metadata.json` at the end: https://bafyreidwm2xwoa5bt632vzt54csphcoi3bjvj7vwknipnljbd7gtx3bioy.ipfs.nftstorage.link/metadata.json
