### ISSUE TITLE
[ Help needed - How to upload 100 GiB of data? ]

### ISSUE THREAD

**Issue by nobionekenopi** [nftstorage/nft.storage#2338]
Hello Good People~!!   Hope all is well.
I am in need of some advice re: IPFS / NFT.storage.

Background: I'm from a NFT Art project that is expanding into metaverse (we will have some gaming elements in the pipeline as well) etc.
We currently use traditional AWS S3 manner to store images but looking to see if hosting an IPFS node in EC2 or use NFT.storage services is a better solution...
The project currently has about 150 GiB of files/images and it could go up to 300-500 GiB in a years time.

Problem statement 1 : Cost and user experience. 
- Can anyone advice if AWS EC2 node hosting or NFT. storage use is a more cost effective solution?
 - will hosting our images and videos in NFT. storage result in a slower user viewing of the images/videos on the product webpages? 

Problem statement 2 : Upload Limit to NFT. storage
- on NFT. storage website. it says it supports up to 31 GiB in size per individual upload. Is this an upload limit set per account? 
or per Upload operation?
As mentioned above we have maybe 100 GiB to upload. Individually these file can be as large as 80mb each but no larger. Assets are mainly PNGs and short 10s videos. 
How can I upload > 100 GiB of data/file/assets?
Any cost involved?

Appreciate the help!!

**Comment by nobionekenopi** [comment]
Why is this closed?

**Comment by dchoi27** [comment]
your question was asked and answered mulitple times on filecoin slack / IPFS discord

**Comment by nobionekenopi** [comment]
Hi David, Thanks for helping and for your reply.Yes and No, part 2 of my question about the 31GiB limitation and how to upload 100GiB , is it per account etc was not answered. Hope someone can help address itSent from my Galaxy
-------- Original message --------From: David Choi ***@***.***> Date: 10/03/2023  12:41  (GMT+08:00) To: "nftstorage/nft.storage" ***@***.***> Cc: MINDNOZA ***@***.***>, Author ***@***.***> Subject: Re: [nftstorage/nft.storage] Why is this closed?? [ Help needed - How to upload 100 GiB of data? ] (Issue #2338) 
your question was asked and answered mulitple times on filecoin slack / IPFS discord
