### ISSUE TITLE
small animations to upload with metadata and static cover image

### ISSUE THREAD

**Issue by Bridburg** [nftstorage/nft.storage#2345]
Hi, 

My NFT project for Opensea is 200 15 second 3D animations as MP4 files. I also have static images upload with the metadata. 

I do NOT need to generate videos or images. 

I do need to set the videos and their respective static image and metadata up as files that go to an URI. 

I am looking for the equivalent of Hashlips for animations but not to generate videos. Just to add them to storage here and to have them work with Opensea. 

Is there a good app to use with the files I am discussing? Are there videos on YouTube for such a product? I simply need a name for such an app which is elusive to me. 

TIA
David Bridburg
bridburg@sbcglobal.net

**Comment by elizabeth-griffiths** [comment]
If you still need support, please re-open this issue and provide more detail. Thanks!
