### ISSUE TITLE
authorization

### ISSUE THREAD

**Issue by georgetalamantez** [nftstorage/nft.storage#2348]
I would like to request authorization for ipfs desktop. I am not able to upload using the api endpoint and my api token. thank you

**Comment by georgetalamantez** [comment]
also, nft up seems to extract all files from subdirectories and put them in one sinle directory. perhaps as a future update the capacity to preserve directory structure in cluding subdirectories.

**Comment by elizabeth-griffiths** [comment]
If you still need support, please re-open this issue and provide more detail. Thanks!
