### ISSUE TITLE
My data is still in the queue

### ISSUE THREAD

**Issue by CoolApeProject** [nftstorage/nft.storage#2360]
hi, 

I uploaded by files almost 12 hours ago but it still shows as queuing how much time will it take to complete the process.

Regards

**Comment by CoolApeProject** [comment]
hi,

kindly update the status of my upload, it's almost 24 hours since I have uploaded the content.

Regards

**Comment by CoolApeProject** [comment]
hi,

any update on my case, it's still in the queue.

**Comment by elizabeth-griffiths** [comment]
If you still need support, please re-open this issue and provide more detail. Thanks!
