### ISSUE TITLE
A question about metadata

### ISSUE THREAD

**Issue by drhomashk** [nftstorage/nft.storage#2366]
Hello,

 Our team has a collection of 1000 nfts that we want to put on Drop Opensea for our users.

The path I followed is as follows:

First, I uploaded my photo file.
(I uploaded it as a folder)

 Test #001.jpg
 Test #002.jpg
 Test #003.jpg

Then I put the address of each photo in each metadata. 

 Currently, I have 3 photos here as an example. 
 And I did this for thousands of photos.

https://bafybeictoijxl52bbkue5fmdaw7pyj3xtay22ku2diwxnzvzelf5es25ti.ipfs.nftstorage.link

In the second step, I uploaded 3 metadata files.  
(I uploaded it as a folder)

 Test #001.json
 Test #002.json
 Test #003.json

https://bafybeich34kiybw7yru5sva2tn5g4tolwybkc3chwzuu25xs2visdtm4fy.ipfs.nftstorage.link

I put the exclusive link of each photo in the image section of the metadata file as it’s attached.
![1](https://user-images.githubusercontent.com/129386810/229320667-47c122a8-3d70-48dd-b1c4-7b0e57ffa33d.jpeg)

Finally, this is the ipfs address of our json files, which we must put in the baseURI part of the smart contract.

 ipfs://bafybeich34kiybw7yru5sva2tn5g4tolwybkc3chwzuu25xs2visdtm4fy

I have done the above steps to create the metadata that is going to be uploaded in the Drop Opensea.

Now I have a question. 
I would like to know if I followed the steps correctly or not?

Thanks in advance

**Comment by elizabeth-griffiths** [comment]
If you still need support, please re-open this issue and provide more detail. Thanks!
