### ISSUE TITLE
Feature Request: Granular API Scopes and User Authorization for NFTStorage

### ISSUE THREAD

**Issue by mangoplane** [nftstorage/nft.storage#2370]
Hello NFTStorage team,

I would like to propose a feature request to introduce granular API scopes for NFTStorage. Currently, API keys do not have user-controlled scopes, which may raise security concerns for some users when sharing their keys. By introducing granular API scopes, users can share their keys with the confidence that it's safe and won't be misused to delete or modify files.

Moreover, I propose a feature allowing a user to authorize another user account to upload to their IPFS on their behalf. This would provide a more convenient way for users to collaborate and manage their NFT assets together.

These features would greatly enhance the security and usability of NFTStorage, making it even more attractive for individual creators, NFT tooling developers, and collectors.

I am interested in contributing to this feature by creating a PR if I find the time. Please let me know if you would consider this feature request and if there are any guidelines or recommendations for contributing to the project.

Thank you for your attention, and I look forward to your feedback.

**Comment by elizabeth-griffiths** [comment]
We’re closing this ticket for now, please re-open if it’s still an issue.
