### ISSUE TITLE
NFT Storage still queuing after 49 hours

### ISSUE THREAD

**Issue by L-JARRETT** [nftstorage/nft.storage#2371]
Hi, I would like to know if my metadata files will be uploaded soon as I require them for a drop on Opensea. Cheers.

**Comment by L-JARRETT** [comment]
Hey, still in the queuing phase... what's going on?? Any replies or email responses?

**Comment by ugurdeniz20** [comment]
I'm having the same problem, it's really ridiculous, I'm going to use other providers. This place is finished.
