### ISSUE TITLE
Error while installing nft.storage in Nuxt 3 application ssr

### ISSUE THREAD

**Issue by angelorc** [nftstorage/nft.storage#2374]
I have tried to install nft.storage in our Nuxt 3 application. However, I am facing an error while compiling which says 
```
"RollupError: 'randomBytes' is not exported by 'node_modules/unenv/runtime/node/crypto/index.mjs', imported by 'node_modules/@web-std/fetch/src/utils/form-data.js'"
```

This seems to be a problem with the unenv package which nft.storage is dependent on.

Do you know how can I fix it?

**Comment by elizabeth-griffiths** [comment]
We’re closing this ticket for now, please re-open if it’s still an issue.
