### ISSUE TITLE
Is it normal that pinning takes a bit long?

### ISSUE THREAD

**Issue by Nanashiworldnft** [nftstorage/nft.storage#2377]
Hi,

Good day, Just wondering if it is normal for a a large file/folder(11GB) takes longer to get pinned, or is the issue connected to the backlog data on filecoin deal? (pinning status is about 13days and counting)

Thank you.

**Comment by heyjay44** [comment]
It does take longer for large files/directories to get pinned. You can find more information here: https://nft.storage/docs/how-to/get-status/#archived
