### ISSUE TITLE
Hi NFT storage teams, I have the following problem (NFT up and ENOSPC error).

### ISSUE THREAD

**Issue by acca3434** [nftstorage/nft.storage#2389]
I want to register 12000 NFTs.
However, I encountered the following issue

Error: packing files: ENOSPC: no space left on device, write

What is this phrase?

For reference, the file size is 7GB in total.

Is this because the capacity is too large?

**Comment by elizabeth-griffiths** [comment]
We’re closing this ticket for now, please re-open if it’s still an issue.
