### ISSUE TITLE
Can't creat a new acount 

### ISSUE THREAD

**Issue by MathieuBurnat** [nftstorage/nft.storage#2390]
When I am creating a new account and clicking on the link via my email :
![image](https://user-images.githubusercontent.com/70205357/236812508-c3b8c000-ea2c-4bb1-aa8c-979a7aaa9041.png)

(I tried this 5times and I always had the same issue)

**Comment by heyjay44** [comment]
Sorry for the delayed response. Magic Link has caused issues for several users. Sometimes using a different browser helps - Firefox has been an issue for some folks. We are pivoting away from Magic Link for login in the future.

**Comment by elizabeth-griffiths** [comment]
If you still need support, please re-open this issue and provide more detail. Thanks!
