### ISSUE TITLE
ERROR: Expected a JavaScript module script but the server responded with a MIME type of "image/png

### ISSUE THREAD

**Issue by Fabriannie** [nftstorage/nft.storage#2391]
[Hello I am getting this error when my minting hub is trying to use the CID link for the image I stored on NFTStorage.:Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "image/png". Strict MIME type checking is enforced for module scripts per HTML spec.

this is the link: bafybeiacbdti5lqozgn2tlj23b33oqdaylhoj3hch74ysz7l6iw56ellba.ipfs.nftstorage.link/) the error is providing

Could you please help?]

**Comment by elizabeth-griffiths** [comment]
If you still need support, please re-open this issue and provide more detail. Thanks!
