### ISSUE TITLE
"API Key is malformed or failed to parse" when calling delete with a UCAN token

### ISSUE THREAD

**Issue by 0x62** [nftstorage/nft.storage#2403]
I've implemented UCAN tokens on our platform to allow users to upload. The flow I've got (just to confirm I'm doing this right) is:

1. Generated and registered platform DID
2. Obtain root UCAN for platform
3. Create keypair for each user and derive child token
4. Send child token and user keypair to client
5. Create request token on the client before each request

This works for uploading without any issues, however trying to call the delete method throws an error "API Key is malformed or failed to parse". 

![image](https://github.com/nftstorage/nft.storage/assets/6038417/fc72fac7-d559-42a0-9b32-8d6fa3e38db8)

`serviceDID` is the DID of nft.storage obtained from the API. `apiToken` is the child UCAN, and `keyPair` is the UCAN keypair recovered from the user private key. 

This is then attached to each request:

![image](https://github.com/nftstorage/nft.storage/assets/6038417/95447054-a38c-4adc-9123-f4ad30c0a934)

The full UCAN chain is:

```
{
  "aud": "did:key:z6MknjRbVGkfWK1x5gyJZb6D4LjMj1EsitFzcSccS3sAaviQ",
  "att": [
    {
      "with": "storage://did:key:z6MkrVim54w4HiHM7LDEQC27jFxAJeqjDde4BwrePG3HNo3y/did:key:z6MkmpWQeMqhaWqRpdYUmhiWmHM19Dxm27CjZfv2zkpmdtjy",
      "can": "upload/*"
    }
  ],
  "exp": 1685023729,
  "iss": "did:key:z6MkmpWQeMqhaWqRpdYUmhiWmHM19Dxm27CjZfv2zkpmdtjy",
  "prf": [
    {
      "aud": "did:key:z6MkmpWQeMqhaWqRpdYUmhiWmHM19Dxm27CjZfv2zkpmdtjy",
      "att": [
        {
          "with": "storage://did:key:z6MkrVim54w4HiHM7LDEQC27jFxAJeqjDde4BwrePG3HNo3y/did:key:z6MkmpWQeMqhaWqRpdYUmhiWmHM19Dxm27CjZfv2zkpmdtjy",
          "can": "upload/*"
        }
      ],
      "exp": 1685542067,
      "iss": "did:key:z6MkrVim54w4HiHM7LDEQC27jFxAJeqjDde4BwrePG3HNo3y",
      "prf": [
        {
          "aud": "did:key:z6MkrVim54w4HiHM7LDEQC27jFxAJeqjDde4BwrePG3HNo3y",
          "att": [
            {
              "with": "storage://did:key:z6MkrVim54w4HiHM7LDEQC27jFxAJeqjDde4BwrePG3HNo3y",
              "can": "upload/*"
            }
          ],
          "exp": 1686146867,
          "iss": "did:key:z6MknjRbVGkfWK1x5gyJZb6D4LjMj1EsitFzcSccS3sAaviQ",
          "prf": []
        }
      ]
    }
  ]
}
```

**Comment by elizabeth-griffiths** [comment]
If you still need support, please re-open this issue and provide more detail. Thanks!
