### ISSUE TITLE
Metadata inquiry

### ISSUE THREAD

**Issue by DamianFalcon9** [nftstorage/nft.storage#2405]
Hello, this is more of a question than issue. I uploaded some metadata and under the storage providers it says pending. I also saw a message that says you guys are working on a backlog. Im curious if this could be why my images aren't loading on opensea. Im just trying to determine if its my code or another issue, thank you guys for your time. And if you need it i'll attach the IPFS URL below.

ipfs://bafybeibw5hpom7vzjqubngo4x4jvocj4aypqqkgjcoi2ltgezadz6a6dqi

**Comment by ronmegini** [comment]
Your metadata looks fine to me, sometime it just take a while for the image to update in opensea.
If you still experience the problem maybe you should follow this guide: https://nft.storage/docs/how-to/mint-erc-1155/#uploading-your-images-assets-and-metadata

I just used it to deploy a contract and it worked just fine and the image presented well in opensea.
