### ISSUE TITLE
Content Security Policy HTTP headers

### ISSUE THREAD

**Issue by vrde** [nftstorage/nft.storage#2413]
I uploaded my dapp to nft.storage. When I visit it using the `ipfs.nftstorage.link` gateway, I get CSP errors because my dapp tries to connect to an ethereum node.

I tried to add my own CSP in the `head` of my html file:

```
<meta
  http-equiv="Content-Security-Policy"
  content="default-src 'self' https://*; style-src 'self' 'unsafe-inline'; img-src 'self'; connect-src https://* wss://*"
/>
```

but AFAIK my CSP doesn't override the one sent in the header by the gateway.

What's the utility of the gateway if I cannot store arbitrary content?

**Comment by elizabeth-griffiths** [comment]
If you still need support, please re-open this issue and provide more detail. Thanks!

**Comment by vrde** [comment]
@elizabeth-griffiths I'm not sure I understand why this issue has been closed :)

To me this issue is crucial because this CSP doesn't allow to connect to arbitrary blockchain endpoints.

I did a quick check and saw that the CSP set in the headers is:

`Content-Security-Policy: default-src 'self' 'unsafe-inline' 'unsafe-eval' blob: data: https://*.w3s.link https://*.nftstorage.link https://*.dweb.link https://ipfs.io/ipfs/ https://*.githubusercontent.com https://polygon-rpc.com https://rpc.testnet.fantom.network ; form-action 'self'; navigate-to 'self'; connect-src 'self' blob: data: https://*.w3s.link https://*.nftstorage.link https://*.dweb.link https://ipfs.io/ipfs/ https://*.githubusercontent.com https://polygon-rpc.com https://rpc.testnet.fantom.network ; report-to csp-endpoint ; report-uri https://csp-report-to.web3.storage`

It whitelists the endpoints my app can connect to:
- it limits what my app can do
- I don't have control over it

That's why I consider this a problem.
