### ISSUE TITLE
ERROR PROMPT DURING FILE UPLOAD

### ISSUE THREAD

**Issue by dbillionere** [nftstorage/nft.storage#2414]
I try uploading my NFT file on NFT up, so upon entering my API KEY for upload

During the upload of the file, at storing file stage, the flow stops and shows an error
message saying ; ERROR; STORING FILES; API KEY IS MALFORMED OR FAILED TO PARSE

pls help,,, thanks

**Comment by elizabeth-griffiths** [comment]
If you still need support, please re-open this issue and provide more detail. Thanks!
