### ISSUE TITLE
429 "Too many requests" fetching error

### ISSUE THREAD

**Issue by bofomike** [nftstorage/nft.storage#2415]
Hey 🫡 
I have JSONs uploaded to nft.storage IPFS and I need to asynchronously fetch 1000 of them. 
The problem is that I'm getting **429 "Too many requests"** error. 

I've tried to split into batches but nothing works. I mean, I've tried 10*100, 100*10, 50*20, ..., ..., I've tried to wait 1 sec, 2 sec between requests but sooner or later I'm getting this error anyway. 

That's what I'm fetching: `https://nftstorage.link/ipfs/${cid}`

Could you tell me what's the max frequency or how to handle this in a better way? 🤔

Thanks in advance 🤝

**Comment by elizabeth-griffiths** [comment]
If you still need support, please reopen the issue.
