### ISSUE TITLE
Hello CID has GONE

### ISSUE THREAD

**Issue by oravix** [nftstorage/nft.storage#2416]
Hi,
I was using Hello CID (   (bafybeifx7yeb55armcsxwwitkymga5xf53dxiarykms3ygqic223w5sk3m) as written on https://ipfs.github.io/public-gateway-checker/ for checking IPFS gateways health. 
I tried also to PIN that CID on my account (using its CAR) but It is anavailable again.
How can i solve?
V.

**Comment by elizabeth-griffiths** [comment]
CIDs that are not NFT data are blocked. If you believe this CID is NFT data, please re-open this ticket and send us more information. Thanks!
