### ISSUE TITLE
hello,why I can't login in my account

### ISSUE THREAD

**Issue by fx168caijing** [nftstorage/nft.storage#2417]
hello,my picture can not open,https://nftstorage.link/ipfs/bafybeiflkjuiseqdnrvzcd4boz6glazoadyy5b4yrtvoim227g6tqahb4u/16732489820002%2520%25E6%25B1%259F%25E6%25B3%25B0.gif,and i also can not login in my account  by git,my account is tan.aidong@fx168group.com，ples help me,ths

**Comment by heyjay44** [comment]
Are you getting an error when you try to login? There have been intermittent issues with Magic Link.

**Comment by elizabeth-griffiths** [comment]
We’re closing this ticket for now since we haven't heard back, please re-open if it’s still an issue.
