### ISSUE TITLE
how to get the stored blob in dapp

### ISSUE THREAD

**Issue by hefansuper** [nftstorage/nft.storage#2432]
hi guys，I stored information using the storeBlob method from ntf.storage. Now, I want to display the corresponding content in my dapp. Can you please guide me on how to achieve this?

my link：https://bafkreicegxlxgijhn3veejgru47outzi3277ttapfkr762s2ba2uqepeme.ipfs.nftstorage.link/

**Comment by elizabeth-griffiths** [comment]
If you still need support, please re-open this issue and provide more detail. Thanks!
