### ISSUE TITLE
/dns4/elastic.dag.house/tcp/443/wss seems to block some IP ranges (handshake failure or 403)

### ISSUE THREAD

**Issue by SmaugPool** [nftstorage/nft.storage#2434]
Some files are advertised on https://cid.contact as provided by `/dns4/elastic.dag.house/tcp/443/wss`, but our IPFS cluster nodes cannot connect to it to retrieve them (as a peer or manually):

```
$ ipfs swarm connect /dns4/elastic.dag.house/tcp/443/wss/p2p/QmQzqxhK82kAmKvARFZSkUVS6fo9sySaiogAnx5EnZ6ZmC
Error: connect QmQzqxhK82kAmKvARFZSkUVS6fo9sySaiogAnx5EnZ6ZmC failure: failed to dial QmQzqxhK82kAmKvARFZSkUVS6fo9sySaiogAnx5EnZ6ZmC:
  * [/ip4/127.0.0.1/tcp/443/tls/sni/localhost/ws] failed to WebSocket dial: failed to send handshake request: Get "https://localhost:443": dial tcp 127.0.0.1:443: connect: connection refused
  * [/ip4/104.18.20.126/tcp/443/wss] failed to WebSocket dial: failed to send handshake request: Get "https://104.18.20.126:443": remote error: tls: handshake failure
  * [/ip4/104.18.21.126/tcp/443/wss] failed to WebSocket dial: failed to send handshake request: Get "https://104.18.21.126:443": remote error: tls: handshake failure
  * [/ip6/2606:4700::6812:157e/tcp/443/wss] failed to WebSocket dial: failed to send handshake request: Get "https://[2606:4700::6812:157e]:443": remote error: tls: handshake failure
  * [/ip6/2606:4700::6812:147e/tcp/443/wss] failed to WebSocket dial: failed to send handshake request: Get "https://[2606:4700::6812:147e]:443": remote error: tls: handshake failure
  * [/ip4/104.18.21.126/tcp/443/tls/sni/elastic.dag.house/ws] failed to WebSocket dial: expected handshake response status code 101 but got 403
  * [/ip4/104.18.20.126/tcp/443/tls/sni/elastic.dag.house/ws] failed to WebSocket dial: expected handshake response status code 101 but got 403
```
I checked that our nodes time is accurate and TLS certificates up to date. 

I thought at first it might come from our configuration, but I made tests from about 10 servers using the same software (Kubo 0.21.0) and connection works from all servers not (co)located in Hetzner datacenters (German and Finland ones):
```
$ ipfs swarm connect /dns4/elastic.dag.house/tcp/443/wss/p2p/QmQzqxhK82kAmKvARFZSkUVS6fo9sySaiogAnx5EnZ6ZmC
connect QmQzqxhK82kAmKvARFZSkUVS6fo9sySaiogAnx5EnZ6ZmC success
```

IP ranges I noticed cannot connect are:
* 159.69.0.0/16
* 95.216.0.0/15
* 65.108.0.0/15
* 188.40.0.0/16

Those are all part of AS24940 Hetzner Online GmbH: https://www.ip2location.com/as24940

We serve millions of optimized NFT images sourced from any IPFS provider and users & customers are asking why NFTs using NFT Storage are not always displayed correctly.

Is there some kind of blocking in place (on purpose or not) and if so why and is there any way to get our cluster unblocked to avoid degrading users experience?

Thank you

**Comment by dchoi27** [comment]
Hey there - you're right, there was blocking in place from a previous incident of abuse of NFT.Storage. We've lifted it now. 

However, more generally, keep in mind that NFT.Storage is a community-run project for off-chain NFT data archival, and we block any unauthorized use where it becomes difficult to support (from users storing non-NFT data to nodes hitting our infrastructure where it becomes cost prohibitive to support their use cases).

> We serve millions of optimized NFT images sourced from any IPFS provider and users & customers are asking why NFTs using NFT Storage are not always displayed correctly. Is there some kind of blocking in place (on purpose or not) and if so why and is there any way to get our cluster unblocked to avoid degrading users experience?

We don't want your users' experience to be degraded! But we also can't support being the origin server for your customers - it's a classic free-rider problem where the project pays the bills for your product. Happy to work with you to figure out a solution, but you'll need to be your own origin server (but feel free to grab content requested by your users from us on the first request). Otherwise, if usage from your project becomes cost-prohibitive, we'll need to protect NFT.Storage.

Marking as closed given the issue is resolved, but happy to respond to your thoughts here.

**Comment by SmaugPool** [comment]
> Hey there - you're right, there was blocking in place from a previous incident of abuse of NFT.Storage. We've lifted it now.

Thank you! It would be nice to document those blocks to make investigations easier unless this raises security issues.

> We don't want your users' experience to be degraded! But we also can't support being the origin server for your customers - it's a classic free-rider problem where the project pays the bills for your product. 

I'm not sure why you assume that without knowing us and that's actually absolutely not the case. We serve NFT files to our customers only from our own infrastructure and we need to fetch files just once to then serve them. Files are also guaranteed to be from NFTs as we only support those identified from their blockchain ID. I'm happy to give you our node IDs or IP addresses if you want to check how we source some files from you.

Our performance and reliability would in fact be deplorable if we had to constantly rely on all IPFS providers, whose levels of quality and reachability from IPFS vary widely, which is why we limit this risk to the first request. And as seen in this very issue we still have to spend quite some time solving issues with providers from which we struggle to fetch files just once.

**Comment by SmaugPool** [comment]
Hi @dchoi27, have you re-enabled blocking? I now get "connection refused".
