### ISSUE TITLE
need to upload 70gb of files

### ISSUE THREAD

**Issue by waifumongen2** [nftstorage/nft.storage#2437]
Need to upload 70 gb of mp4 files. it will be eth 721 nft collection, any idea to split or can i upload all 70gb files?

**Comment by heyjay44** [comment]
I don't fully understand your question. Could you please provide more details?

**Comment by elizabeth-griffiths** [comment]
We’re closing this ticket for now since we haven't heard back, please re-open if it’s still an issue.
