### ISSUE TITLE
This site can't provide a secure connection

### ISSUE THREAD

**Issue by wuhaiyzq** [nftstorage/nft.storage#2438]
When I visit this website(https://bafybeigyzm5ar4ccgss7bkuafzmkmcxs6h4wtt2pk55bomabaqhusbe2du.ipfs.nftstorage.link/cucutx7qbmwqjfbyws.jpg), I am prompted with an error of 'This site can't provide a secure
connection An SSL error has occurred and a secure cannection to the serwer cannot be made NSURLErrorSecureConnectlonFalled'
thanks!

**Comment by elizabeth-griffiths** [comment]
If you still need support, please re-open this issue and provide more detail. Thanks!
