### ISSUE TITLE
Acess denied

### ISSUE THREAD

**Issue by nexwavlabs** [nftstorage/nft.storage#2439]
Hello, I can't create an account with my work email. I'm getting the following message: "Access denied, Sorry, you don't have permission to log in to nft.storage." I can log in with my personal email, but not with my company email. How can I resolve this issue?

**Comment by elizabeth-griffiths** [comment]
Hi - Please send an email to support@nft.storage from the email you are unable to log in from.

**Comment by heyjay44** [comment]
Closing as conversation has been moved to email.
