### ISSUE TITLE
How long does it take to get out of the queue? Thank you!

### ISSUE THREAD

**Issue by nexwavlabs** [nftstorage/nft.storage#2441]
Hello, my 18GB file has been in the queue since 08/05 until 08/11, is this normal? When I access the link through the CID, it opens normally and I can view the files on IPFS.

**Comment by heyjay44** [comment]
@nexwavlabs thanks for your message and bringing this to our attention. Can you provide the CID or the last 8 characters? If you'd prefer to share via email, please send the information to support@nft.storage

**Comment by nexwavlabs** [comment]
The last 8 characters:
yrf5z3my
________________________________
De: Jay ***@***.***>
Enviado: terça-feira, 15 de agosto de 2023 11:02
Para: nftstorage/nft.storage ***@***.***>
Cc: nexwavlabs ***@***.***>; Mention ***@***.***>
Assunto: Re: [nftstorage/nft.storage] How long does it take to get out of the queue? Thank you! (Issue #2441)


@nexwavlabs<https://github.com/nexwavlabs> thanks for your message and bringing this to our attention. Can you provide the CID or the last 8 characters? If you'd prefer to share via email, please send the information to ***@***.******@***.***>
