### ISSUE TITLE
api pinning limits

### ISSUE THREAD

**Issue by privacycoop** [nftstorage/nft.storage#2442]
We are a non profit cooperative association, which help our members, and the public control their data rights.
We expect be creating a significant number of NFTs, which will need a small json object to be pinned, and a small jpg image for display in the member wallets.

What are the limits on pinning rates for the API? We expect to grow into millions of NFTs and need to identify a pinning partner for our service.
We do host an ipfs server in AWS, but need to ensure pinning also occurs elsewhere in the network, so data is never lost, if our servers experience any failures due to cloud issues.

Thanks!

https://privacy.coop

**Comment by heyjay44** [comment]
The pinning service API isn't intended for large amounts of data. If you haven't already, you can read more about pinning here: https://nft.storage/docs/how-to/pinning-service/

**Comment by elizabeth-griffiths** [comment]
We’re closing this ticket for now since we haven't heard back, please re-open if it’s still an issue.
