### ISSUE TITLE
hi, my files are still queue for a week

### ISSUE THREAD

**Issue by downlabs** [nftstorage/nft.storage#2452]
hi, my files are still queue for a week

ipfs://bafybeibveue5lbcjughcrvpkl4kchyvv4akm2gs7ecrnkew2k6pr7dazau

can you guys advice what should i do?

**Comment by downlabs** [comment]
CID: bafybeibveue5lbcjughcrvpkl4kchyvv4akm2gs7ecrnkew2k6pr7dazau

**Comment by heyjay44** [comment]
@downlabs sorry for the delay. Just checking to see if this is still the case?

**Comment by downlabs** [comment]
> @downlabs sorry for the delay. Just checking to see if this is still the case?

sadly yes

**Comment by downlabs** [comment]
i'm trying to reupload but still...bigger images bigger queuing to successfully store?

**Comment by elizabeth-griffiths** [comment]
If the CID appears on the NFT.Storage Gateway you’re all good. The URL is nftstorage.link/ipfs/{enter CID}

We’re closing this ticket for now, please re-open if it’s still an issue.
