### ISSUE TITLE
Unable to retrieve IPFS data

### ISSUE THREAD

**Issue by umairajmal-netsol** [nftstorage/nft.storage#2458]
Hitting this link in the browser downloads a JSON file while trying to fetch same result via code mentioned below gives 400 Bad Request.

**Code:**
```
const response = await axios.get(
    `https://bafyreiguv27r6tupea3fd274uke6fhk3kcncunukljn7nxz72hslvfz2si.ipfs.dweb.link/?format=dag-json`
  );
  console.log(response);
```
**Error:** Your request is invalid. Most probably, the CID (the part after <code>/ipfs/</code> or before\n' +       '                <code>dweb.link</code>) is incorrect

**Comment by elizabeth-griffiths** [comment]
If this is still occurring, please re-open this ticket and provide more details. Thanks!
