### ISSUE TITLE
Error Encountered When Using storeDirectory.mjs

### ISSUE THREAD

**Issue by bj-will** [nftstorage/nft.storage#2475]
**Problem**:
I'm encountering an error while attempting to use the `storeDirectory.mjs` script as documented in the https://nft.storage/docs/how-to/store-directory/

**Error**:
The error message I'm receiving is as follows:
```
import { filesFromPath } from 'files-from-path'                                                                        
         ^^^^^^^^^^^^^                                                                                                 
SyntaxError: The requested module 'files-from-path' does not provide an export named 'filesFromPath'                   
    at ModuleJob._instantiate (node:internal/modules/esm/module_job:122:21)                                            
    at async ModuleJob.run (node:internal/modules/esm/module_job:188:5)
    at async DefaultModuleLoader.import (node:internal/modules/esm/loader:228:24)
    at async loadESM (node:internal/process/esm_loader:40:7)
    at async handleMainPromise (node:internal/modules/run_main:66:12)
```
This error is occurring due to an update of the `files-from-path` package to a new version.

**Solution Attempted:**
In an attempt to resolve this issue, I rolled back to the previous version of the `files-from-path`, and everything started working as expected.

**Request**:
I recommend updating the line with installation instructions for packages in the documentation from the current:

https://github.com/nftstorage/nft.storage/blob/4c9060839c2d0bedb69422078cb07e7accb345ab/packages/website/pages/docs/how-to/store-directory.md?plain=1#L25

to a version-specific package installation code, such as:

```
npm install nft.storage files-from-path@0.2.6
```

**Comment by elizabeth-griffiths** [comment]
We’re closing this ticket for now since we haven't heard back, please re-open if it’s still an issue.
