### ISSUE TITLE
CID is inconsistent.

### ISSUE THREAD

**Issue by singpenguin** [nftstorage/nft.storage#2476]
I use the Kubo client to store files, and the CID I get is inconsistent with the CID I get uploaded through nft.storage. I don’t know what went wrong.

Files uploaded through pinata are consistent with those stored using the kubo client.

Does nft.storage process the data?

Thanks.

**Comment by elizabeth-griffiths** [comment]
If this is still occurring, please re-open this ticket and provide more details. Thanks!
