### ISSUE TITLE
Need help with IPFS issue

### ISSUE THREAD

**Issue by strikey123** [nftstorage/nft.storage#2484]
Hello, 
I released an NFT project a while back and everything was running smoothly no issues. I used NFT generator to facilitate the project and launched on Opensea. Recently when people try to mind, the NFT image does not load. I contacted both companies and both say that it has something to do with IPFS timing out and suggested I come to NFT.Creator to fix the issue. 

I'm not familiar with the platform and know how to fix my issues so would like some help in doing so.
I have the collection json files and image webo files if that helps.

Thank you.

**Comment by strikey123** [comment]
Here is the smart contract for the project: 0xFe1232b8b920dd3d59368F83E6718431A28CE402

**Comment by strikey123** [comment]
![Screenshot 2023-12-08 at 11 35 57](https://github.com/nftstorage/nft.storage/assets/153821038/c8837272-d65a-4514-8b40-50e00c60d0bf)

**Comment by elizabeth-griffiths** [comment]
Please email ***@***.*** from the account email and we will get
this resolved for you asap
