### ISSUE TITLE
504 gateway timeout 

### ISSUE THREAD

**Issue by GolfredoPerezFernandez** [nftstorage/nft.storage#2499]
everything was working good! but suddenly all the uploaded files stopped working says: 
![image](https://github.com/nftstorage/nft.storage/assets/36853339/fb719533-b5e3-4b34-9f7a-c15bfe473109)
my email is golfredo.pf@gmail.com

**Comment by anishsamant7** [comment]
I am facing the same issue. The files seem to randomly show-up but most of the times it gives 504 gateway timeout. Any update regarding this will be greatly appreciated.

**Comment by elizabeth-griffiths** [comment]
Hi there - Is this still an issue?

**Comment by elizabeth-griffiths** [comment]
Hi - We're going to close this ticket since we haven't hear back. If it's still an issue, please re-open the ticket.
