### ISSUE TITLE
Possibility to authenticate automatically with keplr wallet

### ISSUE THREAD

**Issue by iljmur** [nftstorage/nft.storage#2501]
Dear team, 

as nft marketplace we would like our users to be in full custody of their uploaded NFT files. At the same want to keep registration for our users on nft.storage as simple as possible. If users have to register on nft.storage and save their upload token with our platform, then this is absolutely bad experience.

 With UCAN authorization is possible to create subaccounts for users, and it works transparently for users, but central account has access to all files and this is what we want to avoid.

Ideally want to have wallet authentication for our users. Ideally with keplr as this is the main wallet in Cosmos ecosystem. Following documentation I see there are plans for wallet based authentication, but is there already a solution for that?

Thank you, 
Ilja

**Comment by elizabeth-griffiths** [comment]
There is not wallet authentication currently. We will add this to the feature requests. Thanks!
