### ISSUE TITLE
504 Bad Gateway after uploading Images and JSON files to ipfs through NFT.storage

### ISSUE THREAD

**Issue by cychiuak** [nftstorage/nft.storage#2502]
![Screenshot 2024-02-05 at 5 36 34 PM](https://github.com/nftstorage/nft.storage/assets/68217955/5a7106ff-8ff8-4ef4-a1bb-fe635c81b04a)

After uploading images and JSON files to ipfs storage through NFT.storage, I found that the connection is sometimes unstable and sometimes shows 504 bad gateway. I want to ask if anyone encountered before? What might be the potential reason of this unstable connection reason?

**Comment by elizabeth-griffiths** [comment]
Can you please describe in more detail when you get this? Is it when you go to view the CID at nftstorage.link/ipfs/{enter cid}?

**Comment by elizabeth-griffiths** [comment]
We’re closing this ticket for now, please re-open if it’s still an issue.
