### ISSUE TITLE
been queing to pin for 4 months!

### ISSUE THREAD

**Issue by cybernetix3d** [nftstorage/nft.storage#2505]
pleas can you help - bafybeiaw4bvh4ddoqfbrovtpr73z556dvnlzmnqvuyzgh4qmkkcsxwlqb4 - sis still in queue to pin. how do we fix this

**Comment by mirkoprado** [comment]
nobody reply from nftstorage, about the long time on pining

**Comment by elizabeth-griffiths** [comment]
If you can view the image at nftstorage.link/ipfs/{cid} you're good to go.
