### ISSUE TITLE
Cannot login

### ISSUE THREAD

**Issue by pjstarrusa** [nftstorage/nft.storage#2509]
I do not know if i forgot my username or what. I keep logging in. I receive the email. It says I have logged in successfully. Then it just goes back to the login screen again. 

I cannot get to my files. Please help.

Hope this can help find my account... Here is one of my files:
https://bafybeighhicppwg3zizekn64kg4axlduhwxnpl7orjvgpwgsfbd67sgtq4.ipfs.nftstorage.link/3593ad448123f638c7b809b21f82515c.png

Thank you.

**Comment by elizabeth-griffiths** [comment]
This should be resolved now. Please re-open the ticket if you're still not able to log in.
