### ISSUE TITLE
Login link does not log me in

### ISSUE THREAD

**Issue by Fourzin** [nftstorage/nft.storage#2512]
I am trying to login to my account but after clicking on the Login button from the email, I get redirected to the home page at nft.storage

**Comment by elizabeth-griffiths** [comment]
Hi,

Can you please try again? If it doesn't work try in a few browsers and let
me know which ones you've tried.

Thanks!

**Comment by elizabeth-griffiths** [comment]
This should be resolved now. Please re-open the ticket if you're still not able to log in.
