### ISSUE TITLE
Files not uploaded to my ntfStorage account

### ISSUE THREAD

**Issue by Mariner76** [nftstorage/nft.storage#2515]
Hi,
"I successfully upload files through my app locally (node 20, nextjs 14), and all the logs are correctly displayed in the terminal. However, I can't see the files on my nft.storage account, and they are not visible on the IPFS gateway either."
How can I resolve this?
Thanks

**Comment by elizabeth-griffiths** [comment]
Are you able to view the files on the NFT.Storage gateway? 
nftstorage.link/ipfs/{enter cid}

**Comment by elizabeth-griffiths** [comment]
Hi - We're going to close this ticket since we haven't hear back. If it's still an issue, please re-open the ticket.
