### ISSUE TITLE
504 Gateway Timeout

### ISSUE THREAD

**Issue by owenmcateer** [nftstorage/nft.storage#2517]
I uploaded my HTML,JS,CSS artwork to IPFS, everything seemed to have be uploaded correctly and sometimes loads correctly from a gateway but often returns a "504 Gateway Timeout" error. 
Why is this and is there any way to fix it?
CID: bafybeig5escz2gzswqwhgfh4rmjtgpefw5mjvd6emuq2ohitg6yaksv5pm

**Comment by elizabeth-griffiths** [comment]
Is this resolved?

**Comment by elizabeth-griffiths** [comment]
Hi - We're going to close this ticket since we haven't hear back. If it's still an issue, please re-open the ticket.
