### ISSUE TITLE
File disappears

### ISSUE THREAD

**Issue by nultinator** [nftstorage/nft.storage#2521]
When I upload a duplicate file, neither file  (the original and the duplicate) can be retrieved via ipfs.io. So far, this has only happened with one file, which makes it even more perplexing to me.

Any insight related to this would be greatly appreciated.

**Comment by elizabeth-griffiths** [comment]
Can it be retrieved via the NFT.Storage Gateway: nftstorage.link/ipfs/{enter cid}

**Comment by elizabeth-griffiths** [comment]
Hi - We're going to close this ticket since we haven't heard back. If this is still an issue, please re-open the ticket.

**Comment by nultinator** [comment]
Thank you for replying. I didn't see your email at first. Yes the issue has been fixed.
Jake Nulty
Software Developer/Writer
***@***.*** 
 
  On Sat, Apr 20, 2024 at 20:08, Elizabeth ***@***.***> wrote:   


Hi - We're going to close this ticket since we haven't heard back. If this is still an issue, please re-open the ticket.
