### ISSUE TITLE
Issue with Image Upload Failures to NFT.Storage

### ISSUE THREAD

**Issue by Scratchmine-Scratchyours** [nftstorage/nft.storage#2527]
Dear Support Team,

I am encountering a persistent issue with uploading images to NFT.Storage, which is crucial for my NFT project. Despite successful image generation and confirmation of their correct appearance in blob storage, these images fail to upload properly to NFT.Storage. When accessing the URLs meant to display the image and its accompanying JSON data, the images are visible but their content appears to be empty.

I have previously experienced a similar issue, which was attributed to the presence of duplicate images. However, after thorough verification, I can confirm that there are no duplicates in my current uploads. The only recent change to the images has been the addition of a logo in the top left and bottom right corners. I am concerned that this alteration might be causing the system to mistakenly flag the images as duplicates.

For reference, here are two example URLs where the issue can be observed:

[Link 1](https://bafybeiclimqmt54bv7sv3dljew5f2t6h2nnvy22u6z6f7i332znmihn3s4.ipfs.nftstorage.link/00_26_03_2024)
[Link 2](https://bafybeiar6n6gpb4zcon76muvc3dcquwfbxapcb3pul6kqc6dgp6zhed7oy.ipfs.nftstorage.link/12_25_03_2024)
Could you please investigate this matter and advise on a possible solution? The correct upload and display of these images are crucial for the progression of my project.

Thank you for your attention to this matter.

Best regards,
Isaiah

**Comment by elizabeth-griffiths** [comment]
Hi Isaiah - We're you able to resolve the issue? 
If not, please advise if you're using the API or SDK to upload.

**Comment by elizabeth-griffiths** [comment]
Hi - We're going to close this ticket since we haven't heard back. If this is still an issue, please re-open the ticket.
