### ISSUE TITLE
Unable to login

### ISSUE THREAD

**Issue by b0ggs** [nftstorage/nft.storage#2533]
The magic link keeps taking me back to the login page.

**Comment by b0ggs** [comment]
Worked on the 8th time of sending the link. Not sure what the issue was. You can close this issue.

**Comment by elizabeth-griffiths** [comment]
Try clearing your cache. Let me know if that doesn't work.

**Comment by elizabeth-griffiths** [comment]
Closing this issue. Please reopen if it isn't resolved
