### ISSUE TITLE
virus found

### ISSUE THREAD

**Issue by howardgerson** [nftstorage/nft.storage#2538]
I was going to use the Windows version of NFT-UP beta version 1.0 however when I ran it through virustotal.com (the Google online scanner), it reported a virus found, the virus is Trojan.Siggen17.51469, any thoughts on if the file has been infected or not?
Thanks,
Howard

**Comment by elizabeth-griffiths** [comment]
We are looking into this. I will be in touch.

**Comment by elizabeth-griffiths** [comment]
Hi - We're going to close this ticket while we're looking into it. Please contact support@nft.storage directly with any other queries related to this.
