### ISSUE TITLE
ERR_SSL_PROTOCOL_ERROR

### ISSUE THREAD

**Issue by DapperGordy** [nftstorage/nft.storage#2541]
Clicking any of the CID links in the files page leads to an SSL error, preventing looking at the contents of the link. Happens in both chrome and firefox. Clearing cookies, site data, flushing dns via ipconfig, and windows network diagnostics doesn't fix the issue.

![SSL 1](https://github.com/nftstorage/nft.storage/assets/94886859/21f910a4-682b-4445-bf86-46751f90443c)
![SSL 2](https://github.com/nftstorage/nft.storage/assets/94886859/c3bd0e61-b03d-4d39-ac04-aaa32499b429)

**Comment by TheLazySol** [comment]
I seem to be having the same issue. By the looks of it, every and any spl-token using nft.storage ipfs is having the same error. Look at solscan.io alone: (image) 
![image](https://github.com/nftstorage/nft.storage/assets/161502578/f58d6d72-c330-4884-867a-ee6ff4a938ad)

**Comment by TheLazySol** [comment]
### Quick update to what helped me fix this issue for the moment: 

I changed my IP address -- using a VPN of course. This solved my issue and I was able to view the nft.storage links on my end. However, this has not solved my issue permanently and for my own IP address it still does not work.

**Comment by elizabeth-griffiths** [comment]
Can you please check now to see if it's working? 
If it isn't, what internet service provider are using?

**Comment by elizabeth-griffiths** [comment]
Hi - We're going to close this ticket since we haven't heard back. If this is still an issue, please re-open the ticket.
