### ISSUE TITLE
NFT Up issues

### ISSUE THREAD

**Issue by kryscodev** [nftstorage/nft.storage#2572]
Hello,

I can't seem to upload using NFT Up, after pasting the key to upload files it just crashes with an error
    "Error: storing files: API Key is malformed or failed to parse."

**Comment by elizabeth-griffiths** [comment]
Hi,

NFTUp requires an API key from classic.nft.storage

Do you have a Classic account? We're not longer accepting registrations, so
if you don't have an account check out the new version of nft.storage
instead.
