### ISSUE TITLE
Algorand Supported?

### ISSUE THREAD

**Issue by HippieNerdFarmer** [nftstorage/nft.storage#2575]
Hello - I am looking to mint an NFT project on Algorand and do not see that as an option in the drop down.  Is it still supported?

Thanks, 
HNF

**Comment by elizabeth-griffiths** [comment]
Hi There,
Algorand isn't currently supported but we will note your feature request.
To help us better understand the value of prioritizing Algorand, can you
share why you choose to mint there?
Thanks!
