### ISSUE TITLE
Can't upload CAR file or pin NFTs

### ISSUE THREAD

**Issue by OmniBazaar** [nftstorage/nft.storage#2576]
Hello, Support.

I tried uploading a CAR file but got this message: Error uploading: The requested file could not be read, typically due to permission problems that have occurred after a reference to a file was acquired
 
What do you suggest? I didn’t see anywhere to insert my API key. I believe I am still logged into my NFT.storage account.

I also tried to initiate pinning of some test files from within my local IPFS node. The node responded that the file was successfully pinned. And, the files showed up in my NFT.storage "Files" screen. But, 24 hours later, all of the files are still showing "Queued". NONE have uploaded and NONE show as pinned. What do you suggest?

Thank you,
Rick Crites
rickcrites@usa.net

**Comment by elizabeth-griffiths** [comment]
Hi Rick - 
It sounds like everything is working. You can test it out by going to nftstorage.link/ipfs/[enter cid]. If your image loads, then your good to go!
Let us know if you have any other questions!
