### ISSUE TITLE
API key doesn't work as expected 

### ISSUE THREAD

**Issue by NiceArti** [nftstorage/nft.storage#2588]
I have a trouble with API key, so when I go to website and create a new API key I receive it and then when I use your lib https://www.npmjs.com/package/nft.storage and pass the key into NFTStorage class I see an error "Error: API Key is malformed or failed to parse". Why my key doesn't work so I generate new keys and same error ocurs

**Comment by elizabeth-griffiths** [comment]
"API Key is malformed or failed to parse" is because

an API key from https://app.nft.storage/login
Is being used for
https://classic.nft.storage/ SDK.

To use https://app.nft.storage/login, use the dashboard or the API linked from the dashboard docs. There is not an SDK yet.
