### ISSUE TITLE
could not see my html file again

### ISSUE THREAD

**Issue by smile4izu** [nftstorage/nft.storage#2590]
Good day, please I have checked and could not see my html file uploaded here, please advise. thank you

**Comment by smile4izu** [comment]
I hosted html file there before and it has been working until yesterday, it stopped working and I had to reupload only to see csv files only. please advise.

**Comment by elizabeth-griffiths** [comment]
Please share the cid here. 

If the uploaded data is detected as non-nft data it could have been temporarily blocked. 

Please tell me more about your NFT project, and share a link to where we can learn more if it's live?

**Comment by elizabeth-griffiths** [comment]
Hi - We're going to close this ticket since we haven't heard back. If this is still an issue, please re-open the ticket.
