### ISSUE TITLE
IPFS hosted items not loading after 12+ days

### ISSUE THREAD

**Issue by CryptoBulliez** [nftstorage/nft.storage#2591]
https://ipfs.io/ipfs/bafybeifeffvi3eoiv37n2vcczazyef3koz5orqpaxvnobjizz2oaxfgk7q/100.json
https://ipfs.io/ipfs/bafybeifoxr6rkdlclqr23fcnyina6wbwdv4zjovc224wl4kk7fsvu7wlzi/100.png
https://ipfs.io/ipfs/bafybeifac7h4rus2xzcpixltv7vq4rcgotxpmc23ksf4cx4s3lhddqtf3q/sliders/100.html

**Comment by elizabeth-griffiths** [comment]
It looks like they are loading fine on the the NFT.Storage Gateway: nftstorage.link/ipfs/{cid}

For example: https://nftstorage.link/ipfs/bafybeifac7h4rus2xzcpixltv7vq4rcgotxpmc23ksf4cx4s3lhddqtf3q

Please re-open if you still have issues
