### ISSUE TITLE
Having to change platforms

### ISSUE THREAD

**Issue by Leviathon777** [nftstorage/nft.storage#2592]
Since wqe built our entire app on using your services to upload to we hjave to drop that and change all our code to someone else? We built a large marketplace for tokenization of real assets, music, video, art, real estate, etc - Now we cant upload to you anymore? We cant build our nfts here? 

I dont understand - we have to move to cloudflare or something like that to store our data / ipfs NFTs??

**Comment by elizabeth-griffiths** [comment]
Hi there, 

To  ensure the sustainability of our model, we're updating our service offerings. We'll continue to offer the current product under the name NFT.Storage Classic for existing uploads prior to 30 June 2024, but no new uploads to the Classic product will be accepted as of 30 June 2024 at 5pm EST. New account registrations will no longer be accepted for:

- The original NFT.Storage web app, API, and SDK
- NFTUp
- Pinning API

Your benefits as an existing account holder:

- Continue to upload off-chain NFT data using the current products through 30 June 2024, at 5 PM EST
- Maintain access to your links through the NFT.Storage Gateway at https://nftstorage.link/ipfs/{CID} 
- All NFT data you’ve already uploaded and will upload before 30 June 2024, will continue to be safely stored and accessible via IPFS and in the Filecoin Network's long-term storage, though over time latency and availability may degrade.

Read our blog our exploring IPFS upload options: https://nft.storage/blog/onboard-nft-data-to-ipfs

We hope you check out the new version of NFT.Storage, and look forward to your feedback on that.
