### ISSUE TITLE
XRP NFTs & contract address

### ISSUE THREAD

**Issue by billian** [nftstorage/nft.storage#2598]
Hi, I have been using classic, and uploading NFT data & media from my dev website, using js files & api,  can you tell me what modifications I need to make to use the paid service for XRP NFTs?
I see the script requires the contract address? & the networks/platforms do not include XRPL, So does that mean XRP NFTs are not supported? or is there a method to just upload data & media files?
I am a complete novice, so detailed instructions would be helpful.
Thanks in advance  for your help,

**Comment by elizabeth-griffiths** [comment]
Hi there, Thanks for reaching out. We're still adding support for L1s and L2s, XRP is on the list. Can you tell us more about why you choose XRP? 

The way the new version of NFT.Storage works is: 
1.Create an account
Create your account with just one click and future-proof your NFTs with a low one-time fee.


2. Mint + send your NFT data
Mint your NFTs then send us the NFT data—metadata and imagery CIDs, blockchain(s) minted on, contract address and token IDs.

**Comment by billian** [comment]
Hi, I use xrp because I have been in the xrp community since 2013, I like the very low transaction fees, the speed & the ability to make micro payments with virtually zero fees, The addition of NFTs was interesting although late to the party, I recently had a cause to create nfts for a fundraising project that did not materialise, but turned into a prospective venture for me & the person I was going to fundraise for. The NFTs I am creating, unlike the majority of pixel art, will have a utility & potential revenue generating aspect for the participants. I have an onsite procedure for creating the XRPNFTs & automatically uploading & retrieving data & media to/from classic.nft.storage I would like to continue to do this on the new platform, 
I look forward to your advice for implementing this on nft.storage,
I have purchased 1gb to start, But alas cannot use it yet. due to the smart contract requirement, why can we not just upload the data & media as files? & link them to xrp addresses?
many thanks 
Ian
     On Thursday, April 25, 2024 at 01:03:29 PM GMT+1, Elizabeth Griffiths ***@***.***> wrote:  
 
 


Hi there, Thanks for reaching out. We're still adding support for L1s and L2s, XRP is on the list. Can you tell us more about why you choose XRP?

The way the new version of NFT.Storage works is:
1.Create an account
Create your account with just one click and future-proof your NFTs with a low one-time fee.
   
   - Mint + send your NFT data   
Mint your NFTs then send us the NFT data—metadata and imagery CIDs, blockchain(s) minted on, contract address and token IDs.

**Comment by elizabeth-griffiths** [comment]
Hi there - The new version of NFT.Storage requires images and metadata to be uploaded through a seperate service first. This is to ensure the sustainability of our model. NFT.Storage is a public good and is wasn't sustainable to continue to offer this as a service in it's current form. 

After you mint the NFT.Storage, you can go to app.nft.storage to upload the tokenIDs and CIDs to preserve them in NFT.Storage.
