### ISSUE TITLE
Where is NFT.UP?

### ISSUE THREAD

**Issue by jumpsteady2k** [nftstorage/nft.storage#2606]
Dear ladies and gentlemen,

I have just purchased additional 11 GB of space at nft.storage and I am looking for a way to upload my NFT images folder and receive a CID for it, that I can then enter into my JSON files. I was looking for NFT.UP but I cannot find this tool anymore. Is it out of service and which way can I use now to accomplish this?

Thank you.
Best regards,
Michael

**Comment by elizabeth-griffiths** [comment]
Hi Michael, 
The original NFT.Storage product (now called NFT.Storage) includes NFTUp. 
To align our services more closely with our community's needs and ensure the sustainability of our model, we're updating our service offerings. We'll continue to offer the current product under the name NFT.Storage Classic for existing uploads prior to 30 June 2024 , but no new uploads to the Classic product will be accepted as of 30 June 2024 at 5pm EST. New account registrations will no longer be accepted for:
The original NFT.Storage web app, API, and SDK
NFTUp
Pinning API

If you already have a classic.nft.storage account, get an API key from that login and download NFTUp here: https://github.com/nftstorage/nftup. Uploads to NFTUp are free.

If you do not have a classic.nft.storage account, you can use the new version of the product at https://app.nft.storage/.
For the new version, first mint your NFTs then send us the NFT data—metadata and imagery CIDs, blockchain(s) minted on, contract address and token IDs. We store these in long term Filecoin storage. Note that you need to upload the data to IPFS seperately, here's a blog on how to do that: https://nft.storage/blog/onboard-nft-data-to-ipfs
