### ISSUE TITLE
hello, how can I upload image and metadata json files to nft.storage using node.js?

### ISSUE THREAD

**Issue by Albertolischa** [nftstorage/nft.storage#2608]

**Comment by elizabeth-griffiths** [comment]
To use the new version of NFT.Storage first mint your NFTs then send us the NFT data—metadata and imagery CIDs, blockchain(s) minted on, contract address and token IDs. We store these in long term Filecoin storage. Note that you need to upload the data to IPFS seperately, here's a blog on how to do that: https://nft.storage/blog/onboard-nft-data-to-ipfs
