### ISSUE TITLE
change some images?

### ISSUE THREAD

**Issue by ceblo** [nftstorage/nft.storage#2610]
I have uploaded my images files to nft.storage. What if I want to change some images/delete some images and replace them with some new images?

**Comment by elizabeth-griffiths** [comment]
If you're using app.nft.storage (the new version of NFT.Storage) there is no way to change or delete images yet. 

If you're using classic.nft.storage. you can delete data from being associated with your account, and it will no longer appear on the Files page of your account. However, this doesn’t prevent nodes in the IPFS decentralized storage network from retaining copies of the data indefinitely. Do not use NFT.Storage for data that may need to be permanently deleted in the future.
