### ISSUE TITLE
Cannot upload the 12,000 data in nft.storage using the sugar for my auth token

### ISSUE THREAD

**Issue by asmitbhantana** [nftstorage/nft.storage#2612]
>> sugar upload 
[1/4] �  Loading assets
Found 5224 asset pair(s), uploading files:
+--------------------+
| images    |   5224 |
| metadata  |   5224 |
+--------------------+

[2/4] �  Initializing upload

� Error running command (re-run needed): Invalid nft.storage authentication token.

**Comment by asmitbhantana** [comment]
I am using the sugar-cli 2.6.0.

**Comment by elizabeth-griffiths** [comment]
It appears an API key from https://app.nft.storage/login
Is being used for
https://classic.nft.storage/ (the API, SDK or NFTUp).
API keys from https://app.nft.storage/login only work with https://app.nft.storage/login.
