### ISSUE TITLE
How to upload images and matadata json files on nft.storage

### ISSUE THREAD

**Issue by zeeshanhanif** [nftstorage/nft.storage#2614]
I have used NFT storage in past by uploading images in metadata. Now new interface only ask to upload file with TokenId and CId, but I wanted to know how to upload metadata files and images on NFT storage

**Comment by elizabeth-griffiths** [comment]
To align our services more closely with our community's needs and ensure the sustainability of our model, we're updating our service offerings. We'll continue to offer the current product under the name NFT.Storage Classic for existing uploads prior to 30 June 2024 , but no new uploads to the Classic product will be accepted as of 30 June 2024 at 5pm EST. New account registrations will no longer be accepted for:

- The original NFT.Storage web app at classic.nft.storage, API, and SDK
- NFTUp
- Pinning API

If you do not have a classic.nft.storage account, you can use the new version of the product at https://app.nft.storage/.

For the new version, first mint your NFTs then send us the NFT data—metadata and imagery CIDs, blockchain(s) minted on, contract address and token IDs. We store these in long term Filecoin storage. Note that you need to upload the data to IPFS seperately, here's a blog on how to do that: https://nft.storage/blog/onboard-nft-data-to-ipfs
