### ISSUE TITLE
uploading images

### ISSUE THREAD

**Issue by bakingsodalabs** [nftstorage/nft.storage#2615]
Hi- I bought 8GB of storage. However, I do not see how to upload images. Can you please provide explanation how I can upload images for storage?

**Comment by elizabeth-griffiths** [comment]
First mint your NFTs then send us the NFT data—metadata and imagery CIDs, blockchain(s) minted on, contract address and token IDs. We store these in long term Filecoin storage. Note that you need to upload the data to IPFS seperately, here's a blog on how to do that: https://nft.storage/blog/onboard-nft-data-to-ipfs
