### ISSUE TITLE
NFTUP "Error: storing files: API Key is malformed or failed to parse." 

### ISSUE THREAD

**Issue by Tommaso650** [nftstorage/nft.storage#2616]
Hi,
I'm trying to upload an image with nftup for windows, but everytime I paste the API it show me this error "Error: storing files: API Key is malformed or failed to parse."
I tried to create new API keys, to disinstall e install again nftup but it doesn't work.
I've also got 1 GB of storage but again nothing.
Can you help me please? 
Thank you

**Comment by elizabeth-griffiths** [comment]
The original NFT.Storage product (now called NFT.Storage Classic) includes NFTUp. 

To align our services more closely with our community's needs and ensure the sustainability of our model, we're updating our service offerings. We'll continue to offer the current product under the name NFT.Storage Classic for existing uploads prior to 30 June 2024 , but no new uploads to the Classic product will be accepted as of 30 June 2024 at 5pm EST. New account registrations will no longer be accepted for:

- The original NFT.Storage web app, API, and SDK
- NFTUp
- Pinning API

If you already have a classic.nft.storage account, get an API key from that login and download NFTUp here: https://github.com/nftstorage/nftup. Uploads to NFTUp are free.

If you do not have a classic.nft.storage account, you can use the new version of the product at https://app.nft.storage/.
For the new version, first mint your NFTs then send us the NFT data—metadata and imagery CIDs, blockchain(s) minted on, contract address and token IDs. We store these in long term Filecoin storage. Note that you need to upload the data to IPFS separately, here's a blog on how to do that: https://nft.storage/blog/onboard-nft-data-to-ipfs
