### ISSUE TITLE
NFTStorage not properly propagating through IPFS

### ISSUE THREAD

**Issue by agsola** [nftstorage/nft.storage#2617]
We are having issues with the propagation of IPFS content uploaded through NFTStorage, for instance, this image:
https://bafybeietyfhxm7i6tx54ul33h5l7o6v5sjmklordfgbrbchwnl72snrjz4.ipfs.nftstorage.link/1107.webp

Can not be seen in the "official" gateway: 
- https://ipfs.io/ipfs/bafybeietyfhxm7i6tx54ul33h5l7o6v5sjmklordfgbrbchwnl72snrjz4/1107.webp
![image](https://github.com/nftstorage/nft.storage/assets/472079/30757b42-a7b2-481f-a612-4a87db8cde2f)

We've been trying for over 24 hours with no success.

**Comment by elizabeth-griffiths** [comment]
Hi there - We don't have any control over the performance of ipfs.io. We recommend reaching out to the IPFS team about that. 
If you go to https://nftstorage.link/ipfs/bafybeietyfhxm7i6tx54ul33h5l7o6v5sjmklordfgbrbchwnl72snrjz4
the CID appears as expected.
