### ISSUE TITLE
 API Key is not working.

### ISSUE THREAD

**Issue by haemil-developer** [nftstorage/nft.storage#2618]
https://github.com/nftstorage/nft.storage/assets/141383581/5b4a6655-6886-47d1-81a4-5746ed9dc14a

Hi.
I'm using your service.
I have paid 1GB.
then get API Key you give me through the Generate Key button.
But I keep get same error message "API Key is malformed "
please tell me what should I do.
Thank you.

**Comment by elizabeth-griffiths** [comment]
The original NFT.Storage product (now called NFT.Storage Classic) includes NFTUp. 

To align our services more closely with our community's needs and ensure the sustainability of our model, we're updating our service offerings. We'll continue to offer the current product under the name NFT.Storage Classic for existing uploads prior to 30 June 2024 , but no new uploads to the Classic product will be accepted as of 30 June 2024 at 5pm EST. New account registrations will no longer be accepted for:

- The original NFT.Storage web app, API, and SDK
- NFTUp
- Pinning API

If you already have a classic.nft.storage account, get an API key from that login and download NFTUp here: https://github.com/nftstorage/nftup. Uploads to NFTUp are free.

If you do not have a classic.nft.storage account, you can use the new version of the product at https://app.nft.storage/. (This is where you bought the 1GB of data) 

For the new version, first mint your NFTs then send us the NFT data—metadata and imagery CIDs, blockchain(s) minted on, contract address and token IDs. We store these in long term Filecoin storage. Note that you need to upload the data to IPFS separately, here's a blog on how to do that: https://nft.storage/blog/onboard-nft-data-to-ipfs
