### ISSUE TITLE
Does NFTUp still exist

### ISSUE THREAD

**Issue by sucharok123** [nftstorage/nft.storage#2619]
I'd like to upload NFTs to get their CID, what mechanism can i use.

**Comment by elizabeth-griffiths** [comment]
The original NFT.Storage product (now called NFT.Storage Classic) includes NFTUp. 

To align our services more closely with our community's needs and ensure the sustainability of our model, we're updating our service offerings. We'll continue to offer the current product under the name NFT.Storage Classic for existing uploads prior to 30 June 2024 , but no new uploads to the Classic product will be accepted as of 30 June 2024 at 5pm EST. New account registrations will no longer be accepted for:
The original NFT.Storage web app, API, and SDK
NFTUp
Pinning API

If you already have a classic.nft.storage account, get an API key from that login and download NFTUp here: https://github.com/nftstorage/nftup. Uploads to NFTUp are free.

If you do not have a classic.nft.storage account, you can use the new version of the product at https://app.nft.storage/.
For the new version, first mint your NFTs then send us the NFT data—metadata and imagery CIDs, blockchain(s) minted on, contract address and token IDs. We store these in long term Filecoin storage. Note that you need to upload the data to IPFS seperately, here's a blog on how to do that: https://nft.storage/blog/onboard-nft-data-to-ipfs

**Comment by sucharok123** [comment]
Dear Elizabeth,

Please can you refund my 2.99 USD. I paid under the impression that I could
use your app for creating the API keys and all the relevant IDs, as the
documentation to the old version is all over the internet.

Much appreciated, let me know if you need more information about my account
for the refund.

Best wishes,
Kate
