### ISSUE TITLE
bafybeieojvuqke4vamdc43bzz7bv4amniqqpbshocftx2cwnkbscb7smma

### ISSUE THREAD

**Issue by KIRKNFT** [nftstorage/nft.storage#2620]
Is the above subject CID still stored? All of my NFT collection images have disappeared.

I set up the smart contract using the CID bafybeihqha5526lbjcl5mxd3zxerh5wx26ebk7euhp5rzedu42z7uf36ri, which looks to have storage providers. However CID bafybeieojvuqke4vamdc43bzz7bv4amniqqpbshocftx2cwnkbscb7smma has the status as "Queueing"

**Comment by KIRKNFT** [comment]
I am happy to pay for storage if needed to get the images back online. 
I also cannot sign into the new NFT storage platform, as my original login was via email not github.

**Comment by KIRKNFT** [comment]
The original files were uploaded to the old NFT storage site, but this was done via email, how do I transfer this account to the new site?

**Comment by elizabeth-griffiths** [comment]
Hi there - I replied to your email to support: 

Hi there, 
I can confirm that both the CIDs referenced in your originally email are safely stored in NFT.Storage Classic:  
bafybeihqha5526lbjcl5mxd3zxerh5wx26ebk7euhp5rzedu42z7uf36ri\
 bafybeieojvuqke4vamdc43bzz7bv4amniqqpbshocftx2cwnkbscb7smma

As long as the image appears at nftstorage.link/ipfs/{cid} your good to go, which both of these are.

What URL are you using to have the image populating? If you use nftstorage.link/ipfs/{cid} it should work fine.

Let me know if you have any other questions.

Many thanks,
Elizabeth
