### ISSUE TITLE
All files from the account have been deleted. Can you clarify the situation?

### ISSUE THREAD

**Issue by TokenPort** [nftstorage/nft.storage#2621]
Today we discovered that all files from our account have disappeared. What happened?

**Comment by elizabeth-griffiths** [comment]
We haven't deleted any files. Can you log into your NFT.Storage and confirm
if you can still see the list of files?

It's possible that the referring website was blocked if it was mistakenly
flagged as using NfT.Storage for non NFT data. What is the website?

**Comment by TokenPort** [comment]
https://beta.xport.app/collections/XBLOCK-1HDW/

**Comment by TokenPort** [comment]
<img width="1074" alt="Снимок экрана 2024-05-04 в 12 49 27" src="https://github.com/nftstorage/nft.storage/assets/54212279/4719ed2f-39d6-4712-b4ae-41601d5c41b2">

**Comment by TokenPort** [comment]
The data array was available at this link and at links in the image-related JSON
https://bafybeia34htwietk4jkzgsmznr3sp37fsupgy2hfakk5yyhvsizujt7ega.ipfs.dweb.link

**Comment by TokenPort** [comment]
Are there any restrictions for this website
https://beta.xport.app/"

**Comment by TokenPort** [comment]
Can I get an answer?

**Comment by elizabeth-griffiths** [comment]
Hi there- We will look into this and get back to you asap today.

**Comment by elizabeth-griffiths** [comment]
Hi there - 
We have not deleted any NFT.Storage accounts. Got to classic.nft.storage and all of your data will be in your login there. 

Regarding the change from classic.nft.storage to the new version, you should have received an email that included this: 
To align our services more closely with our community's needs and ensure the sustainability of our model, we're updating our service offerings. We'll continue to offer the current product under the name NFT.Storage Classic for existing uploads prior to 30 June 2024 , but no new uploads to the Classic product will be accepted as of 30 June 2024 at 5pm EST. New account registrations will no longer be accepted for:
The original NFT.Storage web app, API, and SDK
NFTUp
Pinning API

Regarding the issues with your data: 

- I can confirm there is not a block on https://beta.xport.app/
- Additionally, the CID bafybeia34htwietk4jkzgsmznr3sp37fsupgy2hfakk5yyhvsizujt7ega loads fine. Try it here: nftstorage.link/ipfs/bafybeia34htwietk4jkzgsmznr3sp37fsupgy2hfakk5yyhvsizujt7ega

If you're still experiencing problems with data loading it is possible that our system has identified content you uploaded as non-NFT data. Any data that is uploaded to NFT.Storage that is not off-chain NFT data does not comply with our terms and conditions. 

If you believe your data should be unblocked, please send us more detailed information about what specifically is blocked, and information about the NFTs and where they are minted, ie. the contract ID.
