### ISSUE TITLE
Cloudflare messing with Cross Origin in SolScan and metadata is not showing up

### ISSUE THREAD

**Issue by fuckNftStorage** [nftstorage/nft.storage#2622]
what the fuck did you guys do, the cloudflare shit is fucking with the cross origin in solscan and the logo and metadata aint showing up there on solscan any more, fix this shit soon or we have to look for alternatives

**Comment by elizabeth-griffiths** [comment]
Hi there,

Firstly, this language is not tolerated. If it continues we will not
respond.

Please send us more information.

What isn't showing up? We need more information to triage this.

Specific CIDs?


You mentioned a logo, please send the information for that.

NFT.Storage is only for off chain NFT data, so any data that is not off
chain NFT data (for example , a logo on a website) will remain blocked.

**Comment by fuckNftStorage** [comment]
Snowflake, looks like you have no idea of what you do there. Tell your boss they will understand. It's very high priority and people have already started to stop using nftstorage

SolScan cannot read metadata from nftstorage because you guys decided to add cloudflare like a true retard. I doubt you even know what SolScan is.

The entire point of nsftstorage is such that other websites can read the image from the metadata, if it remains blocked why would people even use it

**Comment by elizabeth-griffiths** [comment]
This should be resolved now.
