### ISSUE TITLE
Blocked on cloudflare

### ISSUE THREAD

**Issue by somy477** [nftstorage/nft.storage#2623]
I was blocked on cloudflare when trying to download oex app from ipfs. 
I was asked to contact the owners of the website to get unblocked.
Please can you rectify the issue for been blocked and unblock me as soon as possible 
Thanks

**Comment by elizabeth-griffiths** [comment]
Hi there,

Can you please explain further? What happens when you try to download the
app?

NFT.Storage is only for NFTs so we wouldn't block an entire app, unless the
app is using NFT.Storage for non NFT data, in which case the data will
remain blocked.

**Comment by elizabeth-griffiths** [comment]
This should be resolved now.

**Comment by Danielekpat001** [comment]
Hi team..
I was blocked on cloud fare during the process of downloading OEX app through the provide link
