### ISSUE TITLE
Confusing new pricing

### ISSUE THREAD

**Issue by gregorym** [nftstorage/nft.storage#2624]
Hi,

I am looking at your new pricing and it is very confusing. it feels backward.

If I understand correctly, we need to have a smart-contract deployed and all the data already stored on IPFS in order to have NFT Storage to pin the files? Is that correct?

Is it not possible to upload files and have them stored in IPFS anymore?

**Comment by elizabeth-griffiths** [comment]
For the new version, first mint your NFTs then send us the NFT data—metadata and imagery CIDs, blockchain(s) minted on, contract address and token IDs. We store these in long term Filecoin storage to preserve your NFT data. Note that you need to upload the data to IPFS separately, here's a blog on how to do that: https://nft.storage/blog/onboard-nft-data-to-ipfs
