### ISSUE TITLE
i cant upload my HTML file

### ISSUE THREAD

**Issue by kenmitchell616** [nftstorage/nft.storage#2627]
Please i cant seems to upload my html file

**Comment by elizabeth-griffiths** [comment]
Hi there - To use the new version of NFT.Storage at app.nft.storage, first mint your NFTs then send us the NFT data—metadata and imagery CIDs, blockchain(s) minted on, contract address and token IDs. We store these in long term Filecoin storage. Note that you need to upload the data to IPFS separately, here's a blog on how to do that: https://nft.storage/blog/onboard-nft-data-to-ipfs
