### ISSUE TITLE
how to use the classic login page

### ISSUE THREAD

**Issue by actmon** [nftstorage/nft.storage#2630]
Dear team,

kindly share information on how i can login through the classic platform. each time i log on or sign up it returns back to the same sign in or sign up.

Thank you

**Comment by elizabeth-griffiths** [comment]
To align our services more closely with our community's needs and ensure the sustainability of our model, we're updating our service offerings. We'll continue to offer the current product under the name NFT.Storage Classic for existing uploads prior to 30 June 2024 , but no new uploads to the Classic product will be accepted as of 30 June 2024 at 5pm EST. New account registrations will no longer be accepted for:
The original NFT.Storage web app at classic.nft.storage, API, and SDK
NFTUp
Pinning API

If you do not have a classic.nft.storage account, you can use the new version of the product at https://app.nft.storage/.

For the new version, first mint your NFTs then send us the NFT data—metadata and imagery CIDs, blockchain(s) minted on, contract address and token IDs. We store these in long term Filecoin storage. Note that you need to upload the data to IPFS seperately, here's a blog on how to do that: https://nft.storage/blog/onboard-nft-data-to-ipfs
