### ISSUE TITLE
Mintpad storage partnership

### ISSUE THREAD

**Issue by ImmutableLevans** [nftstorage/nft.storage#2636]
Hi there, I work for an NFT Launchpad tool called Mintpad, and we wanted to discuss a much more detailed and sizeable partnership with the team and NFT.Storage if possible!

We would like to use your storage services, and will be using it for large amount of storage continuously, so we we're hoping to discuss some sort of package/deal with you guys.

Either reply here or even better, message me on TG if possible? My handle is immutablelevans. I hope to hear from you soon!

**Comment by elizabeth-griffiths** [comment]
Messaged you on TG. Thanks for reaching out!
