### ISSUE TITLE
Upload Error

### ISSUE THREAD

**Issue by GEquals** [nftstorage/nft.storage#2637]
Hi I am trying to upload a .json metadata file but keep getting a red X error and nothing uploads, the contract will be on Ethereum Blast, can you help?

Or is there any other way for me to upload my collection

**Comment by elizabeth-griffiths** [comment]
To add your data to app.nft.storage, first mint your NFTs then send us the NFT data—metadata and imagery CIDs, blockchain(s) minted on, contract address and token IDs. We store these in long term Filecoin storage. Note that you need to upload the data to IPFS separately, here's a blog on how to do that: https://nft.storage/blog/onboard-nft-data-to-ipfs
