### ISSUE TITLE
API Key is not working

### ISSUE THREAD

**Issue by felipecalixtoreis** [nftstorage/nft.storage#2642]
I tried to run this command to test the API generated on the website, but it is not working.
Is the website down?
curl -X POST -H "Authorization: Bearer my API KEY" -H "Content-Type: application/json" -d '{"name":"Test"}' https://api.nft.storage/upload
{"ok":false,"error":{"code":"ERROR_MALFORMED_TOKEN","message":"API Key is malformed or failed to parse."}}

Could you help?

**Comment by elizabeth-griffiths** [comment]
"API Key is malformed or failed to parse" is because
an API key from https://app.nft.storage/login
Is being used for
https://classic.nft.storage/ (the API, SDK or NFTUp).
API keys from https://app.nft.storage/login only work with https://app.nft.storage/login.
