### ISSUE TITLE
XRP-NFTs

### ISSUE THREAD

**Issue by billian** [nftstorage/nft.storage#2643]
Hi,
I understand you will be implementing facilities to upload XRP-NFTs soon,
do you have any update on the status of this please,
I am a paid account holder & awaiting patiently,
many thanks
paym8

**Comment by elizabeth-griffiths** [comment]
Hi there - Thanks for following up. This is going into the next sprint. We need your help defining the requirements. 
What is the difference between the "Issuer & Owner" and "Minter"? Which is more relevant for us to capture?

**Comment by billian** [comment]
thanks for followup, I have replied via your email a more comprehensive detailed respose.
