### ISSUE TITLE
How to use your new site? -- from a customer of old nft.stroage

### ISSUE THREAD

**Issue by klclee** [nftstorage/nft.storage#2644]
Hi there I have brought some storage, generate the api key. Then using the same way I use to for creating a ipfs links (with the new api key) as per this example:

https://github.com/nftstorage/nft.storage/blob/main/examples/client/node.js/store.js

I am getting the following error:

```
node_modules/nft.storage/src/lib.js:227
                throw new AbortError(result.error.message)
                      ^
Error
    at pRetry__default.default.retries (/Users/charlie/code/editionone/odessy-chain-admin/node_modules/nft.storage/src/lib.js:227:23)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async RetryOperation._fn (/Users/charlie/code/editionone/odessy-chain-admin/node_modules/p-retry/index.js:50:12)
    
 ```
 

Is there a new way to upload now? 

I found this in your docs https://app.nft.storage/v1/docs/client/http-api

But i am not sure thats the way as there is no direction to upload the metadata and image together.

thanks

**Comment by elizabeth-griffiths** [comment]
For the new version, first mint your NFTs then send us the NFT data—metadata and imagery CIDs, blockchain(s) minted on, contract address and token IDs. We store these in long term Filecoin storage. Note that you need to upload the data to IPFS separately, here's a blog on how to do that: https://nft.storage/blog/onboard-nft-data-to-ipfs
