### ISSUE TITLE
403s when reading json programatically

### ISSUE THREAD

**Issue by joefitter** [nftstorage/nft.storage#2645]
Hi, I run a web3 software company specialising in digital assets, mainly on Solana.

Recently we've been receiving increasing bug reports from users who are unable to view/update their assets if the json is hosted using nft.storage. The errors we are getting are 403: Forbidden

Did you guys implement Cloudflare anti scraping? And if so what's the workaround for simply loading in a single NFT's JSON hosted using your platform?

**Comment by elizabeth-griffiths** [comment]
There was a temporary hardware failure on our vendor's side. All systems are operational again, 403s this shouldn't be an issue anymore.

Regarding anti-scraping: 

NFT.Storage has always had rate limits. Recently, we have enabled some additional Cloudflare features such as Challenges on specific referrer URLs, paths, and CIDs.

NFT.Storage is a public good, and as of April 2024, we are an independent entity. The actions we've taken recently are mitigation strategies to ensure we can continue to fund the NFT.Storage Gateway.

We appreciate your understanding and support as we navigate these challenges and work towards sustainable solutions for the NFT.Storage platform.
