### ISSUE TITLE
Trying to create/upload with API key, need help with the flow.

### ISSUE THREAD

**Issue by zombitsu** [nftstorage/nft.storage#2646]
We've been using the classic platform previously, and it was pretty simple to get a new CID inline. With the new methods, it seems we cannot follow this same flow.

We need to create the collection, and then use a CID/TokenID combination.

We are working primarily with Hedera Hashgraph.

Is there more verbose documentation anywhere?

**Comment by zombitsu** [comment]
I suppose the main difference is it seems we dont' upload the media through your API anymore.

**Comment by elizabeth-griffiths** [comment]
That's correct. For the new version, first mint your NFTs then send us the NFT data—metadata and imagery CIDs, blockchain(s) minted on, contract address and token IDs. We store these in long term Filecoin storage. Note that you need to upload the data to IPFS separately, here's a blog on how to do that: https://nft.storage/blog/onboard-nft-data-to-ipfs
