### ISSUE TITLE
I AM UNABLE TO SIGNUP CLASSIC NFT STORAGE

### ISSUE THREAD

**Issue by ynohtna1** [nftstorage/nft.storage#2647]
Hello, My email is dbryne634@gmail.com i'm unable to signin classic.nft.storage as i have signup and tried logging in through github and also via my email but i do not seem to gain access. Kindly help.

**Comment by elizabeth-griffiths** [comment]
To align our services more closely with our community's needs and ensure the sustainability of our model, we're updating our service offerings. We'll continue to offer the current product under the name NFT.Storage Classic for existing uploads prior to 30 June 2024 , but no new uploads to the Classic product will be accepted as of 30 June 2024 at 5pm EST. **New account registrations will no longer be accepted for:
The original NFT.Storage web app at classic.nft.storage, API, and SDK
NFTUp
Pinning API**

If you do not have a classic.nft.storage account, you can use the new version of the product at https://app.nft.storage/.

For the new version, first mint your NFTs then send us the NFT data—metadata and imagery CIDs, blockchain(s) minted on, contract address and token IDs. We store these in long term Filecoin storage. Note that you need to upload the data to IPFS separately, here's a blog on how to do that: https://nft.storage/blog/onboard-nft-data-to-ipfs
