### ISSUE TITLE
Query about low one-time fee for endowment-backed long-term storage

### ISSUE THREAD

**Issue by ashishnair-zil** [nftstorage/nft.storage#2649]
I am an existing user with assets stored on the classic (free) version of NFT.Storage. With the new release, how will this affect me, and what changes do I need to make to support both my existing and new uploads?

**Comment by elizabeth-griffiths** [comment]
What’s Changing:
To align our services more closely with our community's needs and ensure the sustainability of our model, we're updating our service offerings. We'll continue to offer the current product under the name NFT.Storage Classic for existing uploads prior to 30 June 2024 , but no new uploads to the Classic product will be accepted as of 30 June 2024 at 5pm EST. New account registrations will no longer be accepted for:

- The original NFT.Storage web app, API, and SDK
- NFTUp
- Pinning API

Your benefits as an existing account holder:

- Continue to upload off-chain NFT data using the current products through 30 June 2024, at 5 PM EST
- Maintain access to your links through the NFT.Storage Gateway at https://nftstorage.link/ipfs/{CID} 
- All NFT data you’ve already uploaded and will upload before 30 June 2024, will continue to be safely stored and accessible via IPFS and in the Filecoin Network's long-term storage, though over time latency and availability may degrade.

Planning for the Transition:
This transition is a crucial step towards reinforcing NFT.Storage as a public good, aiming to ensure we can continue to provide a sustainable service. Starting now:

- We're here to assist you in finding the best decentralized IPFS upload solution for your needs. Check our resources below for guidance
- Consider adding additional IPFS hosts to mirror your content from NFT.Storage for improved performance
- Bookmark classic.nft.storage for continued access to upload NFT data to the original platform


What’s Next:

- Evolution of NFT.Storage: Dive into the expanded capabilities and services of the new NFT.Storage platform. Note: A new account creation will be required
- Support NFT.Storage: By joining the NFT.Storage DAO, you can play a crucial role in helping shape the future of NFT.Storage. Your support directly contributes to the platform's growth and sustainability.

Helpful Resources:

- [Read our blog our exploring IPFS upload options](https://nft.storage/blog/onboard-nft-data-to-ipfs)
- [Learn more about the Future of NFT.Storage](https://nft.storage/blog/the-next-chapter-of-nftstorage)
- [Bookmark the link to access the original NFT.Storage web app](https://classic.nft.storage/login/)
- Need More Information?
