### ISSUE TITLE
I am trying to use the API key and it tells me is wrong

### ISSUE THREAD

**Issue by hydraerozine** [nftstorage/nft.storage#2650]
I am trying to use the API key and it tells me is wrong

import axios from 'axios';
import dotenv from 'dotenv';
import fs from 'fs';
import FormData from 'form-data';
import path from 'path';

dotenv.config();

const API_KEY = process.env.NFT_STORAGE_API_KEY;
const API_BASE_URL = 'https://preserve.nft.storage/api/v1';

// Debug: Print API Key to ensure it's being read correctly
console.log('Using API Key:', API_KEY);

async function createCollection(contractAddress, collectionName = 'MyCollection', chainID = '1', network = 'mainnet') {
    const url = `${API_BASE_URL}/collection/create_collection`;
    const data = {
        contractAddress,
        collectionName,
        chainID,
        network,
    };

    try {
        const response = await axios.post(url, data, {
            headers: {
                'Authorization': `Bearer ${API_KEY}`,
                'Content-Type': 'application/json',
            },
        });

        console.log(`Collection Created: ${JSON.stringify(response.data)}`); // Debug: Print full response
        return response.data.value.collectionID; // Correctly access the collectionID
    } catch (error) {
        console.error('Error creating collection:', error.response ? error.response.data : error.message);
        throw new Error('Failed to create collection.');
    }
}

async function uploadToIPFS(filePath, contentType = 'application/octet-stream') {
    const url = 'https://api.nft.storage/upload';
    const formData = new FormData();
    formData.append('file', fs.createReadStream(filePath));

    try {
        const response = await axios.post(url, formData, {
            headers: {
                ...formData.getHeaders(),
                'Authorization': `Bearer ${API_KEY}`,
            },
        });

        const { cid } = response.data;
        const ipfsUrl = `https://ipfs.io/ipfs/${cid}`;
        console.log(`File uploaded to IPFS: ${ipfsUrl}`);
        return { cid, ipfsUrl };
    } catch (error) {
        console.error('Error uploading to IPFS:', error.response ? error.response.data : error.message);
        throw new Error('Failed to upload to IPFS.');
    }
}

async function uploadMetadataToIPFS(metadata) {
    const metadataFilePath = './metadata.json';
    fs.writeFileSync(metadataFilePath, JSON.stringify(metadata));
    const { ipfsUrl: metadataIPFSUrl, cid: metadataCID } = await uploadToIPFS(metadataFilePath, 'application/json');
    fs.unlinkSync(metadataFilePath); // Clean up by removing the temporary file
    return { metadataIPFSUrl, metadataCID };
}

async function addTokensToCollection(collectionID, tokens) {
    const url = `${API_BASE_URL}/collection/add_tokens`;
    const csvContent = tokens.map(token => `${token.tokenID},${token.cid}`).join('\n');
    const csvFilePath = './tokens.csv';
    fs.writeFileSync(csvFilePath, csvContent);

    const formData = new FormData();
    formData.append('collectionID', collectionID);
    formData.append('file', fs.createReadStream(csvFilePath));

    try {
        const response = await axios.post(url, formData, {
            headers: {
                ...formData.getHeaders(),
                'Authorization': `Bearer ${API_KEY}`,
            },
        });

        console.log('Tokens added:', response.data);
        fs.unlinkSync(csvFilePath); // Clean up by removing the temporary file
    } catch (error) {
        console.error('Error adding tokens to collection:', error.response ? error.response.data : error.message);
        throw new Error('Failed to add tokens to collection.');
    }
}

async function main() {
    const contractAddress = '0xBA4c63867E04d691B9754a6b4d1d3a2ed5eFc7FB';
    const collectionName = 'Solar Planetary Alliance Passports';
    const chainID = '1'; // Ethereum mainnet
    const network = 'mainnet';

    try {
        // Step 1: Create Collection
        const collectionID = await createCollection(contractAddress, collectionName, chainID, network);
        console.log(`Successfully created collection with ID: ${collectionID}`);

        // Step 2: Upload Image to IPFS
        const imagePath = './passportSPA.png';
        const { ipfsUrl: ipfsImageUrl } = await uploadToIPFS(imagePath, 'image/png');
        console.log(`Successfully uploaded image to IPFS: ${ipfsImageUrl}`);

        // Step 3: Define Metadata and Upload to IPFS
        const metadata = {
            name: "Solar Planetary Alliance Passport",
            description: "Passport granted for citizen to be able to travel across planets.",
            image: ipfsImageUrl,
            attributes: [
                { trait_type: "Country", value: "USA" },
                { trait_type: "Planet", value: "Earth" },
                { trait_type: "Identity", value: "Human" },
                { trait_type: "Chain ID", value: "BSC" },
                { trait_type: "Credit Score", value: 0 },
                { trait_type: "Clan Tag", value: "none" },
                { trait_type: "Voting Score", value: 0 },
                { trait_type: "Social", value: "telegram tbd" }
            ]
        };

        const { metadataCID } = await uploadMetadataToIPFS(metadata);
        console.log(`Successfully uploaded metadata to IPFS with CID: ${metadataCID}`);

        // Step 4: Add Tokens to Collection
        const tokens = [{ tokenID: 1, cid: metadataCID }];
        await addTokensToCollection(collectionID, tokens);
        console.log('Tokens successfully added to collection.');
    } catch (error) {
        console.error(error);
    }
}

main();

**Comment by elizabeth-griffiths** [comment]
Can you confirm that you're using an API key from app.nft.storage?

**Comment by elizabeth-griffiths** [comment]
I'm closing this since we haven't heard back. Please re-open if needed.
