### ISSUE TITLE
(Urgent) Metadata not uploading

### ISSUE THREAD

**Issue by oharukaaa** [nftstorage/nft.storage#2651]
Hello, we airdropped yesterday and starting our public sale in two hours, but majority of the collection's metadata isnt updating yet. It's been more than 12 hours now, so I think something is stopping it on NFT Storge's end.

Opensea: https://opensea.io/collection/sinka-live-series-ep-v

Here our the CID info:

API Key
eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkaWQ6ZXRocjoweDIxMzc1MkFENjYzNDQ0MjE4MDY5NjkwMUQ4MDE0NkE4RmRjY0I2QTAiLCJpc3MiOiJuZnQtc3RvcmFnZSIsImlhdCI6MTcxNjMzNjI5NjYyOSwibmFtZSI6InlveW9naSJ9.KvC3tWhCLny2J3JDdDoEkvYCybbKslwihdWnxIVVWEA

MP4
CID
bafybeihv6w3ynvsgw4gl3pe6w34wzeshtwqds7ix2llydvjx2tes3as3ra
IPFS URL
ipfs://bafybeihv6w3ynvsgw4gl3pe6w34wzeshtwqds7ix2llydvjx2tes3as3ra
Gateway URL
https://nftstorage.link/ipfs/bafybeihv6w3ynvsgw4gl3pe6w34wzeshtwqds7ix2llydvjx2tes3as3ra

jpg
CID
bafybeie5eyfdwycoa3dlwjnn66hynqgircteayrzcjmjct6vcgfn6fjlie
IPFS URL
ipfs://bafybeie5eyfdwycoa3dlwjnn66hynqgircteayrzcjmjct6vcgfn6fjlie
Gateway URL
https://nftstorage.link/ipfs/bafybeie5eyfdwycoa3dlwjnn66hynqgircteayrzcjmjct6vcgfn6fjlie

Metadata
CID: bafybeiet43pykj63lqhao7t7gzfbnq5yujinthez4gfikdycoqft7owr4i 

We are using heymint to airdrop and mint (Just fyi)
https://launchpad.heymint.xyz/projects/28946/721/contract/general

**Comment by elizabeth-griffiths** [comment]
It looks to me like the images are loading from the NFT.Storage Gateway fine. If there is still an issue please re-open the ticket. Thanks!

**Comment by oharukaaa** [comment]
Hi Elizabeth, there are suppose to be images and video (mp4). Were you able to confirm both is loading correctly? It's been days now and we still see "content not available" for majority of the collection and our client would like to know what is causing the delay. Thank you.

**Comment by oharukaaa** [comment]
Hi Elizabeth, there are suppose to be images and video (mp4). Were you able
to confirm both is loading correctly? It's been days now and we still see
"content not available" for majority of the collection and our client would
like to know what is causing the delay. Thank you.
