### ISSUE TITLE
Old NFT Storage 

### ISSUE THREAD

**Issue by Futurity-Galaxies** [nftstorage/nft.storage#2652]
Hello, 

I set up an NFT collection using your old NFT storage site. With the recent change, I made a new account and will start working through there. However, my NFT collection I minted using your old method is not showing images on the marketplace. Do I need to convert everything and move it to my new NFT storage account? If so, what does this process look like? And if I can't move my old collection over, what is the solution? 

Thank you for your help, 

-Samantha

**Comment by elizabeth-griffiths** [comment]
Hi Samantha, 

You do not need to migrate - there's likely another issue at play here. 

Can you view the CIDs at all? 
Try going to nftstorage.link/ipfs/{enter CID} . Does that work? 
If so, its likely an issue with the marketplace, not your CIDs.

**Comment by elizabeth-griffiths** [comment]
Hi there - I'm going to close this since we haven't heard back. Please reopen it if you're still having issues
