### ISSUE TITLE
Detailed error information: API Key is malformed or failed to parse.

### ISSUE THREAD

**Issue by 0xbilly** [nftstorage/nft.storage#2653]
Hi, the issue is that I keep getting this error I tried different API and its all the same what can be the issue?

**Comment by elizabeth-griffiths** [comment]
"API Key is malformed or failed to parse" is because
an API key from https://app.nft.storage/login
Is being used for
https://classic.nft.storage/ (the API, SDK or NFTUp).
API keys from https://app.nft.storage/login only work with https://app.nft.storage/login.

**Comment by 0xbilly** [comment]
So how can I get a unique API key?

**Comment by TheFlexLab** [comment]
@0xbilly @elizabeth-griffiths  Issue resolved?
