### ISSUE TITLE
How do I use the pinning service with existing CID, without uploading to mainnet?

### ISSUE THREAD

**Issue by startyNFT** [nftstorage/nft.storage#2654]
Hello,

I uploaded my files using NFT Classic. My collection will be on Stargaze (stargaze.zone).

They have not been pinned yet - to make them available faster, **I'd like to use your pinning service.**
However, when I go to the new page, it requests a contract address - which is not ideal in this case since I'm first testing on testnet.
I dont want to upload to mainnet before verifying the rarity and everything on testnet, and that I can only do once the tokens show up on the indexer - and for that, it needs to be pinned.
Anyways, I submit with a testnet contract address. However it says that the 10k were unable to be uploaded: "10000 tokens rejected due to invalid CID or tokenID."

This is how the file is:

TokenID | CID
-- | --
1 | ipfs:///bafyb...d2beral4k6vxvycra/1
2 | ipfs:///bafyb...d2beral4k6vxvycra/2
3 | ipfs:///bafyb...d2beral4k6vxvycra/3
4 | ipfs:///bafyb...d2beral4k6vxvycra/4
5 | ipfs:///bafyb...d2beral4k6vxvycra/5

Can you point out what I am doing wrong here?

If the CID needs to be the actual CID (individual for each token), I'm afraid I wouldn't be able to even request that, as it will be a humongous work to figure out. thanks.

**Comment by elizabeth-griffiths** [comment]
NFT.Storage Classic is the pinning service. 

To align our services more closely with our community's needs and ensure the sustainability of our model, we're updating our service offerings. We'll continue to offer classic.nft.sotrage under the name NFT.Storage Classic for existing uploads prior to 30 June 2024 , but no new uploads to the Classic product will be accepted as of 30 June 2024 at 5pm EST. New account registrations will no longer be accepted for:
The original NFT.Storage web app at classic.nft.storage, API, and SDK
NFTUp
Pinning API

If you do not have a classic.nft.storage account, you can use the new version of the product at https://app.nft.storage/. I believe this is what you're using.

For the new version, first mint your NFTs then send us the NFT data—metadata and imagery CIDs, blockchain(s) minted on, contract address and token IDs. We store these in long term Filecoin storage. Note that you need to upload the data to IPFS separately, here's a blog on how to do that: https://nft.storage/blog/onboard-nft-data-to-ipfs
