### ISSUE TITLE
Modify email to log in

### ISSUE THREAD

**Issue by gigiflower** [nftstorage/nft.storage#2655]
I was using Skiff mail to log in NFT storage, where I uploaded my NFTs.
However, Skiff mail is shutting down their services, which means I won't be able to log in my NFT storage account anymore. 
Is there a way for me to update my account with a new email address?
Thanks!

**Comment by elizabeth-griffiths** [comment]
Hi there - Can you please clarify if you're using classic.nft.storage, app.nft.storage or both? 

When is Skiff shutting down their service?

**Comment by gigiflower** [comment]
Hey, thank you for your reply!
I'm using classic.nft.storage, and Skiff is shutting down their service, I believe, in August or around that time.

**Comment by elizabeth-griffiths** [comment]
Ok, I think the timing aligns with some changes to NFT.Storage Classic. In case you didn't see...
To align our services more closely with our community's needs and ensure the sustainability of our model, we're updating our service offerings. We'll continue to offer the current product under the name NFT.Storage Classic for existing uploads prior to 30 June 2024 , but no new uploads to the Classic product will be accepted as of 30 June 2024 at 5pm EST. New account registrations will no longer be accepted for:
The original NFT.Storage web app at classic.nft.storage, API, and SDK
NFTUp
Pinning API

If you do not have a classic.nft.storage account, you can use the new version of the product at https://app.nft.storage/.

For the new version, first mint your NFTs then send us the NFT data—metadata and imagery CIDs, blockchain(s) minted on, contract address and token IDs. We store these in long term Filecoin storage. Note that you need to upload the data to IPFS separately, here's a blog on how to do that: https://nft.storage/blog/onboard-nft-data-to-ipfs
