### ISSUE TITLE
The new NFT storage do not allow for storing arbitrary blobs

### ISSUE THREAD

**Issue by lughino** [nftstorage/nft.storage#2660]
Until the new change I was able to store images (or other content) of my NFT and arbitrary metadata via this tool.
Now, **there is no possibility to do that**.

This is a huge downgrade in a very useful service with great client integrations.
I appreciate you can't sustain the service to be used for free, but why drop all the features and leave a useless service?
I want  to keep using the classic integration but I am willing to pay for the space used

**Comment by elizabeth-griffiths** [comment]
Thanks for the feedback, we're working hard to get a replacement in.
