### ISSUE TITLE
multiversx

### ISSUE THREAD

**Issue by kencrowley11** [nftstorage/nft.storage#2661]
hi im trying to use your service, new version and i cannot get past the csv upload :Upload your first item!

Add a contract ID, select a network and
upload a CID/Token ID match csv.

icon-plus
Add items

i try to add csv files etc but A: what is contract address B: no wallet for multiversx C: how to i send the file including CID when its you that create this?

thanks for any help as little confused at the moment cheers 
ken.

**Comment by elizabeth-griffiths** [comment]
If you've purchased storage, it can be used to store data in the same login where you purchased it—app.nft.storage.
First mint your NFTs then send us the NFT data—metadata and imagery CIDs, blockchain(s) minted on, contract address and token IDs. We store these in long term Filecoin storage. Note that you need to upload the data to IPFS separately, here's a blog on how to do that: https://nft.storage/blog/onboard-nft-data-to-ipfs

To answer your questions: 
A: what is contract address - The blockchain NFT contract address
B: no wallet for multiversx - We don't support wallets. Are you referring to the blockchain /network selection dropdown?
C: how to i send the file including CID when its you that create this? Note that you need to upload the data to IPFS separately, here's a blog on how to do that: https://nft.storage/blog/onboard-nft-data-to-ipfs
