### ISSUE TITLE
NFT.storage issue

### ISSUE THREAD

**Issue by poopdeck85** [nftstorage/nft.storage#2662]
My large files have stayed in "pinning" mode. Is there a way to push and resolve?

Thank you!

**Comment by elizabeth-griffiths** [comment]
If you can view them nftstorage.link/ipfs/{cid} you're good to go

**Comment by poopdeck85** [comment]
Hi Elizabeth,My NFT portal (nftinator) is having difficulties loading the nft.storage CID.It still says “pinning” and it won’t complete. Any thoughts?ThanksSent from my iPhoneOn Jun 4, 2024, at 3:05 AM, Elizabeth Griffiths ***@***.***> wrote:﻿
Closed #2662 as completed.
