### ISSUE TITLE
GEM Icon PNG to upload for cosmos use

### ISSUE THREAD

**Issue by Studio-Mojo** [nftstorage/nft.storage#2666]
Hi Nft.Storage, 

I got a recommendation to use nft.storage to upload GEM DAO's icon, so it can be used by the community and protected. 

This came about due to other issues using Igrum and 404 errors that have been occurring. 

But I was uncertain how to utilize nft.storage to upload our gem.png image file > as it requires it to be in a CVS formate.  

Something I have never done before, and still massively wet behind the ears (just learning this world of coding)

If we can use nft.storage to host our images to be shared to dapps like, CoinHall, Enterprise, Smartstake, ASTRO, etc... 

Do you have any step by step for this process yet? 

Thank you for the help! 

Mojo-Studio

**Comment by elizabeth-griffiths** [comment]
Hi Mojo-Studio - 

I think there's some confusion with what you've been advised. NFT.Storage is only for just that - storage of NFT data.

NFT.Storage is a public good designed to preserve NFT data in decentralized, verifiable Filecoin storage. Aimed at ensuring every NFT remains accessible, we provide a low-cost, one-time fee solution for long-term preservation, aiming to seamlessly integrate across all NFT minting platforms and marketplaces.The cost to store your digital assets on NFT.Storage is USD $2.99 per GB. This is a one-time fee that aims to ensure your NFT data is preserved.
