### ISSUE TITLE
We are not able to log onto the NFT storage app to check our activity

### ISSUE THREAD

**Issue by AndyTsang-artifactlabs** [nftstorage/nft.storage#2667]
NFT Storage Support team,

We tried to log onto the NFT storage app to check our activity and payment detail for us to estimate the cost required.

However, we are not able to log onto the web app successfully after clicking the magic link received on the following email account.

nft-storage-dev-fw@artifactlabs.com
scmp-nft-storage@artifactlabs.com

Could you help on it?

Thanks
Andy

**Comment by elizabeth-griffiths** [comment]
Hi there, 
There are 2 versions of NFT.Storage. You're looking for app.nft.storage, where you log in through Github.
To estimate payment, it's $2.99/GB one-time fee. 

Thanks for using NFT.Storage!
