### ISSUE TITLE
Upload 120gb NFT collection

### ISSUE THREAD

**Issue by MetaGene01** [nftstorage/nft.storage#2669]
Hey! I need to upload my 120gb NFT collection. How I can do it?

**Comment by elizabeth-griffiths** [comment]
Excellent. Go to app.nft.storage. Buy storage, it's $2.99 / GB one-time fee. 

Send your NFT data to us for long-term preservation.
Send us your NFT data—CIDs, blockchain, contract address, and token IDs. 

Let me know if you have any specific questions. Just open a new ticket here.

**Comment by MetaGene01** [comment]
Hi. NFT.Storage used to have an app for mac and windows to upload NFT collection, but after the update I no longer see how I can upload NFT collection. Can you please tell me how I can do it, thanks!
