### ISSUE TITLE
IPFS CIDS are not reachable outside of your network as far as I can tell.

### ISSUE THREAD

**Issue by richtera** [nftstorage/nft.storage#2671]
A lot of our NFTs are missing images within our network (I work at LUKSO) and I found many of them pinned using nft.storage. The problem is that the CIDs containing this content are not retrievable from either pinata, infura, 4everland or a local ipfs cluster using p2p and so on. i.e. I can't find the CIDs registered in the DHT at all. I have some sample CIDs to look at, but I didn't want to post them in this issue because it's didn't want to make URLs public which are not mine to publish, but I can make them available privately.
The only thing I could think of is to use nftstorage.link as a public gateway to funnel all of our images in the network through a proxy service on cloudflare or gcp.
Please advise.
Andreas

**Comment by elizabeth-griffiths** [comment]
Let's pick this up privately. Please email this and the CIDs to support@nft.storage

**Comment by richtera** [comment]
Someone turned on a human check for the gateway so now the proxy solution will also no longer work. I sent an email.

**Comment by michaelcohen716** [comment]
experiencing this issue as well @richtera 

need a clean json response from gateway but getting the "just a moment" html document which breaks my app
