### ISSUE TITLE
Question on process

### ISSUE THREAD

**Issue by beachheadsystems** [nftstorage/nft.storage#2672]
In reading your documentation some steps seem to be missing. Where do I get these?

TokenID, CID
1, bafy...
2, bafz...
3, bafx...

Don't I need to store the NFT image and metadata with you to get the CID? If I use sugar is all this automated?

Thanks,
Jerry

**Comment by elizabeth-griffiths** [comment]
This is how you get the CID: https://nft.storage/blog/onboard-nft-data-to-ipfs
