### ISSUE TITLE
Invalid API key 

### ISSUE THREAD

**Issue by whYTee183** [nftstorage/nft.storage#2673]
Im trying to use the NFT storage API Key at NFT-inator but when loading to the NFT-inator page for adding IPFS account it says "Invalid API Key try again" .  I have tried multiple new API Keys but same results. I have been sending emails to NFT-inator for weeks for help but have not received any replies back and have given me zero help. Not sure what im doing wrong or who to ask for help. If you can help greatly appreciated. 

Thanks,

John Underwood

**Comment by beachheadsystems** [comment]
Getting the same error :
Error running command (re-run needed): Invalid nft.storage authentication token.

**Comment by beachheadsystems** [comment]
So what's the api key to use with Candy Machine? Your documentation is a
little lacking.

**Comment by kittenwifhat** [comment]
I have bought the storage of this [https://app.nft.storage/login](https://app.nft.storage/loginl) how can I get a refund?
