### ISSUE TITLE
Add backup URLs to upload list

### ISSUE THREAD

**Issue by vasco-santos** [nftstorage/nft.storage#2674]
Context: https://github.com/w3s-project/nonpublic/issues/15

**Comment by elizabeth-griffiths** [comment]
Hi Vascos - This issues list is for customer issues and bugs. I think this was added to the wrong list.

**Comment by vasco-santos** [comment]
Hi @elizabeth-griffiths 
Can you point me to the contribution guide and where that is documented? This is a feature request for the listing api 🤔

**Comment by elizabeth-griffiths** [comment]
Are you referring to the NFT.Storage Gateway?
Please write out the feature request as the link did not work.

**Comment by vasco-santos** [comment]
No I mean, add URLs to the list from the classic nft.storage, so that we can work on the Bulk downloader. This is a feature required in classic nft.storage to have a bulk downloader
