### ISSUE TITLE
"Just a moment" human check breaks integrations

### ISSUE THREAD

**Issue by michaelcohen716** [nftstorage/nft.storage#2676]
Using the nftstorage gateway to read a URI in a backend server i'm running. it was previously working but now no longer works, because the fetch returns an html document with the check instead of the expected json.

is there a way maybe to pass the api key to circumvent the check and get a clean return vaue?

**Comment by elizabeth-griffiths** [comment]
Hi Michael - I see you've also sent our support team an email. Let's discuss there.
