### ISSUE TITLE
Can I pay with crypto for storage?

### ISSUE THREAD

**Issue by satorioshi** [nftstorage/nft.storage#2679]

**Comment by elizabeth-griffiths** [comment]
Hey Satorioshi - We don't have a way to pay with crypto self serve yet. If you need an important collection preserved or have a lot of NFT to preserve we can work with you to do this. Can you tell me more about how much data you need, and what token you want to pay in?

**Comment by satorioshi** [comment]
Looking for 10gb and want to pay in Solana. Is that okay?

**Comment by elizabeth-griffiths** [comment]
Let me check with our finance director and get back to you. We will try to get this to work.

**Comment by elizabeth-griffiths** [comment]
Hi there! Letting you know that I have a solution - we will be able to accept SOL this week. Are you looking for back up data for Solana NFTs as well, or are the NFTs minted somewhere else?

**Comment by elizabeth-griffiths** [comment]
Friendly bump

**Comment by elizabeth-griffiths** [comment]
Friendly bump @satorioshi

**Comment by elizabeth-griffiths** [comment]
Hey @satorioshi - We have our beta Pay With Crypto ready to go. Email us at support@nft.storage if you'd like to use it. 
Thanks!
