### ISSUE TITLE
Issue retrieving metadata from opensea

### ISSUE THREAD

**Issue by jackbhowell** [nftstorage/nft.storage#2681]
Hiya,

I seem to be getting a lot of issues recently in regards to opensea reading the metadata from my contract. See the attached screenshot.

It seems some are going through ok, but others are pointing to an old ipfs url and also others just dont load at all.

Can you help? Opensea and Thirdweb can't pinpoint the issue but have mentioned NFT Storage could be the bottle neck here.

Thanks,
![Contract Problem 07](https://github.com/nftstorage/nft.storage/assets/106402238/3cee7b4f-ae04-408e-ad0b-83cf52138e4e)
![Contract Problem 01](https://github.com/nftstorage/nft.storage/assets/106402238/0054f597-84f0-4e31-8207-76ce916119cb)
![Contract Problem 02](https://github.com/nftstorage/nft.storage/assets/106402238/51ed37d0-ea33-4dc5-b643-cd010d273157)
![Contract Problem 03](https://github.com/nftstorage/nft.storage/assets/106402238/4a5214a6-f3f7-4fc8-b6bf-918512aefe7a)
![Contract Problem 04](https://github.com/nftstorage/nft.storage/assets/106402238/3e6ae48e-ca92-4e31-931a-265fff0b03f7)
![Contract Problem 05](https://github.com/nftstorage/nft.storage/assets/106402238/d0e0d6fc-ba0b-4fbb-9fe4-ed54ed740a47)
![Contract Problem 06](https://github.com/nftstorage/nft.storage/assets/106402238/73e4d61d-21a8-402f-8c74-5395e3eaf850)

Jack

**Comment by elizabeth-griffiths** [comment]
Hi Jack - If the metadata is available through the NFT.Storage Gateway at nftstorage.link/ipfs/{enter cid} then it's working as intended from our end. 

Please also note the latest update message that we're trying to get out: 

Subject: Important Reminder: NFT.Storage transition & exclusive benefits

Hi there,
Hello from NFT.Storage!
As we approach the transition deadline for NFT.Storage Classic, we want to remind you of the important changes taking place and the exclusive benefits available to you. Our goal is to ensure that your data remains safe and accessible while introducing you to our new partnerships that support the sustainability of our services.

Transition deadline reminder
Starting June 30, 2024, at 5 PM EST, NFT.Storage Classic will no longer accept new uploads. However, rest assured, all data you've uploaded before this deadline will continue to be safely stored and accessible via IPFS and the Filecoin Network. Over time, latency and availability may degrade, but your data is secure. Uploads will no longer be accepted for:
The original NFT.Storage web app, API, and SDK
NFTUp
Pinning API

New partnerships with Pinata and Lighthouse
We are excited to announce our new partnerships with Pinata and Lighthouse for hot storage solutions. As an NFT.Storage user, you support our platform when you choose Pinata and Lighthouse and use our referral links, helping to sustain our valuable public goods.

Pinata Discount Code: An exclusive discount code for our community. Use code NFTSTORAGE50 at checkout to enjoy 50% off your first month.
Referral link: https://www.pinata.cloud/nft-storage-pinata


Lighthouse free trial: A 30-day free trial is available. 
Referral link: https://files.lighthouse.storage/?referby=NFTStorage

How does using Pinata and Lighthouse support NFT.Storage?
For new customers who sign up with the NFT.Storage referral links, NFT.Storage receives a percentage of every dollar you spend with Pinata and a percentage of your first storage purchase with Lighthouse. These funds help support our mission.

Do I need to migrate my NFT.Storage Classic data to Pinata or Lighthouse?
Migration isn't required, but given how critical your NFT data is, NFT.Storage always advocates for storage layer maximalism. By that we mean, if there's even a fraction of a chance you believe one solution might fail, it's worth considering using multiple storage solutions. Both Pinata and Lighthouse have a simple tool to help you copy your NFT.Storage Classic data in under 5 minutes. See the FAQs for details.

How Do NFT.Storage and Pinata/Lighthouse complement each other?
Pinata and Lighthouse offer hot storage for your data that make your data retrievable by marketplaces, wallets, or any other website. The new version of NFT.Storage focuses on the long-term preservation of NFT data. By using both a hot storage service and NFT.Storage’s preservation benefits, you can ensure your data is highly available while we aim to ensure your NFT data is preserved in endowment-backed Filecoin storage.

Keeping Your Data Safe
Your NFT data's safety is our top priority. Here's a detailed guide on how to keep your data secure:

Use Multiple Storage Solutions: Diversify your storage solutions as a best practice. Use the tool Pinata or Lighthouse tools to easily copy your data. Learn more: https://nft.storage/blog/why-copy-your-nft-storage-classic-data-and-how-to-do-it

Long-term Backups: Ensure you have backups of your data by uploading to our endowment-backed Filecoin storage by using the new version of NFT.Storage. Sign up: https://app.nft.storage/login

Stay Informed: Keep up with the latest updates from NFT.Storage. Follow us on x: https://twitter.com/nftdotstorage?lang=en

NFT.Storage Classic: A free service
We appreciate your trust in NFT.Storage Classic, a public good that’s been free for over 3 years. For any questions or assistance, please don't hesitate to [reach out to our support team.](https://nft.storage/contact-us)
Thank you for being a valued member of the NFT.Storage community. Together, we look forward to a promising future for NFT.Storage and the broader NFT ecosystem.

Helpful Resources:
[Learn more about our partnerships with Pinata and Lighthouse](https://nft.storage/blog/announcing-our-new-partnerships-with-pinata-and-lighthouse)
[Read the FAQs](https://nft.storage/faq)
[Bookmark the link to access the original NFT.Storage Classic web app](https://classic.nft.storage/login/)

Best regards,
The NFT.Storage Team
