### ISSUE TITLE
Error: storing files: API Key is malformed or failed to parse.

### ISSUE THREAD

**Issue by m4nki** [nftstorage/nft.storage#2682]
Hi!

When I try to upload an image via NFTUp, I get the following error, despite having previously entered my API Key from NFT.Storage correctly:

Error: storing files: API Key is malformed or failed to parse.

What's the reason for this? Is it, because I didn't purchase any storage or is it a different reason?

Thank you!

**Comment by elizabeth-griffiths** [comment]
The original NFT.Storage product (now called NFT.Storage Classic) includes NFTUp. 
To align our services more closely with our community's needs and ensure the sustainability of our model, we're updating our service offerings. We'll continue to offer the current product under the name NFT.Storage Classic for existing uploads prior to 30 June 2024 , but no new uploads to the Classic product will be accepted as of 30 June 2024 at 5pm EST. New account registrations will no longer be accepted for:
The original NFT.Storage web app, API, and SDK
NFTUp
Pinning API

If you already have a classic.nft.storage account, get an API key from that login and download NFTUp here: https://github.com/nftstorage/nftup. Uploads to NFTUp are free.

If you do not have a classic.nft.storage account, you can use the new version of the product at https://app.nft.storage/.

For the new version, first mint your NFTs then send us the NFT data—metadata and imagery CIDs, blockchain(s) minted on, contract address and token IDs. We store these in long term Filecoin storage. Note that you need to upload the data to IPFS separately, we recommend using Pinata or Lighthouse with our referral links to support NFT.Storage: 
https://nft.storage/blog/announcing-our-new-partnerships-with-pinata-and-lighthouse
