### ISSUE TITLE
Can't log in

### ISSUE THREAD

**Issue by Okato7** [nftstorage/nft.storage#2684]
Dear  NFT.Storage Team,

I have been struggling to log into my classic account.
What is happening please?

Regards,

Yokato7

**Comment by elizabeth-griffiths** [comment]
Hi Yokato7 - You can log into classic at classic.nft.storage. What happens when you try to log in?

**Comment by Okato7** [comment]
Hi,
The screen remains blank after I input my username. password, and press ENTER.

**Comment by lukacan** [comment]
Hey guys, the same thing happens to me. Once I log in (using GitHub or entering email), everything completes but I`m actually not logged in and I have to do the login process again , this then repeats ..

**Comment by elizabeth-griffiths** [comment]
This should be resolved now.

Transition deadline reminder
Starting June 30, 2024, at 5 PM EST, NFT.Storage Classic will no longer accept new uploads. However, rest assured, all data you've uploaded before this deadline will continue to be safely stored and accessible via IPFS and the Filecoin Network. Over time, latency and availability may degrade, but your data is secure. Uploads will no longer be accepted for:

- The original NFT.Storage web app, API, and SDK
- NFTUp
- Pinning API

**New partnerships with Pinata and Lighthouse**
We are excited to announce our new partnerships with Pinata and Lighthouse for hot storage solutions. As an NFT.Storage user, you support our platform when you choose Pinata and Lighthouse and use our referral links, helping to sustain our valuable public goods.

**Pinata Discount Code:** An exclusive discount code for our community. Use code NFTSTORAGE50 at checkout to enjoy 50% off your first month.
Referral link: https://www.pinata.cloud/nft-storage-pinata


**Lighthouse free trial:** A 30-day free trial is available. 
Referral link: https://files.lighthouse.storage/?referby=NFTStorage
