### ISSUE TITLE
Account Recovery / RePinning

### ISSUE THREAD

**Issue by ethanvandoorne** [nftstorage/nft.storage#2686]
Hello. I've taken over an NFT project and it seems our pinning is broken. I've been looking all over and it seems that the CIDs associated with our project start with bay* and that seems to be consistent with NFT Storage. Here's one example of one of our images: 

https://nftstorage.link/ipfs/bafybeieazgqq2q3z5gkl3bhncsuiigxcwv6zv3zwjwitwnvxkgtiaguhky

It may have been a part of an account associated with "Sturdy" or "Sturdy Exchange" - possibly dev@sturdy.exchange

Could you help me determine which account is associated with that image, and possibly trigger a password reset?

**Comment by elizabeth-griffiths** [comment]
Hi - I can see that there is an account associated with the email domain, however it's not dev@.
Please email support@nft.storage to discuss further for privacy reasons.
