### ISSUE TITLE
Pinning - who is solving it?

### ISSUE THREAD

**Issue by n00b21337** [nftstorage/nft.storage#2687]
Is pinning also secured with NFT storage or do I need to take care of pinning myself to make sure content is always accessible?
If pinning is done, who does it, Filecoin that is getting paid or nft.storage service?

**Comment by elizabeth-griffiths** [comment]
For the new version, first mint your NFTs then send us the NFT data—metadata and imagery CIDs, blockchain(s) minted on, contract address and token IDs. We store these in long term Filecoin storage to preserve your NFT data. Note that you need to upload the data to IPFS separately (and pin it), we recommend using Pinata or Lighthouse with our referral links to support NFT.Storage: 
https://nft.storage/blog/announcing-our-new-partnerships-with-pinata-and-lighthouse
