### ISSUE TITLE
support for multiversx

### ISSUE THREAD

**Issue by kencrowley11** [nftstorage/nft.storage#2688]
does this site support multiversx? as im struggling to get this new site version  to work thanks in advance for any help

**Comment by elizabeth-griffiths** [comment]
Do multiversx NFT contracts have a contract ID and token ID/

**Comment by kencrowley11** [comment]
Yes both

**Comment by elizabeth-griffiths** [comment]
I've added your request to our new feedback request tool: https://nftstorage.canny.io/feature-requests/p/support-multiversx
Can you tell me how many collections you plan to back up in nft.storage if we add support? 
And are you able to influence others in the ecosystem to back up their collections?
