### ISSUE TITLE
Entire List of URIs Gone

### ISSUE THREAD

**Issue by futjrnaut** [nftstorage/nft.storage#2690]
So it looks like you guys updated the app and now my entire list of URIs is gone :( what do?

**Comment by elizabeth-griffiths** [comment]
This should not have happened. Can you please send me more information about this at support@nft.storage. Please include: 
* Account email/github login
* When you first noticed they are gone
* Examples of CIDs that are gone

Let's continue the conversaton over email.

**Comment by futjrnaut** [comment]
hi
futjrnaut github handle
i needed to pin something yesterday logged in saw your new layout and my
account wiped
ive been using your service since you opened, its not countless things but
it was a couple pages and they were mine =/
any help in recovering my archive is greatly appreciated <3

**Comment by elizabeth-griffiths** [comment]
I suspect what has happened is you've logged into the new instance of
nft.storage at app.nft.storage.

Try logging in at classic.nft.storage.

**Comment by futjrnaut** [comment]
that fixed it thanks!
