### ISSUE TITLE
Had a classic account

### ISSUE THREAD

**Issue by bpjones101** [nftstorage/nft.storage#2692]
How do I recover the Files from my previous account with NFT Storage
[cids.csv](https://github.com/user-attachments/files/15962294/cids.csv)

**Comment by elizabeth-griffiths** [comment]
Your files are accessible at classic.nft.storage. 

Friendly reminder regarding upcoming changes: 
The original NFT.Storage product (now called NFT.Storage Classic) includes NFTUp. 
To align our services more closely with our community's needs and ensure the sustainability of our model, we're updating our service offerings. We'll continue to offer the current product under the name NFT.Storage Classic for existing uploads prior to 30 June 2024 , but no new uploads to the Classic product will be accepted as of 30 June 2024 at 5pm EST. New account registrations will no longer be accepted for:
The original NFT.Storage web app, API, and SDK
NFTUp



Migration isn't required, but given how critical your NFT data is, NFT.Storage always advocates for storage layer maximalism. By that we mean, if there's even a fraction of a chance you believe one solution might fail, it's worth considering using multiple storage solutions. Both Pinata and Lighthouse have a simple tool to help you copy your NFT.Storage Classic data in under 5 minutes. [Learn how here.](https://nft.storage/blog/why-copy-your-nft-storage-classic-data-and-how-to-do-it)
