### ISSUE TITLE
NFT Storage link is broken

### ISSUE THREAD

**Issue by Huzitatuguharu** [nftstorage/nft.storage#2693]
Dear NFT Storage Support Team,

I hope this message finds you well. I am writing to seek assistance regarding ongoing access issues I have been experiencing with my NFT Storage links. Despite following the recommended troubleshooting steps, such as checking the network connections, clearing browser cache, and ensuring correct URL inputs, the issue persists.

Could you please help investigate and provide a resolution or guide me through any additional steps that might help? Thank you very much for your time and assistance.

**Comment by Huzitatuguharu** [comment]
This is one of the inaccessible URLs
https://bafkreietwa5k44v2xpekcmvc4dcdpjqyt4ukuxjjew4eib3o5buk2eijku.ipfs.nftstorage.link/

**Comment by phnode** [comment]
i have same problem

**Comment by Apollo50** [comment]
Have the same problem.
All our NFT metadata is unavailable.

Get `DNS_PROBE_FINISHED_NXDOMAIN` error

**Comment by elizabeth-griffiths** [comment]
There was a DNS change yesterday that is impacting some CIDS, it should be fully propagated soon.

You can view all your CIDs at classic.nft.storage. 

Friendly reminder about upcoming changes: 
To align our services more closely with our community's needs and ensure the sustainability of our model, we're updating our service offerings. We'll continue to offer the current product under the name NFT.Storage Classic for existing uploads prior to 30 June 2024 , but no new uploads to the Classic product will be accepted as of 30 June 2024 at 5pm EST. New account registrations will no longer be accepted for:

- The original NFT.Storage web app at classic.nft.storage, API, and SDK
- NFTUp
- Pinning API

For the new version, first mint your NFTs then send us the NFT data—metadata and imagery CIDs, blockchain(s) minted on, contract address and token IDs. We store these in long term Filecoin storage. Note that you need to upload the data to IPFS separately, we recommend using Pinata or Lighthouse with our referral links to support NFT.Storage: 
https://nft.storage/blog/announcing-our-new-partnerships-with-pinata-and-lighthouse

**Comment by elizabeth-griffiths** [comment]
This is resolved now

**Comment by phnode** [comment]
Hi, thank you for reply
I have a live mint with the nft storage classic,do I need to change to new version for continue our mint after 30 june
