### ISSUE TITLE
Bypass cloudflare challenge for ipfs.nftstorage.link

### ISSUE THREAD

**Issue by ikryvorotenko** [nftstorage/nft.storage#2696]
duplicating the issue https://github.com/nftstorage/nft.storage/issues/2578 as it's not resolved.

example: 
https://bafkreid2t4f3i36tq4aowwaaa5633ggslefthxfdudaimog6unwu36umha.ipfs.nftstorage.link routes me to cloudflare challenge page. `Ray ID: 899601d49d1ed0cd` for reference.

**Comment by elizabeth-griffiths** [comment]
That CID was caught in the filters. It should be resolved now. Thanks for following up!
