### ISSUE TITLE
API Key

### ISSUE THREAD

**Issue by Uajer** [nftstorage/nft.storage#2697]
Hi there.
How can i get api token?
it is same as api key?
I encountered an unauthorized error while uploading image.
other token is something like "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkaWQ6ZXRocjoweDQ1MzQ5MDNFMGQxNUFkZUM1Q0I2RWIzRTk1NmZmODBEMjBjMzBlQzEiLCJpc3MiOiJuZnQtc3RvcmFnZSIsImlhdCI6MTY1Nzg3MjEzOTIwOCwibmFtZSI6ImRlbW8xIn0.orLjmbg_zHNJ22jGj0rtFZgjUApZSoMygZGq0DhqVy4".
but my token is "b37cdd10.ece028322d0b421a8efda7ba76fa402e".
why is it too small?

**Comment by elizabeth-griffiths** [comment]
API key is the same as API token.

An API key from https://app.nft.storage/login
Is being used for
https://classic.nft.storage/ (the API, SDK or NFTUp).
API keys from https://app.nft.storage/login only work with https://app.nft.storage/login.

IMPORTANT PRODUCT UPDATE: 
To align our services more closely with our community's needs and ensure the sustainability of our model, we're updating our service offerings. We'll continue to offer the current product under the name NFT.Storage Classic for existing uploads prior to 30 June 2024 , but no new uploads to the Classic product will be accepted as of 30 June 2024 at 5pm EST. New account registrations will no longer be accepted for:
The original NFT.Storage web app at classic.nft.storage, API, and SDK
NFTUp
Pinning API

If you do not have a classic.nft.storage account, you can use the new version of the product at https://app.nft.storage/.

For the new version, first mint your NFTs then send us the NFT data—metadata and imagery CIDs, blockchain(s) minted on, contract address and token IDs. We store these in long term Filecoin storage. Note that you need to upload the data to IPFS separately, we recommend using Pinata or Lighthouse with our referral links to support NFT.Storage: 
https://nft.storage/blog/announcing-our-new-partnerships-with-pinata-and-lighthouse
