### ISSUE TITLE
Can I still upload files to 

### ISSUE THREAD

**Issue by sedeyre** [nftstorage/nft.storage#2710]
Hi!
Can I still upload files to NFT.storage with API using JS nft.storage library, as I did before with Classic NFT?
Should I only use a newly generated token after purchasing  a storage quota?
Thx

**Comment by elizabeth-griffiths** [comment]
Here is the latest information regarding NFT.Storage Classic, including NFTUp, and your data. As of 30 June 2024, no new uploads to the Classic product (including NFTUp) will be accepted but if you have used the products before your data is safe. Your data is safely stored and accessible via the NFT.Storage Gateway and in decentralized long-term storage in the Filecoin Network. However, over time, latency and availability may degrade.

Check out the new version of NFT.Storage. For the new version, first mint your NFTs then send us the NFT data—metadata and imagery CIDs, blockchain(s) minted on, contract address and token IDs. We store these in long term Filecoin storage. Note that you need to upload the data to IPFS separately, we recommend using Pinata or Lighthouse with our referral links to support NFT.Storage: 
https://nft.storage/blog/announcing-our-new-partnerships-with-pinata-and-lighthouse

Let us know if you have any other questions.
Thanks!
