### ISSUE TITLE
Invalid Auth token

### ISSUE THREAD

**Issue by soulanalive** [nftstorage/nft.storage#2712]
![image](https://github.com/nftstorage/nft.storage/assets/171570233/9f5f06c2-950b-43cd-9f52-3924bab94267)

I am trying to use nft storage as a medium to upload my nft collection via sugar. I copied the auth code 1:1 but it seems to not work and parsed out as invalid. please assist.

**Comment by elizabeth-griffiths** [comment]
Here is the latest information regarding NFT.Storage Classic, including NFTUp, and your data. As of 30 June 2024, no new uploads to the Classic product (including NFTUp) will be accepted but if you have used the products before your data is safe. Your data is safely stored and accessible via the NFT.Storage Gateway and in decentralized long-term storage in the Filecoin Network. However, over time, latency and availability may degrade.

Check out the new version of NFT.Storage. For the new version, first mint your NFTs then send us the NFT data—metadata and imagery CIDs, blockchain(s) minted on, contract address and token IDs. We store these in long term Filecoin storage. Note that you need to upload the data to IPFS separately, we recommend using Pinata or Lighthouse with our referral links to support NFT.Storage: 
https://nft.storage/blog/announcing-our-new-partnerships-with-pinata-and-lighthouse

**Comment by Buff-Doge-Coin** [comment]
I'm also facing the same issue man
