### ISSUE TITLE
My NFT platform used NFT Storage - now what?

### ISSUE THREAD

**Issue by robertzen1** [nftstorage/nft.storage#2715]
Hello, our NFT platform https://www.versatio.eu/ is using NFT Storage. We have our own minter for NFTs and we are using NFT Storage to store images. We are using API from https://classic-app.nft.storage/ to upload our images. Now our minter is stuck on minting, because NFT Storage cant upload new images, if I understand that correctly. I want to find a solution for this issue ideally without having to interfere with the code of our platform, i.e. if the API key could remain the same. Is this somehow possible? For example create an account on another provider, e.g. Pinata and somehow link our old API key from NFT storage there, so our platform can continue to upload images? Or what are the steps to make it work? Thank you

**Comment by elizabeth-griffiths** [comment]
Here is the latest information regarding NFT.Storage Classic, including NFTUp, and your data. As of 30 June 2024, no new uploads to the Classic product (including NFTUp) will be accepted but if you have used the products before your data is safe. Your data is safely stored and accessible via the NFT.Storage Gateway and in decentralized long-term storage in the Filecoin Network. However, over time, latency and availability may degrade.

Check out the new version of NFT.Storage. For the new version, first mint your NFTs then send us the NFT data—metadata and imagery CIDs, blockchain(s) minted on, contract address and token IDs. We store these in long term Filecoin storage. Note that you need to upload the data to IPFS separately, we recommend using Pinata or Lighthouse with our referral links to support NFT.Storage: 
https://nft.storage/blog/announcing-our-new-partnerships-with-pinata-and-lighthouse

**Comment by robertzen1** [comment]
Thank you for your reply, but this is not a complete solution to our problem, as our inhouse minter is fully automated and generates and sends this data automatically on every mint. The image itself is automatically uploaded to NFT Storage via the API. I can't send you the data for each minted NFT. We need the process to be automatic. Can you somehow redirect on your side our current NFT Storage API so that images continue to be uploaded to a new provider such as Pinata, but under the current API and API key we have set up for NFT Storage? We can't now interfere with our minter code and change the API there to the new one. Alternatively, advise me how to solve this. Thanks
