### ISSUE TITLE
My NFT platform used NFT Storage - solution for automated miner

### ISSUE THREAD

**Issue by robertzen1** [nftstorage/nft.storage#2717]
Hello, you closed my ticket before I could reply. So I'll take the liberty of writing another, more detailed ticket...

Our NFT platform, https://www.versatio.eu/, is using NFT Storage to store images via the API from https://classic-app.nft.storage/. Currently, our minter is stuck on minting because NFT Storage can't upload new images, if I understand correctly. We are seeking a solution to this issue without having to modify our platform's code, meaning we need to keep the same API key.

In your previous response, the solution provided wasn't complete for our needs. Our in-house minter is fully automated and generates and sends data automatically with each mint. The images are uploaded to NFT Storage via the API without manual intervention, so manually sending data for each NFT is not feasible.

We need an automatic solution. Can you redirect our current NFT Storage API to a new provider, such as Pinata, while retaining our current API and API key set up for NFT Storage? If this redirection is not possible, please advise on alternative steps we can take to resolve this issue without interfering with our minter's code. Or the only solution to this is changing API in our minter to Pinata?

Thank you.

**Comment by huketo** [comment]
https://github.com/orgs/nftstorage/people

Is the nft.storage team safe? I think the current members, including the CEO, are missing.
I also e-mailed the inquiry a week ago, but I didn't get an answer.

**Comment by elizabeth-griffiths** [comment]
@huketo We strive to reply to every github ticket and email within 24 business hours. I'm not sure how yours slipped through the cracks. I don't have any outstanding inquiries. Can you please submit a github ticket or resend your email to support@nft.storage? Thanks!

**Comment by elizabeth-griffiths** [comment]
@robertzen1 , Apologies for closing the ticket too soon. 

I'll respond to your message in segments: 

> Our NFT platform, https://www.versatio.eu/, is using NFT Storage to store images via the API from https://classic-app.nft.storage/. Currently, our minter is stuck on minting because NFT Storage can't upload new images, if I understand correctly. We are seeking a solution to this issue without having to modify our platform's code, meaning we need to keep the same API key.
It's not possible to solve this without modifying the code or keeping the same API key. The NFT.Storage Classic uploading capability has been decommissioned.

> We need an automatic solution. Can you redirect our current NFT Storage API to a new provider, such as Pinata, while retaining our current API and API key set up for NFT Storage? If this redirection is not possible, please advise on alternative steps we can take to resolve this issue without interfering with our minter's code. Or the only solution to this is changing API in our minter to Pinata?
The only solution is to change the API in your minter to a different hot storage solution such as Pinata. If you choose Pinata, we kindly ask that you use our referral link so that you continue to support NFT.Storage. Here it is: https://www.pinata.cloud/nft-storage-pinata

**Comment by huketo** [comment]
@elizabeth-griffiths , I sent you an email again. please check it.

E-mail: huke.lsware@gmail.com

**Comment by elizabeth-griffiths** [comment]
> huke.lsware@gmail.com

We have replied to your email.

**Comment by elizabeth-griffiths** [comment]
@robertzen1 friendly bump.

**Comment by elizabeth-griffiths** [comment]
I'm going to close this ticket since we haven't heard back in 5 days.
