### ISSUE TITLE
Inquiry Regarding Filecoin Deal Issues and Potential Refund

### ISSUE THREAD

**Issue by huketo** [nftstorage/nft.storage#2718]
Hello, I'm a developer of LSware, a Korean blockchain company, and we run an NFT Marketplace and it was subordinate to nft.storage. However, because the person in charge left the company due to the change in the company's workforce, we didn't receive the news of the large-scale update of nft.storage, and we learned this late because nft.storage was not working after the nft.storage update. Therefore, we didn't have time to figure out the changes in nft.storage to respond urgently for the operation of nft marketplace.

I thought it would be solved if I pay because it was simply a transition from a free service to a paid service, but I didn't know that the method of using nft.storage had changed. This is because I thought it was an update that was at the level of integrating into an API method after the SDK disappeared.

We compared the pricing policies of nft.storage with pinata and web3.storage internally and decided that the existing nft.storage was an ipfs service that we would continue to use. However, we knew that nft.storage alone could not upload files to ipfs only after we had already paid 20GB for testing.

 I had no choice but to run the IPFS node on the server and then tested it using the nft.storage API, but I am in a very difficult situation because I confirmed that the Filecoin Deal does not stick even after a long time.

Thank you so much for providing IPFS services for free. However, I think it will be difficult for our company to use nft.storage in the future. Of course, it's also my fault that I didn't know exactly about the changes.

So I'm inquiring about whether I can cancel the payment.

The email for the github account that has signed up for nft.storage is huke.lsware@gmail.com .

**Comment by elizabeth-griffiths** [comment]
Hi there, 
You're email was quarantined, but now we have received it and responded. I'll close this ticket.
