### ISSUE TITLE
Upload MetaData / Image

### ISSUE THREAD

**Issue by marcusbond67** [nftstorage/nft.storage#2721]
How do I upload nft json meta data or image file. Ive been using this service for a while but it seems to have stopped working. Ive just purchased storage but it still doesnt seem to work.

The only file i can see to upload is a csv file.
Thanks
Marcus

**Comment by elizabeth-griffiths** [comment]
The original NFT.Storage product (now called NFT.Storage Classic) includes NFTUp.
To align our services more closely with our community's needs and ensure the sustainability of our model, we're updating our service offerings. We'll continue to offer the current product under the name NFT.Storage Classic for existing uploads prior to 30 June 2024 , but no new uploads to the Classic product will be accepted as of 30 June 2024 at 5pm EST.

If you do not have a classic.nft.storage account, you can use the new version of the product at https://app.nft.storage/.
For the new version, first mint your NFTs then send us the NFT data—metadata and imagery CIDs, blockchain(s) minted on, contract address and token IDs. We preserve these in long term Filecoin storage. Note that you need to upload the data to IPFS separately, we recommend using Pinata or Lighthouse with our referral links to support NFT.Storage:
https://nft.storage/blog/announcing-our-new-partnerships-with-pinata-and-lighthouse
