### ISSUE TITLE
How to pin Hashgraph medai

### ISSUE THREAD

**Issue by zombitsu** [nftstorage/nft.storage#2725]
No chain option for Hedera Hashgraph; will this work?

**Comment by elizabeth-griffiths** [comment]
Can you tell us more about why you choose to mint on Hedera Hashgraph, and the NFT volume you plan to back up using NFT.Storage? Do you think others in the Hedera Hashgraph community would use NFT.Storage if we added support for Hedera Hashgraph?

As we don't support Hedera Hashgraph, there is not an option to use NFT.Storage. However, we're interested in learning more from you and will consider adding support.

**Comment by zombitsu** [comment]
Hello Elizabeth,

We are the creators of https://altlantis.tools and https://altlantis.market
on the hashgraph.

We support hundreds of web3 creators and their communities, solely on the
hashgraph. Our minting tools leveraged your old API for uploading to IPFS;
we'd love to direct our customers to pay you to continue pinning the media
rather than have them go elsewhere. There are quite a large number of
creators on the hashgraph.

Over the past year hundreds of thousands of NFTs were minted through our
platform. We anticipate some major growth due to the cost effectiveness and
performance of the network.

What do you require from me in order to make this happen?

Thanks,

David

**Comment by elizabeth-griffiths** [comment]
Hi there - If we add support for hashgraph, approximately how many NFT collections do you plan to back up with NFT.Storage? Will you integrate your tools with NFT.Storage? 

I have logged support for Cronos to our new feature request tool. We'd love for you to vote for it there: https://nftstorage.canny.io/feature-requests

**Comment by zombitsu** [comment]
Hello Elizabeth,

I suspect hundreds of collections would initially be backed up, and we
would integrate your solution into our platform as we had previously.

I appreciate your response, I will of course be voting.

**Comment by MrWiki15** [comment]
🤍
