### ISSUE TITLE
Log in Problems

### ISSUE THREAD

**Issue by Caparicaner** [nftstorage/nft.storage#2729]
Hello there, 

I tried to log into my account. I had to use my github credentials and when logged in, there were no files. I think i used a different method to access nft.storage, maybe the old version which is not available anymore. 

Could you assist me please. 

Appreciate the help. 

cheers

**Comment by Caparicaner** [comment]
alrighty, update. 

i was reading your blog posts and saw that nft.storage classic has ended. i found out how to log into the classic app with my correct credentials just to find out that my files were gone in there too. 

Now im not sure how to proceed and appreciate any help. 

do i have to inscribe it as an ordinal to avoid such problems in the future hahaahah

but for real, i need help. 

thank you

**Comment by elizabeth-griffiths** [comment]
Hahaha, all good. Your data is safe.
You were logged into the new app.
Try this: go to classic.nft.storage - select the log in button at the top
right. When you log in you'll see your files

**Comment by Caparicaner** [comment]
hello elizabeth, 

thanks for the reply. i tried that but my files are not there. ill add a screenshot. 

its quite strange as some of the nfts are still visible in the marketplace while others are not. 

what should i do next or how can i find my files in order to transfer them.

thank you

<img width="1272" alt="Screenshot 2024-07-22 at 22 36 26" src="https://github.com/user-attachments/assets/a0217df8-c528-487e-8b4c-37604da68b14">

**Comment by elizabeth-griffiths** [comment]
Do you log in with this GitHub account or with an email address?

Can you send me an example cid that you created with nft.storage classic
that isn't appearing?

**Comment by Caparicaner** [comment]
oh god, im stupid. wow. used an email-address to log in but its on the github account. 

so basically my files are there. really appreciate the help. 

i will now just follow your transfer guide (https://nft.storage/blog/why-copy-your-nft-storage-classic-data-and-how-to-do-it) and if i run in another stupid mistake on my site i will contact you again haha. 

again, thank you for your help and have a lovely evening.

**Comment by elizabeth-griffiths** [comment]
No worries, glad it was an easy solve!

**Comment by elizabeth-griffiths** [comment]
No worries at all, happy to help!
