### ISSUE TITLE
Upload on cronos chain

### ISSUE THREAD

**Issue by Tam4tik** [nftstorage/nft.storage#2731]
Hello, 

I was used to build with NFT.storage, and cannot upload anymore with NFT up 

I did bought 4 gigs of file storage.

Seems like we need to create our contract first, but no cronos evm chain (it is what we use) what can I do

**Comment by elizabeth-griffiths** [comment]
The original NFT.Storage product (now called NFT.Storage Classic) includes NFTUp. 
To align our services more closely with our community's needs and ensure the sustainability of our model, we're updating our service offerings. We'll continue to offer the current product under the name NFT.Storage Classic for existing uploads prior to 30 June 2024 , but no new uploads to the Classic product will be accepted as of 30 June 2024 at 5pm EST. 

Now, you can use the new version of the product at https://app.nft.storage/.

For the new version, first mint your NFTs then send us the NFT data—metadata and imagery CIDs, blockchain(s) minted on, contract address and token IDs. We preserve these in long term Filecoin storage. Note that you need to upload the data to IPFS separately, we recommend using Pinata or Lighthouse with our referral links to support NFT.Storage: 
https://nft.storage/blog/announcing-our-new-partnerships-with-pinata-and-lighthouse

Let us know if you have any other questions!

**Comment by elizabeth-griffiths** [comment]
Regarding Cronos - you're correct, we don't currently support Cronos.
Can you tell us more about why you choose to mint on Cronos, and the NFT volume you plan to back up using NFT.Storage? Do you think others in the Cronos community would use NFT.Storage if we added support for Cronos?

**Comment by Tam4tik** [comment]
Ok you got bought by pinata, damned, no way I pay 20usd/month just for IPFS upload. Can I get refund for the storage I bought?

**Comment by elizabeth-griffiths** [comment]
NFT.Storagw is an independent entity, a public good.

Please email ***@***.*** with refund requests

**Comment by elizabeth-griffiths** [comment]
I have logged support for Cronos to our new feature request tool. We'd love for you to vote for it there: https://nftstorage.canny.io/feature-requests
