### ISSUE TITLE
Pinned files can not access via public gateway

### ISSUE THREAD

**Issue by viaweb3** [nftstorage/nft.storage#2732]
**What product are you using?**
Select one:
*  NFT.Storage Classic - Web app (classic.nft.storage)

**What is the problem?**

All the pinned and Archived files can not access via any public gateway.
cids like:
bafybeiblkctaogvvfttpxrc6pwqamj3m3ogq4qetdjox6272bdpgf4daoq
bafybeihcgafuhnsghzbl7jzi2zgr6q7legsn5niguw5ba7sfhsw6swhme4

**What did you expect to happen?**
Can be access.

**Comment by viaweb3** [comment]
And can not migrate to lighthouse as well, lighthouse can not import such files.

**Comment by elizabeth-griffiths** [comment]
Hi there - I have a few questions:
1. We're these files uploaded to NFT.Storage Classic? (Classic.nft.storage)
2. What happens when you try to access them via the gateway?

**Comment by viaweb3** [comment]
> Hi there - I have a few questions:
> 
> 1. We're these files uploaded to NFT.Storage Classic? (Classic.nft.storage)
Yes
> 2. What happens when you try to access them via the gateway?
No response. Just like: https://ipfs.io/ipfs/bafybeihcgafuhnsghzbl7jzi2zgr6q7legsn5niguw5ba7sfhsw6swhme4

**Comment by elizabeth-griffiths** [comment]
Try retrieving from the NFT.Storage Gateway:
nftstorage.link/ipfs/{enter cid}

Let me know if that works

**Comment by viaweb3** [comment]
https://nftstorage.link/ipfs/bafybeihcgafuhnsghzbl7jzi2zgr6q7legsn5niguw5ba7sfhsw6swhme4
 not work, @elizabeth-griffiths

**Comment by elizabeth-griffiths** [comment]
Ok, I'm going to need to check your classic.nft.storage account. Please email support@nft.storage to inform me of the email address associated with your account. Do not put your email address here for privacy reasons.

**Comment by elizabeth-griffiths** [comment]
Closing this, please email support

**Comment by viaweb3** [comment]
Email sent, no response.

**Comment by elizabeth-griffiths** [comment]
Apologies for the delayed reply. Your email landed in my spam folder. 

Are all of your CIDs impacted, or only some? 
When did you first notice this happening? 
When you try to copy the data to Lighthouse, what is the error that you get?

**Comment by agmap** [comment]
This is a general problem that I have already addressed with ipfs. The two CIDs are on DHT, but can only fetched using graphsync. Unfortunately kubo does not support the `graphsync` protocol.
Using Lassie, the two CIDs can be obtained without any problems.
![image](https://github.com/user-attachments/assets/e724f932-6f24-4d0a-87b7-40d038b70788)
![image](https://github.com/user-attachments/assets/3a6cf7f2-9450-4f7c-ac9c-d8e67c939a00)

**Comment by viaweb3** [comment]
> graphsync

Will nft.storage fix this issue? @agmap  @elizabeth-griffiths

**Comment by melwong** [comment]
I have the same issue. We are a recipient of Filecoin grants and we were using classic nft.storage. It used to allow us to access the files via the dweb.link URL but apparently this public gateway is no longer working - https://postimg.cc/8JmWN5K7 

If you go to https://bafybeie2kjd2rwbjlmc5rsqi2ltr2572l5b2gx5av3a37wmz4hisvdewmi.ipfs.nftstorage.link you will be redirected to https://bafybeie2kjd2rwbjlmc5rsqi2ltr2572l5b2gx5av3a37wmz4hisvdewmi.ipfs.dweb.link and you will get a HTTP 400 "This site can’t be reached" error. I'm very sure that the CID bafybeie2kjd2rwbjlmc5rsqi2ltr2572l5b2gx5av3a37wmz4hisvdewmi was pinned on NFT.storage.

Also, you stated that all the files for classic NFT.storage are still intact. But can we still access them without a local IPFS node? Will you be decommissioning your nftstorage.link aka dweb.link domains? I tried to import the files at my CID at my local node but it's not responding.

**Comment by elizabeth-griffiths** [comment]
We are looking into this.

**Comment by elizabeth-griffiths** [comment]
Thank you for your patience as we continue to investigate the issue with accessing pinned files via public gateways. We understand how frustrating this can be, and are looking into the problem.

In the meantime, we highly recommend copying your data from NFT.Storage Classic to ensure its accessibility. For detailed instructions on how to copy your data, you can refer to our guide here: [Why Copy Your NFT.Storage Classic Data and How to Do It](https://nft.storage/blog/why-copy-your-nft-storage-classic-data-and-how-to-do-it).

If you need further assistance or have additional questions, please don’t hesitate to reach out.

Best regards,
Elizabeth

**Comment by NFTStorageGithub** [comment]
If any of the issues in this ticket are not resolved please email support@nft.storage from with your account email and we will look to resolve your issue asap.
