### ISSUE TITLE
What the heck are you doing.

### ISSUE THREAD

**Issue by ChitinNature** [nftstorage/nft.storage#2733]
This is reply to ticket Issue https://github.com/nftstorage/nft.storage/issues/2728

Hey ya, so I can't just upload my json files?

Where would I store my images to get CIDs, do I have to store them else where now?
We change our images constantly and would need to upload our meta on a regular basis. If we have to contact you every time, its like you went back like 20 years in tech and now we need another human to upload stuff on the internet.

Your documents are completely out of wack. It guides you through saying that you can upload your items here via csv and json and also give json examples.. then it guides you to buy it, so I did, then it ends with awful instructions.

So I have to store offsite with piñata and then send it in there? Pay for offsite subscription and waste my money here? which seems already wasted.

I dont get what you guys did and its super garbage and it realllllllyyy is messsing things up.

So not cool.

**Comment by elizabeth-griffiths** [comment]
Hi, Thanks for your.message and feedback. We're working on improving the docs.

For the new version, first mint your NFTs then send us the NFT data—metadata and imagery CIDs, blockchain(s) minted on, contract address and token IDs. We preserve these in long term Filecoin storage. Note that you need to upload the data to IPFS separately, we recommend using Pinata or Lighthouse with our referral links to support NFT.Storage: 
https://nft.storage/blog/announcing-our-new-partnerships-with-pinata-and-lighthouse

**Comment by ChitinNature** [comment]
Any way I can get my money back from purchasing storage?

**Comment by elizabeth-griffiths** [comment]
Please email ***@***.*** with refund requests

**Comment by Iamknownasfesal** [comment]
i want a refund too, where can i get one

**Comment by elizabeth-griffiths** [comment]
Please email support@nft.storage with refund requests.
