### ISSUE TITLE
Vulnerability Issue Report

### ISSUE THREAD

**Issue by serundengsapi** [nftstorage/nft.storage#2734]
Hello NFT.Storage Team!

Does nft.storage have a bug bounty program? I found a vulnerability issue with preauth account takeover at nft.storage website.

If you don't mind, please drop the email to this thread for i can send the details vulnerabilities.

Thank you,

**Comment by elizabeth-griffiths** [comment]
NFT.Storage is an open source project and a public good. We don't have budget for a bug bounty program right now, but we kindly ask you to contribute either through creating a PR or sending us an email so that we can resolve the thread. You can reach us at support @ nft.storage. Thanks!
