### ISSUE TITLE
How do I Upload images to get a Cid? 

### ISSUE THREAD

**Issue by FelipeDiasR** [nftstorage/nft.storage#2736]
I need help to understand how I can upload Images to get The CID on the New NFT storage.

**Comment by elizabeth-griffiths** [comment]
For the new version, first mint your NFTs then send us the NFT data—metadata and imagery CIDs, blockchain(s) minted on, contract address and token IDs. We preserve these in long term Filecoin storage. Note that you need to upload the data to IPFS to get CIDs separately, we recommend using Pinata or Lighthouse with our referral links to support NFT.Storage: 
https://nft.storage/blog/announcing-our-new-partnerships-with-pinata-and-lighthouse
