### ISSUE TITLE
how can i upload a collection?

### ISSUE THREAD

**Issue by TheRabbidInc** [nftstorage/nft.storage#2738]
Hello! I've been using nftup for a while now, until it got decommissioned. Currently I am trying to upload an nft collection on app.nft.storage, but i can see it requires me to upload the cid, which clearly i do not have. The collection is classically made of pngs and json files. 
Please help!

Thank you

**Comment by elizabeth-griffiths** [comment]
For the new version, first mint your NFTs then send us the NFT data—metadata and imagery CIDs, blockchain(s) minted on, contract address and token IDs. We store these in long term Filecoin storage. Note that you need to upload the data to IPFS to get CIDs separately, we recommend using Pinata or Lighthouse with our referral links to support NFT.Storage: 
https://nft.storage/blog/announcing-our-new-partnerships-with-pinata-and-lighthouse
