### ISSUE TITLE
Can I pin my files already uploaded to ipfs? 

### ISSUE THREAD

**Issue by WildyPixel** [nftstorage/nft.storage#2741]
I bought storage. But it seems a little different from what I expected.

Can I pin my files already uploaded to ipfs?

**Comment by elizabeth-griffiths** [comment]
For the storage you bought, first mint your NFTs then send us the NFT data—metadata and imagery CIDs, blockchain(s) minted on, contract address and token IDs. We store these in long term Filecoin storage to preserve your NFT data. Note that you need to upload the data to IPFS separately, we recommend using Pinata or Lighthouse with our referral links to support NFT.Storage: 
https://nft.storage/blog/announcing-our-new-partnerships-with-pinata-and-lighthouse

**Comment by WildyPixel** [comment]
There are some parts I don't understand. Why is NFT's contraact address needed?  Isn't it just uploading to ipfs and doing a pin?

What to make sure is 
1. This service is used to pin files that have already been uploaded to IPFS.
2. I cannot pin files that has not been minted.

Is this correct?

So, does that mean I can pin my files, after uploading to ipfs and wait until all nfts of my collections are minted?

**Comment by elizabeth-griffiths** [comment]
Yes, that's correct. 

The data is preserved in long term Filecoin storage—it is not pinned anywhere. It's like a back up for your NFT data.

For your data to be in hot storage, and pinned to IPFS, you need to upload the data to IPFS separately, we recommend using Pinata or Lighthouse with our referral links to support NFT.Storage: 
https://nft.storage/blog/announcing-our-new-partnerships-with-pinata-and-lighthouse
