### ISSUE TITLE
NFT Up not working

### ISSUE THREAD

**Issue by lovidlovid** [nftstorage/nft.storage#2742]
It seems stuck on the upload.

**Comment by elizabeth-griffiths** [comment]
Hi there, Is that the Lovid that we know and are friends with? 

We sent out email communications about NFTUp changing beginning in April. Here's the update:

Here is the latest information regarding NFT.Storage Classic, including NFTUp, and your data. As of 30 June 2024, no new uploads to the Classic product (including NFTUp) will be accepted but if you have used the products before your data is safe. Your data is safely stored and accessible via the NFT.Storage Gateway and in decentralized long-term storage in the Filecoin Network. However, over time, latency and availability may degrade.

Check out the new version of NFT.Storage. For the new version, first mint your NFTs then send us the NFT data—metadata and imagery CIDs, blockchain(s) minted on, contract address and token IDs. We store these in long term Filecoin storage. Note that you need to upload the data to IPFS separately, we recommend using Pinata or Lighthouse with our referral links to support NFT.Storage: 
https://nft.storage/blog/announcing-our-new-partnerships-with-pinata-and-lighthouse

Let us know if you have any questions.

Thanks,
Elizabeth

**Comment by lovidlovid** [comment]
Hi Elizabeth!
This is the same LoVid. Thanks for the update - we had seen the
notification before but hadn't understood all of the details.  We will try
Pinata now. We also received an invite to be part of the NFT.Storage
community a little while back but had some questions about the contract.
If we didn't miss the boat and that's still of interest, let us know and
maybe we can discuss that a bit more?
Best,
T/K
