### ISSUE TITLE
API Key coming back with error

### ISSUE THREAD

**Issue by L3fty913** [nftstorage/nft.storage#2743]
When trying to connect to the api via Solana CLI we keep getting an api key error 

8d6295aa.3ab1c78461ee4008b2b0c1964b2c5778

**Comment by elizabeth-griffiths** [comment]
The original NFT.Storage product (now called NFT.Storage Classic) includes NFTUp.
To align our services more closely with our community's needs and ensure the sustainability of our model, we're updating our service offerings. We'll continue to offer the current product under the name NFT.Storage Classic for existing uploads prior to 30 June 2024 , but no new uploads to the Classic product will be accepted as of 30 June 2024 at 5pm EST. 

Now, you can use the new version of the product at https://app.nft.storage/.

For the new version, first mint your NFTs then send us the NFT data—metadata and imagery CIDs, blockchain(s) minted on, contract address and token IDs. We preserve these in long term Filecoin storage. Note that you need to upload the data to IPFS separately, we recommend using Pinata or Lighthouse with our referral links to support NFT.Storage: 
https://nft.storage/blog/announcing-our-new-partnerships-with-pinata-and-lighthouse
