### ISSUE TITLE
Storing files

### ISSUE THREAD

**Issue by jayp84847** [nftstorage/nft.storage#2744]
**What product are you using?**
Select one:
*  NFT.Storage Classic - NFTUp

**What is the problem?**
Am using NFTUp app on Mac. Its showing **Error: storing files: API undergoing maintenance, check https://status.nft.storage for more info** Error. Will it take more time?

**Comment by elizabeth-griffiths** [comment]
The original NFT.Storage product (now called NFT.Storage Classic) includes NFTUp. 
To align our services more closely with our community's needs and ensure the sustainability of our model, we're updating our service offerings. We'll continue to offer the current product under the name NFT.Storage Classic for existing uploads prior to 30 June 2024 , but no new uploads to the Classic product will be accepted as of 30 June 2024 at 5pm EST. 

Now, you can use the new version of the product at https://app.nft.storage/.

For the new version, first mint your NFTs then send us the NFT data—metadata and imagery CIDs, blockchain(s) minted on, contract address and token IDs. We preserve these in long term Filecoin storage. Note that you need to upload the data to IPFS separately, we recommend using Pinata or Lighthouse with our referral links to support NFT.Storage: 
https://nft.storage/blog/announcing-our-new-partnerships-with-pinata-and-lighthouse
