### ISSUE TITLE
Uploading the images folder

### ISSUE THREAD

**Issue by Vidensnft** [nftstorage/nft.storage#2745]
Hello !
 I generated my NFT collection and I want to upload the image folder to have the CID, except that I don't see how to do that on my 
 dashboard

Best Regard !

**Comment by elizabeth-griffiths** [comment]
First mint your NFTs then send us the NFT data—metadata and imagery CIDs, blockchain(s) minted on, contract address and token IDs. We preserve these in long term Filecoin storage. 

Note that you need to upload the data to IPFS separately, we recommend using Pinata or Lighthouse with our referral links to support NFT.Storage: 
https://nft.storage/blog/announcing-our-new-partnerships-with-pinata-and-lighthouse
