### ISSUE TITLE
Can't upload, error when uploading csv

### ISSUE THREAD

**Issue by rbb77** [nftstorage/nft.storage#2746]
Hi 

I'm getting an 'invalid ID or CID' error when uploading my csv file, I don't understand why because my csv it's correct

Ethereum Contract address 0x93c791a83bf5844433ea4600dafd85b65116ff34

[nft-storage-state.csv](https://github.com/user-attachments/files/16873537/nft-storage-state.csv)

My files are already pinned in Pinata, I've just copied the CIDs from pinata into the csv file.

Thanks for the support
Best

**Comment by jayp84847** [comment]
Did NFT UP closed services for NFTs upload from NFT UP application?

**Comment by elizabeth-griffiths** [comment]
Ensure your CSV file follows the specified structure:
Each row represents a token.

The CSV file should include columns for token ID and content ID (cid).

Example structure:

tokenID, cid
1, bafy...
2, bafz...
3, bafx...

**Comment by rbb77** [comment]
My csv looks like this, my cids does not start with baf, start with Qm, is because of this that nft storage doesn't import them?

tokenID, cid
1, QmTNEvTTX5HdvL3RbCypBZQ79mN4uy8yQkboRz5wDrN8Wm
2, QmcPUme6MgkRDhQNhBMLVVqsLWqPDA2pbcumiRy5M58sg7
3, QmPwnTa25...

**Comment by elizabeth-griffiths** [comment]
I will check with the team and get back to you as quickly as possible. For faster response times, email support@

**Comment by rbb77** [comment]
For anyone out there with the same problem reading this, 
just delete the spaces after the comma and it will work :

tokenID, cid
1,QmTNEvTTX5HdvL3RbCypBZQ79mN4uy8yQkboRz5wDrN8Wm
2,QmcPUme6MgkRDhQNhBMLVVqsLWqPDA2pbcumiRy5M58sg7
3,QmPwnTa25...
