### ISSUE TITLE
NFT UP

### ISSUE THREAD

**Issue by jayp84847** [nftstorage/nft.storage#2747]
Did NFT UP closed services for NFTs upload from NFT UP application?

<img width="870" alt="Screenshot 2024-09-07 at 2 59 21 PM" src="https://github.com/user-attachments/assets/89a97682-97b7-4b23-aff3-6d8236708ac1">

**Comment by elizabeth-griffiths** [comment]
The original NFT.Storage product (now called NFT.Storage Classic) includes NFTUp. 
To align our services more closely with our community's needs and ensure the sustainability of our model, we're updating our service offerings. We'll continue to offer the current product under the name NFT.Storage Classic for existing uploads prior to 30 June 2024 , but no new uploads to the Classic product will be accepted as of 30 June 2024 at 5pm EST. 

Now, you can use the new version of the product at https://app.nft.storage/.

For the new version, first mint your NFTs then send us the NFT data—metadata and imagery CIDs, blockchain(s) minted on, contract address and token IDs. We preserve these in long term Filecoin storage. Note that you need to upload the data to IPFS separately, we recommend using Pinata or Lighthouse with our referral links to support NFT.Storage: 
https://nft.storage/blog/announcing-our-new-partnerships-with-pinata-and-lighthouse
