### ISSUE TITLE
Is there a way to migrate classic storage to paid?

### ISSUE THREAD

**Issue by h8ku** [nftstorage/nft.storage#2748]
There are some CIDs I need migrated that no longer respond at all on classic storage

**Comment by elizabeth-griffiths** [comment]
Thank you for reaching out, and I'm sorry to hear you're encountering an issue.

NFT.Storage Classic, our original service, will continue to support existing uploads but does not allow new uploads after June 30, 2024. To meet our community's evolving needs, we've launched a new flagship product at https://app.nft.storage/. This platform is where you can back up off-chain NFT data, it is not hot storage.

Why You Should Copy Your NFT.Storage Classic Data:
As we’ve transitioned to the new platform, we recommend copying any existing uploads you have stored in NFT.Storage Classic to an additional hot storage platform.

You can find more information on how to do this in our guide: [Why Copy Your NFT.Storage Classic Data and How to Do It](https://nft.storage/blog/why-copy-your-nft-storage-classic-data-and-how-to-do-it).

If you continue to experience issues logging in or need any assistance, please don’t hesitate to reach out.

**Comment by h8ku** [comment]
> Thank you for reaching out, and I'm sorry to hear you're encountering an issue.
> 
> NFT.Storage Classic, our original service, will continue to support existing uploads but does not allow new uploads after June 30, 2024. To meet our community's evolving needs, we've launched a new flagship product at https://app.nft.storage/. This platform is where you can back up off-chain NFT data, it is not hot storage.
> 
> Why You Should Copy Your NFT.Storage Classic Data: As we’ve transitioned to the new platform, we recommend copying any existing uploads you have stored in NFT.Storage Classic to an additional hot storage platform.
> 
> You can find more information on how to do this in our guide: [Why Copy Your NFT.Storage Classic Data and How to Do It](https://nft.storage/blog/why-copy-your-nft-storage-classic-data-and-how-to-do-it).
> 
> If you continue to experience issues logging in or need any assistance, please don’t hesitate to reach out.

Is there a way I can just 1 click pay to move the data?

**Comment by elizabeth-griffiths** [comment]
How about 3 clicks? :)
I'll paste the instructions here to use our recommended vendors: 

Lighthouse
Step 1: Create a Lighthouse account using our [referral link](https://files.lighthouse.storage/?referby=NFTStorage).
Step 2: Use the Migration Tool: https://docs.lighthouse.storage/lighthouse-1/how-to/migrate-files

Pinata
Step 1:Create a Pinata account using our [referral link](https://www.pinata.cloud/nft-storage-pinata).
Step 2:Log in to your NFT.Storage Classic account. Navigate to the API keys section and create a new API key.
Step 3: ILog in to your Pinata account. Use the API key from NFT.Storage to integrate with Pinata.
Step 4: Start Copying. Begin the copy process by following the instructions provided by Pinata.
Exclusive Offer: Use the discount code NFTSTORAGE50 at checkout to enjoy 50% off your first month on any paid plan.

For detailed instructions, visit the [Pinata Migration Guide](https://docs.pinata.cloud/quickstart/migrating-from-nft-storage).
