### ISSUE TITLE
Please stop charging me 

### ISSUE THREAD

**Issue by Mtmarkowitz** [nftstorage/nft.storage#2755]
I bought one order of 10GB of storage but my bank has over 7 charges from your company. Please - I only want one order of 10 for 29.99. Am I being scammed?
![IMG_8139](https://github.com/user-attachments/assets/d4e6294e-f20e-4044-af2b-4b754194cd2d)

**Comment by elizabeth-griffiths** [comment]
Thank you for bringing this to our attention. I can see from the screenshot that there are several pending payments listed from our company. However, after reviewing our system, I can confirm that you were only charged once for your 10GB storage order at $29.99.

The additional charges you're seeing are likely pending authorizations from your bank, which should be removed shortly. If these pending payments do not clear in the next few days, I recommend contacting your bank for further clarification.

Please rest assured that you are not being scammed, and we're here to help with any additional questions or concerns.

Best regards,
Elizabeth

**Comment by Mtmarkowitz** [comment]
Ok cool - yeah, I called them - they told me that for every attempt it
automatically does a second attempt or something like that hence the
multiple attempts. I cleared it with them. Thank you for your kind and
thorough response  though.

Melissa Markowitz
561 856 2673
***@***.***
www.MelissaMarkowitz.com
