### ISSUE TITLE
Old account on NFT storage I can't log in

### ISSUE THREAD

**Issue by alienuslegendary** [nftstorage/nft.storage#2756]
I can't log in to NFT storage because my account is old. How can I solve this? The button that indicates to log in with the old account is showing a 404 error. 
old account email: alienuslegendary@gmail.com

![404](https://github.com/user-attachments/assets/4d4b1f65-02fe-46a0-903c-28f8652b2f55)

**Comment by Terabithiana** [comment]
There is not much evidence of reactions within one working day. Can this obvious error be corrected quickly?

**Comment by elizabeth-griffiths** [comment]
Hi Alienuslegendary,

Thank you for reaching out, and I’m sorry for the delay. The past week has been unusual for us, as the core team has been unwell and we missed the notification for this issue. We sincerely apologize for the inconvenience and appreciate your patience.

To access your NFT.Storage Classic account, please log in here: https://classic-app.nft.storage/login.

Why You Should Copy Your NFT.Storage Classic Data:
As we’ve transitioned to the new platform, we recommend copying your data from NFT.Storage Classic to ensure its accessibility. You can find more information on how to do this in our guide: [Why Copy Your NFT.Storage Classic Data and How to Do It](https://nft.storage/blog/why-copy-your-nft-storage-classic-data-and-how-to-do-it).

If you continue to experience issues logging in or need any assistance, please don’t hesitate to reach out.

Best,
Elizabeth

**Comment by Terabithiana** [comment]
The error still exists! Take a look here: https://classic.nft.storage/login

![grafik](https://github.com/user-attachments/assets/b0734ebb-1c97-46c7-91e6-22d22abf50fd)
