### ISSUE TITLE
Classic login site leads to 404, unable to migrate to new account

### ISSUE THREAD

**Issue by RowanSkie** [nftstorage/nft.storage#2759]

**Comment by elizabeth-griffiths** [comment]
Thank you for reaching out! If you're looking to access your NFT.Storage Classic account, you can log in here: https://classic-app.nft.storage/login.

Why Copy Your NFT.Storage Classic Data and How to Do It
We recommend copying your data from NFT.Storage Classic to ensure its long-term access. As we’ve transitioned to the new platform, it's important to safeguard your existing uploads.

To learn more about why and how to copy your data, please refer to our guide here: [Why Copy Your NFT.Storage Classic Data and How to Do It](https://nft.storage/blog/why-copy-your-nft-storage-classic-data-and-how-to-do-it).

If you have any further questions or need assistance, feel free to contact us.

Best,
[Your Name]
