### ISSUE TITLE
Having some trouble Uploading Metadata

### ISSUE THREAD

**Issue by rizziospace** [nftstorage/nft.storage#2761]
I am having some trouble with this metadata uploading from bueno. Status is not changing to completed.

**Comment by elizabeth-griffiths** [comment]
We wanted to update you on the latest information regarding NFT.Storage Classic, including NFTUp, and your data. As of 30 June 2024, no new uploads are being accepted to the Classic product (including NFTUp). Rest assured, if you've previously used these products, your data is stored and remains accessible via the NFT.Storage Gateway and in decentralized long-term storage on the Filecoin Network. However, please be aware that over time, latency and availability may degrade.
To ensure your data remains easily accessible, we recommend copying it to an additional hot storage provider. You can find detailed instructions on how to do that here:[ Link](https://nft.storage/blog/why-copy-your-nft-storage-classic-data-and-how-to-do-it).
We also encourage you to explore the new version of NFT.Storage. In the new version, simply mint your NFTs and send us the NFT data—metadata and imagery CIDs, blockchain(s) minted on, contract address, and token IDs. We will store these in long-term Filecoin storage. Please note that you will need to upload the data to IPFS separately. We recommend using Pinata or Lighthouse for this, and you can support NFT.Storage by using our referral links:[ Link](https://nft.storage/blog/announcing-our-new-partnerships-with-pinata-and-lighthouse).
Thank you for your continued support. If you have any questions, feel free to reach out.
