### ISSUE TITLE
Uploading Video Files to nft.storage

### ISSUE THREAD

**Issue by lovidlovid** [nftstorage/nft.storage#2765]
We would like to upload video files to nft.storage and we purchased space. Unfortunately the site says only CSVs are accepted. We also tried to use NFT Up but that still seems broken and not able to access the extra data that we purchased. Is it no longer possible to upload video files to IPFS through nft.storage? Or are we missing something?

**Comment by elizabeth-griffiths** [comment]
Hi Lovid, 

So lovely to hear from you.

We wanted to update you on the latest information regarding NFT.Storage Classic, including NFTUp, and your data. As of 30 June 2024, no new uploads are being accepted to the Classic product (including NFTUp). Rest assured, if you've previously used these products, your data is stored and remains accessible via the NFT.Storage Gateway and in decentralized long-term storage on the Filecoin Network. However, please be aware that over time, latency and availability may degrade.
To ensure your data remains easily accessible, we recommend copying it to an additional hot storage provider. You can find detailed instructions on how to do that here:[ Link](https://nft.storage/blog/why-copy-your-nft-storage-classic-data-and-how-to-do-it).
We also encourage you to explore the new version of NFT.Storage. In the new version, simply mint your NFTs and send us the NFT data—metadata and imagery CIDs, blockchain(s) minted on, contract address, and token IDs. We will store these in long-term Filecoin storage. Please note that you will need to upload the data to IPFS separately. We recommend using Pinata or Lighthouse for this, and you can support NFT.Storage by using our referral links:[ Link](https://nft.storage/blog/announcing-our-new-partnerships-with-pinata-and-lighthouse).

Additionally, I want to be sure you receive the most up to date information in the future. Would you like us to add a different email address to the mailing list? If so, I'd recommend sending us a quick note from the email address to keep your email private. You can send it to support @ nft.storage.

Thank you for your continued support. If you have any questions, feel free to reach out.
