### ISSUE TITLE
NFT.Storage: Deal Status does not progress

### ISSUE THREAD

**Issue by Entron001** [nftstorage/nft.storage#2770]
**What product are you using?**
NFT.Storage

**What is the problem?**
Deal Status of all my pinned CIDs remain in "started" status since 2 days

**What did you expect to happen?**
I expected the status to change to any of the other statuses (PinningFailed/InQueue/DataCapExceed/Complete) as stated in the docs

**Comment by NFTStorageGithub** [comment]
Thank you for reaching out and letting us know about the issue with your pinned CIDs remaining in the "started" status.

We’re currently undergoing a significant system upgrade aimed at making the pinning process faster and more efficient. This may cause some delays in status updates.

Please check back in 24 hours to see if the statuses have progressed. If they haven’t, let us know by replying to this email with your account email or GitHub username, and we’ll investigate further.

We appreciate your patience and understanding as we improve the platform.

**Comment by NFTStorageGithub** [comment]
Please re-open this ticket if the problem is not resolved
