### ISSUE TITLE
Extend recursive pinning files from inside out in storeDirectory

### ISSUE THREAD

**Issue by jnthnvctr** [nftstorage/nft.storage#292]
See gist here: https://gist.github.com/sbauch/9c49632abc4352b131a33e9438efd008

Objective would be to pin a directory of JSON metadata under the same hash such that that hash can be used as the baseUri. This could be useful when one wants to pin 10k json files for a pfp project, and the user wants those to all be under the same hash (that i can use in baseUri and then append token ID to the path). 

In the Gist, you can see how Sam from 0xEssential tackles this): first pinning an image, getting the cid, and then using the cid to manually pin the json object inside the directory in order to share the same parent hash. Extend the same idea of recursively pinning files from inside out in storeDirectory could be a nice win!

**Comment by sbauch** [comment]
thanks for opening this! thought i would add a little more context.

NFT.storage works perfectly for me when doing more 1 of 1 NFTs. I've got a repo here that uses the project in a dApp that allows an artist to mint a piece against their own contract and into their own wallet - https://github.com/0xEssential/smartist-contract

But when I started thinking about how to use this with an NFT project that's more similar to a 10k generative pfp thing, that's when things started to break down.

You all probably have a better understanding of this all, but my first pass on the right way to do something like this is to pin a bunch of metadata JSON files under one content hash. that way we dont have to map 10k hashes to token Id. 

I wrote a blog post about how to do a metadata reveal for a pfp project here that elucidates a bit more - https://docs.wrasslers.com/blog/how-to-reveal-nft-metadata/

**Comment by mGonzim** [comment]
@jnthnvctr I'm looking to do the same thing. Did you find anything?

**Comment by dchoi27** [comment]
@jchris @cmunns @JeffLowe for thinking about the large directory uploader (#1015) and how to make it really useful to support large NFT drops, we might consider a feature that mass generates metadata and uploads the metadata files to the same directory. the user would have to configure what goes into the metadata based on the files they've uploaded and what they want to go into the metadata, but I think we probably need something like this to maximize the usefulness of the tool.
