### ISSUE TITLE
Webpack import error using NFT.Storage

### ISSUE THREAD

**Issue by max-andrew** [nftstorage/nft.storage#305]
After running the `build` command in my Next.js environment, I get the webpack error:

    Failed to compile.

    ./node_modules/@ipld/car/esm/lib/decoder.js
    Attempted import error: 'decode' is not exported from '@ipld/dag-cbor' (imported as 'decodeDagCbor').

The code runs successfully in development. Webpack and Node are up to date.

**Comment by dchoi27** [comment]
@hugomrdias any thoughts?

**Comment by dchoi27** [comment]
@vasco-santos any thoughts?

**Comment by vasco-santos** [comment]
Hey @max-andrew 

What webpack version are you using? Webpack@4 does not support map exports, and this is probably the issue. But running in dev makes it stranger. If you have a replication repo I could have a look would be great

Also, if you do `npm ls @ipld/car` and `npm ls @ipld/dag-cbor`, what are the versions you have?

**Comment by max-andrew** [comment]
I'm running the latest version of webpack 5. I can work on getting a strictly replication repo but before then you could check out my HackFS project at github.com/max-andrew/rightoken to see if anything jumps out.

@ipld/car@3.1.16
@ipld/dag-cbor@6.0.9

**Comment by max-andrew** [comment]
Hey @vasco-santos -- I figured this out! I was using the Zora SDK `@zoralabs/zdk`, which I assume caused a naming collision.

[I replicated the error in a repo here.](https://github.com/max-andrew/nft-storage-test) Running `build` should fail with the error given above, but will succeed after uninstalling `@zoralabs/zdk`.

**Comment by nickadamson** [comment]
> Hey @vasco-santos -- I figured this out! I was using the Zora SDK `@zoralabs/zdk`, which I assume caused a naming collision.
> 
> [I replicated the error in a repo here.](https://github.com/max-andrew/nft-storage-test) Running `build` should fail with the error given above, but will succeed after uninstalling `@zoralabs/zdk`.

Can confirm. Seems to become an issue when using yarn as package manager instead of npm. I've had it happen a few times now. 
Deleting ./node_modules and package-lock.json/yarn.lock (as well as any other cached, build, etc files) and reinstalling with npm is the fastest solution I've come across.

**Comment by dchoi27** [comment]
@yusefnapora thoughts on where we could add to docs? maybe a section in the Github README? eventually maybe we add as a section in NFT.School / a future docs page for NFT.Storage
