### ISSUE TITLE
Add end-to-end tests for uploading content and run them automatically and often

### ISSUE THREAD

**Issue by alanshaw** [nftstorage/nft.storage#356]
Add end-to-end tests for:

- [ ] uploading via http
- [ ] uploading via client
- [ ] uploading via website (P3)
- [ ] read uploaded data from nftstorage.link

Run them every n minutes, and raise an alert on failure. For bonus points, time how long each run takes and push it to prometheus so we an chart upload perf over time.

**Comment by dchoi27** [comment]
Coordinate with what's being done with #342

**Comment by dchoi27** [comment]
Future (can make into a separate issue): Test uploads to individual nodes in the Cluster

**Comment by dchoi27** [comment]
Split website one into its own issue

**Comment by fabiolrodriguez** [comment]
Related to https://github.com/web3-storage/web3.storage/issues/421

**Comment by dchoi27** [comment]
@gobengo mind linking your PR here and closing this issue?
