### ISSUE TITLE
Clean up styles for NFT.Storage API docs

### ISSUE THREAD

**Issue by dchoi27** [nftstorage/nft.storage#362]
@alanshaw for these docs? https://ipfs-shipyard.github.io/nft.storage/client/

**Comment by alanshaw** [comment]
No these ones: https://nft.storage/api-docs/

This is low priority but it would be good to stort things like text sizes, fonts and colours to be more in keeping with the rest of the site.

**Comment by dchoi27** [comment]
@Codigo-Fuentes if you have a chance feel free to pick this up, these docs are super ugly
