### ISSUE TITLE
Add "First" pagination buttons to the Files page

### ISSUE THREAD

**Issue by dchoi27** [nftstorage/nft.storage#368]
We should have "First" and "Last" pagination buttons on the Files page since some users have thousands of files stored on their account.

## Scoping adjustment
- scoping this to first page only, and ticketing last page separately due to complexity.

**Comment by alanshaw** [comment]
We could add a "first" button easily but adding "last" is blocked on https://github.com/ipfs-shipyard/nft.storage/issues/331
