### ISSUE TITLE
Figure out if we need to have pin locations

### ISSUE THREAD

**Issue by Gozala** [nftstorage/nft.storage#371]
This came up during the db migrations call, because it was left out in the @hugomrdias's schema while still present in web3.storage schema. @hugomrdias also pointed out that maybe pin location should also include `multiaddrs`.

**Comment by Gozala** [comment]
Quoting @alanshaw's comment from the [meeting notes](https://hackmd.io/ZM-sDUX-TTuowEM2Hp28tw?both#Action-Items)

> This is a separate concern, not part of the database migration. We should stick with what we have in both projects for now.

**Comment by Gozala** [comment]
@alanshaw, @hugomrdias I think @alanshaw makes a good point there, however I'll leave it up to you to either close it as resolved with a decision to leave things as is or keep it open for post-migration discussion.

**Comment by alanshaw** [comment]
AI for @alanshaw: write up what we discussed and propose rough for each product (although consider we may want to tackle this as part of the grand unification)

Reminder notes: like nft.storage, but also with the extra bits like region, delegates, etc. that come from an API that can be cached etc. - lets define API for asking information for a CID(s) at a given pinning location (Cluster/Pinata/S3).

**Comment by dchoi27** [comment]
@alanshaw does #1030 mean we are storing the pin locations of CIDs? Can we close this issue, or is this issue bigger than that?
