### ISSUE TITLE
Demonstrate hasura schema migrations tool

### ISSUE THREAD

**Issue by Gozala** [nftstorage/nft.storage#382]
Hasura has it's [own migrations tool](https://hasura.io/docs/latest/graphql/core/migrations/index.html) as it needs to track metadata for the query endpoints. If we end up using hasura it would be important to use their tool as opposed to alternatives to keep metadata and db schema in sync.

**Comment by alanshaw** [comment]
@Gozala please run a workshop asap (after DB migration).

**Comment by the-simian** [comment]
related to #379

**Comment by dchoi27** [comment]
Can we close this?

**Comment by Gozala** [comment]
I'll schedule a demo next week to force myself into doing this!

**Comment by dchoi27** [comment]
Closing this
