### ISSUE TITLE
docs/faq: explain alternate CID encodings

### ISSUE THREAD

**Issue by yusefnapora** [nftstorage/nft.storage#420]
This is based on the discussion in https://github.com/ipfs-shipyard/nft.storage/issues/417#issuecomment-917815040 where the default base32 CID encoding was too large to fit in the limits of an existing smart contract, but base36 was compact enough to work.

We should add an FAQ entry to explain that CIDs can be converted into alternate encodings, and mention base36 as a more compact alternative that's well supported by gateways, etc.

Could link to ProtoSchool [Anatomy of a CID](https://proto.school/anatomy-of-a-cid/) lesson.

**Comment by dchoi27** [comment]
Can mention `multiformats` as a thing that can help reencode the CID:
```
import { CID } from 'multiformats/cid'
import { base2 } from 'multiformats/base2'

const cid = CID.parse('bafy...') // base32
console.info(cid.toString(base2)) // 010101...
```
