### ISSUE TITLE
SEO optimizations

### ISSUE THREAD

**Issue by dchoi27** [nftstorage/nft.storage#437]
Ping @dchoi27 for link to Google Sheet with some easy SEO optimizations

- [x] complete seo optimizations as listed in spreadsheet https://docs.google.com/spreadsheets/d/1-nQrw4n8C_Tr3IOBRg6Q52ALpy8ymy9R1y23XB7EkxI/edit
- [x] add robots.txt and sitemap.xml files to the build (as seen done here https://github.com/web3-storage/web3.storage/pull/517/files )
- [x] update metadata (similarly as seen done here https://github.com/web3-storage/web3.storage/pull/522/files )

**Comment by alanshaw** [comment]
@dchoi27 can you link the spreadsheet plz?

**Comment by dchoi27** [comment]
https://docs.google.com/spreadsheets/d/1gTAWWpxEmjS3Ux1TwYweb0NLFX41kNYMqsMEP_GtwEE/edit#gid=1109174869

**Comment by JeffLowe** [comment]
Per callout in slack that this shoudl be passed over to Adam, reassigning to @Codigo-Fuentes
