### ISSUE TITLE
Add as an IPFS pinning service? (IPFS Desktop)

### ISSUE THREAD

**Issue by melMass** [nftstorage/nft.storage#469]
Hi,

I'm trying to use `nft.storage` as an IPFS pinning service.
I managed to add it using the following values:

API Endpoint: https://api.nft.storage/
Secret access token: $API_KEY (using a key created on nft.storage)

It is properly added as seen here:
![image](https://user-images.githubusercontent.com/7041726/134785391-5a34e69e-6f98-45cf-973c-a062c1ce6d0d.png)

I can then use the `Set Pinning` function on my file setting it to nft.storage
![image](https://user-images.githubusercontent.com/7041726/134785409-bbe676c8-4355-476a-a000-32c36f550ef8.png)

But after a few minutes the pinning is no more:
![image](https://user-images.githubusercontent.com/7041726/134785426-e9b9e40c-4947-404a-9412-68089ea432b2.png)

Can nft.storage be used like that, and if so how can I properly check the pinning state of an asset?

Bear in mind that I'm quite new to IPFS and all concepts aren't crystal clear to me, yet I'm eager to learn more.

Thanks

**Comment by melMass** [comment]
Oh I just discovered this:

![image](https://user-images.githubusercontent.com/7041726/134785547-d0a419a9-b02b-4696-8f0a-37e641765c69.png)

I'm not sure to understand the layout:
- 1st link points me to an IPFS directory containing my two files
- 2nd link to the mp4
- 3rd link to the gif

Is that expected? And the size being 0 is it ok?

**Comment by dchoi27** [comment]
Yes, the size should update after the backend's had a chance to do a roundtrip grabbing the data. If it can't find the data on the network it would remain 0.
