### ISSUE TITLE
Make it a PWA and Share Target

### ISSUE THREAD

**Issue by rafaelramalho19** [nftstorage/nft.storage#474]
- We should make nft.storage a PWA so we can use it as a Share Target for mobile phones. That way, users can quickly share files directly from their file explorer/gallery, helping us get users that would normally just upload that file to another platform. 
- More info at: https://web.dev/web-share-target/
---
- Making this app a [PWA has other benefits too](https://love2dev.com/pwa/benefits/).

**Comment by JeffLowe** [comment]
Per slack conversation, assigning to @Codigo-Fuentes

**Comment by dchoi27** [comment]
Not high prio, unassigning from all for now

**Comment by dchoi27** [comment]
Don't think we'll end up doing this, closing for now!
