### ISSUE TITLE
Document Niftysave (as of fall 2021)

### ISSUE THREAD

**Issue by the-simian** [nftstorage/nft.storage#477]
* [x] Schemas 
* [ ] Domain Concepts
* [ ] Migration utility
* [ ] Scraper - Architecture
* [ ] Scraper - Sequence of events
* [ ] Services 
    * [ ] hasura
    * [ ] heroku
    * [ ] gql api

     
(this list might be amended as we cover more things that should be documented)

**Comment by JeffLowe** [comment]
Due to rearchitecture, closing this out as irrelevant.  
We have a quickstart guide for SST
And we will have live architecture and orchestreation view. 
Jesse wil be running a workshop soon .
