### ISSUE TITLE
Consolidate secrets into a single location

### ISSUE THREAD

**Issue by alanshaw** [nftstorage/nft.storage#483]
We currently have secrets in cloudflare (via `wrangler secret put`), in github repo secrets and also in `.env.local` files.

How about we remove wrangler secrets, and have staging/prod secrets only in github and bundle them with the application at build time. We use `.env.local` for secrets in local dev.

We should also have a `.env.local` at the top level of the repo to allow sharing of config/secrets in local dev.

It'll reduce the number of places to look for a secret and removes the overhead of using `wrangler secret put` for new developers.

It's roughly equivalent to cloudflare injecting the vars as globals but we lose the ability to update secrets dynamically, i.e. we need to redeploy to get a secret updated. Note that due to the way we access and cache secrets in `constants.js` we already have to do this.

**Comment by hugomrdias** [comment]
@alanshaw https://github.com/nftstorage/nft.storage/pull/999 unified .env in the root except for nextjs which needs it in the website folder.
This issue also talks about `wrangler secret put` and make that only live in the workflow, do you want to keep this issue for that or close it ?
