### ISSUE TITLE
Clean up JS client docs

### ISSUE THREAD

**Issue by dchoi27** [nftstorage/nft.storage#508]
The JS client docs are pretty ugly. We should clean them up to have a similar look / feel as the NFT.Storage website.

They also feel unintuitive for me, but I'm not a JS developer, so if the docs are following common patterns, think it's fine.

https://nft.storage/api-docs/

**Comment by JeffLowe** [comment]
Note:  https://github.com/web3-storage/web3.storage/issues/2156 calls for unified api docs for web3.  likely need to keep that implementation in mind when reexamining this.
