### ISSUE TITLE
Merge the complete data sets of nft.storage and niftysave

### ISSUE THREAD

**Issue by the-simian** [nftstorage/nft.storage#515]
This is a placeholder issue to represent the large goal of ultimately combining the data in nft.storage and niftysave into a unified dataset. Schemas have been aligned to this represents the actual hydration of tables in a unified dataset. More subitems will be added as they are discovered

**Comment by JeffLowe** [comment]
Moving this to "Needs Discussion" column.  We will work to slowly flesh this out a bit asynchronously (identifying known tasks and blockers/dependencies), but to move this forward properly, we'll need a dedicated worksession for planning it out.  
@alanshaw @the-simian who all should be in this meeting?  Let's list them out here and we'll work on getting a worksession scheduled.

**Comment by JeffLowe** [comment]
closing...not relevant with new weup architecture
