### ISSUE TITLE
niftysave could leverage *.storage API for content upload as opposed to cluster

### ISSUE THREAD

**Issue by Gozala** [nftstorage/nft.storage#527]
As we were rewiring niftysave to a new backend we realized it might be a good idea to switch piece of code that adds content to ipfs with *.storage API as opposed to talking to IPFS cluster directly because:

1. Our db records indicate failures when cluster was unreachable. In fact #520 was motivated by this failure rate.
2. web3.storage is more reliable as it would hold your content in S3 even if cluster has issues.
3. If we do assemble a CAR locally for the metadata.json we are guaranteed that computed CID will be the one pinned, even if cluster or our code changes hashing and chunking settings.
4. Thanks to no 2 we could avoid having to store CAR / metadata.json content on a side when cluster is failing for retrying it later.

In practice that would imply changing below piece of code, with an API call to *.storage API.

https://github.com/ipfs-shipyard/nft.storage/blob/f70fc527eca893d6e559f377046e54b11773b97b/packages/niftysave/src/cluster.js#L28-L54

Unfortunately niftysave would still need to continue reaching for cluster when fetching content for `tokenURI` as it needs to parse it (or it could be replaced with some other endpoint)

https://github.com/ipfs-shipyard/nft.storage/blob/main/packages/niftysave/src/ipfs.js#L22-L41

And it would still need to continue using cluster to pin content by ipfs URL as we do not want to fetch it just to upload it

https://github.com/ipfs-shipyard/nft.storage/blob/f70fc527eca893d6e559f377046e54b11773b97b/packages/niftysave/src/cluster.js#L58-L83

**Comment by JeffLowe** [comment]
We are using nft.storage client now.
