### ISSUE TITLE
Incongruently large DAGs

### ISSUE THREAD

**Issue by ribasushi** [nftstorage/nft.storage#55]
While most of the "maximum size" DAGs in the KVstore currently hover around ~55MiB, there is a single outlier dierectory of 8k entries clocking at 2.1GiB.

@hugomrdias asked for this ticket so he can investigate
https://ipfs.io/ipfs/QmWVsx8f8ZKFzvKykdty1wETMaeotnwofaMxM9sqAdBT4C ( might not load through a gateway: directory is way too large )

<img width="849" alt="image" src="https://user-images.githubusercontent.com/356110/113605434-efcd0500-9646-11eb-9456-1f303b00cdbb.png">

**Comment by alanshaw** [comment]
Closing this as #148 will hopefully stop the majority of this kind of abuse (assuming this is not NFT content).
