### ISSUE TITLE
Dedicated FAQ page

### ISSUE THREAD

**Issue by dchoi27** [nftstorage/nft.storage#555]
We should make a dedicated FAQ page on NFT.Storage where we can list an exhaustive list of FAQs. We can link from the top menu bar, as well as at the FAQs at the bottom of the main page.

- [x] add FAQs to top nav and bottom footer on main page
- [x] pull in FAQ content from main page and use as FAQ content https://nft.storage/
- [x] pull in additional FAQ content confirmed by @dchoi27 and/or @alanshaw

**Comment by alanshaw** [comment]
Candidate items:

* https://github.com/ipfs-shipyard/nft.storage/issues/546
* https://github.com/ipfs-shipyard/nft.storage/issues/514

**Comment by JeffLowe** [comment]
Per discussion in slack, reassigning to @Codigo-Fuentes

**Comment by JeffLowe** [comment]
@dchoi27 @alanshaw Do we have any other content (FAQs) to populate into this page other than the 4 links in above comment?
Also, is there a copywriter / content specialist on your side that needs to draft copy, or do you want us to take a first pass at the draft for the entries?

**Comment by dchoi27** [comment]
could you take a first pass, and then loop me and @yusefnapora in for review? thanks!
