### ISSUE TITLE
Drop obsolete erc721_import and erc721_import_by_nft tables

### ISSUE THREAD

**Issue by Gozala** [nftstorage/nft.storage#565]
Those made sense when we were ingesting in batches, as it allowed us to track which tokens were ingested in which batch. However new setup no longer batches imports so these tables are obsolete and should be dropped.

**Comment by the-simian** [comment]
do at the same time as #1353  and #1362

**Comment by elizabeth-griffiths** [comment]
We're closing this issue. If you still need help please open a new issue.
