### ISSUE TITLE
Support CIDv0

### ISSUE THREAD

**Issue by NoRulesJustFeels** [nftstorage/nft.storage#571]
I'm trying to use Nft.Storage for uploading the metadata for the Hic Et Nunc NFTs. It seems that the HEN v1 minting smart contract is checking that the metadata URI is exactly 53 chars long which means it only supports CIDv0. 

It's not clear if Nft.Storage supports CIDv0; I don't see anything in the docs for the Nft.Storage JS client library. By default, I'm always getting CIDv1 with Nft.Storage.

**Comment by NoRulesJustFeels** [comment]
Also, I tried the cids library but it seems the NFT.Storage  CIDs can't be converted to CIDv0 since I get this error when calling cid.toV0():
Cannot convert a non dag-pb CID to CIDv0

**Comment by dchoi27** [comment]
With the update to ipfs-car supporting raw leaves, can we close this @alanshaw ?

**Comment by dchoi27** [comment]
#991 will add to the docs how to use CIDv0. Closing this issue, let us know if any questions!
