### ISSUE TITLE
StoreDirectory sample doesn't work

### ISSUE THREAD

**Issue by LeonNicholls** [nftstorage/nft.storage#573]
Running this nft.storage example in a Chrome browser gives a cors error:
https://github.com/ipfs-shipyard/nft.storage/blob/main/packages/client/examples/browser/storeDirectory.html
<img width="928" alt="direrror" src="https://user-images.githubusercontent.com/564979/136786763-0cb2a4b7-5af8-4496-a074-4664ccf6cb71.png">

**Comment by NoRulesJustFeels** [comment]
Chrome Version 94.0.4606.81
I'm trying to upload the files in a folder (see attached zip of the folder)
[HTML.zip](https://github.com/ipfs-shipyard/nft.storage/files/7325693/HTML.zip)

**Comment by NoRulesJustFeels** [comment]
I've used both the Infura and Pinata IPFS APIs with the same set of files and they work fine. I haven't had to use CAR files with either of them.

**Comment by NoRulesJustFeels** [comment]
Tried the codesandbox but got the same error. Tried in incognito and it fails too.
Tried it in Firefox and got the same cors error.
Even tried it on a VPN but same error.
Even tried a different API key but the same error.
It only works if I exclude index.html.
