### ISSUE TITLE
how to update a directory?

### ISSUE THREAD

**Issue by rafinskipg** [nftstorage/nft.storage#596]
Hello, i'm having a hard time trying to understand the API for this. 

I want to upload a directory , for that i used client.storeDirectory which allows to upload different files. 

The thing is, now i want to add more files to the same directory. Is that possible? Can i update a directory?

Thanks

**Comment by dferendo** [comment]
Hi @dchoi27, is it possible to update the directory by only adding new files to the directory?

**Comment by dchoi27** [comment]
Hey, no it's not (it's a feature of content addressing). Take a look at the link I shared in the last post!
