### ISSUE TITLE
Create rate limits

### ISSUE THREAD

**Issue by dchoi27** [nftstorage/nft.storage#603]
To protect our infrastructure from individual users' activity, we should establish rate limits. We can enforce these limits where it makes the most sense - potentially in the code in the Cloudflare Workers?

As far as what the rate limit should be, one benchmark is S3 with [3,500 put requests per second](https://aws.amazon.com/premiumsupport/knowledge-center/s3-503-within-request-rate-prefix/#:~:text=Amazon%20S3%20supports%20a%20request,per%20prefix%20in%20a%20bucket.). But we can bring this number down depending on what our infrastructure can handle.

**Comment by olizilla** [comment]
We can enforce rate limits in cloudflare config
https://www.cloudflare.com/en-gb/rate-limiting/

we just need to get it enabled on our account so we can configure it
<img width="1065" alt="Screenshot 2021-10-14 at 19 16 25" src="https://user-images.githubusercontent.com/58871/137373770-f37e3e50-3a93-430f-bb4d-8edc65378363.png">

**Comment by dchoi27** [comment]
Awesome, would be curious to see what the configuration options were. @mikeal had a good point that ideally we'd be able to not rate limit certain users on an approvelist, but not sure if that's controllable at the Worker level.
