### ISSUE TITLE
I am unable to upload a .car file

### ISSUE THREAD

**Issue by davethedead** [nftstorage/nft.storage#604]
I have a .car file it is 2.5GB of images. However, when I try to upload it to nft.storage it gives an error "Error uploading: The requested file could not be read, typically due to permission problems that have occurred after a reference to a file was acquired."  
![Screen Shot 2021-10-14 at 10 10 37](https://user-images.githubusercontent.com/90647409/137295831-7d5b63db-6f77-4ceb-b14a-08b2beea49f4.jpg)

I thought it might have to do with the scheduled maintenance but it is too early for that. Please could you help?

**Comment by alessandrohk** [comment]
I am having the same issue, please help me

**Comment by dchoi27** [comment]
Hey there, could you open a new issue with this, and include the details we asked for here: https://github.com/nftstorage/nft.storage/issues/604#issuecomment-946324869

It's likely some weird browser thing specific to your environment, so we need more info to help debug!

**Comment by dchoi27** [comment]
Check out NFT UP for the easiest way to store large files or directories https://nft.storage/blog/post/2022-04-05-announcing-nftup/
