### ISSUE TITLE
Filter/trim storing full multipart/form-data mime type

### ISSUE THREAD

**Issue by alanshaw** [nftstorage/nft.storage#623]
We're seeing mime types like this in the DB:

```json
"mime_type": "multipart/form-data; boundary=---------------------------123821742118716"
```

This should be trimmed to just `multipart/form-data` or alternatively just not stored at all because the `type` field effectively tells us this information.

**Comment by elizabeth-griffiths** [comment]
We're closing this issue. If you still need help please open a new issue.
