### ISSUE TITLE
Evaluate hasura remote schemas as an alternative to ingesting subgraph

### ISSUE THREAD

**Issue by Gozala** [nftstorage/nft.storage#627]
Hasura has a feature that allows composing remote external GraphQL services which they call [remote schemas](https://hasura.io/docs/latest/graphql/core/remote-schemas/index.html) which would be worth looking into and evaluating if it would be a valuable alternative to ingestion done by `ingest.js` right now.

**Comment by elizabeth-griffiths** [comment]
e.
