### ISSUE TITLE
implement nft.owner GraphQL relationship

### ISSUE THREAD

**Issue by Gozala** [nftstorage/nft.storage#632]
Niftysave currently has nft_ownership table where it logs all `nft_id`, `owner_id`, `block_number` because nft owner may change over time and this would let us track the history.

However to expose `nft.owner` we would need to query `nft_ownership` to pull the most recent owner for `nft_id` which would be the one with the greatest `block_number`. I think the best option would be to create an sql view and that use simple hasura relationship to from `nft.id →  nft_owner_view.nft_id` 

There are some unknowns however:

1. I am not sure if the sub(graph) preserves history or does in place update. I suspect later which would mean we wont really have a accurate history unless we do some work on the sub(graph) as well.

**Comment by elizabeth-griffiths** [comment]
Closing as this ticket is over 1 year old. If you still need support, please re-open this issue and provide more detail. Thanks!
