### ISSUE TITLE
niftysave analyzer should pin by ipfs path when it can be inferred

### ISSUE THREAD

**Issue by Gozala** [nftstorage/nft.storage#636]
After analyzer has a `tokenURI` it will attempt to fetch it either from ipfs or web depending if it is able to infer ipfs:// url

https://github.com/ipfs-shipyard/nft.storage/blob/f8b56d1577f5abc1fb640bcd19f8b3e4ade03e85/packages/niftysave/src/analyze.js#L249-L262

However it goes with a same code path when it comes to pinning tokenURI content regardless of whether it came from ipfs or web:

https://github.com/ipfs-shipyard/nft.storage/blob/f8b56d1577f5abc1fb640bcd19f8b3e4ade03e85/packages/niftysave/src/analyze.js#L278-L293

Primary motivation there was to retain ability to retry pinning later if first attempt failed without running into #613 . To do that pin-metadata job will pull metadata json from db produce same car and retry the pin:

https://github.com/ipfs-shipyard/nft.storage/blob/f8b56d1577f5abc1fb640bcd19f8b3e4ade03e85/packages/niftysave/src/pin-metadata.js#L219-L224

### What we should do

However if we:

1. Are able to derive ipfs:// url
2. Are able to get a content from that URL

We do not have the retry problem, more specifically we can assume that we would get same content for the same ipfs:// url (hooray cryptographic identifiers 🥳) so we could have deterministic retry while retaining original CIDs.

Which is why I think we should change current analyzer to:

1. Obtain content, it's CID and dagSize from the ipfs:// URL
   - Note that would imply figuring out `cid` of the content when the URL has a path e.g `ipfs://bafy…hash/dir/file`. I hope we could make that part of #589 
   - In the meantime we could combine two requests:
      1. [`/files/stat`](https://docs.ipfs.io/reference/http/api/#api-v0-files-stat) to get cid / dagSize
      2. [`/cat`](https://docs.ipfs.io/reference/http/api/#api-v0-cat) to get content.
2. Try pinning by ipfs URL as opposed to car import if when ipfs:// URL was derived (or resolved CID)

And change `pin-metadata` task to:

1. If `ipfsURL` for parsed nft_asset is known.
    - attempt pinning by ipfs:// URL (or by a `metadata_cid`)
2. If `ipfsURL` is null
    - `Car.encodeJSON(metadata.json)`
    - Pin via `NFTStorage.storeCar` API

**Comment by elizabeth-griffiths** [comment]
Closing as this ticket is over 1 year old. If you still need support, please re-open this issue and provide more detail. Thanks!
