### ISSUE TITLE
nft.storage should make sure that blocks don't exceed 1MiB

### ISSUE THREAD

**Issue by Gozala** [nftstorage/nft.storage#637]
Larger blocks are problematic because IPFS would accept them but then fail to provide. It would gladly accept a giant json in `store` API and produce a block that could exceed 1MiB limit

https://github.com/ipfs-shipyard/nft.storage/blob/f8b56d1577f5abc1fb640bcd19f8b3e4ade03e85/packages/api/src/routes/nfts-store.js#L53-L62

### Solution

Our encoder should use chunking strategy and factor out large fields e.g. data urls into separate blocks and validate that in the end all blocks fit the limits. If this naive strategy fails it could error and ask user to refactor metadata instead.

**Comment by JeffLowe** [comment]
related to #390 per Alan

**Comment by dchoi27** [comment]
Yeah more precisely #645 will close this
