### ISSUE TITLE
Discrepancy with Uploaded CIDs using NFT.Storage-tools

### ISSUE THREAD

**Issue by davethedead** [nftstorage/nft.storage#657]
I have uploaded some files in a txt containing the CIDs file using NFT.storage-tools node import.js. 1 when uploaded I see them in NFT.storage. 
However, 1 of them shows a size of the data as 16mb and the other shows 0 KB. The 0 KB one should be 2.65GB. I can click on it and it shows that files exist but I am worried that it will get garbage collected or something because it is not really there (I hope you get my drift). 
Are they properly pinned when uploaded to NFT.storage in this way?
![Screen Shot 2021-10-22 at 14 17 54](https://user-images.githubusercontent.com/90647409/138461416-df38c7ed-bd65-4fa7-bff2-fa7c97407e13.jpg)

**Comment by dchoi27** [comment]
Think the storeCar problems should be fixed - let us know if you have any follow up questions or are experiencing issues still!

**Comment by davethedead** [comment]
Thank you!!
