### ISSUE TITLE
Potentially incorrect conditional check when fetching pin info

### ISSUE THREAD

**Issue by mhahnenberg** [nftstorage/nft.storage#662]
https://github.com/nftstorage/nft.storage/blob/181c5991dc74bc43689b07a30b1164700efe2c65/packages/api/src/routes/pins-get.js#L33

This was discovered upon inspection of the code. It seems like this line is meant to say "if (!pin)" rather than "if (!nft)". There was a previous check for "if (!nft)" and there was no assignment to the nft variable between that check and this check. Additionally, the error message seems to indicate it was meant to check whether the pin was found. This could cause the server to incorrectly assume that pin was found and go on to do bad things later in the function.

**Comment by dchoi27** [comment]
This code will get deleted by #714
