### ISSUE TITLE
TimeOut when uploading multiple files. 

### ISSUE THREAD

**Issue by rafinskipg** [nftstorage/nft.storage#679]
Hello, i'm using the storeDirectory method. Now just uploading 300 json with a pretty small size. 

Error: 524: Origin Time-out

This code worked before (even it gave a timeout, at the end it produced the hash), now it does not

The code i have follows the example from here https://github.com/nftstorage/nft.storage/blob/main/packages/client/examples/node.js/storeDirectory.js

**Comment by LucasMoskun** [comment]
+1 experiencing the same error while attempting to upload 1000 meta data files

**Comment by LucasMoskun** [comment]
Is it possible to append files to an existing directory? Seems to work fine if I only add a few files

**Comment by rafinskipg** [comment]
@LucasMoskun  it is not possible to edit directories

**Comment by Gozala** [comment]
This is caused by the same issue as #660, cluster takes long to respond and CF aborts requests. I'm going to close this one in favor of the other. Please reopen if fixing other one does not resolve this.
