### ISSUE TITLE
can't log in

### ISSUE THREAD

**Issue by SnakeBearLB** [nftstorage/nft.storage#682]
At sign in, after submitting my email, then clicking the link sent to email inbox, I'm redirected back to nft.storage website with the loading screen. But that's as far as it goes. It will stay at the spinning circle.  It never actually logs in and then eventually takes me back to the login page. It worked yesterday.

**Comment by dreamhi724** [comment]
same issue again for me

**Comment by secretmedellin** [comment]
same issue, how do I login in ?

**Comment by secretmedellin** [comment]
how to login with my github account ?

**Comment by Ataye** [comment]
Necromancing this old one, still happening.
