### ISSUE TITLE
Simplify toolchains for more efficient dev onboarding

### ISSUE THREAD

**Issue by JeffLowe** [nftstorage/nft.storage#695]
We need to remove the barriers that exist in new dev onboarding and make our toolchains easier to use. Every time a dev has to touch code not contributed to recently, they find themselves spending hours bootstraping all the .env configs etc.  Lot’s of manual work. 
- Have to currently invest hours to get new dev to codebase onboarded and set up.
- Every single readme has 10 steps or so for getting started. (Running tests does not work unless you perform those steps etc).  there is no reason to have readme saying run this command, copy & paste output into that file. If those steps are needed we should just have a script that does all the steps and writes results into necessary files
- A main point of complexity here is when accounts need to be setup, like CF Worker, Magic
- originated with this slack discussion:  https://filecoinproject.slack.com/archives/C02BZPRS9HP/p1635197078134600

Possible approach to  articulating out needs in this epic:
- Try testing, running (in dev mode) each package and automate whatever is needed so everyone can test / debug / write patches without much ceremony
- Throughout workday as opportunities are identified, ticket them and add to this epic. 

Gold Standard measure for done:  A new user can essentially run npm install npm run dev (or yarn) on any operating system and everything works.

## Considerations to include
Slack posting etiquette https://filecoinproject.slack.com/archives/C02BZPRS9HP/p1636483565106100

**Comment by dchoi27** [comment]
@yusefnapora should add your notes here!
