### ISSUE TITLE
Pin-by-hash needs an upper limit both due to technical limitations and to prevent abuse

### ISSUE THREAD

**Issue by ribasushi** [nftstorage/nft.storage#70]
Tangentially related to, but distinct from https://github.com/ipfs-shipyard/nft.storage/issues/55

The largest dag we currently host is 22(!)GiB. If a dag grows beyond 31.5GiB - it will become extremely tedious/non-standard to store such a dag on filecoin.

Moreover - a multi-gigabyte nft is incongruent with the spirit of nfts in general.

While clients uploading via the website have natural limits due to cludflare, there is effectively no limit as to how much one could attempt to pin-by-cid.

Additionally: a large pin-by-cid request implies multiple minutes (hours?) to attempt to pin the entire dag. If the originator host goes away in the meantime, the pin will never complete and the resulting optics will be "nft.storage lost my data".

Requests:
- Institute a policy of hard-max dag size, above which we will not pin the CID under any circumstances ( this number must be less than 31.5GiB for technical reasons, but likely should be much lower )
- Institute a policy for pin-by-cid limits, to mitigate excessive background pinning tasks, and possible datalostt

**Comment by hugomrdias** [comment]
Closing this one in favor of #148 

Thanks you 🙏
