### ISSUE TITLE
Tagging uploads

### ISSUE THREAD

**Issue by arndom** [nftstorage/nft.storage#719]
I think a feature where  files uploaded could be grouped by a user-specified category would be appreciated instead of the current method of sequential alone

**Comment by dchoi27** [comment]
Yes, great idea. In the same vein of deleting files, we're figuring out a way to give users the ability to tag their end-users' uploads. You can follow this conversation here in this issue from our sister project: https://github.com/web3-storage/web3.storage/issues/577
