### ISSUE TITLE
Blog for NFT.Storage

### ISSUE THREAD

**Issue by dchoi27** [nftstorage/nft.storage#722]
We should have a blog website for NFT.Storage! Would be a great place to announce new features, etc.

Related to blog request for web3 https://github.com/web3-storage/web3.storage/issues/591

## Acceptance criteria:
- [x] Email subscriber list implemented
- [x] insert first blog post content https://docs.google.com/document/d/1E_f9iMmaYuPgw1cj17-3l0GHVHvqwkEKLhp5Bsx3fig/edit

- [x] Blog design implemented at blog.nft.storage
- [x] Repo for writing blog content
- [x] Blob placed on /blog route, with blog.nft.storage redirecting to /blog
- [x] ensure blog top nav matches nft.storage top nav

**Comment by JeffLowe** [comment]
FYI @Codigo-Fuentes latest design https://www.figma.com/file/mxRXqlzGd4MovE85euZtu8/NFT-STORAGE?node-id=1307%3A354

**Comment by JeffLowe** [comment]
@dchoi27 Regarding the "Email subscriber list implemented" requirement, what email subscription service do we need to integrate with?

**Comment by JeffLowe** [comment]
@dchoi27 We implemented the blog posts into markdown files housed in a folder in the repo. Is this acceptable for the MVP?

**Comment by dchoi27** [comment]
Asked @andyschwab about the email subscriber service, let's see what he says. 

Blog posts in Markdown works - that's what we do elsewhere if I'm not mistaken!

**Comment by Codigo-Fuentes** [comment]
Also, @JeffLowe @dchoi27 is there a launch plan / has someone / is someone going to write the first blog?

**Comment by dchoi27** [comment]
First blog post is almost ready!
