### ISSUE TITLE
Centralization of monitoring and on-call tools

### ISSUE THREAD

**Issue by dchoi27** [nftstorage/nft.storage#724]
# Alerts to opsgenie

- [x] heroku db
- [x] heroku psql-rest
- [x] better uptime http/tls checks
- [x] Sentry alerts 
- [x] grafana alerts
- [x] cluster grafana alerts waiting on merge for nft3 cluster 
- [x] better uptime cronjobs
- [x] logtail alerts 

# On-call cheat sheet
As discussed, should have a doc (probably Notion) for the team with a list of all the monitoring solutions, instructions for using them, and what to do in certain on-call situations.

- Logtail for Cloudflare Workers
- Heroku for database
- Cluster
- Website
- Status Page incidents
- Cloudflare metrics dashboards
- Sentry

**Comment by hugomrdias** [comment]
yes im gonna close this, its done for now.
