### ISSUE TITLE
Log monitoring solution

### ISSUE THREAD

**Issue by dchoi27** [nftstorage/nft.storage#725]
Evaluate and set up a monitoring solution for Cloudflare Worker logs

Related to #746

- [x] Logtail account setup
- [x] Add support for Logtail to our API code (PR pending)
- [x] Hook up heroku to Logtail
- [x] Add everyone to the account

Also need to do some of this in web3.storage

**Comment by JeffLowe** [comment]
Per Nitro meeting, team aligned on setting up Splunk.  
FYI wil need to add @the-simian access to system
