### ISSUE TITLE
Use Miniflare for testing API code

### ISSUE THREAD

**Issue by dchoi27** [nftstorage/nft.storage#726]
Test Miniflare and, if it's good for our use case, create a deployable instance for our devs

- [ ] API unit tests
- [ ] Client E2E tests
- [ ] Website E2E tests

**Comment by dchoi27** [comment]
Could also have Potato work on this

**Comment by JeffLowe** [comment]
@redaphid is actually queued up to tackle this and other "improve dev toolchain" tickets (if that's still desired).  He was waiting until wrapping work on LFUploader CLI to start.

**Comment by JeffLowe** [comment]
Daniel's working on Electron app, freeing up Redaphid to focus on these efficiency multipliers

**Comment by plwileverts** [comment]
Needs acceptance criteria
