### ISSUE TITLE
Progress of .storeDirectory

### ISSUE THREAD

**Issue by theshadowagent** [nftstorage/nft.storage#730]
Is it possible to get progress of uploading a directory with `NFTStorage.storeDirectory`, at least like in `.storeCar`?

**Comment by dchoi27** [comment]
@alanshaw what do you think? Since we convert to CAR client side it's probably possible, right?

**Comment by alanshaw** [comment]
v4 of the client library automatically splits uploads in ~10MB chunks and you can do the following to get a callback when a chunk has been uploaded:

```js
import { NFTStorage } from 'nft.storage'

const { cid, car } = await NFTStorage.encodeDirectory(files)

await NFTStorage.storeCar({ token }, car, {
  onStoredChunk: size => console.log(`Stored a chunk of ${size} bytes`)
})
```

**Comment by alanshaw** [comment]
@theshadowagent HTH - please shout if you need anything else!
