### ISSUE TITLE
Show Filecoin deal information in WebUI

### ISSUE THREAD

**Issue by dchoi27** [nftstorage/nft.storage#735]
The check endpoint already returns deal info for a given CID. We should show this in the Web UI like in Web3.Storage.

**Comment by JeffLowe** [comment]
@dchoi27 Is there a mock of how this should look?  Or, at least a screenshot of how it looks in web3.storage?

**Comment by dchoi27** [comment]
I'd just make a web3.storage account so you can click around with it yourself! And if you have any thoughts on improvements that'd be great.

**Comment by JeffLowe** [comment]
noting here, blocked until we get the cf access resolved (note @Codigo-Fuentes
