### ISSUE TITLE
Add logos of big name marketplaces using NFT.Storage to homepage

### ISSUE THREAD

**Issue by dchoi27** [nftstorage/nft.storage#736]
Will reach out to marketplaces this week asking if it'd be OK - will follow up with who we want to include

When we put this on our homepage, we should do it in a way that auto-scales as more users' logos are added, so future users can PR to the folder including these logos and make it easy to add more logos.

## Designs
unknown

## Logo Assets for engineers
https://drive.google.com/drive/folders/1RpvlUcMTFIPVwhyPPS1nnK3GiXQYQMyw?usp=sharing

## AC / Tasks
- [x] developers can PR to add new logos
- [x] Homepage has section showing all marketplace logos
- [ ]  Before deploying out to production, share review link with David (so he can share with OpenSea who has requested review before publishing)
- [ ] add a "Trusted by" header
- [ ] move all the logos  into one row if possible (so it doesn't take up too much space)

**Comment by JeffLowe** [comment]
@dchoi27 Are there any mocks (or any example sites) we can model implementation upon?  
Q:  Do we need hyperlinks on the logos leading to marketplace homepages, or only the logos?

**Comment by dchoi27** [comment]
Skimming through SaaS websites, it seems either they just integrate the logos on the page without a different background (e.g. [Stripe](https://stripe.com/)) or have a dedicated case studies section (e.g. [Twilio](https://www.twilio.com/)). Would be cool to do the latter eventually (#834) but for now, think the former is good!

My instinct would be to put at the bottom of the About section using the same blue-green background, but could be convinced to have higher up on the page too if folks have strong thoughts.

No hyperlinks from the logos please - creates extra stuff to manage and it doesn't look like others do it
