### ISSUE TITLE
Develop NFT market stats public dashboard

### ISSUE THREAD

**Issue by dchoi27** [nftstorage/nft.storage#750]
## OVERVIEW
Build an nft.storage stats page per design.

## Original Notes
We should make a public stats dashboard to share data about how much data is stored on NFT.Storage, etc. A design like https://fnd.info/ would be really like.

We want a page that shows:
- Total number of uploads, with the week over week growth rate in brackets

- Total amount of data in Filecoin deals, with the week over week growth rate in brackets

**Comment by protocolin** [comment]
Need:
- Graphs showing the growth vs. static stats, really important
- Logos of all the big users / partners / adopters / ecosystems that use it (Flow, etc)
- Any way we can compare to others or have a sense of "NFT Market share"?

**Comment by dchoi27** [comment]
Thank you! Feedback sent over to the designer.

Re: market share, that's probably better off as part of the stats dashboard for niftysave (cc @JeffLowe @the-simian) - the NFTs we're counting for NFT.Storage will be uploads to NFT.Storage, which might not all have made it into NFTs yet + aren't the exhaustive list of NFTs stored in IPFS/Filecoin. The only way we could really calculate the denominator for total NFTs is through scraping the chains anyway.

**Comment by dchoi27** [comment]
@JeffLowe let's make some placeholder issues for this epic, even if it's just one showing that we're researching requirements
