### ISSUE TITLE
Front-end changes to IPFS Check

### ISSUE THREAD

**Issue by dchoi27** [nftstorage/nft.storage#751]
@aschmahmann graciously is helping us modify https://ipfs-check.on.fleek.co/ to help isolate issues with CIDs when NFT folks are having trouble with some CIDs but it's not NFT.Storage. More specifically, we're going to try to make it easy for users to check if their CID is stored with any of the major pinning services / IPFS infra providers (to see if there are any patterns with the CIDs that they're seeing are not retrievable).

@aschmahmann - is there a repo that we can fork for collaborating on front-end things?

**Comment by aschmahmann** [comment]
@dchoi27 the repo with both the frontend and backend code is https://github.com/aschmahmann/ipfs-check. The frontend code is in the `web` folder.

Let me know if people want permissions to the repo (they can fork and do a PR, but I'm also happy to grant permissions). Probably that repo should move to the ipfs-shipyard org, but it's likely not worth messing with at the moment.

If there's anything needed from me on the backend lmk and I'm happy to do so.

**Comment by dchoi27** [comment]
Great, thanks. Could you share where the list of peer IDs across service providers lives?

**Comment by dchoi27** [comment]
Closing this for now given we're not the team handling gateway issues (where most these complaints come in)
