### ISSUE TITLE
Very small records limit to GET all uploaded items - No option to .csv export either

### ISSUE THREAD

**Issue by wiyye** [nftstorage/nft.storage#754]
The limit of records with this API call is like 100... That is ridiculously low. Most NFT collections have 2k-10k images + 2k-10k jsons.

I need to export the full list of CIDs uploaded. How can I do this? I think it's not even possible.

**Comment by alanshaw** [comment]
I believe this was recently updated to 1,000 (from 100). Are there some docs we forgot to update that you're reading?

**Comment by wiyye** [comment]
Ah yes I see that 1000 works. In the documentation in the "Try now" part it only allows 100.

Still, 1000 is also a bit limited. I uploaded quite some files now and there is no way to grab all the CIDs. Only the first 1000 or doing 1 by 1 in the website. Any workaround?

**Comment by dchoi27** [comment]
Hey there - `GET` accepts a timestamp to grab all records before, so should make it simple to paginate. Does that work for you? 
![image.png](https://images.zenhubusercontent.com/5fa04bd64afb77249c77235b/7ad669b3-833d-4925-842d-20978532aca8)

Can you link / screenshot where you see 100 in the docs?

@yusefnapora mind updating the docs here to specify the limit for number of records (right now it gives default of 10 and doesn't actually state the max) https://nft.storage/api-docs/

**Comment by wiyye** [comment]
Hi,

That also doesn't help since all files where uploaded at once, same time. I had to copy/paste them all manually at the end.

Here is where it only supports 100 records: https://gyazo.com/3b8bba75976d223b7d3e9caecde6164f

As a user, please accept my feedback on how you can improve this great service easily:
- Possibility to add a custom file or metaname to each file when uploading so we can easily fetch the generated hashes with the local files. Right now not possible.
- Remove the limit on the GET API so it can be  100% usable without manual work.
- Add a new API call to REMOVE all files or batch remove

Thank you anyways :)

**Comment by alanshaw** [comment]
> Here is where it only supports 100 records: https://gyazo.com/3b8bba75976d223b7d3e9caecde6164f

Will be fixed here https://github.com/nftstorage/nft.storage/pull/762

> As a user, please accept my feedback on how you can improve this great service easily:
> * Possibility to add a custom file or metaname to each file when uploading so we can easily fetch the generated hashes with the local files. Right now not possible.

The CID for an uploaded file is returned by the service, you should not need to query the uploads listing to obtain it.

> * Remove the limit on the GET API so it can be  100% usable without manual work.

Apologies, but there needs to be some limit here to mitigate abuse.

> * Add a new API call to REMOVE all files or batch remove

Just a note about this: deleting uploads does _not_ remove the content from IPFS or from any Filecoin deals that it gets added to, it only removes from _your_ file listing.

I've opened https://github.com/nftstorage/nft.storage/issues/763 for this.
