### ISSUE TITLE
async gateway read tests on every write

### ISSUE THREAD

**Issue by mikeal** [nftstorage/nft.storage#755]
> As part of https://github.com/nftstorage/nft.storage/issues/823 epic

We’ve received reports of intermittent gateway issues from some users. These are difficult to reproduce because many of them end up being delays in availability, so by the time we find out the issue appears to be resolved.

We also don’t have great metrics for read performance since those come out of different gateways and aren’t part of our core service.

We could kick of an async process (maybe in Lambda so that we can get a longer timeout) on every new write that reads data from multiple gateways and logs the performance of each. It could also trigger an alert when data is not available from our own gateways within a reasonable timeframe and we could use this to pro-actively investigate issues before we get a report from users.

**Comment by dchoi27** [comment]
Are there any considerations here for file size (might cause unforseen issues if there happens to be 5 requests in a row for 10GB content)?

**Comment by vasco-santos** [comment]
Closing in favour of work stream in https://github.com/nftstorage/nft.storage/issues/1488 + https://github.com/nftstorage/checkup
