### ISSUE TITLE
Migrate data from old Cluster

### ISSUE THREAD

**Issue by dchoi27** [nftstorage/nft.storage#760]
We'd like to migrate data from the old Cluster (that is no longer being written to) into a new Cluster with flat-fs. Opened an issue with infra to get a new Cluster set up. https://github.com/protocol/bifrost-infra/issues/1484

**Comment by hugomrdias** [comment]
I discussed this with Hector and we came up with a plan

- [ ] copy state from nft1 to nft3 directly and let it finish syncing 
- [ ] prepara a PR to change API to nft3 
- [ ] make nft2 read only and change production to nft3
- [ ] copy state from nft2 to nft3 and let it sync

**Comment by dchoi27** [comment]
When will copying data from nft1 kick off? It's been a few weeks now.

We have #862 which would otherwise cover the 2-4 checkboxes, can we rescope this issue and close that one if we want to track everything in this issue?

Do we need to copy state from nft2 to nft3? I was under the impression no. cc @mikeal

**Comment by hugomrdias** [comment]
nft1 transfer will start tomorrow, i will close #862 and track everything here.
