### ISSUE TITLE
Can't run example

### ISSUE THREAD

**Issue by pmannle** [nftstorage/nft.storage#761]
Hi team, I'm following the examples on this page and the code results in errors:

https://github.com/nftstorage/nft.storage/tree/main/packages/client/examples/node.js

`SyntaxError: Cannot use import statement outside a module`

I've updated with require statements, and get the following:

`Error: Cannot find module 'carbites/treewalk'`

The /browser examples work fine - any chance to get this working?

**Comment by dchoi27** [comment]
Hey there - what version of Node are you using? We'd recommend using the latest version.

**Comment by the-simian** [comment]
@pmannle just to troubleshoot, can you try adding `{ type: "module" }` to your package.json? [(see here)](https://nodejs.org/api/packages.html#packages_type)

**Comment by pmannle** [comment]
I'm running latest stable node version (v12.14.1), and updated npm, on OSX. 

I did a hard reset of the repo, delete the package-lock.json, and all the node_modules folder.

`% node store.js
Debugger attached.
Waiting for the debugger to disconnect...
/Users/phil_mannle/Solidity/nft.storage/packages/client/examples/node.js/store.js:1
import fs from 'fs'
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at Module._compile (internal/modules/cjs/loader.js:891:18)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1043:10)
    at internal/main/run_main_module.js:17:11`

Also, here is my package.json, which already includes the type: module setting:

`{
  "name": "nft-storage-examples",
  "version": "0.0.0",
  "private": true,
  "description": "Examples of using nft.storage in Node.js",
  "main": "snigle.js",
  "type": "module",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "Alan Shaw",
  "license": "(Apache-2.0 AND MIT)",
  "dependencies": {
    "ipfs-car": "^0.5.8",
    "nft.storage": "^3.3.0"
  }
}
`

**Comment by pmannle** [comment]
Ok I also tried with node v17.1.0 (npm v8.1.2), and I get this:

```
% node store.js
file:///Users/phil/Solidity/nft.storage/packages/client/examples/node.js/node_modules/nft.storage/src/lib.js:211
      throw new Error(result.error.message)
            ^

Error: Magic Admin SDK Error: [ERROR_MALFORMED_TOKEN] The DID token is malformed or failed to parse.
    at Function.store (file:///Users/phil/Solidity/nft.storage/packages/client/examples/node.js/node_modules/nft.storage/src/lib.js:211:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async main (file:///Users/phil/Solidity/nft.storage/packages/client/examples/node.js/store.js:9:20)
```
