### ISSUE TITLE
import Tezos NFT assets and metadata into niftysave

### ISSUE THREAD

**Issue by mikeal** [nftstorage/nft.storage#772]
There’s a nice graphql API for querying an index of Tezos (https://hicdex.com/).

An earlier thread in Slack produced this query:

```
query MyQuery {
  hic_et_nunc_token {
    metadata
    thumbnail_uri
    display_uri
    artifact_uri
  }
}
```

> And I think there’s a total of ~531416 tokens or so from their aggregate stats.

Many of these NFT’s are from HEN and they recently produced a list of CID’s from their pinner on Infura. https://t.co/zDvodexhLM?amp=1  (from twitter https://twitter.com/artnome/status/1459310362935898122?s=20).

We could bootstrap the work to [replace our write pipeline from pinning to the nft.storage API](https://github.com/nftstorage/nft.storage/issues/635) with this.

**Comment by kylegrover** [comment]
fwiw we have a banlist of wallets here: https://github.com/hicetnunc2000/hicetnunc-reports/blob/main/filters/w.json
these are generally stolen artworks, so you could feel free to exclude them from your archive. The decision is yours of course, as the banlist is a human product and it's impossible to avoid biases when making these judgements you may decide that you'd rather pin the banned art as well

**Comment by kylegrover** [comment]
also note the thumbnail_uri is generally always the black square, unless someone modified the minting process. again you can choose to process those but there shouldn't actually be any objkt specific CIDs there

**Comment by kylegrover** [comment]
532995 :)
`query ObjktsCount {
  hic_et_nunc_token_aggregate {
    aggregate {
      count
    }
  }
}`
of note also are the missing objkts (the earliest minted) and a number of broken metadata, again from people modifying the minting process, using their own scripts
