### ISSUE TITLE
niftysave: public blockchain backup NFT’s

### ISSUE THREAD

**Issue by mikeal** [nftstorage/nft.storage#779]
I’d like to start backing up all the public blockchains in Filecoin.

Let’s create a system that mints an NFT for every epoch of a public chain. The NFT will link to the blocks, and CAR file hash, of the delta that epoch produced.

We’ll figure out what we want to do with the NFT’s later (sell on the public market to fund the backup, act as voting shares in a Data DAO, whatever). We’ll need cheap minting, maybe we build it on Solana.

We can start with Bitcoin, we have good codecs and CAR files for a lot of the history already built.

**Comment by JeffLowe** [comment]
Seems Related to #806

**Comment by alanshaw** [comment]
@JeffLowe ok I re-read this and thought about it some more and I think it's a great idea. I think there's historical events that have happened on chains that folks would love to own as an NFT. Like, I'd _love_ to own the genesis block for bitcoin, or block 148,888 on Filecoin (launch block) or blocks where forks happened or huge transfers etc. etc.

My original thought was that this was more of a task for web3.storage and that it doesn't really belong to niftysave - why would you make an NFT for every block? Niftysave is _not_ about creating NFTs, it's about saving them from disappearing. It _is_ about reading data from blockchains, but that's where the overlap ends.

My feeling is that I'd love your team should tackle this, but personally I'd view it as a separate project to niftysave albiet with some parts that can be reused.
