### ISSUE TITLE
How to transfer my NFT.Storage data to a differnt email addres?

### ISSUE THREAD

**Issue by JacobSloan** [nftstorage/nft.storage#783]
Currently I created an NFT Marketplace and have around 4,000 IPFS stored on NFT.Storage. The issue is that I used my personal email address to create my NFT.Storage account. I need to tranfer all data to a business email, is there any way to do this?

**Comment by dchoi27** [comment]
Hey there - email us at support (at) nft.storage and we can help!

**Comment by dchoi27** [comment]
Closing for now - feel free to reach out to us via the email above!
