### ISSUE TITLE
nft.storage could not display image from [cid].ipfs.dweb.link

### ISSUE THREAD

**Issue by melwong** [nftstorage/nft.storage#797]
I've been trying for 3 days using different methods (other than node.js as I don't know node). I could get my images uploaded but they only appear as strings when viewed from the ipfs.dweb.link such as this -> https://bafkreigxyjxp24pc2uxflqmvg46x7oip3lee2aovyqbidtoiztn6b6wr7q.ipfs.dweb.link/ (Chrome prompts to download a file called "download" or this -> https://bafkreihxiweiopz4pfmqtub5klhsq7wuu7wrw24inbrozbl7cshd4uaqxq.ipfs.dweb.link/ (image binary string)

Below is my code. The only way I could properly upload/display an image is via curl command from my PC.

```
let files = new FormData(); // you can consider this as 'data bag'
			
files.append('upload-file-hidden', $('#upload-file-hidden').get(0).files[0]);

var url = "https://api.nft.storage/upload";

var xhr = new XMLHttpRequest();
xhr.open("POST", url);

xhr.setRequestHeader("Authorization", "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ....");
xhr.setRequestHeader("Content-Type", "image/jpg");

xhr.onreadystatechange = function () {
   if (xhr.readyState === 4) {
	  console.log(xhr.status);
	  console.log(xhr.responseText);
   }};

xhr.send(files);
```

Am I missing something? Wrong or missing header perhaps?

**Comment by alanshaw** [comment]
A couple of issues I can see here:

* The form data propery should be named `file` (not `upload-file-hidden`)
* Since you're using `FormData` the `Content-Type` should be `multipart/form-data`

Let me know if you get any further with that.

If you `ipfs cat bafkreigxyjxp24pc2uxflqmvg46x7oip3lee2aovyqbidtoiztn6b6wr7q` then you can see that the entire body has been saved to IPFS, including the multipart headers:

```console
$ ipfs cat bafkreigxyjxp24pc2uxflqmvg46x7oip3lee2aovyqbidtoiztn6b6wr7q
------WebKitFormBoundary5peilISl2YOOweQy
Content-Disposition: form-data; name="acadp-upload-file-hidden"; filename="assfsdfds.png"
Content-Type: image/png

404 not found?PNG

IHDR,y}?u??IDATx??w?%?U??=O??;???Q3ʣl?J?,!'0??lX??&?,??e?zI???????????9I???,?4?{?s߾?????Q?{?gz?f??Q}?S???֭po???
...
```

**Comment by dchoi27** [comment]
Hey there, closing this for now. Let us know if still an issue after @alanshaw's comment!
