### ISSUE TITLE
ERROR  Failed to compile with 2 errors, ipfs-car/

### ISSUE THREAD

**Issue by rapeflower** [nftstorage/nft.storage#800]
These dependencies were not found:

* ipfs-car/blockstore/memory in ./node_modules/nft.storage/src/platform.web.js
* ipfs-car/pack in ./node_modules/nft.storage/src/lib.js

To install them, you can run: npm install --save ipfs-car/blockstore/memory ipfs-car/pack

**Comment by dchoi27** [comment]
Can you share more about your environment and make sure you're using the latest Node version?

**Comment by dchoi27** [comment]
Closing for now, please let us know if this is still an issue!

**Comment by CamTosh** [comment]
I have the same issue. 

NodeJS : v17.1.0
MacOS : Bigsur 11.3
Nft.storage: 5.0.0

**Comment by alanshaw** [comment]
Are you using webpack4?

**Comment by rapeflower** [comment]
> Can you share more about your environment and make sure you're using the latest Node version?

node: v14.17.3
webpack:  4.6.x

**Comment by rapeflower** [comment]
> Are you using webpack4?

Yes, webpack: 4.6.x

**Comment by CamTosh** [comment]
> Are you using webpack4?

Yes 4.6

**Comment by melwong** [comment]
Me too. I have the same issue. 
Node v16.13.1
Nft.storage v5.2.0

This temp fix works -> https://stackoverflow.com/questions/70063600/cant-resolve-ipfs-car-blockstore-memory-when-importing-nft-storage

**Comment by Aoi1011** [comment]
I could compile it by specific version.
Node v17.3.0
nft.storage 3.3.0
