### ISSUE TITLE
skypack cdn does not provide an export named 'normaliseInput'

### ISSUE THREAD

**Issue by lukeyounge** [nftstorage/nft.storage#802]
This import is causing an error since yesterday

`  import { NFTStorage } from 'https://cdn.skypack.dev/nft.storage' `

Error is 

` Uncaught SyntaxError: The requested module '/-/ipfs-core-utils@v0.10.5-qUdqS0pJ7xHVq6EQnGSz/dist=es2019,mode=imports/unoptimized/src/files/normalise-input/index.js' does not provide an export named 'normaliseInput' `

**Comment by dchoi27** [comment]
Hey there - we're tracking the issue with skypack here: https://github.com/multiformats/js-multiformats/issues/115 Sorry for the inconvenience!

**Comment by lukeyounge** [comment]
Great, thank you for the follow up!

**Comment by lukeyounge** [comment]
So - is there any way around this issue at the moment? Just trying to use the blob file

**Comment by zyumbik** [comment]
Try setting the version to `3.4.0` (https://www.npmjs.com/package/nft.storage) seems like it works. In store.html: `import { NFTStorage } from 'https://cdn.skypack.dev/nft.storage@3.4.0'`

**Comment by alanshaw** [comment]
Unfortunately we're still working through the skypack issues, but in the mean time you can import the prebuilt bundle in the browser from `https://cdn.jsdelivr.net/npm/nft.storage@v5.1.3/dist/bundle.esm.min.js`

**Comment by dchoi27** [comment]
Closing, let us know if you have any issues!
