### ISSUE TITLE
Pinning Api is reporting Failed to fetch

### ISSUE THREAD

**Issue by axmad22** [nftstorage/nft.storage#805]
I uploaded files to ipfs using their desktop IDE and I have added nft.storage as a custom PINNING SERVICES everything was working fine but now the pinning has failed and its showing  Failed to fetch error. The url I used was https://nft.storage/api. I have created in ipfs a  directory with files from different directories already uploaded, so that when I want to access a file i use directory CID \ fileName . How can I  add\pin the ipfs directory to nft.storage  without uploading each file to  nft.storage manually

thanks

**Comment by alanshaw** [comment]
1. That's a old URL, you should use `https://api.nft.storage` now.
2. If you want to not have to upload the data then you need to ensure the directories you created have been added to an IPFS node that is publically available on the internet (i.e. not behind a NAT)?
3. Please ensure you're sending [`origins`](https://ipfs.github.io/pinning-services-api-spec/#tag/pins/paths/~1pins/post) with your request so our cluster knows where the data can be retrieved from.

If you can share the response body of your failed request and the code you're using I can help more.

**Comment by axmad22** [comment]
@alanshaw thanks man, I used ipfs desktop GUI to upload my files to IPFS and when I tried adding the new api endpoint to nft-storage as a custom pinning service it does not produce error logs, but it  just prints out Failed to fetch all in red and would not let me pin the files. If there is code I can use to pin the files that would b very appreciated
