### ISSUE TITLE
Allow CAR files that were split using the simple strategy

### ISSUE THREAD

**Issue by alanshaw** [nftstorage/nft.storage#821]
This allows us to support _any_ IPLD codec not just pb, cbor and raw.

We never GC so there's no need to ensure every block in a CAR is referenced.

There is some performance gain to be had by not decoding every block in a CAR.

We can either alter the simple strategy in carbites to always use the root CID of the DAG in every split CAR or we can alter our service to simply not add a row to the upload table when it encounters a CAR with a `bafkqaaa` root.

**Comment by Gozala** [comment]
> We can either alter the simple strategy in carbites to always use the root CID of the DAG in every split CAR 

That would imply that for large file we need to chunk it up & assemble a dag before we can start uploading. This in turn implies that blocks need to be stored somewhere (in memory or disk) which is not ideal.

**Comment by Gozala** [comment]
> or we can alter our service to simply not add a row to the upload table when it encounters a CAR with a bafkqaaa root.

Why even have a root requirement ? What if car uploads without roots just don't get listed in uploads ? Or rather aren't listed by default e.g. we could have some way to list partial uploads too
