### ISSUE TITLE
Uploading a dir/folder so that I can use a base URI

### ISSUE THREAD

**Issue by mGonzim** [nftstorage/nft.storage#824]
I trying to upload an entire NFT collection along with the metadata. I have been looking for clear documentation or tutorial/demo to how this can be done if it can be done. 

Any help would be appreciated.

**Comment by alanshaw** [comment]
There's an example of [uploading a directory here](https://github.com/nftstorage/nft.storage/blob/main/packages/client/examples/node.js/storeDirectory.js) and [API docs for storeDirectory here](https://nftstorage.github.io/nft.storage/client/classes/lib.NFTStorage.html#storeDirectory).

You'll need to use `fs.promises.readdir` to read directory contents.

Let me know if you need any more help!

**Comment by jamesrwaugh** [comment]
@alanshaw Not sure if the original question was answered, but I have the same question.

I would like the following

`<ipfsCid>/1.jpg`
`<ipfsCid>/1.json (where the the "image" refers to 1.jpg)`
`<ipfsCid>/2.jpg`
`<ipfsCid>/2.json (where the the "image" refers to 2.jpg)`

It looks like the examples are just uploading images without any metadata. I suppose the metadata files could be uploaded as well, but I don't see how to get the `image` property to point to the image which hasn't been uploaded yet.

Am I misunderstanding something?
