### ISSUE TITLE
Module not found: Error

### ISSUE THREAD

**Issue by Meyanis95** [nftstorage/nft.storage#828]
`Module not found: Error: Can't resolve 'ipfs-car/blockstore/memory'`
`Module not found: Error: Can't resolve 'ipfs-car/pack'`
`Module not found: Error: Can't resolve 'ipfs-car/pack'`

Impossible to use nft.storage in my react app built with webpack and the latest version of node (v17.1.0). 

I've already added `"type": "module"` in my `package.json`

**Comment by faithinyous** [comment]
same problem here

These dependencies were not found:
*ipfs-car/blockstore/memory in ./node_modules/nft.storage/src/platform.web.js
* ipfs-car/pack in ./node_modules/nft.storage/src/lib.js, ./node_modules/nft.storage/src/token.js
 
I am using Quasar framework.

**Comment by Jorropo** [comment]
@faithinyous @Meyanis95 
From what I remember, I belive that error shows if you are using `require("nft.storage")` and not ES6 imports like `import { NFTStorage } from "nft.storage"`.

**Comment by Meyanis95** [comment]
It throws me an error even when I'm using ES6 import `import { NFTStorage } from "nft.storage"`

**Comment by Meyanis95** [comment]
As the module import didn't work for me in my react app, I went through a fetch request and it works!

```
async function main() {
    var url = "https://api.nft.storage/upload";
    var data = new Blob([bytes], { type: "image/png"});
                    
    fetch(url, {
        "method": "POST",
        "headers": {
             "Authorization": "Bearer",
             "Content-Type": "application/x-www-form-urlencoded"
           },
         "body": data,
      })
     .then(response => {
          console.log(response);
     })
```

**Comment by alanshaw** [comment]
Please use webpack5 with NFT.Storage. Webpack4 does not support the `exports` field in `package.json` and it's why it's saying it can't find modules.
