### ISSUE TITLE
2Gb files upload

### ISSUE THREAD

**Issue by stefanogalizia** [nftstorage/nft.storage#831]
Dear team, 
thanks for the great job. I am trying to upload a large files (2gb in size) and i always get: 

(failed)net::ERR_CONNECTION_CLOSED (From browser)

i have read on doc the file size limit is 31Gib

Any help on this?

Thanks

**Comment by stefanogalizia** [comment]
I have tried also from cURL and doing post through HTTP api and i get the following error:

The remote server returned an error: (413) Request Entity Too Large.

Thanks

**Comment by dchoi27** [comment]
Hey there - it sounds like the error in the browser comes from an interrupted connection. We can investigate whether that's something on our side - can you provide the browser logs you get?

Re: using the HTTP API, take a look at [this issue](https://github.com/nftstorage/nft.storage/issues/413#issuecomment-918410081) for some more details. Basically, every individual API request needs to be <100MB. You can [convert your data](https://github.com/web3-storage/ipfs-car) to a CAR and [chunk it](https://github.com/nftstorage/carbites-cli/) before sending in multiple requests. Opened an issue to make this more clear in the API docs (#832).

Alternatively, all the JS client library storage functions will do this for you automatically.

**Comment by stefanogalizia** [comment]
Hi @dchoi27 , 
thanks for your answer. 
Splitting files into CAR i was able to upload file. That was not clear to me in the API

Many thanks for your help

**Comment by dchoi27** [comment]
We'll upload the docs to make better! #832
