### ISSUE TITLE
zsh: parse error near `}'

### ISSUE THREAD

**Issue by mattyg2218** [nftstorage/nft.storage#855]
import { NFTStorage, File } from 'nft.storage'

const apiKey = 'YOUR_API_KEY'
const client = new NFTStorage({ token: apiKey })

const metadata = await client.store({
  name: 'Pinpie',
  description: 'Pin is not delicious beef!',
  image: new File([/* data */], 'pinpie.jpg', { type: 'image/jpg' })
})
console.log(metadata.url)
// ipfs://bafyreib4pff766vhpbxbhjbqqnsh5emeznvujayjj4z2iu533cprgbz23m/metadata.json
zsh: parse error near `}'

**Comment by alanshaw** [comment]
You need to add that to a `index.mjs` file and then run from the command line with `node index.mjs`.
