### ISSUE TITLE
More prominent warnings on uploading files

### ISSUE THREAD

**Issue by dchoi27** [nftstorage/nft.storage#856]
## Task
- [ ] add Upload warning copy onto the nft.storage upload page

## Copy to add to nft upload page
🌍 Public data

All data uploaded to Nft.Storage is available to anyone who requests it using the correct CID. Do not store any private or sensitive information in an unencrypted form using Nft.Storage.

♾️ Permanent data

Deleting files from the Nft.Storage site’s [Files](https://nft.storage/files/) page will remove them from the file listing for your account, but that doesn’t prevent nodes on the decentralized storage network from retaining copies of the data indefinitely. Do not use Nft.Storage for data that may need to be permanently deleted in the future.

## Business Need
We should have a similar warning to Web3.Storage on NFT.Storage's upload screen:

![image.png](https://images.zenhubusercontent.com/5fa04bd64afb77249c77235b/f7a93c5c-803a-4f77-9112-e9e53067855f)

## Web3 Storage Upload Screen
![image](https://user-images.githubusercontent.com/2078567/144085856-34926dc6-a29c-4209-9487-dd0b0b7400d3.png)

## Nft.storage CURRENT upload screen (what we need to change)
![image](https://user-images.githubusercontent.com/2078567/144086015-47de03fb-f4e7-4627-b2f2-b67ab354439a.png)

**Comment by JeffLowe** [comment]
@dchoi27 Will that decentralized storage link remain the same (https://docs.web3.storage/concepts/decentralized-storage/) or will it need to be updated to an nft.storage documentation page link.

**Comment by dchoi27** [comment]
Let's just leave the link out for now! And it will need to be updated later.
