### ISSUE TITLE
Module not found: Can't resolve 'ipfs-car/blockstore/memory'

### ISSUE THREAD

**Issue by mjamaleddine** [nftstorage/nft.storage#876]
When trying to upgrade to the newest version of nft storage I receive this error:

`Module not found: Can't resolve 'ipfs-car/blockstore/memory' in '\node_modules\nft.storage\src'`

Before I was using version 3.2.0 and it was fine. How can I fix this? Adding ipfs-car to the dependencies did not help.

**Comment by hanlife** [comment]
![1638449952(1)](https://user-images.githubusercontent.com/21124833/144426778-37bc14fc-d4ee-406d-9381-21754e6cd93a.jpg)

**Comment by yusefnapora** [comment]
Any chance you're using webpack 4? I'm investigating a similar issue that seems to be caused by webpack 4 not supporting the `exports` field in package.json.

**Comment by alanshaw** [comment]
Yes, webpack 4 does not support `package.json` `exports` field so is unable to resolve the dependency.

If you can't upgrade to webpack 5, you can now (as of nft.storage@5.1.3) use the prebuilt library:

```js
import { NFTStorage } from 'nft.storage/dist/bundle.esm.min.js'
```

**Comment by juliendorra** [comment]
Hi, 

if like me you have this bug because you are using Parcel, here's the issue about it at Parcel's repo:

https://github.com/parcel-bundler/parcel/issues/4155

You will find a few different workarounds in the thread.
