### ISSUE TITLE
Adding files to already existing folder

### ISSUE THREAD

**Issue by dferendo** [nftstorage/nft.storage#880]
Is it possible to add a functionality that given a CID of a directory on IPFS, i can use that CID (using ipfs files write) to add more files to that directory and returns a new CID.

This can currently be done by downloading all the files from a given CID and re-upload these files with the new files. This is a bit wasteful.

If this feature is possible and others would also like it I can work on it as well! Thanks

**Comment by yusefnapora** [comment]
I think this is blocked on support for partial DAGs. We have an open issue for this in web3.storage, but I believe it applies here as well: https://github.com/web3-storage/web3.storage/issues/394

**Comment by dchoi27** [comment]
Being tracked it #686
