### ISSUE TITLE
Edit language on homepage on website to make value prop more clear

### ISSUE THREAD

**Issue by dchoi27** [nftstorage/nft.storage#893]
Right now, the language on the website assumes a bit too much knowledge about the benefits of using IPFS when trying to illustrate the value of NFT.Storage. Let's spell this out a bit more, and where Filecoin comes into play.

Can we make the following language changes to the homepage:
- [ ] Add an "and 10,000+ other users!" underneath logos
- [ ] ensure the last paragraph currently in About (To learn more about the importance of content addressing ...) gets deleted (it is not included in the updated copy below)
- [ ] Under `About`:
```
NFT.Storage is a long-term storage service designed for off-chain NFT data (like metadata, images, and other assets) for up to 31GiB in size. Data is [content addressed](https://nftschool.dev/concepts/content-addressing) using IPFS, meaning the URL pointing to a piece of data (“ipfs://...”) is completely unique to that data. IPFS URLs can be used in NFTs and their metadata to ensure the an NFT forever actually refers to the intended data (eliminating things like rug pulls).

NFT.Storage stores many copies of uploaded data on the public IPFS network in two primary ways: in dedicated IPFS servers managed by NFT.Storage, and decentralized on [Filecoin](https://filecoin.io/). Since IPFS is a standard used by many different storage services, it’s easy to redundantly store data uploaded to NFT.Storage on any other IPFS-compatible storage solution from [pinning services](https://docs.ipfs.io/how-to/work-with-pinning-services/), to your [local IPFS node](https://docs.ipfs.io/install/ipfs-desktop), to other decentralized networks like Arweave or Storj.
```

- [ ]  in ABOUT section, change the current single column to a 2 column layout as seen in figma
### Current ABOUT
![image](https://user-images.githubusercontent.com/2078567/145489276-fff655f3-6811-4903-b394-4252921da575.png)

### NEW ABOUT
![image](https://user-images.githubusercontent.com/2078567/145489386-233f5465-b603-4a82-8376-bc6976cc1ccc.png)

- [ ] Modify `Store`:
```
Just upload your data and you'll receive an IPFS hash of the content (a "CID," or content address) that you can use to make an IPFS URL (`ipfs://<cid>`). Use this IPFS URL in your NFT data to refer to off-chain data (e.g., the metadata field in your NFT, the image field in your metadata) as a pointer to the content.

Filecoin provides long-term storage for the data ensuring that even if NFT.Storage is attacked or taken down the NFT data persists! And NFT.Storage will continue to decentralize itself out of the picture moving forward (e.g., making perpetual storage completely smart contract-based utilizing future tools like the [Filecoin Virtual Machine](https://filecoin.io/blog/posts/introducing-the-filecoin-virtual-machine/)).

Have additional preferences on where to store your data? Pin your data to any storage solution running a [pinning service API](https://ipfs.github.io/pinning-services-api-spec/).
```
- [ ] Change "nft.storage" to "NFT.Storage" throughout the homepage

**Comment by dchoi27** [comment]
Hey @dashcraft - updated the copy. Could you also make sure the last paragraph currently in About (`To learn more about the importance of content addressing ...`) gets deleted (saw it was still in #907)?

**Comment by JeffLowe** [comment]
Updated description specs to reflect what's currently needed so it can act as review checklist in PR review.

**Comment by dchoi27** [comment]
Ooh one more thing. Can we adjust the "and more" under the logos to say "and 10,000+ other users!" Adjusted the initial issue to reflect this.

**Comment by dashcraft** [comment]
Mobile:
![image](https://user-images.githubusercontent.com/11915975/145491802-52598ab6-0c96-4d15-9862-dcf261aceab2.png)

Desktop:
![image](https://user-images.githubusercontent.com/11915975/145491844-34887b91-afba-4a4b-9c36-e5a84721ec5e.png)
