### ISSUE TITLE
Add "Responses" section to /store in API docs

### ISSUE THREAD

**Issue by dchoi27** [nftstorage/nft.storage#903]
The `/store` docs here https://nft.storage/api-docs/ don't include details on the possible responses the endpoint can give.

**Comment by JeffLowe** [comment]
Looks like this is included now (see screenshot).  Is there anything else needed on this, or shall we close this out?
![Screen Shot 2022-02-27 at 1 17 00 PM](https://user-images.githubusercontent.com/2078567/155896467-6c7b6282-60c0-4bea-8a14-ded33d83ef84.png)

**Comment by dchoi27** [comment]
Can close, thanks!
