### ISSUE TITLE
Update the README about how to properly set secrets for api, etc

### ISSUE THREAD

**Issue by the-simian** [nftstorage/nft.storage#904]
Assigned here: https://github.com/nftstorage/nft.storage/pull/838#discussion_r762897991

Basically need to update the Project README for how  you're supposed to manage secrets in the project

**Comment by hugomrdias** [comment]
https://github.com/nftstorage/nft.storage/pull/999 improved the readme around this topic so im gonna close this issue but if you think we need further improvements please open a new issue.
