### ISSUE TITLE
Menu rendering issue in Safari

### ISSUE THREAD

**Issue by the-simian** [nftstorage/nft.storage#913]
Safari
![image](https://user-images.githubusercontent.com/954596/145128360-18f72b90-b5a6-480a-a7cf-434517cd16bf.png)

Every other browser 
![image](https://user-images.githubusercontent.com/954596/145128419-0831a2c3-fab8-4586-bf82-23509c9b5605.png)

Safari is not rendering some of the button-hologram styles, and the button is mishapen. This is only on the 'small variant' button, the others are working correctly

**Comment by dashcraft** [comment]
If you mess around with dev tools and resize/trigger mobile view, you can reproduce this as well.

![image](https://user-images.githubusercontent.com/11915975/145136738-c1cdcd7e-65dc-4689-b45a-e74cbd30b41e.png)

**Comment by the-simian** [comment]
fixed in #914
