### ISSUE TITLE
In older mobile devices (eg. Iphone 6) the useResizeObserver approach for mobile detection breaks the layout

### ISSUE THREAD

**Issue by the-simian** [nftstorage/nft.storage#915]
The way the `navbar.js` handles mobile detection can cause issues in older and older devices. https://caniuse.com/?search=ResizeObserver, shows that this will likely never work in any IE browsers and will probably fail in older versions of safari and all opera.

We should prefer a CSS based solution that is more stable

**Comment by dashcraft** [comment]
If you mess around with dev tools and resize/trigger mobile view, you can reproduce this as well.

![image](https://user-images.githubusercontent.com/11915975/145136738-c1cdcd7e-65dc-4689-b45a-e74cbd30b41e.png)

**Comment by dashcraft** [comment]
Potential solution proposed in semantic-ui-react for instance, is to use...
https://github.com/artsy/fresnel

I've had a good experience with semantic-ui-react in the past.

**Comment by the-simian** [comment]
FYI, I think the resizeObserver is responsible for this one as well (IOS 12):
![image](https://user-images.githubusercontent.com/954596/145312424-437cde60-34ab-42b8-b9f0-d5a6b2eaf9ff.png)

Anything earlier than IOS13 really doesn't support this. We've got some user reports of this as well. 

re: fresnel, semantic-ui-react (both of which I've used). These are reasonable suggestions, but IMO This is a job for CSS. I don't think more js layout abstractions are what will help us, that's why this is breaking in the first place. In the case of semantic-ui-react, for instance, its grid abstraction predates CSS grid. So they give you things like gutters, auto-repeating, and things like that but this is really handled just fine in CSS grid, we get all that 'for free' now just in the browser. As for the breakpoints, we shouldn't need several of these, not enough to warrant fresnel. I think we need to just not do this in JS at all. It will remove the bug and tbh help performance as well.

I'm happy to take this one if needed, this is not a large card in terms of labor. Mostly deleting, tbh. Also, with the recently refactored CSS build it will be much easier to implement than it was when this was first composed.

**Comment by the-simian** [comment]
Just to clarify this isn't a regression the issue was already there:
Here is the image I took of the 27-day-old site on my iPhone 6 when testing (to verify the issue was already there)
![image](https://user-images.githubusercontent.com/954596/145407213-893edd59-1013-47b7-b7a9-01d8869fca31.png)
