### ISSUE TITLE
Delete button has lost it's colour on API keys page

### ISSUE THREAD

**Issue by alanshaw** [nftstorage/nft.storage#923]
It all white and should be red (for danger):

<img width="313" alt="Screenshot 2021-12-08 at 18 05 08" src="https://user-images.githubusercontent.com/152863/145260428-8bc6f4ea-f7e1-4017-83a1-4cf1bedc059f.png">

**Comment by the-simian** [comment]
needs class or variant caution like here:
https://github.com/nftstorage/nft.storage/blob/5a73856c760569633daf0e5c227f9ae808d25054/packages/website/pages/files.js#L182

**Comment by the-simian** [comment]
resolved by #925
