### ISSUE TITLE
Rate limits by user

### ISSUE THREAD

**Issue by dchoi27** [nftstorage/nft.storage#935]
Power users of NFT.Storage have started asking for increased rate limits. Sounds like this is pretty easy to do with Cloudflare by token, but let's confirm. Then we can offer this to certain bigger users who bring it up.

This gets more complicated by UCAN-based auth (#851) and private key auth like for Solana (#781), where it wouldn't be as simple as screening for the API key. But let's get this right with a unit case first, like via API token, before expanding.

**Comment by alanshaw** [comment]
I've disabled the per-IP rule and enabled a per-header ("Authorization") rule as follows:

<img width="1060" alt="Screenshot 2022-01-24 at 16 19 21" src="https://user-images.githubusercontent.com/152863/150821830-87aa25d8-97d6-458e-bf34-902d82eaf4b3.png">
