### ISSUE TITLE
Allowing storeBlob to retain the uploaded File filename

### ISSUE THREAD

**Issue by bokobza** [nftstorage/nft.storage#937]
When an item is uploaded using the `store()` method, the link to the uploaded file maintains it's filename, as per the documentation:

https://github.com/nftstorage/nft.storage/blob/e8f7bed8953a6894421f1a72105d7775b4e72f2e/packages/client/src/lib.js#L196-L198

However, for `storeBlob()`, the filename is not retained, i.e the result of  a successful `storeBlob` call would be `ipfs://bafy...grg4eabo3`:
https://github.com/nftstorage/nft.storage/blob/e8f7bed8953a6894421f1a72105d7775b4e72f2e/packages/client/src/lib.js#L405-L406

Is there any technical reason why this is the case?
Having a hash followed by /filename.ext is a lot more explicit and gives an indication of what type of file is at the end of the CID.
Would you consider giving clients the choice?

**Comment by bokobza** [comment]
I understand that the only way to do this is to have a directory with the single file in it.
Feel free to close this issue if this is correct :-)

**Comment by dchoi27** [comment]
Hey! Yes that would be the way (via directory), thanks for the follow up :)
