### ISSUE TITLE
IPSF ID NFT 

### ISSUE THREAD

**Issue by TUSOLLYWOOD** [nftstorage/nft.storage#940]
hi guys, i'm a young Nfts creator and i'd like to know how could i get the ID when i mint an NFT on OPENSEA .
because without IPSF  you got this kind of ID 328024482882138038193 but i want this one #4292 . 
im not a coder i'm just a creator if you could help me thanks

**Comment by dchoi27** [comment]
Hey there! Happy to help. Think the issue you linked to in your post doesn't exist, but looks like you might be looking for a [CID](https://proto.school/anatomy-of-a-cid/01), which is like a URL in IPFS, but unique to the data itself. Note that this is not the same as the NFT ID or the OpenSea ID - an NFT can have both a metadata CID (to link to off-chain data) and other types of identifiers for the NFT itself. Keep in mind that IPFS is used for many things other than NFTs!

For OpenSea specifically, you'll probably get better help asking them directly, but I know the primary way to get an `ipfs://<cid>` URL for your metadata is via its [freeze metadata feature](https://support.opensea.io/hc/en-us/articles/1500012270982-What-is-Freezing-Metadata-).

**Comment by dchoi27** [comment]
Closing for now, hopefully the OpenSea community can help with any more questions on this topic!
