### ISSUE TITLE
Implement footnotes in blog

### ISSUE THREAD

**Issue by dchoi27** [nftstorage/nft.storage#944]
Let's get the blog to support footnotes. No preference between tooltips that have information on hover or links to footnotes at the bottom - whatever is easiest to support.

**Comment by Codigo-Fuentes** [comment]
Supported.

Syntax is: 

This is a paragraph and i want to note something.[^1]

...

<bottom of document>
[^1]: here is the footnote

**Comment by Codigo-Fuentes** [comment]
Supported.

Syntax is:

This is a paragraph and i want to note something.[^1]

...

[^1]: here is the footnote
