### ISSUE TITLE
Storage Layer Maximalism blog post

### ISSUE THREAD

**Issue by dchoi27** [nftstorage/nft.storage#945]
https://docs.google.com/document/d/1tJN6w5-tMXWoH_NoaF2rDmUT15TOMDockwGd_PRUdxQ/edit

Want to post this on Tuesday Dec 14 2022
Blocked on getting blog art, and adding footnotes (#944)

- [x] update copy with latest copy in gdoc
- [x] correct any markdown issues in PR
- [x] provide engineer with the thumbnail image when ready. https://user-images.githubusercontent.com/22168118/146032386-32c27adf-5f16-4ac3-9103-2e09c03053f7.png
- [x] secure top level description

## Description
NFTs continue to grow mainstream adoption, and as we push into new frontiers (Videos, GameFi, Metaverse) it’s critical that we take a keen eye to ensuring digital assets are created in a way ready to stand the test of time. In this post, we’ll make the case for storage layer maximalism and why every NFT needs an IPFS CID.

**Comment by JeffLowe** [comment]
@dchoi27 Do you have a preference on the thumbnail image?  I notice none was provided.

**Comment by dchoi27** [comment]
referenced in OP as "blog art" - should have today!

**Comment by JeffLowe** [comment]
@dchoi27 do you have a top-level description of the post that will appear in the spotlight (see preview  https://c758faa5.nft-storage-1at.pages.dev/blog/post/2021-12-14-storage-layer-maximalism/

**Comment by dchoi27** [comment]
^pinged @jnthnvctr about this!

**Comment by dchoi27** [comment]
@JeffLowe 

> NFTs continue to grow mainstream adoption, and as we push into new frontiers (Videos, GameFi, Metaverse) it’s critical that we take a keen eye to ensuring digital assets are created in a way ready to stand the test of time. In this post, we’ll make the case for storage layer maximalism and why every NFT needs an IPFS CID.

**Comment by dchoi27** [comment]
the thumbnail image is a placeholder, right? we're still waiting on design, but the checkbox in the OP is checked now
