### ISSUE TITLE
Unable to upload large files >70MB using sdk

### ISSUE THREAD

**Issue by midgerate** [nftstorage/nft.storage#954]
Receiving an error when uploading a video. 

Magic Admin SDK Error: [ERROR_MALFORMED_TOKEN] the DID token is malformed or failed to parse. 

Here's the code I used. 

```
  const fileBuffer = readFileSync(newFilePath)
  const blob = new Blob([fileBuffer])
  const ipfsHash = await nftStorageClient.storeBlob(blob)
```

**Comment by hugomrdias** [comment]
Can you provide more info around your code? How do you instantiate the client ? 
Please read the docs https://nftstorage.github.io/nft.storage/client/ you will probably find the solution there.

**Comment by midgerate** [comment]
@hugomrdias 

```
const nftStorageClient = new NFTStorage({
    token: String(process.env.NFTSTORAGE_API_KEY),
  })

```

I also found that even a 1 MB mp4 gives me error however a 8MB webm uploads fine using this.

**Comment by midgerate** [comment]
@hugomrdias nevermind, I found the problem! I did not have the API key in my environment. :)
