### ISSUE TITLE
Erroro in terminal

### ISSUE THREAD

**Issue by ronlawrence** [nftstorage/nft.storage#963]
I installed the package using npm. I obtained an API token from https://nft.storage and use it in place of API_TOKEN. I named my script index.mjs. When i Run the script: node index.mjs, I get an Error: Cannot find module ‘/Users/ronlawrence/index.mjs’

Also, what does “use npm init to create a new package.json” mean? Once I figure those two parts out i think I will be ok. Not sure what I am doing wrong

**Comment by jchris** [comment]
Happy to help you make progress. It sounds like you are getting started with node as well as NFTs. It would be useful to know what you are working on, as depending on the goal there may be simpler paths. 

Did you try running the script after renaming in index.js? `npm init` is a command for initializing your current working directory as an npm module. `package.json` is the file it makes, and you'd add `"type": "module"` to it (JavaScript and node are going through some growing pains related to modules...)

**Comment by dchoi27** [comment]
Hey there, closing this for now. Let us know you still need help getting set up.
