### ISSUE TITLE
Large File Uploader (LFU) App MVP to support 10K NFT drops

### ISSUE THREAD

**Issue by dchoi27** [nftstorage/nft.storage#981]
## High Level Feature Overview
As a part of #928, we are creating a first version of an Electron application that functions as an uploader to NFT.Storage. Broadly, the goal of this uploader is to make it easier for end-users that want to upload files/directories in a no-code way (supporting folks like NFT creators who might not be developers).

This should be able to upload anything that the JS client can handle (functioning as a sort of wrapper over the client), but in addition, we want to unlock additional use cases that end-users demand. These are documented more robustly in #928, but generally it involves being able to upload larger files / directories of different structures and file types.

The primary need we want to support is the ability to upload 10K+ small files in a directory. 

After discussing with the team, this is something that can be supported today without revamping CAR generation of large directories (#980). We can do this by detecting if the target directory is too large, and if so, splitting the directory up and doing multiple uploads.

Once a file/directory is uploaded, there should be useful output for the user to easily integrate it with their minting flow. This can vary depending on the tooling the user is utilizing. 

## Requirements
Detailed specifically in https://github.com/nftstorage/nft.storage/issues/1015

Post-MVP features captured in https://github.com/nftstorage/nft.storage/labels/topic%2FLFU

## Notes
[#4](https://github.com/nftstorage/nft.storage-tools/issues/4) is related (client code used for that can be largely reused for this)

## Approach
- 1st implement CLI tool (separate Epic and product)
- Next design MVP electron app
- create MVP electron app

cc @jchris, feel free to edit

**Comment by jchris** [comment]
Here are some of my rough notes about this. @funkytek suggested a PRD. This is the beginning of notes on it. The 2-pass upload model is worth talking through. I think we can keep the user's mental model in the file domain, which will give us more flexibility in the long run.

Packages 

Electron download 
- Standalone app
- Full node IPFS / Filecoin Station retrieval market
- Prewarm with NFTs (or users fave collections?)

Upload.js web library
- Simplest api surface area to add uploads to 3rd party site
- 2 lines of code and you’re uploading
- Used by NFT.Storage website to provide upload capabilities


Upload data model
- Promulgate CID / base URL as an API lingua franca
- 2 pass uploader 
    - 1st pass is asset uploading, you give us an assets directory and once we have it uploaded we rewrite the URLs in your metadata directory and upload it
    - Based on the directory structure of HashLips and OpenSea tutorials (Alternative to fixing the upload directory schema, is to make the URL rewriter programmable, but then you lose the audience)
- After the upload is done
- The uploaded CID will have directory layout:
    - Root
        - metadata/
            - 1.json, 2.json, 3.json…
        - assets/
            - 1.png, 1.mp4, 1.jpg, 2.png…
- All we care about is uploading the assets to 1 CID, and then rewriting the metadata json to include the individual asset gateway URLs
- Then we upload the metadata to a metadata root CID
- Then we have the option to create a new umbrella root dag that is structured like:
    - Umbrella root CID
        - Asset root CID
            - 1.png…
        - Metadata root CID
            - 1.json…
- Then end result allows the data consumer to pin the final umbrella root, and have all the assets and metadata pinned. While at the same time have the metadata JSON able to contain gateway URLs to the assets (under the Asset root CID)

**Comment by dchoi27** [comment]
This issue was scoped to just be able to handle uploading a large number of small files in a directory, which NFT UP now takes care of for us https://nft.storage/blog/post/2022-04-05-announcing-nftup/ Closing this one

We should split out work for any CLI we want to make, as well as any schema work we want to do to support large drops, into separate issues.
