### ISSUE TITLE
Browser sample to store files does not work

### ISSUE THREAD

**Issue by NoRulesJustFeels** [nftstorage/nft.storage#996]
Using this sample: https://github.com/nftstorage/nft.storage/blob/main/packages/client/examples/browser/storeDirectory.html

I get these errors in chrome: 
Access to fetch at 'https://api.nft.storage/upload/' from origin 'http://localhost:5000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
POST https://api.nft.storage/upload/ net::ERR_FAILED 403

Also, on line 25, the 'endpoint' variable hasn't been declared. I removed that and kept the token value to test the code.

**Comment by NoRulesJustFeels** [comment]
Tested on Chrome 96.0.4664.110 (Windows 10), both desktop and laptop.
Tested on Firefox 95.0.2 (Windows 10), both desktop and laptop.
Tested on Chrome 96.0.4664.110 (Ubuntu 21.10) desktop.

If I upload an HTML or JavaScript file the cors errors happen. If I upload other files like CSS or JPG, uploading works fine.

Doesn't seem to be the same behavior as in: https://github.com/nftstorage/nft.storage/issues/573

Did the fix for uploading JavaScript get reverted?

**Comment by NoRulesJustFeels** [comment]
Running this node.js sample on Windows 10: https://github.com/nftstorage/nft.storage/blob/main/packages/client/examples/node.js/storeDirectory.js

If I upload a JPG file, it works fine.
If I upload an HTML or JavaScript file there is a JSON error.

**Comment by NoRulesJustFeels** [comment]
[](url
[HTML.zip](https://github.com/nftstorage/nft.storage/files/7749262/HTML.zip)
)

**Comment by vasco-santos** [comment]
Hey @NoRulesJustFeels 

Thanks for reaching out. I could replicate this in my chrome when using HTML and/or the JS file. I will have a look and get back to you

**Comment by vasco-santos** [comment]
@NoRulesJustFeels this was blocked by Cloudflare Web Application Firewall. Should be good now.
Can you please test and let me know?

**Comment by NoRulesJustFeels** [comment]
Great. Working now. Thanks!
