### ISSUE TITLE
website-pages-faq-filesLimit: update text, issue #220 has been resolved

### ISSUE THREAD

**Issue by A0xStealth** [nftstorage/nft.storage#998]
website issue:
https://nft.storage/faq/#is-there-a-limit-on-numbers-of-files-in-a-directory

updates requested here:
https://github.com/nftstorage/nft.storage/blob/8fc8c4554763b0f921d3dbcacbe4961c9b656aae/packages/website/pages/faq.js#L64-L67
https://github.com/nftstorage/nft.storage/blob/8fc8c4554763b0f921d3dbcacbe4961c9b656aae/packages/website/lib/faqContent.js#L141-L148

resolved issue #220

**Comment by dchoi27** [comment]
Thanks for flagging! To summarize, we have to update the text in: https://nft.storage/faq/#is-there-a-limit-on-numbers-of-files-in-a-directory

@alanshaw does #220 eliminate the need to talk about separately using `ipfs-car` to create a CAR with `shardSplitThreshold: 1000` (i.e., `storeDirectory` does this already), or should we keep this question in the FAQs?
